MeterLogger: user/ac/ac_out.c File Reference
ac_out.c File Reference
#include <esp8266.h>
#include "led.h"
#include "ac_out.h"
#include "config.h"
Enumerations
enum ac_pwm_state_t { ON, OFF }
Functions
ICACHE_FLASH_ATTR void ac_out_init ()
ICACHE_FLASH_ATTR static void ac_test_timer_func (void *arg)
ICACHE_FLASH_ATTR static void ac_out_off_timer_func (void *arg)
ICACHE_FLASH_ATTR static void ac_pwm_timer_func (void *arg)
ICACHE_FLASH_ATTR void ac_test ()
ICACHE_FLASH_ATTR void ac_motor_valve_open ()
ICACHE_FLASH_ATTR void ac_motor_valve_close ()
ICACHE_FLASH_ATTR void ac_thermo_open ()
ICACHE_FLASH_ATTR void ac_thermo_close ()
ICACHE_FLASH_ATTR void ac_thermo_pwm (unsigned int duty_cycle)
ICACHE_FLASH_ATTR void ac_off ()
Variables
static os_timer_t ac_test_timer
static os_timer_t ac_out_off_timer
static os_timer_t ac_pwm_timer
unsigned int ac_pwm_duty_cycle
ac_pwm_state_t ac_pwm_state = OFF
Enumeration Type Documentation
ac_pwm_state_t
enum ac_pwm_state_t
Enumerator
ON
OFF
Definition at line 12 of file ac_out.c.
Function Documentation
ac_motor_valve_close()
ICACHE_FLASH_ATTR void ac_motor_valve_close ()
Definition at line 148 of file ac_out.c.
References ac_off(), ac_out_off_timer, ac_out_off_timer_func(), BIT15, gpio_output_set(), ICACHE_FLASH_ATTR, led_pattern_b(), NULL, os_printf(), os_timer_arm, os_timer_disarm, os_timer_func_t, and os_timer_setfn.
ac_motor_valve_open()
ICACHE_FLASH_ATTR void ac_motor_valve_open ()
Definition at line 129 of file ac_out.c.
References ac_off(), ac_out_off_timer, ac_out_off_timer_func(), BIT14, gpio_output_set(), ICACHE_FLASH_ATTR, led_pattern_a(), NULL, os_printf(), os_timer_arm, os_timer_disarm, os_timer_func_t, and os_timer_setfn.
ac_off()
ICACHE_FLASH_ATTR void ac_off ()
Definition at line 233 of file ac_out.c.
References ac_out_off_timer, ac_out_off_timer_func(), ac_test_timer, NULL, os_timer_arm, os_timer_disarm, os_timer_func_t, and os_timer_setfn.
Referenced by ac_motor_valve_close(), ac_motor_valve_open(), and minute_timer_func().
ac_out_init()
ICACHE_FLASH_ATTR void ac_out_init ()
Definition at line 17 of file ac_out.c.
References FUNC_GPIO14, FUNC_GPIO15, ICACHE_FLASH_ATTR, PERIPHS_IO_MUX_MTDO_U, PERIPHS_IO_MUX_MTMS_U, and PIN_FUNC_SELECT.
ac_out_off_timer_func()
ICACHE_FLASH_ATTR static void ac_out_off_timer_func (void * arg) static
Definition at line 51 of file ac_out.c.
References BIT14, BIT15, gpio_output_set(), led_off(), led_stop_pattern(), and os_printf().
Referenced by ac_motor_valve_close(), ac_motor_valve_open(), and ac_off().
ac_pwm_timer_func()
ICACHE_FLASH_ATTR static void ac_pwm_timer_func (void * arg) static
Definition at line 68 of file ac_out.c.
References ac_pwm_duty_cycle, ac_pwm_state, ac_pwm_timer, BIT14, gpio_output_set(), ICACHE_FLASH_ATTR, led_off(), led_on(), NULL, OFF, ON, os_timer_arm, os_timer_disarm, os_timer_func_t, and os_timer_setfn.
Referenced by ac_thermo_pwm().
ac_test()
ICACHE_FLASH_ATTR void ac_test ()
Definition at line 111 of file ac_out.c.
References ac_test_timer, ac_test_timer_func(), BIT14, BIT15, gpio_output_set(), ICACHE_FLASH_ATTR, led_pattern_a(), NULL, os_printf(), os_timer_arm, os_timer_disarm, os_timer_func_t, and os_timer_setfn.
Referenced by minute_timer_func().
ac_test_timer_func()
ICACHE_FLASH_ATTR static void ac_test_timer_func (void * arg) static
Definition at line 24 of file ac_out.c.
References BIT14, BIT15, GPIO_OUT_ADDRESS, gpio_output_set(), GPIO_REG_READ, led_pattern_a(), and led_pattern_b().
Referenced by ac_test().
ac_thermo_close()
ICACHE_FLASH_ATTR void ac_thermo_close ()
Definition at line 193 of file ac_out.c.
References syscfg_t::ac_thermo_state, BIT14, BIT15, cfg_save_defered(), gpio_output_set(), ICACHE_FLASH_ATTR, led_pattern_a(), os_printf(), and sys_cfg.
Referenced by minute_timer_func().
ac_thermo_open()
ICACHE_FLASH_ATTR void ac_thermo_open ()
Definition at line 167 of file ac_out.c.
References syscfg_t::ac_thermo_state, BIT14, BIT15, cfg_save_defered(), gpio_output_set(), ICACHE_FLASH_ATTR, led_pattern_b(), os_printf(), and sys_cfg.
Referenced by minute_timer_func().
ac_thermo_pwm()
ICACHE_FLASH_ATTR void ac_thermo_pwm (unsigned int duty_cycle)
Definition at line 219 of file ac_out.c.
References ac_pwm_duty_cycle, ac_pwm_timer, ac_pwm_timer_func(), ICACHE_FLASH_ATTR, led_stop_pattern(), NULL, os_printf(), os_timer_arm, os_timer_disarm, os_timer_func_t, and os_timer_setfn.
Variable Documentation
ac_out_off_timer
os_timer_t ac_out_off_timer static
Definition at line 8 of file ac_out.c.
Referenced by ac_motor_valve_close(), ac_motor_valve_open(), and ac_off().
ac_pwm_duty_cycle
unsigned int ac_pwm_duty_cycle
Definition at line 11 of file ac_out.c.
Referenced by ac_pwm_timer_func(), and ac_thermo_pwm().
ac_pwm_state
ac_pwm_state_t ac_pwm_state = OFF
Definition at line 13 of file ac_out.c.
Referenced by ac_pwm_timer_func().
ac_pwm_timer
os_timer_t ac_pwm_timer static
Definition at line 9 of file ac_out.c.
Referenced by ac_pwm_timer_func(), and ac_thermo_pwm().
ac_test_timer
os_timer_t ac_test_timer static
Definition at line 7 of file ac_out.c.
Referenced by ac_off(), and ac_test().