MeterLogger: user/ac/ac_out.h File Reference
ac_out.h File Reference
Functions
ICACHE_FLASH_ATTR void ac_out_init ()
ICACHE_FLASH_ATTR void ac_test ()
ICACHE_FLASH_ATTR void ac_motor_valve_open ()
ICACHE_FLASH_ATTR void ac_motor_valve_close ()
ICACHE_FLASH_ATTR void ac_thermo_open ()
ICACHE_FLASH_ATTR void ac_thermo_close ()
ICACHE_FLASH_ATTR void ac_thermo_pwm (unsigned int pwm)
ICACHE_FLASH_ATTR void ac_off ()
Function Documentation
ac_motor_valve_close()
ICACHE_FLASH_ATTR void ac_motor_valve_close ()
Definition at line 148 of file ac_out.c.
References ac_off(), ac_out_off_timer, ac_out_off_timer_func(), ICACHE_FLASH_ATTR, led_pattern_b(), NULL, os_printf(), os_timer_arm, os_timer_disarm, os_timer_func_t, and os_timer_setfn.
{
 #ifdef DEBUG
     os_printf("\n\rac 2 on\n\r");
 #endif
     ac_off();
 #ifdef LED_ON_AC
     led_pattern_b();
 #endif
     //Set GPI15 to HIGH
 //  gpio_output_set(BIT15, 0, BIT15, 0);
     // wait 60 seconds and turn ac output off
     os_timer_disarm(&ac_out_off_timer);
     os_timer_setfn(&ac_out_off_timer, (os_timer_func_t *)ac_out_off_timer_func, NULL);
     os_timer_arm(&ac_out_off_timer, 60000, 0);
 }
ac_motor_valve_open()
ICACHE_FLASH_ATTR void ac_motor_valve_open ()
Definition at line 129 of file ac_out.c.
References ac_off(), ac_out_off_timer, ac_out_off_timer_func(), BIT14, gpio_output_set(), ICACHE_FLASH_ATTR, led_pattern_a(), NULL, os_printf(), os_timer_arm, os_timer_disarm, os_timer_func_t, and os_timer_setfn.
{
 #ifdef DEBUG
     os_printf("\n\rac 1 on\n\r");
 #endif
     ac_off();
 #ifdef LED_ON_AC
     led_pattern_a();
 #endif
     //Set GPI14 to HIGH
     gpio_output_set(BIT14, 0, BIT14, 0);
     // wait 60 seconds and turn ac output off
     os_timer_disarm(&ac_out_off_timer);
     os_timer_setfn(&ac_out_off_timer, (os_timer_func_t *)ac_out_off_timer_func, NULL);
     os_timer_arm(&ac_out_off_timer, 60000, 0);
 }
ac_off()
ICACHE_FLASH_ATTR void ac_off ()
Definition at line 233 of file ac_out.c.
References ac_out_off_timer, ac_out_off_timer_func(), ac_test_timer, NULL, os_timer_arm, os_timer_disarm, os_timer_func_t, and os_timer_setfn.
Referenced by ac_motor_valve_close(), ac_motor_valve_open(), and minute_timer_func().
               {
     // turn ac output off
     os_timer_disarm(&ac_test_timer);
     os_timer_disarm(&ac_out_off_timer);
     os_timer_setfn(&ac_out_off_timer, (os_timer_func_t *)ac_out_off_timer_func, NULL);
     os_timer_arm(&ac_out_off_timer, 0, 0);
 }
ac_out_init()
ICACHE_FLASH_ATTR void ac_out_init ()
Definition at line 17 of file ac_out.c.
References FUNC_GPIO14, ICACHE_FLASH_ATTR, PERIPHS_IO_MUX_MTMS_U, and PIN_FUNC_SELECT.
                    {
     //Set GPIO14 and GPIO15 to output mode
     PIN_FUNC_SELECT(PERIPHS_IO_MUX_MTMS_U, FUNC_GPIO14);
 //  PIN_FUNC_SELECT(PERIPHS_IO_MUX_MTDO_U, FUNC_GPIO15);    // DEBUG: disables becouse it may keep the esp in SD-Card Boot mode if kept hig at boot
 }
ac_test()
ICACHE_FLASH_ATTR void ac_test ()
Definition at line 111 of file ac_out.c.
References ac_test_timer, ac_test_timer_func(), BIT14, gpio_output_set(), ICACHE_FLASH_ATTR, led_pattern_a(), NULL, os_printf(), os_timer_arm, os_timer_disarm, os_timer_func_t, and os_timer_setfn.
Referenced by minute_timer_func().
                {
 #ifdef DEBUG
     os_printf("\n\rac test on\n\r");
 #endif
 #ifdef LED_ON_AC
     led_pattern_a();
 #endif
     // set GPIO14 high and GPIO15 low
     gpio_output_set(BIT14, 0, BIT14, 0);
 //  gpio_output_set(0, BIT15, BIT15, 0);
     os_timer_disarm(&ac_test_timer);
     os_timer_setfn(&ac_test_timer, (os_timer_func_t *)ac_test_timer_func, NULL);
     os_timer_arm(&ac_test_timer, 120000, 1);
 }
ac_thermo_close()
ICACHE_FLASH_ATTR void ac_thermo_close ()
Definition at line 193 of file ac_out.c.
References syscfg_t::ac_thermo_state, BIT14, cfg_save_defered(), gpio_output_set(), ICACHE_FLASH_ATTR, led_pattern_a(), os_printf(), and sys_cfg.
Referenced by minute_timer_func().
{
 #ifdef DEBUG
     os_printf("\n\rac 1 close\n\r");
 #endif
 #ifdef LED_ON_AC
     led_pattern_a();
 #endif
 #ifdef THERMO_NO
     //Set GPI14 to HIGHT
     gpio_output_set(BIT14, 0, BIT14, 0);
     //Set GPI15 to HIGH
 //  gpio_output_set(BIT15, 0, BIT15, 0);
 #else   // THERMO_NC
     //Set GPI14 to LOW
     gpio_output_set(0, BIT14, BIT14, 0);
     //Set GPI15 to LOW
 //  gpio_output_set(0, BIT15, BIT15, 0);
 #endif
     if (sys_cfg.ac_thermo_state) {  // only save if state changed
         sys_cfg.ac_thermo_state = 0;
         cfg_save_defered();
     }
 }
ac_thermo_open()
ICACHE_FLASH_ATTR void ac_thermo_open ()
Definition at line 167 of file ac_out.c.
References syscfg_t::ac_thermo_state, BIT14, cfg_save_defered(), gpio_output_set(), ICACHE_FLASH_ATTR, led_pattern_b(), os_printf(), and sys_cfg.
Referenced by minute_timer_func().
                       {
 #ifdef DEBUG
     os_printf("\n\rac 1 open\n\r");
 #endif
 #ifdef LED_ON_AC
     led_pattern_b();
 #endif
 #ifdef THERMO_NO
     //Set GPI14 to LOW
     gpio_output_set(0, BIT14, BIT14, 0);
     //Set GPI15 to LOW
 //  gpio_output_set(0, BIT15, BIT15, 0);
 #else   // THERMO_NC
     //Set GPI14 to HIGH
     gpio_output_set(BIT14, 0, BIT14, 0);
     //Set GPI15 to HIGH
 //  gpio_output_set(BIT15, 0, BIT15, 0);
 #endif
     if (!sys_cfg.ac_thermo_state) { // only save if state changed
         sys_cfg.ac_thermo_state = 1;
         cfg_save_defered();
     }
 }
ac_thermo_pwm()
ICACHE_FLASH_ATTR void ac_thermo_pwm (unsigned int pwm)
Definition at line 219 of file ac_out.c.
References ac_pwm_duty_cycle, ac_pwm_timer, ac_pwm_timer_func(), ICACHE_FLASH_ATTR, led_stop_pattern(), NULL, os_printf(), os_timer_arm, os_timer_disarm, os_timer_func_t, and os_timer_setfn.
{
 #ifdef DEBUG
     os_printf("\n\rac 1 pwm\n\r");
 #endif
 #ifdef LED_ON_AC
     led_stop_pattern();
 #endif
     ac_pwm_duty_cycle = duty_cycle;
     os_timer_disarm(&ac_pwm_timer);
     os_timer_setfn(&ac_pwm_timer, (os_timer_func_t *)ac_pwm_timer_func, NULL);
     os_timer_arm(&ac_pwm_timer, 0, 0);  // fire now once, ac_pwm_timer start itself
 }