MeterLogger: user/crypto/aes.h File Reference
aes.h File Reference
#include <esp8266.h>
#include <stdint.h>
Macros
#define CBC 1
#define ECB 1
Functions
ICACHE_FLASH_ATTR void AES128_ECB_encrypt (const uint8_t *input, const uint8_t *key, uint8_t *output)
ICACHE_FLASH_ATTR void AES128_ECB_decrypt (const uint8_t *input, const uint8_t *key, uint8_t *output)
ICACHE_FLASH_ATTR void AES128_CBC_encrypt_buffer (uint8_t *output, uint8_t *input, uint32_t length, const uint8_t *key, uint8_t *iv)
ICACHE_FLASH_ATTR void AES128_CBC_decrypt_buffer (uint8_t *output, uint8_t *input, uint32_t length, const uint8_t *key, uint8_t *iv)
Macro Definition Documentation
CBC
#define CBC 1
Definition at line 15 of file aes.h.
ECB
#define ECB 1
Definition at line 19 of file aes.h.
Function Documentation
AES128_CBC_decrypt_buffer()
ICACHE_FLASH_ATTR void AES128_CBC_decrypt_buffer (uint8_t * output, uint8_t * input, uint32_t length, const uint8_t * key, uint8_t * iv)
Referenced by BlockCopy(), and decrypt_aes_hmac_combined().
AES128_CBC_encrypt_buffer()
ICACHE_FLASH_ATTR void AES128_CBC_encrypt_buffer (uint8_t * output, uint8_t * input, uint32_t length, const uint8_t * key, uint8_t * iv)
Referenced by BlockCopy(), and encrypt_aes_hmac_combined().
AES128_ECB_decrypt()
ICACHE_FLASH_ATTR void AES128_ECB_decrypt (const uint8_t * input, const uint8_t * key, uint8_t * output)
Referenced by BlockCopy().
AES128_ECB_encrypt()
ICACHE_FLASH_ATTR void AES128_ECB_encrypt (const uint8_t * input, const uint8_t * key, uint8_t * output)
Referenced by BlockCopy().