MeterLogger: user/auth.c File Reference
auth.c File Reference
#include <esp8266.h>
#include "httpd.h"
#include "cgi.h"
#include "auth.h"
#include "base64.h"
Functions
int ICACHE_FLASH_ATTR authBasic (HttpdConnData *connData)
Function Documentation
authBasic()
int ICACHE_FLASH_ATTR authBasic (HttpdConnData * connData)
Definition at line 21 of file auth.c.
References AUTH_MAX_PASS_LEN, AUTH_MAX_USER_LEN, base64_decode(), HttpdConnData::cgiArg, HttpdConnData::conn, HTTP_AUTH_REALM, HTTPD_CGI_AUTHENTICATED, HTTPD_CGI_DONE, httpdEndHeaders(), httpdGetHeader(), httpdHeader(), httpdSend(), httpdStartResponse(), NULL, os_strcmp, os_strncmp, strlen, and strncmp.