MeterLogger: user/auth.h File Reference
auth.h File Reference
#include "httpdconfig.h"
Macros
#define HTTP_AUTH_REALM "Protected"
#define HTTPD_AUTH_SINGLE 0
#define HTTPD_AUTH_CALLBACK 1
#define AUTH_MAX_USER_LEN 32
#define AUTH_MAX_PASS_LEN 32
Typedefs
typedef int(* AuthGetUserPw) (HttpdConnData *connData, int no, char *user, int userLen, char *pass, int passLen)
Functions
int ICACHE_FLASH_ATTR authBasic (HttpdConnData *connData)
Macro Definition Documentation
#define AUTH_MAX_PASS_LEN 32
Definition at line 14 of file auth.h.
Referenced by authBasic().
#define AUTH_MAX_USER_LEN 32
Definition at line 13 of file auth.h.
Referenced by authBasic().
#define HTTP_AUTH_REALM "Protected"
Definition at line 7 of file auth.h.
Referenced by authBasic().
#define HTTPD_AUTH_CALLBACK 1
Definition at line 11 of file auth.h.
#define HTTPD_AUTH_SINGLE 0
Definition at line 10 of file auth.h.
Typedef Documentation
typedef int(* AuthGetUserPw) (HttpdConnData *connData, int no, char *user, int userLen, char *pass, int passLen)
Definition at line 18 of file auth.h.
Function Documentation
int ICACHE_FLASH_ATTR authBasic (HttpdConnData * connData)
Definition at line 21 of file auth.c.
References AUTH_MAX_PASS_LEN, AUTH_MAX_USER_LEN, base64_decode(), HttpdConnData::cgiArg, HttpdConnData::conn, HTTP_AUTH_REALM, HTTPD_CGI_AUTHENTICATED, HTTPD_CGI_DONE, httpdEndHeaders(), httpdGetHeader(), httpdHeader(), httpdSend(), httpdStartResponse(), os_strcmp, os_strncmp, strlen, and strncmp.