MeterLogger: user/captdns.h File Reference
captdns.h File Reference
Functions
void ICACHE_FLASH_ATTR captdnsInit (void)
void ICACHE_FLASH_ATTR captdnsStop (void)
Function Documentation
captdnsInit()
void ICACHE_FLASH_ATTR captdnsInit (void)
Definition at line 344 of file captdns.c.
References captdnsRecv(), espconn_create(), espconn_regist_recvcb(), ESPCONN_UDP, _esp_udp::local_port, espconn::proto, espconn::type, and espconn::udp.
Referenced by captdnsRecv().
{
     static esp_udp udpconn;
     conn.type=ESPCONN_UDP;
     conn.proto.udp=&udpconn;
     conn.proto.udp->local_port = 53;
     espconn_regist_recvcb(&conn, captdnsRecv);
     espconn_create(&conn);
 }
captdnsStop()
void ICACHE_FLASH_ATTR captdnsStop (void)
Definition at line 353 of file captdns.c.
References espconn_delete().
{
     espconn_delete(&conn);
 }