MeterLogger: user/captdns.c File Reference
captdns.c File Reference
#include <esp8266.h>
#include <lwip/ip.h>
#include <lwip/udp.h>
#include <lwip/tcp_impl.h>
#include <netif/etharp.h>
#include <lwip/netif.h>
#include <lwip/lwip_napt.h>
#include <lwip/dns.h>
#include <lwip/app/dhcpserver.h>
#include <lwip/opt.h>
#include <espconn.h>
Macros
#define DNS_LEN 512
#define FLAG_QR (1<<7)
#define FLAG_AA (1<<2)
#define FLAG_TC (1<<1)
#define FLAG_RD (1<<0)
#define QTYPE_A 1
#define QTYPE_NS 2
#define QTYPE_CNAME 5
#define QTYPE_SOA 6
#define QTYPE_WKS 11
#define QTYPE_PTR 12
#define QTYPE_HINFO 13
#define QTYPE_MINFO 14
#define QTYPE_MX 15
#define QTYPE_TXT 16
#define QTYPE_URI 256
#define QCLASS_IN 1
#define QCLASS_ANY 255
#define QCLASS_URI 256
Functions
struct __attribute__ ((packed))
static void ICACHE_FLASH_ATTR setn16 (void *pp, int16_t n)
static void ICACHE_FLASH_ATTR setn32 (void *pp, int32_t n)
static uint16_t ICACHE_FLASH_ATTR my_ntohs (uint16_t *in)
static char *ICACHE_FLASH_ATTR labelToStr (char *packet, char *labelPtr, int packetSz, char *res, int resMaxLen)
static char ICACHE_FLASH_ATTR * strToLabel (char *str, char *label, int maxLen)
static void ICACHE_FLASH_ATTR captdnsRecv (void *arg, char *pusrdata, unsigned short length)
void ICACHE_FLASH_ATTR captdnsInit (void)
void ICACHE_FLASH_ATTR captdnsStop (void)
Variables
static struct espconn conn
DnsHeader
DnsLabel
DnsQuestionFooter
DnsResourceFooter
DnsUriHdr
Macro Definition Documentation
DNS_LEN
#define DNS_LEN 512
Definition at line 47 of file captdns.c.
Referenced by captdnsRecv().
FLAG_AA
#define FLAG_AA (1<<2)
Definition at line 93 of file captdns.c.
FLAG_QR
#define FLAG_QR (1<<7)
Definition at line 92 of file captdns.c.
Referenced by captdnsRecv().
FLAG_RD
#define FLAG_RD (1<<0)
Definition at line 95 of file captdns.c.
FLAG_TC
#define FLAG_TC (1<<1)
Definition at line 94 of file captdns.c.
Referenced by captdnsRecv().
QCLASS_ANY
#define QCLASS_ANY 255
Definition at line 110 of file captdns.c.
QCLASS_IN
#define QCLASS_IN 1
Definition at line 109 of file captdns.c.
Referenced by captdnsRecv().
QCLASS_URI
#define QCLASS_URI 256
Definition at line 111 of file captdns.c.
Referenced by captdnsRecv().
QTYPE_A
#define QTYPE_A 1
Definition at line 97 of file captdns.c.
Referenced by captdnsRecv().
QTYPE_CNAME
#define QTYPE_CNAME 5
Definition at line 99 of file captdns.c.
QTYPE_HINFO
#define QTYPE_HINFO 13
Definition at line 103 of file captdns.c.
QTYPE_MINFO
#define QTYPE_MINFO 14
Definition at line 104 of file captdns.c.
QTYPE_MX
#define QTYPE_MX 15
Definition at line 105 of file captdns.c.
QTYPE_NS
#define QTYPE_NS 2
Definition at line 98 of file captdns.c.
Referenced by captdnsRecv().
QTYPE_PTR
#define QTYPE_PTR 12
Definition at line 102 of file captdns.c.
QTYPE_SOA
#define QTYPE_SOA 6
Definition at line 100 of file captdns.c.
QTYPE_TXT
#define QTYPE_TXT 16
Definition at line 106 of file captdns.c.
QTYPE_URI
#define QTYPE_URI 256
Definition at line 107 of file captdns.c.
Referenced by captdnsRecv().
QTYPE_WKS
#define QTYPE_WKS 11
Definition at line 101 of file captdns.c.
Function Documentation
__attribute__()
struct __attribute__ ((packed))
Definition at line 53 of file captdns.c.
Referenced by espconn_sendto().
{
     uint16_t id;
     uint8_t flags;
     uint8_t rcode;
     uint16_t qdcount;
     uint16_t ancount;
     uint16_t nscount;
     uint16_t arcount;
 } DnsHeader;
captdnsInit()
void ICACHE_FLASH_ATTR captdnsInit (void)
Definition at line 344 of file captdns.c.
References captdnsRecv(), espconn_create(), espconn_regist_recvcb(), ESPCONN_UDP, _esp_udp::local_port, espconn::proto, espconn::type, and espconn::udp.
Referenced by captdnsRecv().
{
     static esp_udp udpconn;
     conn.type=ESPCONN_UDP;
     conn.proto.udp=&udpconn;
     conn.proto.udp->local_port = 53;
     espconn_regist_recvcb(&conn, captdnsRecv);
     espconn_create(&conn);
 }
captdnsRecv()
static void ICACHE_FLASH_ATTR captdnsRecv (void * arg, char * pusrdata, unsigned short length) static
Definition at line 192 of file captdns.c.
References captdnsInit(), conn, DNS_LEN, DnsHeader, DnsQuestionFooter, DnsResourceFooter, DnsUriHdr, espconn_get_connection_info(), ESPCONN_OK, espconn_sendto(), FLAG_QR, FLAG_TC, htons, ICACHE_FLASH_ATTR, INADDR_ANY, ip_info::ip, ip4_addr1, ip4_addr2, ip4_addr3, ip4_addr4, labelToStr(), memcpy, memset, my_ntohs(), NULL, espconn::proto, QCLASS_IN, QCLASS_URI, QTYPE_A, QTYPE_NS, QTYPE_URI, _esp_udp::remote_ip, _remot_info::remote_ip, _esp_udp::remote_port, _remot_info::remote_port, setn16(), setn32(), SOFTAP_IF, strToLabel(), espconn::udp, and wifi_get_ip_info().
Referenced by captdnsInit().
{
     struct espconn *conn=(struct espconn *)arg;
 #else
 static void ICACHE_FLASH_ATTR captdnsRecv(struct sockaddr_in *premote_addr, char *pusrdata, unsigned short length) {
 #endif
     char buff[DNS_LEN];
     char reply[DNS_LEN];
     int i;
     char *rend=&reply[length];
     char *p=pusrdata;
     DnsHeader *hdr=(DnsHeader*)p;
     DnsHeader *rhdr=(DnsHeader*)&reply[0];
     p+=sizeof(DnsHeader);
 //  httpd_printf("DNS packet: id 0x%X flags 0x%X rcode 0x%X qcnt %d ancnt %d nscount %d arcount %d len %d\n",
 //      my_ntohs(&hdr->id), hdr->flags, hdr->rcode, my_ntohs(&hdr->qdcount), my_ntohs(&hdr->ancount), my_ntohs(&hdr->nscount), my_ntohs(&hdr->arcount), length);
     //Some sanity checks:
     if (length>DNS_LEN) return;                                 //Packet is longer than DNS implementation allows
     if (length<sizeof(DnsHeader)) return;                       //Packet is too short
     if (hdr->ancount || hdr->nscount || hdr->arcount) return;   //this is a reply, don't know what to do with it
     if (hdr->flags&FLAG_TC) return;                             //truncated, can't use this
     //Reply is basically the request plus the needed data
     memcpy(reply, pusrdata, length);
     rhdr->flags|=FLAG_QR;
     for (i=0; i<my_ntohs(&hdr->qdcount); i++) {
         //Grab the labels in the q string
         p=labelToStr(pusrdata, p, length, buff, sizeof(buff));
         if (p==NULL) return;
         DnsQuestionFooter *qf=(DnsQuestionFooter*)p;
         p+=sizeof(DnsQuestionFooter);
 //      httpd_printf("DNS: Q (type 0x%X class 0x%X) for %s\n", my_ntohs(&qf->type), my_ntohs(&qf->class), buff);
         if (my_ntohs(&qf->type)==QTYPE_A) {
             //They want to know the IPv4 address of something.
             //Build the response.
             rend=strToLabel(buff, rend, sizeof(reply)-(rend-reply)); //Add the label
             if (rend==NULL) return;
             DnsResourceFooter *rf=(DnsResourceFooter *)rend;
             rend+=sizeof(DnsResourceFooter);
             setn16(&rf->type, QTYPE_A);
             setn16(&rf->class, QCLASS_IN);
             setn32(&rf->ttl, 0);
             setn16(&rf->rdlength, 4); //IPv4 addr is 4 bytes;
             //Grab the current IP of the softap interface
             struct ip_info info;
             wifi_get_ip_info(SOFTAP_IF, &info);
             *rend++=ip4_addr1(&info.ip);
             *rend++=ip4_addr2(&info.ip);
             *rend++=ip4_addr3(&info.ip);
             *rend++=ip4_addr4(&info.ip);
             setn16(&rhdr->ancount, my_ntohs(&rhdr->ancount)+1);
 //          httpd_printf("Added A rec to resp. Resp len is %d\n", (rend-reply));
         } else if (my_ntohs(&qf->type)==QTYPE_NS) {
             //Give ns server. Basically can be whatever we want because it'll get resolved to our IP later anyway.
             rend=strToLabel(buff, rend, sizeof(reply)-(rend-reply)); //Add the label
             DnsResourceFooter *rf=(DnsResourceFooter *)rend;
             rend+=sizeof(DnsResourceFooter);
             setn16(&rf->type, QTYPE_NS);
             setn16(&rf->class, QCLASS_IN);
             setn16(&rf->ttl, 0);
             setn16(&rf->rdlength, 4);
             *rend++=2;
             *rend++='n';
             *rend++='s';
             *rend++=0;
             setn16(&rhdr->ancount, my_ntohs(&rhdr->ancount)+1);
 //          httpd_printf("Added NS rec to resp. Resp len is %d\n", (rend-reply));
         } else if (my_ntohs(&qf->type)==QTYPE_URI) {
             //Give uri to us
             rend=strToLabel(buff, rend, sizeof(reply)-(rend-reply)); //Add the label
             DnsResourceFooter *rf=(DnsResourceFooter *)rend;
             rend+=sizeof(DnsResourceFooter);
             DnsUriHdr *uh=(DnsUriHdr *)rend;
             rend+=sizeof(DnsUriHdr);
             setn16(&rf->type, QTYPE_URI);
             setn16(&rf->class, QCLASS_URI);
             setn16(&rf->ttl, 0);
             setn16(&rf->rdlength, 4+16);
             setn16(&uh->prio, 10);
             setn16(&uh->weight, 1);
             memcpy(rend, "http://esp.nonet", 16);
             rend+=16;
             setn16(&rhdr->ancount, my_ntohs(&rhdr->ancount)+1);
 //          httpd_printf("Added NS rec to resp. Resp len is %d\n", (rend-reply));
         }
     }
     //Send the response
 #ifndef FREERTOS
     remot_info *remInfo=NULL;
     //Send data to port/ip it came from, not to the ip/port we listen on.
     if (espconn_get_connection_info(conn, &remInfo, 0)==ESPCONN_OK) {
         conn->proto.udp->remote_port=remInfo->remote_port;
         memcpy(conn->proto.udp->remote_ip, remInfo->remote_ip, sizeof(remInfo->remote_ip));
     }
     espconn_sendto(conn, (uint8*)reply, rend-reply);
 #else
     sendto(sockFd,(uint8*)reply, rend-reply, 0, (struct sockaddr *)premote_addr, sizeof(struct sockaddr_in));
 #endif
 }
captdnsStop()
void ICACHE_FLASH_ATTR captdnsStop (void)
Definition at line 353 of file captdns.c.
References espconn_delete().
{
     espconn_delete(&conn);
 }
labelToStr()
static char* ICACHE_FLASH_ATTR labelToStr (char * packet, char * labelPtr, int packetSz, char * res, int resMaxLen) static
Definition at line 138 of file captdns.c.
References my_ntohs(), and NULL.
Referenced by captdnsRecv().
{
     int i, j, k;
     char *endPtr=NULL;
     i=0;
     do {
         if ((*labelPtr&0xC0)==0) {
             j=*labelPtr++; //skip past length
             //Add separator period if there already is data in res
             if (i<resMaxLen && i!=0) res[i++]='.';
             //Copy label to res
             for (k=0; k<j; k++) {
                 if ((labelPtr-packet)>packetSz) return NULL;
                 if (i<resMaxLen) res[i++]=*labelPtr++;
             }
         } else if ((*labelPtr&0xC0)==0xC0) {
             //Compressed label pointer
             endPtr=labelPtr+2;
             int offset=my_ntohs(((uint16_t *)labelPtr))&0x3FFF;
             //Check if offset points to somewhere outside of the packet
             if (offset>packetSz) return NULL;
             labelPtr=&packet[offset];
         }
         //check for out-of-bound-ness
         if ((labelPtr-packet)>packetSz) return NULL;
     } while (*labelPtr!=0);
     res[i]=0; //zero-terminate
     if (endPtr==NULL) endPtr=labelPtr+1;
     return endPtr;
 }
my_ntohs()
static uint16_t ICACHE_FLASH_ATTR my_ntohs (uint16_t * in) static
Definition at line 130 of file captdns.c.
Referenced by captdnsRecv(), and labelToStr().
{
     char *p=(char*)in;
     return ((p[0]<<8)&0xff00)|(p[1]&0xff);
 }
setn16()
static void ICACHE_FLASH_ATTR setn16 (void * pp, int16_t n) static
Definition at line 115 of file captdns.c.
Referenced by captdnsRecv().
{
     char *p=pp;
     *p++=(n>>8);
     *p++=(n&0xff);
 }
setn32()
static void ICACHE_FLASH_ATTR setn32 (void * pp, int32_t n) static
Definition at line 122 of file captdns.c.
Referenced by captdnsRecv().
{
     char *p=pp;
     *p++=(n>>24)&0xff;
     *p++=(n>>16)&0xff;
     *p++=(n>>8)&0xff;
     *p++=(n&0xff);
 }
strToLabel()
static char ICACHE_FLASH_ATTR* strToLabel (char * str, char * label, int maxLen) static
Definition at line 170 of file captdns.c.
Referenced by captdnsRecv().
{
     char *len=label; //ptr to len byte
     char *p=label+1; //ptr to next label byte to be written
     while (1) {
         if (*str=='.' || *str==0) {
             *len=((p-len)-1);   //write len of label bit
             len=p;              //pos of len for next part
             p++;                //data ptr is one past len
             if (*str==0) break; //done
             str++;
         } else {
             *p++=*str++;    //copy byte
 //          if ((p-label)>maxLen) return NULL;  //check out of bounds
         }
     }
     *len=0;
     return p; //ptr to first free byte in resp
 }
Variable Documentation
conn
struct espconn conn static
Definition at line 50 of file captdns.c.
Referenced by captdnsRecv(), httpdConnectCb(), httpdDisconCb(), httpdFindConnData(), httpdReconCb(), httpdRecvCb(), and httpdSentCb().
DnsHeader
DnsHeader
Definition at line 61 of file captdns.c.
Referenced by captdnsRecv().
DnsLabel
DnsLabel
Definition at line 67 of file captdns.c.
DnsQuestionFooter
DnsQuestionFooter
Definition at line 74 of file captdns.c.
Referenced by captdnsRecv().
DnsResourceFooter
DnsResourceFooter
Definition at line 84 of file captdns.c.
Referenced by captdnsRecv().
DnsUriHdr
DnsUriHdr
Definition at line 89 of file captdns.c.
Referenced by captdnsRecv().