MeterLogger: user/cgi.h File Reference
cgi.h File Reference
#include "httpd.h"
Functions
int cgiLed (HttpdConnData *connData)
void tplLed (HttpdConnData *connData, char *token, void **arg)
int cgiReadFlash (HttpdConnData *connData)
void tplCounter (HttpdConnData *connData, char *token, void **arg)
Function Documentation
int cgiLed (HttpdConnData * connData)
Definition at line 27 of file cgi.c.
References atoi(), HttpdConnData::conn, currLedState, HTTPD_CGI_DONE, httpdFindArg(), httpdRedirect(), and HttpdConnData::postBuff.
int cgiReadFlash (HttpdConnData * connData)
Definition at line 80 of file cgi.c.
References HttpdConnData::cgiData, HttpdConnData::conn, HTTPD_CGI_DONE, HTTPD_CGI_MORE, httpdEndHeaders(), httpdHeader(), httpdStartResponse(), and INFO.
void tplCounter (HttpdConnData * connData, char * token, void ** arg)
Definition at line 67 of file cgi.c.
References hitCounter, httpdSend(), os_strcmp, and tfp_snprintf().
void tplLed (HttpdConnData * connData, char * token, void ** arg)
Definition at line 49 of file cgi.c.
References currLedState, httpdSend(), os_strcmp, and os_strcpy.