MeterLogger: user/cgi.c File Reference
cgi.c File Reference
#include <esp8266.h>
#include "httpd.h"
#include "cgi.h"
#include "debug.h"
#include "tinyprintf.h"
Functions
int ICACHE_FLASH_ATTR cgiLed (HttpdConnData *connData)
void ICACHE_FLASH_ATTR tplLed (HttpdConnData *connData, char *token, void **arg)
void ICACHE_FLASH_ATTR tplCounter (HttpdConnData *connData, char *token, void **arg)
int ICACHE_FLASH_ATTR cgiReadFlash (HttpdConnData *connData)
Variables
static char currLedState =0
static long hitCounter =0
Function Documentation
cgiLed()
int ICACHE_FLASH_ATTR cgiLed (HttpdConnData * connData)
Definition at line 27 of file cgi.c.
References atoi(), HttpdConnData::conn, currLedState, HTTPD_CGI_DONE, httpdFindArg(), httpdRedirect(), and HttpdConnData::postBuff.
cgiReadFlash()
int ICACHE_FLASH_ATTR cgiReadFlash (HttpdConnData * connData)
Definition at line 80 of file cgi.c.
References HttpdConnData::cgiData, HttpdConnData::conn, HTTPD_CGI_DONE, HTTPD_CGI_MORE, httpdEndHeaders(), httpdHeader(), httpdStartResponse(), and INFO.
tplCounter()
void ICACHE_FLASH_ATTR tplCounter (HttpdConnData * connData, char * token, void ** arg)
Definition at line 67 of file cgi.c.
References hitCounter, httpdSend(), os_strcmp, and tfp_snprintf().
tplLed()
void ICACHE_FLASH_ATTR tplLed (HttpdConnData * connData, char * token, void ** arg)
Definition at line 49 of file cgi.c.
References currLedState, httpdSend(), os_strcmp, and os_strcpy.
Variable Documentation
currLedState
char currLedState =0 static
Definition at line 24 of file cgi.c.
Referenced by cgiLed(), and tplLed().
hitCounter
long hitCounter =0 static
Definition at line 64 of file cgi.c.
Referenced by tplCounter().