MeterLogger: user/cgiwifi.c File Reference
cgiwifi.c File Reference
#include <esp8266.h>
#include "httpd.h"
#include "config.h"
#include "debug.h"
#include "utils.h"
#include "tinyprintf.h"
Data Structures
struct ApData
struct ScanResultData
Functions
void ICACHE_FLASH_ATTR wifiScanDoneCb (void *arg, STATUS status)
static void ICACHE_FLASH_ATTR wifiStartScan ()
int ICACHE_FLASH_ATTR cgiWiFiScan (HttpdConnData *connData)
static void ICACHE_FLASH_ATTR resetTimerCb (void *arg)
int ICACHE_FLASH_ATTR cgiSetup (HttpdConnData *connData)
int ICACHE_FLASH_ATTR cgiWifiSetMode (HttpdConnData *connData)
void ICACHE_FLASH_ATTR tplSetup (HttpdConnData *connData, char *token, void **arg)
Variables
ScanResultData cgiWifiAps
static os_timer_t resetTimer
Function Documentation
cgiSetup()
int ICACHE_FLASH_ATTR cgiSetup (HttpdConnData * connData)
Definition at line 168 of file cgiwifi.c.
References cfg_save(), HttpdConnData::conn, HTTPD_CGI_DONE, httpdFindArg(), httpdRedirect(), INFO, kw_to_w_str(), NULL, os_strncpy, os_timer_arm, os_timer_disarm, os_timer_setfn, HttpdConnData::postBuff, resetTimer, resetTimerCb(), syscfg_t::sta_pwd, syscfg_t::sta_ssid, and sys_cfg.
{
     char essid[128];
     char passwd[128];
 #ifdef IMPULSE
     char impulse_meter_serial[32 + 1];
     char impulse_meter_energy_kw[32 + 1];
     char impulse_meter_energy[32 + 1];
     char impulses_per_kwh[8 + 1];
 #endif
     if (connData->conn==NULL) {
         //Connection aborted. Clean up.
         return HTTPD_CGI_DONE;
     }
     httpdFindArg(connData->postBuff, "essid", essid, sizeof(essid));
     httpdFindArg(connData->postBuff, "passwd", passwd, sizeof(passwd));
 #ifdef IMPULSE
     httpdFindArg(connData->postBuff, "impulse_meter_serial", impulse_meter_serial, sizeof(impulse_meter_serial));
     httpdFindArg(connData->postBuff, "impulse_meter_energy", impulse_meter_energy_kw, sizeof(impulse_meter_energy_kw));
     httpdFindArg(connData->postBuff, "impulses_per_kwh", impulses_per_kwh, sizeof(impulses_per_kwh));
 #endif
     os_strncpy((char*)sys_cfg.sta_ssid, essid, 32);
     os_strncpy((char*)sys_cfg.sta_pwd, passwd, 64);
 #ifdef IMPULSE
     os_strncpy((char*)sys_cfg.impulse_meter_serial, impulse_meter_serial, 32 + 1);
     kw_to_w_str(impulse_meter_energy_kw, impulse_meter_energy);
     os_strncpy((char*)sys_cfg.impulse_meter_energy, impulse_meter_energy, 32 + 1);
     os_strncpy((char*)sys_cfg.impulses_per_kwh, impulses_per_kwh, 8 + 1);
     sys_cfg.impulse_meter_count = 0;
 #endif
     cfg_save();
     INFO("Try to connect to AP %s pw %s\n", essid, passwd);
     //Schedule disconnect/connect
     os_timer_disarm(&resetTimer);
     os_timer_setfn(&resetTimer, resetTimerCb, NULL);
     os_timer_arm(&resetTimer, 1000, 0);
 #ifdef IMPULSE
     httpdRedirect(connData, "impulse_meter_setting_up.html");
 #else
     httpdRedirect(connData, "setting_up.html");
 #endif
     // restart to go directly to sample mode after 5 seconds
     os_timer_disarm(&resetTimer);
     os_timer_setfn(&resetTimer, resetTimerCb, NULL);
     os_timer_arm(&resetTimer, 5000, 0);
     return HTTPD_CGI_DONE;
 }
cgiWiFiScan()
int ICACHE_FLASH_ATTR cgiWiFiScan (HttpdConnData * connData)
Definition at line 108 of file cgiwifi.c.
References ScanResultData::apData, ApData::enc, HTTPD_CGI_DONE, httpdEndHeaders(), httpdHeader(), httpdSend(), httpdStartResponse(), ScanResultData::noAps, NULL, ApData::rssi, ScanResultData::scanInProgress, ApData::ssid, strlen, tfp_snprintf(), and wifiStartScan().
{
     int len;
     int i;
     char buff[1024];
     httpdStartResponse(connData, 200);
     httpdHeader(connData, "Content-Type", "text/json");
     httpdEndHeaders(connData);
     if (cgiWifiAps.scanInProgress==1) {
         //We're still scanning. Tell Javascript code that.
         tfp_snprintf(buff, 1024, "{\n \"result\": { \n\"inProgress\": \"1\"\n }\n}\n");
         len = strlen(buff);
         httpdSend(connData, buff, len);
     } else {
         //We have a scan result. Pass it on.
         tfp_snprintf(buff, 1024, "{\n \"result\": { \n\"inProgress\": \"0\", \n\"APs\": [\n");
         len = strlen(buff);
         httpdSend(connData, buff, len);
         if (cgiWifiAps.apData==NULL) cgiWifiAps.noAps=0;
         for (i=0; i<cgiWifiAps.noAps; i++) {
             //Fill in json code for an access point
             tfp_snprintf(buff, 1024, "{\"essid\": \"%s\", \"rssi\": \"%d\", \"enc\": \"%d\"}%s\n",
                     cgiWifiAps.apData[i]->ssid, cgiWifiAps.apData[i]->rssi,
                     cgiWifiAps.apData[i]->enc, (i==cgiWifiAps.noAps-1)?"":",");
             len = strlen(buff);
             httpdSend(connData, buff, len);
         }
         tfp_snprintf(buff, 1024, "]\n}\n}\n");
         len = strlen(buff);
         httpdSend(connData, buff, len);
         //Also start a new scan.
         wifiStartScan();
     }
     return HTTPD_CGI_DONE;
 }
cgiWifiSetMode()
int ICACHE_FLASH_ATTR cgiWifiSetMode (HttpdConnData * connData)
Definition at line 225 of file cgiwifi.c.
References HttpdConnData::conn, HttpdConnData::getArgs, HTTPD_CGI_DONE, httpdFindArg(), httpdRedirect(), INFO, NULL, system_restart(), and wifi_set_opmode().
{
     int len;
     char buff[1024];
     if (connData->conn==NULL) {
         //Connection aborted. Clean up.
         return HTTPD_CGI_DONE;
     }
     len=httpdFindArg(connData->getArgs, "mode", buff, sizeof(buff));
     if (len!=0) {
         INFO("cgiWifiSetMode: %s\n", buff);
 #ifndef DEMO_MODE
         wifi_set_opmode(atoi(buff));
         system_restart();
 #endif
     }
     httpdRedirect(connData, "/wifi");
     return HTTPD_CGI_DONE;
 }
resetTimerCb()
static void ICACHE_FLASH_ATTR resetTimerCb (void * arg) static
Definition at line 150 of file cgiwifi.c.
References os_printf, and system_restart().
Referenced by cgiSetup().
{
 //  int x=wifi_station_get_connect_status();
 //  if (x==STATION_GOT_IP) {
 //      //Go to STA mode. This needs a reset, so do that.
 //      INFO("Got IP. Going into STA mode..\n");
 #ifdef DEBUG
     os_printf("restarting...\n");
 #endif
 //      wifi_set_opmode(1);
     system_restart();
 //  } else {
 //      INFO("Connect fail. Not going into STA-only mode.\n");
 //      //Maybe also pass this through on the webpage?
 //  }
 }
tplSetup()
void ICACHE_FLASH_ATTR tplSetup (HttpdConnData * connData, char * token, void ** arg)
Definition at line 247 of file cgiwifi.c.
References cfg_load(), httpdSend(), NULL, os_strcmp, os_strcpy, syscfg_t::sta_pwd, syscfg_t::sta_ssid, sys_cfg, tfp_snprintf(), w_to_kw_str(), and wifi_get_opmode().
{
     char buff[1024];
 #ifdef IMPULSE
     char impulse_meter_energy[32 + 1];
 #endif // IMPULSE
     int x;
     //static struct station_config stconf;
     if (token==NULL) return;
     //wifi_station_get_config(&stconf);
     cfg_load();
     os_strcpy(buff, "Unknown");
     if (os_strcmp(token, "WiFiMode")==0) {
         x=wifi_get_opmode();
         if (x == 1) os_strcpy(buff, "Client");
         if (x == 2) os_strcpy(buff, "SoftAP");
         if (x == 3) os_strcpy(buff, "STA+AP");
     }
     else if (os_strcmp(token, "currSsid") == 0) {
         os_strcpy(buff, (char*)sys_cfg.sta_ssid);
     }
     else if (os_strcmp(token, "WiFiPasswd") == 0) {
         os_strcpy(buff, (char*)sys_cfg.sta_pwd);
     }
     else if (os_strcmp(token, "WiFiapwarn") == 0) {
         x = wifi_get_opmode();
         if (x == 2) {
             os_strcpy(buff, "<b>Can't scan in this mode.</b> Click <a href=\"setmode.cgi?mode=3\">here</a> to go to STA+AP mode.");
         }
         else {
             os_strcpy(buff, "Click <a href=\"setmode.cgi?mode=2\">here</a> to go to standalone AP mode.");
         }
     }
 #ifdef IMPULSE
     else if (os_strcmp(token, "ImpulseMeterSerial") == 0) {
         os_strcpy(buff, (char*)sys_cfg.impulse_meter_serial);
     }
     else if (os_strcmp(token, "ImpulseMeterEnergy") == 0) {
         tfp_snprintf(impulse_meter_energy, 32 + 1, "%u", atoi(sys_cfg.impulse_meter_energy) + sys_cfg.impulse_meter_count * (1000 / atoi(sys_cfg.impulses_per_kwh)));
         w_to_kw_str(impulse_meter_energy, buff);
     }
     else if (os_strcmp(token, "ImpulsesPerKwh") == 0) {
         os_strcpy(buff, (char*)sys_cfg.impulses_per_kwh);
     }
 #endif
     httpdSend(connData, buff, -1);
 }
wifiScanDoneCb()
void ICACHE_FLASH_ATTR wifiScanDoneCb (void * arg, STATUS status)
Definition at line 47 of file cgiwifi.c.
References ScanResultData::apData, bss_info::authmode, ApData::enc, INFO, ScanResultData::noAps, NULL, OK, os_free, os_malloc, ApData::rssi, bss_info::rssi, ScanResultData::scanInProgress, ApData::ssid, bss_info::ssid, and strncpy.
Referenced by wifiStartScan().
{
     int n;
     struct bss_info *bss_link = (struct bss_info *)arg;
     INFO("wifiScanDoneCb %d\n", status);
     if (status!=OK) {
         cgiWifiAps.scanInProgress=0;
         return;
     }
     //Clear prev ap data if needed.
     if (cgiWifiAps.apData!=NULL) {
         for (n=0; n<cgiWifiAps.noAps; n++) os_free(cgiWifiAps.apData[n]);
         os_free(cgiWifiAps.apData);
     }
     //Count amount of access points found.
     n=0;
     while (bss_link != NULL) {
         bss_link = bss_link->next.stqe_next;
         n++;
     }
     //Allocate memory for access point data
     cgiWifiAps.apData=(ApData **)os_malloc(sizeof(ApData *)*n);
     cgiWifiAps.noAps=n;
     INFO("Scan done: found %d APs\n", n);
     //Copy access point data to the static struct
     n=0;
     bss_link = (struct bss_info *)arg;
     while (bss_link != NULL) {
         if (n>=cgiWifiAps.noAps) {
             //This means the bss_link changed under our nose. Shouldn't happen!
             //Break because otherwise we will write in unallocated memory.
             INFO("Huh? I have more than the allocated %d aps!\n", cgiWifiAps.noAps);
             break;
         }
         //Save the ap data.
         cgiWifiAps.apData[n]=(ApData *)os_malloc(sizeof(ApData));
         cgiWifiAps.apData[n]->rssi=bss_link->rssi;
         cgiWifiAps.apData[n]->enc=bss_link->authmode;
         strncpy(cgiWifiAps.apData[n]->ssid, (char*)bss_link->ssid, 32);
         bss_link = bss_link->next.stqe_next;
         n++;
     }
     //We're done.
     cgiWifiAps.scanInProgress=0;
 }
wifiStartScan()
static void ICACHE_FLASH_ATTR wifiStartScan () static
Definition at line 98 of file cgiwifi.c.
References NULL, ScanResultData::scanInProgress, wifi_station_scan(), and wifiScanDoneCb().
Referenced by cgiWiFiScan().
{
 //  int x;
     if (cgiWifiAps.scanInProgress) return;
     cgiWifiAps.scanInProgress=1;
     wifi_station_scan(NULL, wifiScanDoneCb);
 }
Variable Documentation
cgiWifiAps
ScanResultData cgiWifiAps
Definition at line 41 of file cgiwifi.c.
resetTimer
os_timer_t resetTimer static
Definition at line 43 of file cgiwifi.c.
Referenced by cgiSetup().