MeterLogger: modules/include/config.h File Reference
config.h File Reference
#include "user_config.h"
#include "cron/cron.h"
Data Structures
struct syscfg_t
struct SAVE_FLAG
Macros
#define METER_SERIAL_LEN 8
Functions
void ICACHE_FLASH_ATTR cfg_save ()
void ICACHE_FLASH_ATTR cfg_load ()
void ICACHE_FLASH_ATTR cfg_save_defered ()
ICACHE_FLASH_ATTR void config_save_timer_func (void *arg)
Variables
static const char key [] = KEY
syscfg_t sys_cfg
Macro Definition Documentation
METER_SERIAL_LEN
#define METER_SERIAL_LEN 8
Definition at line 39 of file config.h.
Function Documentation
cfg_load()
void ICACHE_FLASH_ATTR cfg_load ()
Definition at line 77 of file config.c.
References ccit_crc16(), syscfg_t::ccit_crc16, CFG_LOCATION, cfg_save(), DEFAULT_METER_SERIAL, DEFAULT_SECURITY, EXT_CFG_LOCATION, ext_spi_flash_read(), EXT_SPI_RAM_SEC_SIZE, ICACHE_FLASH_ATTR, INFO, key, memcpy, memset, MQTT_CLIENT_ID, MQTT_HOST, MQTT_KEEPALIVE, MQTT_PASS, MQTT_PORT, MQTT_USER, os_memset, os_printf(), STA_PASS, STA_SSID, STA_TYPE, system_get_chip_id(), system_param_load(), and tfp_snprintf().
Referenced by tplSetup().
            {
     // DEBUG: we suppose nothing else is touching sys_cfg while saving otherwise checksum becomes wrong
     INFO("\r\nload ...\r\n");
 #if defined(IMPULSE) && !defined(DEBUG_NO_METER)    // use internal flash if built with DEBUG_NO_METER=1
     ext_spi_flash_read((EXT_CFG_LOCATION + 2) * EXT_SPI_RAM_SEC_SIZE,
                    (uint32 *)&saveFlag, sizeof(SAVE_FLAG));
     if (saveFlag.flag == 0) {
         ext_spi_flash_read((EXT_CFG_LOCATION + 0) * EXT_SPI_RAM_SEC_SIZE,
                        (uint32 *)&sys_cfg, sizeof(syscfg_t));
     } else {
         ext_spi_flash_read((EXT_CFG_LOCATION + 1) * EXT_SPI_RAM_SEC_SIZE,
                        (uint32 *)&sys_cfg, sizeof(syscfg_t));
     }
 #else
     system_param_load(CFG_LOCATION, 0, &sys_cfg, sizeof(syscfg_t));
 #endif  // IMPULSE
     // if checksum fails...
     if (sys_cfg.ccit_crc16 != ccit_crc16(0xffff, (uint8_t *)&sys_cfg, offsetof(syscfg_t, ccit_crc16) - offsetof(syscfg_t, cfg_holder))) {
 #ifdef DEBUG
         os_printf("config crc error, default conf loaded\n");
 #endif // DEBUG
         // if first time config load default conf
         os_memset(&sys_cfg, 0x00, sizeof(syscfg_t));
         tfp_snprintf(sys_cfg.sta_ssid, 64, "%s", STA_SSID);
         tfp_snprintf(sys_cfg.sta_pwd, 64, "%s", STA_PASS);
         sys_cfg.sta_type = STA_TYPE;
 #ifdef AP
         sys_cfg.ap_enabled = true;
 #else
         sys_cfg.ap_enabled = false;
 #endif
         tfp_snprintf(sys_cfg.device_id, 16, MQTT_CLIENT_ID, system_get_chip_id());
         tfp_snprintf(sys_cfg.mqtt_host, 64, "%s", MQTT_HOST);
         sys_cfg.mqtt_port = MQTT_PORT;
         tfp_snprintf(sys_cfg.mqtt_user, 32, "%s", MQTT_USER);
         tfp_snprintf(sys_cfg.mqtt_pass, 32, "%s", MQTT_PASS);
         sys_cfg.security = DEFAULT_SECURITY;    //default non ssl
         memcpy(sys_cfg.key, key, sizeof(key));
         sys_cfg.mqtt_keepalive = MQTT_KEEPALIVE;
 #ifdef IMPULSE
         tfp_snprintf(sys_cfg.impulse_meter_serial, IMPULSE_METER_SERIAL_LEN, DEFAULT_METER_SERIAL);
         tfp_snprintf(sys_cfg.impulse_meter_energy, 2, "0");
         tfp_snprintf(sys_cfg.impulses_per_kwh, 4, "100");
         sys_cfg.impulse_meter_count = 0;
 #else
         sys_cfg.ac_thermo_state = 0;
         sys_cfg.offline_close_at = 0;
         memset(&sys_cfg.cron_jobs, 0, sizeof(cron_job_t));
 #endif  // IMPULSE
         INFO(" default configuration\r\n");
         cfg_save();
     }
     else {
 #ifdef DEBUG
         os_printf("config crc ok\n");
 #endif // DEBUG
     }
 }
cfg_save()
void ICACHE_FLASH_ATTR cfg_save ()
Definition at line 28 of file config.c.
References ccit_crc16(), syscfg_t::ccit_crc16, CFG_LOCATION, EXT_CFG_LOCATION, ext_spi_flash_erase_sector(), ext_spi_flash_read(), ext_spi_flash_write(), EXT_SPI_RAM_SEC_SIZE, ICACHE_FLASH_ATTR, and system_param_save_with_protect().
Referenced by cfg_load(), cgiSetup(), and config_save_timer_func().
            {
 #ifdef IMPULSE
     uint32_t impulse_meter_count_temp;
 #endif // IMPULSE
 #if defined(IMPULSE) && !defined(DEBUG_NO_METER)    // use internal flash if built with DEBUG_NO_METER=1
     do {
         // try to save until sys_cfg.impulse_meter_count does not change
         impulse_meter_count_temp = sys_cfg.impulse_meter_count;
         // calculate checksum on sys_cfg struct without ccit_crc16
         sys_cfg.ccit_crc16 = ccit_crc16(0xffff, (uint8_t *)&sys_cfg, offsetof(syscfg_t, ccit_crc16) - offsetof(syscfg_t, cfg_holder));
         ext_spi_flash_read((EXT_CFG_LOCATION + 2) * EXT_SPI_RAM_SEC_SIZE,
                            (uint32 *)&saveFlag, sizeof(SAVE_FLAG));
         if (saveFlag.flag == 0) {
 #ifdef EXT_SPI_RAM_IS_NAND
             ext_spi_flash_erase_sector(EXT_CFG_LOCATION + 1);
 #endif  // EXT_SPI_RAM_IS_NAND
             ext_spi_flash_write((EXT_CFG_LOCATION + 1) * EXT_SPI_RAM_SEC_SIZE,
                             (uint32 *)&sys_cfg, sizeof(syscfg_t));
             saveFlag.flag = 1;
 #ifdef EXT_SPI_RAM_IS_NAND
             ext_spi_flash_erase_sector(EXT_CFG_LOCATION + 2);
 #endif  // EXT_SPI_RAM_IS_NAND
             ext_spi_flash_write((EXT_CFG_LOCATION + 2) * EXT_SPI_RAM_SEC_SIZE,
                             (uint32 *)&saveFlag, sizeof(SAVE_FLAG));
         } else {
 #ifdef EXT_SPI_RAM_IS_NAND
             ext_spi_flash_erase_sector(EXT_CFG_LOCATION + 0);
 #endif  // EXT_SPI_RAM_IS_NAND
             ext_spi_flash_write((EXT_CFG_LOCATION + 0) * EXT_SPI_RAM_SEC_SIZE,
                             (uint32 *)&sys_cfg, sizeof(syscfg_t));
             saveFlag.flag = 0;
 #ifdef EXT_SPI_RAM_IS_NAND
             ext_spi_flash_erase_sector(EXT_CFG_LOCATION + 2);
 #endif  // EXT_SPI_RAM_IS_NAND
             ext_spi_flash_write((EXT_CFG_LOCATION + 2) * EXT_SPI_RAM_SEC_SIZE,
                             (uint32 *)&saveFlag, sizeof(SAVE_FLAG));
         }
     } while (sys_cfg.impulse_meter_count != impulse_meter_count_temp);
 #else
     // calculate checksum on sys_cfg struct without ccit_crc16
     sys_cfg.ccit_crc16 = ccit_crc16(0xffff, (uint8_t *)&sys_cfg, offsetof(syscfg_t, ccit_crc16) - offsetof(syscfg_t, cfg_holder));
     system_param_save_with_protect(CFG_LOCATION, &sys_cfg, sizeof(syscfg_t));
 #endif  // IMPULSE
 }
cfg_save_defered()
void ICACHE_FLASH_ATTR cfg_save_defered ()
Definition at line 144 of file config.c.
References config_save_timer, config_save_timer_func(), ICACHE_FLASH_ATTR, NULL, os_timer_arm, os_timer_disarm, os_timer_func_t, os_timer_setfn, and SAVE_DEFER_TIME.
Referenced by ac_thermo_close(), ac_thermo_open(), add_cron_job_from_query(), and clear_cron_jobs().
                    {
     os_timer_disarm(&config_save_timer);
     os_timer_setfn(&config_save_timer, (os_timer_func_t *)config_save_timer_func, NULL);
     os_timer_arm(&config_save_timer, SAVE_DEFER_TIME, 0);
 }
config_save_timer_func()
ICACHE_FLASH_ATTR void config_save_timer_func (void * arg)
Definition at line 151 of file config.c.
References cfg_save(), config_save_timer, config_save_timer_func(), config_save_timer_running, NULL, os_timer_arm, os_timer_disarm, os_timer_func_t, os_timer_setfn, and SAVE_DEFER_TIME.
Referenced by cfg_save_defered(), and config_save_timer_func().
{
     if (config_save_timer_running) {
         // reschedule
         os_timer_disarm(&config_save_timer);
         os_timer_setfn(&config_save_timer, (os_timer_func_t *)config_save_timer_func, NULL);
         os_timer_arm(&config_save_timer, SAVE_DEFER_TIME, 0);
     }
     else {
         // stop timer
         os_timer_disarm(&config_save_timer);
         config_save_timer_running = 0;
         cfg_save();
     }
 }
Variable Documentation
key
const char key[] = KEY static
Definition at line 42 of file config.h.
Referenced by add_cron_job_from_query(), BlockCopy(), and cfg_load().
sys_cfg
syscfg_t sys_cfg
Definition at line 12 of file config.c.
Referenced by ac_thermo_close(), ac_thermo_open(), add_cron_job_from_query(), cgiSetup(), clear_cron_jobs(), cron_init(), minute_timer_func(), tplSetup(), wifi_connect(), wifi_handle_event_cb(), and wifi_scan_done_cb().