MeterLogger: esp-open-lwip/lwip/core/def.c File Reference
def.c File Reference
#include "lwip/opt.h"
#include "lwip/def.h"
Functions
u16_t lwip_htons (u16_t n)
u16_t lwip_ntohs (u16_t n)
u32_t lwip_htonl (u32_t n)
u32_t lwip_ntohl (u32_t n)
Detailed Description
Common functions used throughout the stack.
Definition in file def.c.
Function Documentation
lwip_htonl()
u32_t lwip_htonl (u32_t n)
Convert an u32_t from host- to network byte order.
Parameters
n u32_t in host byte order
Returns
n in network byte order
Definition at line 88 of file def.c.
Referenced by ip4_addr_netmask_valid(), and lwip_ntohl().
 {
   return ((n & 0xff) << 24) |
     ((n & 0xff00) << 8) |
     ((n & 0xff0000UL) >> 8) |
     ((n & 0xff000000UL) >> 24);
 }
lwip_htons()
u16_t lwip_htons (u16_t n)
These are reference implementations of the byte swapping functions. Again with the aim of being simple, correct and fully portable. Byte swapping is the second thing you would want to optimize. You will need to port it to your architecture and in your cc.h:
#define LWIP_PLATFORM_BYTESWAP 1 #define LWIP_PLATFORM_HTONS(x) <your_htons> #define LWIP_PLATFORM_HTONL(x) <your_htonl>
Note ntohs() and ntohl() are merely references to the htonx counterparts. Convert an u16_t from host- to network byte order.
Parameters
n u16_t in host byte order
Returns
n in network byte order
Definition at line 64 of file def.c.
Referenced by lwip_ntohs().
 {
   return ((n & 0xff) << 8) | ((n & 0xff00) >> 8);
 }
lwip_ntohl()
u32_t lwip_ntohl (u32_t n)
Convert an u32_t from network- to host byte order.
Parameters
n u32_t in network byte order
Returns
n in host byte order
Definition at line 103 of file def.c.
References lwip_htonl().
 {
   return lwip_htonl(n);
 }
lwip_ntohs()
u16_t lwip_ntohs (u16_t n)
Convert an u16_t from network- to host byte order.
Parameters
n u16_t in network byte order
Returns
n in host byte order
Definition at line 76 of file def.c.
References lwip_htons().
 {
   return lwip_htons(n);
 }