MeterLogger: esp-open-lwip/lwip/app/espconn.c File Reference
espconn.c File Reference
#include "lwip/netif.h"
#include "lwip/inet.h"
#include "netif/etharp.h"
#include "lwip/tcp.h"
#include "lwip/ip.h"
#include "lwip/init.h"
#include "ets_sys.h"
#include "os_type.h"
#include "lwip/mem.h"
#include "lwip/app/espconn_tcp.h"
#include "lwip/app/espconn_udp.h"
#include "lwip/app/espconn.h"
#include "user_interface.h"
Functions
static uint8 espconn_tcp_get_buf_count (espconn_buf *pesp_buf)
void ICACHE_FLASH_ATTR espconn_copy_partial (struct espconn *pesp_dest, struct espconn *pesp_source)
void ICACHE_FLASH_ATTR espconn_list_creat (espconn_msg **phead, espconn_msg *pinsert)
void ICACHE_FLASH_ATTR espconn_list_delete (espconn_msg **phead, espconn_msg *pdelete)
void ICACHE_FLASH_ATTR espconn_pbuf_create (espconn_buf **phead, espconn_buf *pinsert)
void ICACHE_FLASH_ATTR espconn_pbuf_delete (espconn_buf **phead, espconn_buf *pdelete)
bool ICACHE_FLASH_ATTR espconn_find_connection (struct espconn *pespconn, espconn_msg **pnode)
static uint8 ICACHE_FLASH_ATTR espconn_get_acticve_num (uint8 type)
sint8 ICACHE_FLASH_ATTR espconn_connect (struct espconn *espconn)
sint8 ICACHE_FLASH_ATTR espconn_create (struct espconn *espconn)
sint8 ICACHE_FLASH_ATTR espconn_sent (struct espconn *espconn, uint8 *psent, uint16 length)
sint16 ICACHE_FLASH_ATTR espconn_sendto (struct espconn *espconn, uint8 *psent, uint16 length)
sint8 espconn_send (struct espconn *espconn, uint8 *psent, uint16 length) __attribute__((alias("espconn_sent")))
uint8 ICACHE_FLASH_ATTR espconn_tcp_get_wnd (void)
sint8 ICACHE_FLASH_ATTR espconn_tcp_set_wnd (uint8 num)
uint16 ICACHE_FLASH_ATTR espconn_tcp_get_mss (void)
uint8 ICACHE_FLASH_ATTR espconn_tcp_get_max_con (void)
sint8 ICACHE_FLASH_ATTR espconn_tcp_set_max_con (uint8 num)
uint8 ICACHE_FLASH_ATTR espconn_tcp_get_max_retran (void)
sint8 ICACHE_FLASH_ATTR espconn_tcp_set_max_retran (uint8 num)
uint8 ICACHE_FLASH_ATTR espconn_tcp_get_max_syn (void)
sint8 ICACHE_FLASH_ATTR espconn_tcp_set_max_syn (uint8 num)
sint8 ICACHE_FLASH_ATTR espconn_tcp_get_max_con_allow (struct espconn *espconn)
sint8 ICACHE_FLASH_ATTR espconn_tcp_set_max_con_allow (struct espconn *espconn, uint8 num)
sint8 ICACHE_FLASH_ATTR espconn_tcp_set_buf_count (struct espconn *espconn, uint8 num)
sint8 ICACHE_FLASH_ATTR espconn_regist_sentcb (struct espconn *espconn, espconn_sent_callback sent_cb)
sint8 ICACHE_FLASH_ATTR espconn_regist_write_finish (struct espconn *espconn, espconn_connect_callback write_finish_fn)
sint8 ICACHE_FLASH_ATTR espconn_regist_connectcb (struct espconn *espconn, espconn_connect_callback connect_cb)
sint8 ICACHE_FLASH_ATTR espconn_regist_recvcb (struct espconn *espconn, espconn_recv_callback recv_cb)
sint8 ICACHE_FLASH_ATTR espconn_regist_reconcb (struct espconn *espconn, espconn_reconnect_callback recon_cb)
sint8 ICACHE_FLASH_ATTR espconn_regist_disconcb (struct espconn *espconn, espconn_connect_callback discon_cb)
sint8 ICACHE_FLASH_ATTR espconn_get_connection_info (struct espconn *pespconn, remot_info **pcon_info, uint8 typeflags)
sint8 ICACHE_FLASH_ATTR espconn_accept (struct espconn *espconn)
sint8 ICACHE_FLASH_ATTR espconn_regist_time (struct espconn *espconn, uint32 interval, uint8 type_flag)
sint8 ICACHE_FLASH_ATTR espconn_disconnect (struct espconn *espconn)
sint8 ICACHE_FLASH_ATTR espconn_abort (struct espconn *espconn)
sint8 ICACHE_FLASH_ATTR espconn_get_packet_info (struct espconn *espconn, struct espconn_packet *infoarg)
sint8 ICACHE_FLASH_ATTR espconn_set_opt (struct espconn *espconn, uint8 opt)
sint8 ICACHE_FLASH_ATTR espconn_clear_opt (struct espconn *espconn, uint8 opt)
sint8 ICACHE_FLASH_ATTR espconn_set_keepalive (struct espconn *espconn, uint8 level, void *optarg)
sint8 ICACHE_FLASH_ATTR espconn_get_keepalive (struct espconn *espconn, uint8 level, void *optarg)
sint8 ICACHE_FLASH_ATTR espconn_delete (struct espconn *espconn)
uint32 ICACHE_FLASH_ATTR espconn_port (void)
err_t ICACHE_FLASH_ATTR espconn_gethostbyname (struct espconn *pespconn, const char *hostname, ip_addr_t *addr, dns_found_callback found)
void ICACHE_FLASH_ATTR espconn_dns_setserver (u8_t numdns, ip_addr_t *dnsserver)
Variables
espconn_msg * plink_active = NULL
espconn_msg * pserver_list = NULL
remot_info premot [linkMax]
struct espconn_packet pktinfo [2]
Function Documentation
espconn_abort()
sint8 ICACHE_FLASH_ATTR espconn_abort (struct espconn * espconn)
Definition at line 972 of file espconn.c.
References ESPCONN_ARG, ESPCONN_CLOSE, espconn_find_connection(), ESPCONN_INPROGRESS, ESPCONN_OK, ESPCONN_TCP, espconn_tcp_disconnect(), ICACHE_FLASH_ATTR, NULL, and espconn::state.
Referenced by mqtt_tcpclient_delete().
 {
     espconn_msg *pnode = NULL;
     bool value = false;
     if (espconn == NULL) {
         return ESPCONN_ARG;;
     } else if (espconn ->type != ESPCONN_TCP)
         return ESPCONN_ARG;
     /*Find the node depend on the espconn message*/
     value = espconn_find_connection(espconn, &pnode);
     if (value){
         /*protect for redisconnection*/
         if (espconn->state == ESPCONN_CLOSE)
             return ESPCONN_INPROGRESS;
         espconn_tcp_disconnect(pnode,1);    //1 force, 0 normal
         return ESPCONN_OK;
     } else
         return ESPCONN_ARG;
 }
espconn_accept()
sint8 ICACHE_FLASH_ATTR espconn_accept (struct espconn * espconn)
Definition at line 875 of file espconn.c.
References ESPCONN_ARG, ESPCONN_ISCONN, ESPCONN_OK, ESPCONN_TCP, espconn_tcp_server(), _esp_tcp::local_port, NULL, _espconn_msg::pespconn, plist, _espconn_msg::pnext, espconn::proto, espconn::tcp, and espconn::type.
Referenced by httpdInit().
 {
     sint8 value = ESPCONN_OK;
     espconn_msg *plist = NULL;
     if (espconn == NULL) {
         return ESPCONN_ARG;
     } else if (espconn ->type != ESPCONN_TCP)
         return ESPCONN_ARG;
     /*check the active node information whether is the same as the entity or not*/
     for (plist = plink_active; plist != NULL; plist = plist->pnext){
         if (plist->pespconn && plist->pespconn->type == ESPCONN_TCP){
             if (espconn->proto.tcp->local_port == plist->pespconn->proto.tcp->local_port){
                 return ESPCONN_ISCONN;
             }
         }
     }
     value = espconn_tcp_server(espconn);
     return value;
 }
espconn_clear_opt()
sint8 ICACHE_FLASH_ATTR espconn_clear_opt (struct espconn * espconn, uint8 opt)
Definition at line 1092 of file espconn.c.
References ESPCONN_ARG, espconn_delay_enabled, espconn_find_connection(), espconn_keepalive_disable, espconn_keepalive_enabled, ESPCONN_OK, _comon_pkt::espconn_opt, ESPCONN_TCP, NULL, _comon_pkt::pcb, _espconn_msg::pcommon, and espconn::type.
 {
     espconn_msg *pnode = NULL;
     struct tcp_pcb *tpcb;
     bool value = false;
     if (espconn == NULL) {
         return ESPCONN_ARG;;
     } else if (espconn->type != ESPCONN_TCP)
         return ESPCONN_ARG;
     /*Find the node depend on the espconn message*/
     value = espconn_find_connection(espconn, &pnode);
     if (value) {
         pnode->pcommon.espconn_opt &= ~opt;
         tpcb = pnode->pcommon.pcb;
         if (espconn_keepalive_enabled(pnode))
             espconn_keepalive_disable(tpcb);
         if (espconn_delay_enabled(pnode))
             tcp_nagle_enable(tpcb);
         return ESPCONN_OK;
     } else
         return ESPCONN_ARG;
 }
espconn_connect()
sint8 ICACHE_FLASH_ATTR espconn_connect (struct espconn * espconn)
Definition at line 260 of file espconn.c.
References ip_addr::addr, AP_NETIF, ESPCONN_AP, ESPCONN_AP_STA, ESPCONN_ARG, espconn_get_acticve_num(), ESPCONN_ISCONN, ESPCONN_OK, espconn_printf, ESPCONN_RTE, ESPCONN_STA, ESPCONN_TCP, espconn_tcp_client(), espconn_tcp_get_max_con(), ICACHE_FLASH_ATTR, ip_info::ip, IP4_ADDR, _esp_tcp::local_port, NULL, _espconn_msg::pespconn, plist, _espconn_msg::pnext, espconn::proto, _esp_tcp::remote_ip, STA_NETIF, STATION_GOT_IP, STATION_IDLE, espconn::tcp, espconn::type, wifi_get_ip_info(), wifi_get_opmode(), and wifi_station_get_connect_status().
Referenced by MQTT_Connect(), and mqtt_dns_found().
 {
     struct ip_addr ipaddr;
     struct ip_info ipinfo;
     uint8 connect_status = 0;
     sint8 value = ESPCONN_OK;
     espconn_msg *plist = NULL;
     remot_info *pinfo = NULL;
     if (espconn == NULL) {
         return ESPCONN_ARG;
     } else if (espconn ->type != ESPCONN_TCP)
         return ESPCONN_ARG;
     /*Check the active node count whether is the limit or not*/
     if (espconn_get_acticve_num(ESPCONN_TCP) >= espconn_tcp_get_max_con())
         return ESPCONN_ISCONN;
     /*Check the IP address whether is zero or not in different mode*/
     if (wifi_get_opmode() == ESPCONN_STA){
         wifi_get_ip_info(STA_NETIF,&ipinfo);
         if (ipinfo.ip.addr == 0){
             return ESPCONN_RTE;
         }
     } else if(wifi_get_opmode() == ESPCONN_AP){
         wifi_get_ip_info(AP_NETIF,&ipinfo);
         if (ipinfo.ip.addr == 0){
             return ESPCONN_RTE;
         }
     } else if(wifi_get_opmode() == ESPCONN_AP_STA){
         IP4_ADDR(&ipaddr, espconn->proto.tcp->remote_ip[0],
                             espconn->proto.tcp->remote_ip[1],
                             espconn->proto.tcp->remote_ip[2],
                             espconn->proto.tcp->remote_ip[3]);
         ipaddr.addr <<= 8;
         wifi_get_ip_info(AP_NETIF,&ipinfo);
         ipinfo.ip.addr <<= 8;
         espconn_printf("softap_addr = %x, remote_addr = %x\n", ipinfo.ip.addr, ipaddr.addr);
         if (ipaddr.addr != ipinfo.ip.addr){
             connect_status = wifi_station_get_connect_status();
             if (connect_status == STATION_GOT_IP){
                 wifi_get_ip_info(STA_NETIF,&ipinfo);
                 if (ipinfo.ip.addr == 0)
                     return ESPCONN_RTE;
             } else if (connect_status == STATION_IDLE){
                 return ESPCONN_RTE;
             } else {
                 return connect_status;
             }
         }
     }
     /*check the active node information whether is the same as the entity or not*/
     for (plist = plink_active; plist != NULL; plist = plist->pnext){
         if (plist->pespconn && plist->pespconn->type == ESPCONN_TCP){
             if (espconn->proto.tcp->local_port == plist->pespconn->proto.tcp->local_port){
                 return ESPCONN_ISCONN;
             }
         }
     }
     value = espconn_tcp_client(espconn);
     return value;
 }
espconn_copy_partial()
void ICACHE_FLASH_ATTR espconn_copy_partial (struct espconn * pesp_dest, struct espconn * pesp_source)
Definition at line 46 of file espconn.c.
References _esp_tcp::connect_callback, _esp_tcp::disconnect_callback, ESPCONN_TCP, espconn::link_cnt, _esp_tcp::local_ip, _esp_udp::local_ip, _esp_tcp::local_port, _esp_udp::local_port, os_memcpy, espconn::proto, _esp_tcp::reconnect_callback, espconn::recv_callback, _esp_tcp::remote_ip, _esp_udp::remote_ip, _esp_tcp::remote_port, _esp_udp::remote_port, espconn::reverse, espconn::sent_callback, espconn::state, espconn::tcp, espconn::type, and espconn::udp.
Referenced by espconn_tcp_accept(), espconn_tcp_disconnect_successful(), and espconn_tcp_reconnect().
 {
     pesp_dest->type = pesp_source->type;
     pesp_dest->state = pesp_source->state;
     if (pesp_source->type == ESPCONN_TCP){
         pesp_dest->proto.tcp->remote_port = pesp_source->proto.tcp->remote_port;
         pesp_dest->proto.tcp->local_port = pesp_source->proto.tcp->local_port;
         os_memcpy(pesp_dest->proto.tcp->remote_ip, pesp_source->proto.tcp->remote_ip, 4);
         os_memcpy(pesp_dest->proto.tcp->local_ip, pesp_source->proto.tcp->local_ip, 4);
         pesp_dest->proto.tcp->connect_callback = pesp_source->proto.tcp->connect_callback;
         pesp_dest->proto.tcp->reconnect_callback = pesp_source->proto.tcp->reconnect_callback;
         pesp_dest->proto.tcp->disconnect_callback = pesp_source->proto.tcp->disconnect_callback;
     } else {
         pesp_dest->proto.udp->remote_port = pesp_source->proto.udp->remote_port;
         pesp_dest->proto.udp->local_port = pesp_source->proto.udp->local_port;
         os_memcpy(pesp_dest->proto.udp->remote_ip, pesp_source->proto.udp->remote_ip, 4);
         os_memcpy(pesp_dest->proto.udp->local_ip, pesp_source->proto.udp->local_ip, 4);
     }
     pesp_dest->recv_callback = pesp_source->recv_callback;
     pesp_dest->sent_callback = pesp_source->sent_callback;
     pesp_dest->link_cnt = pesp_source->link_cnt;
     pesp_dest->reverse = pesp_source->reverse;
 }
espconn_create()
sint8 ICACHE_FLASH_ATTR espconn_create (struct espconn * espconn)
Definition at line 334 of file espconn.c.
References ESPCONN_ARG, ESPCONN_ISCONN, ESPCONN_OK, ESPCONN_UDP, espconn_udp_server(), ICACHE_FLASH_ATTR, _esp_udp::local_port, NULL, _espconn_msg::pespconn, plist, _espconn_msg::pnext, espconn::proto, espconn::type, and espconn::udp.
Referenced by captdnsInit().
 {
     sint8 value = ESPCONN_OK;
     espconn_msg *plist = NULL;
     if (espconn == NULL) {
         return ESPCONN_ARG;
     } else if (espconn ->type != ESPCONN_UDP){
         return ESPCONN_ARG;
     }
     /*check the active node information whether is the same as the entity or not*/
     for (plist = plink_active; plist != NULL; plist = plist->pnext){
         if (plist->pespconn && plist->pespconn->type == ESPCONN_UDP){
             if (espconn->proto.udp->local_port == plist->pespconn->proto.udp->local_port){
                 return ESPCONN_ISCONN;
             }
         }
     }
     value = espconn_udp_server(espconn);
     return value;
 }
espconn_delete()
sint8 ICACHE_FLASH_ATTR espconn_delete (struct espconn * espconn)
Definition at line 1217 of file espconn.c.
References ESPCONN_ARG, espconn_find_connection(), ESPCONN_OK, espconn_tcp_delete(), ESPCONN_UDP, espconn_udp_disconnect(), ICACHE_FLASH_ATTR, and NULL.
Referenced by captdnsStop(), httpdStop(), and mqtt_tcpclient_delete().
 {
     espconn_msg *pnode = NULL;
     bool value = false;
     if (espconn == NULL) {
         return ESPCONN_ARG;
     } else if (espconn ->type != ESPCONN_UDP)
         return espconn_tcp_delete(espconn);
     /*Find the node depend on the espconn message*/
     value = espconn_find_connection(espconn, &pnode);
     if (value){
         espconn_udp_disconnect(pnode);
         return ESPCONN_OK;
     } else
         return ESPCONN_ARG;
 }
espconn_disconnect()
sint8 ICACHE_FLASH_ATTR espconn_disconnect (struct espconn * espconn)
Definition at line 942 of file espconn.c.
References ESPCONN_ARG, ESPCONN_CLOSE, espconn_find_connection(), ESPCONN_INPROGRESS, ESPCONN_OK, ESPCONN_TCP, espconn_tcp_disconnect(), ICACHE_FLASH_ATTR, NULL, and espconn::state.
Referenced by httpdConnectCb(), httpdSentCb(), httpdStop(), MQTT_Task(), and mqtt_tcpclient_recv().
 {
     espconn_msg *pnode = NULL;
     bool value = false;
     if (espconn == NULL) {
         return ESPCONN_ARG;;
     } else if (espconn ->type != ESPCONN_TCP)
         return ESPCONN_ARG;
     /*Find the node depend on the espconn message*/
     value = espconn_find_connection(espconn, &pnode);
     if (value){
         /*protect for redisconnection*/
         if (espconn->state == ESPCONN_CLOSE)
             return ESPCONN_INPROGRESS;
         espconn_tcp_disconnect(pnode,0);    //1 force, 0 normal
         return ESPCONN_OK;
     } else
         return ESPCONN_ARG;
 }
espconn_dns_setserver()
void ICACHE_FLASH_ATTR espconn_dns_setserver (u8_t numdns, ip_addr_t * dnsserver)
Definition at line 1302 of file espconn.c.
Referenced by wifi_softap_ip_config().
 {
     dns_setserver(numdns,dnsserver);
 }
espconn_find_connection()
bool ICACHE_FLASH_ATTR espconn_find_connection (struct espconn * pespconn, espconn_msg ** pnode)
Definition at line 186 of file espconn.c.
References ip_addr::addr, ICACHE_FLASH_ATTR, IP4_ADDR, IPADDR_ANY, NULL, _espconn_msg::pcommon, _espconn_msg::pespconn, plist, _espconn_msg::pnext, espconn::proto, _esp_tcp::remote_ip, _comon_pkt::remote_ip, _esp_tcp::remote_port, _comon_pkt::remote_port, and espconn::tcp.
Referenced by espconn_abort(), espconn_clear_opt(), espconn_delete(), espconn_disconnect(), espconn_get_keepalive(), espconn_get_packet_info(), espconn_recv_hold(), espconn_recv_unhold(), espconn_regist_time(), espconn_sendto(), espconn_sent(), espconn_set_keepalive(), and espconn_set_opt().
 {
     espconn_msg *plist = NULL;
     struct ip_addr ip_remot;
     struct ip_addr ip_list;
     if (pespconn == NULL)
         return false;
     /*find the active connection node*/
     for (plist = plink_active; plist != NULL; plist = plist->pnext){
         if (pespconn == plist->pespconn) {
             *pnode = plist;
             return true;
         }
     }
     /*find the active server node*/
     for (plist = pserver_list; plist != NULL; plist = plist->pnext){
         if (pespconn == plist->pespconn) {
             if (pespconn->proto.tcp == NULL)
                 return false;
             IP4_ADDR(&ip_remot, pespconn->proto.tcp->remote_ip[0],
                     pespconn->proto.tcp->remote_ip[1],
                     pespconn->proto.tcp->remote_ip[2],
                     pespconn->proto.tcp->remote_ip[3]);
             if ((ip_remot.addr == IPADDR_ANY) || (pespconn->proto.tcp->remote_port == 0))
                 return false;
             /*find the active connection node*/
             for (plist = plink_active; plist != NULL; plist = plist->pnext){
                 IP4_ADDR(&ip_list, plist->pcommon.remote_ip[0],
                         plist->pcommon.remote_ip[1], plist->pcommon.remote_ip[2],
                         plist->pcommon.remote_ip[3]);
                 if ((ip_list.addr == ip_remot.addr) && (pespconn->proto.tcp->remote_port == plist->pcommon.remote_port)) {
                     *pnode = plist;
                     return true;
                 }
             }
             return false;
         }
     }
     return false;
 }
espconn_get_acticve_num()
static uint8 ICACHE_FLASH_ATTR espconn_get_acticve_num (uint8 type) static
Definition at line 239 of file espconn.c.
References ICACHE_FLASH_ATTR, NULL, _espconn_msg::pespconn, plist, _espconn_msg::pnext, and espconn::type.
Referenced by espconn_connect().
 {
     espconn_msg *plist = NULL;
     uint8 num_tcp_active = 0;
     for (plist = plink_active; plist != NULL; plist = plist->pnext) {
         if (plist->pespconn != NULL && plist->pespconn->type == type) {
             num_tcp_active++;
         }
     }
     return num_tcp_active;
 }
espconn_get_connection_info()
sint8 ICACHE_FLASH_ATTR espconn_get_connection_info (struct espconn * pespconn, remot_info ** pcon_info, uint8 typeflags)
Definition at line 825 of file espconn.c.
References ESPCONN_ARG, ESPCONN_OK, ESPCONN_TCP, ESPCONN_UDP, ICACHE_FLASH_ATTR, espconn::link_cnt, NULL, os_memcpy, os_memset, _espconn_msg::pcommon, _espconn_msg::pespconn, plink_active, plist, _espconn_msg::pnext, premot, _espconn_msg::preverse, _remot_info::remote_ip, _comon_pkt::remote_ip, _remot_info::remote_port, _comon_pkt::remote_port, _remot_info::state, espconn::state, and espconn::type.
Referenced by captdnsRecv(), espconn_tcp_accept(), and espconn_tcp_delete().
 {
     espconn_msg *plist = NULL;
     if (pespconn == NULL)
         return ESPCONN_ARG;
     os_memset(premot, 0, sizeof(premot));
     pespconn->link_cnt = 0;
     plist = plink_active;
     switch (pespconn->type){
         case ESPCONN_TCP:
             while(plist != NULL){
                 if (plist->preverse == pespconn){
                     premot[pespconn->link_cnt].state = plist->pespconn->state;
                     premot[pespconn->link_cnt].remote_port = plist->pcommon.remote_port;
                     os_memcpy(premot[pespconn->link_cnt].remote_ip, plist->pcommon.remote_ip, 4);
                     pespconn->link_cnt ++;
                 }
                 plist = plist->pnext;
             }
             break;
         case ESPCONN_UDP:
             while(plist != NULL){
                 if (plist->pespconn == pespconn){
                     premot[pespconn->link_cnt].state = plist->pespconn->state;
                     premot[pespconn->link_cnt].remote_port = plist->pcommon.remote_port;
                     os_memcpy(premot[pespconn->link_cnt].remote_ip, plist->pcommon.remote_ip, 4);
                     pespconn->link_cnt ++;
                 }
                 plist = plist->pnext;
             }
             break;
         default:
             break;
     }
     *pcon_info = premot;
     if (pespconn->link_cnt == 0)
         return ESPCONN_ARG;
     return ESPCONN_OK;
 }
espconn_get_keepalive()
sint8 ICACHE_FLASH_ATTR espconn_get_keepalive (struct espconn * espconn, uint8 level, void * optarg)
Definition at line 1173 of file espconn.c.
References ESPCONN_ARG, espconn_find_connection(), espconn_keepalive_disabled, ESPCONN_KEEPCNT, ESPCONN_KEEPIDLE, ESPCONN_KEEPINTVL, ESPCONN_OK, ESPCONN_TCP, ICACHE_FLASH_ATTR, NULL, _comon_pkt::pcb, _espconn_msg::pcommon, and espconn::type.
 {
     espconn_msg *pnode = NULL;
     bool value = false;
     sint8 ret = ESPCONN_OK;
     if (espconn == NULL || optarg == NULL) {
         return ESPCONN_ARG;;
     } else if (espconn->type != ESPCONN_TCP)
         return ESPCONN_ARG;
     /*Find the node depend on the espconn message*/
     value = espconn_find_connection(espconn, &pnode);
     if (value && espconn_keepalive_disabled(pnode)) {
         struct tcp_pcb *pcb = pnode->pcommon.pcb;
         switch (level) {
         case ESPCONN_KEEPIDLE:
             *(int*)optarg = (int)(pcb->keep_idle/1000);
             ret = ESPCONN_OK;
             break;
         case ESPCONN_KEEPINTVL:
             *(int*)optarg = (int)(pcb->keep_intvl/1000);
             ret = ESPCONN_OK;
             break;
         case ESPCONN_KEEPCNT:
             *(int*)optarg = (int)(pcb->keep_cnt);
             ret = ESPCONN_OK;
             break;
         default:
             ret = ESPCONN_ARG;
             break;
         }
         return ret;
     } else
         return ESPCONN_ARG;
 }
espconn_get_packet_info()
sint8 ICACHE_FLASH_ATTR espconn_get_packet_info (struct espconn * espconn, struct espconn_packet * infoarg)
Definition at line 1004 of file espconn.c.
References ESPCONN_ARG, ESPCONN_CLOSE, espconn_find_connection(), ESPCONN_NONE, ESPCONN_OK, ESPCONN_TCP, ICACHE_FLASH_ATTR, NULL, os_memcpy, _comon_pkt::packet_info, espconn_packet::packseq_nxt, espconn_packet::packseqno, _comon_pkt::pcb, _espconn_msg::pcommon, pktinfo, espconn_packet::snd_buf_size, espconn_packet::snd_queuelen, espconn::state, TCP_SND_QUEUELEN, espconn_packet::total_queuelen, and espconn::type.
 {
     espconn_msg *pnode = NULL;
     err_t err;
     bool value = false;
     if (espconn == NULL || infoarg == NULL) {
         return ESPCONN_ARG;;
     } else if (espconn->type != ESPCONN_TCP)
         return ESPCONN_ARG;
     /*Find the node depend on the espconn message*/
     value = espconn_find_connection(espconn, &pnode);
     if (value) {
         struct tcp_pcb *pcb = pnode->pcommon.pcb;
         if (pcb == NULL)
             return ESPCONN_ARG;
         pnode->pcommon.packet_info.packseq_nxt = pcb->rcv_nxt;
         pnode->pcommon.packet_info.packseqno = pcb->snd_nxt;
         pnode->pcommon.packet_info.snd_buf_size = pcb->snd_buf;
         pnode->pcommon.packet_info.total_queuelen = TCP_SND_QUEUELEN;
         pnode->pcommon.packet_info.snd_queuelen = pnode->pcommon.packet_info.total_queuelen - pcb->snd_queuelen;
         os_memcpy(infoarg,(void*)&pnode->pcommon.packet_info, sizeof(struct espconn_packet));
         return ESPCONN_OK;
     } else {
         switch (espconn->state){
             case ESPCONN_CLOSE:
                 os_memcpy(infoarg,(void*)&pktinfo[0], sizeof(struct espconn_packet));
                 err = ESPCONN_OK;
                 break;
             case ESPCONN_NONE:
                 os_memcpy(infoarg,(void*)&pktinfo[1], sizeof(struct espconn_packet));
                 err = ESPCONN_OK;
                 break;
             default:
                 err = ESPCONN_ARG;
                 break;
         }
         return err;
     }
 }
espconn_gethostbyname()
err_t ICACHE_FLASH_ATTR espconn_gethostbyname (struct espconn * pespconn, const char * hostname, ip_addr_t * addr, dns_found_callback found)
Definition at line 1288 of file espconn.c.
References ICACHE_FLASH_ATTR.
Referenced by MQTT_Connect().
 {
     return dns_gethostbyname(hostname, addr, found, pespconn);
 }
espconn_list_creat()
void ICACHE_FLASH_ATTR espconn_list_creat (espconn_msg ** phead, espconn_msg * pinsert)
Definition at line 76 of file espconn.c.
References NULL, plist, and _espconn_msg::pnext.
Referenced by espconn_tcp_accept(), espconn_tcp_client(), espconn_tcp_server(), and espconn_udp_server().
 {
     espconn_msg *plist = NULL;
 //  espconn_msg *ptest = NULL;
     if (*phead == NULL)
         *phead = pinsert;
     else {
         plist = *phead;
         while (plist->pnext != NULL) {
             plist = plist->pnext;
         }
         plist->pnext = pinsert;
     }
     pinsert->pnext = NULL;
 /*  ptest = *phead;
     while(ptest != NULL){
         os_printf("espconn_list_creat %p\n", ptest);
         ptest = ptest->pnext;
     }*/
 }
espconn_list_delete()
void ICACHE_FLASH_ATTR espconn_list_delete (espconn_msg ** phead, espconn_msg * pdelete)
Definition at line 104 of file espconn.c.
References NULL, plist, and _espconn_msg::pnext.
Referenced by espconn_Task(), espconn_tcp_client(), espconn_tcp_delete(), and espconn_udp_disconnect().
 {
     espconn_msg *plist = NULL;
 //  espconn_msg *ptest = NULL;
     plist = *phead;
     if (plist == NULL){
         *phead = NULL;
     } else {
         if (plist == pdelete){
             *phead = plist->pnext;
         } else {
             while (plist != NULL) {
                 if (plist->pnext == pdelete){
                     plist->pnext = pdelete->pnext;
                 }
                 plist = plist->pnext;
             }
         }
     }
 /*  ptest = *phead;
     while(ptest != NULL){
         os_printf("espconn_list_delete %p\n", ptest);
         ptest = ptest->pnext;
     }*/
 }
espconn_pbuf_create()
void ICACHE_FLASH_ATTR espconn_pbuf_create (espconn_buf ** phead, espconn_buf * pinsert)
Definition at line 136 of file espconn.c.
References NULL, plist, and _espconn_buf::pnext.
Referenced by espconn_sent().
 {
     espconn_buf *plist = NULL;
     if (*phead == NULL)
         *phead = pinsert;
     else {
         plist = *phead;
         while (plist->pnext != NULL) {
             plist = plist->pnext;
         }
         plist->pnext = pinsert;
     }
     pinsert->pnext = NULL;
 }
espconn_pbuf_delete()
void ICACHE_FLASH_ATTR espconn_pbuf_delete (espconn_buf ** phead, espconn_buf * pdelete)
Definition at line 158 of file espconn.c.
References NULL, plist, and _espconn_buf::pnext.
Referenced by espconn_tcp_disconnect_successful(), espconn_tcp_finish(), and espconn_tcp_reconnect().
 {
     espconn_buf *plist = NULL;
     plist = *phead;
     if (plist == NULL){
         *phead = NULL;
     } else {
         if (plist == pdelete){
             *phead = plist->pnext;
         } else {
             while (plist != NULL) {
                 if (plist->pnext == pdelete){
                     plist->pnext = pdelete->pnext;
                 }
                 plist = plist->pnext;
             }
         }
     }
 }
espconn_port()
uint32 ICACHE_FLASH_ATTR espconn_port (void)
Definition at line 1245 of file espconn.c.
References ICACHE_FLASH_ATTR, and os_random().
Referenced by MQTT_Connect().
 {
     uint32 port = 0;
     static uint32 randnum = 0;
     do {
         port = os_random();
         if (port < 0) {
             port = os_random() - port;
         }
         port %= 0xc350;
         if (port < 0x400) {
             port += 0x400;
         }
     } while (port == randnum);
     randnum = port;
     return port;
 }
espconn_regist_connectcb()
sint8 ICACHE_FLASH_ATTR espconn_regist_connectcb (struct espconn * espconn, espconn_connect_callback connect_cb)
Definition at line 751 of file espconn.c.
References _esp_tcp::connect_callback, ESPCONN_ARG, ESPCONN_OK, ICACHE_FLASH_ATTR, NULL, espconn::proto, and espconn::tcp.
Referenced by httpdInit(), and MQTT_Connect().
 {
     if (espconn == NULL) {
         return ESPCONN_ARG;
     }
     espconn->proto.tcp->connect_callback = connect_cb;
     return ESPCONN_OK;
 }
espconn_regist_disconcb()
sint8 ICACHE_FLASH_ATTR espconn_regist_disconcb (struct espconn * espconn, espconn_connect_callback discon_cb)
Definition at line 807 of file espconn.c.
References _esp_tcp::disconnect_callback, ESPCONN_ARG, ESPCONN_OK, ICACHE_FLASH_ATTR, NULL, espconn::proto, and espconn::tcp.
Referenced by httpdConnectCb(), and mqtt_tcpclient_connect_cb().
 {
     if (espconn == NULL) {
         return ESPCONN_ARG;
     }
     espconn ->proto.tcp->disconnect_callback = discon_cb;
     return ESPCONN_OK;
 }
espconn_regist_reconcb()
sint8 ICACHE_FLASH_ATTR espconn_regist_reconcb (struct espconn * espconn, espconn_reconnect_callback recon_cb)
Definition at line 789 of file espconn.c.
References ESPCONN_ARG, ESPCONN_OK, ICACHE_FLASH_ATTR, NULL, espconn::proto, _esp_tcp::reconnect_callback, and espconn::tcp.
Referenced by httpdConnectCb(), and MQTT_Connect().
 {
     if (espconn == NULL) {
         return ESPCONN_ARG;
     }
     espconn ->proto.tcp->reconnect_callback = recon_cb;
     return ESPCONN_OK;
 }
espconn_regist_recvcb()
sint8 ICACHE_FLASH_ATTR espconn_regist_recvcb (struct espconn * espconn, espconn_recv_callback recv_cb)
Definition at line 770 of file espconn.c.
References ESPCONN_ARG, ESPCONN_OK, ICACHE_FLASH_ATTR, NULL, and espconn::recv_callback.
Referenced by captdnsInit(), httpdConnectCb(), and mqtt_tcpclient_connect_cb().
 {
     if (espconn == NULL) {
         return ESPCONN_ARG;
     }
     espconn ->recv_callback = recv_cb;
     return ESPCONN_OK;
 }
espconn_regist_sentcb()
sint8 ICACHE_FLASH_ATTR espconn_regist_sentcb (struct espconn * espconn, espconn_sent_callback sent_cb)
Definition at line 712 of file espconn.c.
References ESPCONN_ARG, ESPCONN_OK, ICACHE_FLASH_ATTR, NULL, and espconn::sent_callback.
Referenced by httpdConnectCb(), and mqtt_tcpclient_connect_cb().
 {
     if (espconn == NULL) {
         return ESPCONN_ARG;
     }
     espconn ->sent_callback = sent_cb;
     return ESPCONN_OK;
 }
espconn_regist_time()
sint8 ICACHE_FLASH_ATTR espconn_regist_time (struct espconn * espconn, uint32 interval, uint8 type_flag)
Definition at line 905 of file espconn.c.
References ESPCONN_ARG, espconn_find_connection(), ESPCONN_OK, ICACHE_FLASH_ATTR, NULL, _espconn_msg::pcommon, _espconn_msg::pespconn, _espconn_msg::pnext, pserver_list, and _comon_pkt::timeout.
 {
     espconn_msg *pnode = NULL;
     espconn_msg *ptime_msg = NULL;
     bool value = false;
     if ((espconn == NULL) || (type_flag > 0x01))
         return ESPCONN_ARG;
     if (type_flag == 0x01){
         /*set the timeout time for one active connection of the server*/
         value = espconn_find_connection(espconn, &pnode);
         if (value){
             pnode->pcommon.timeout = interval;
             return ESPCONN_OK;
         } else
             return ESPCONN_ARG;
     } else {
         /*set the timeout time for all active connection of the server*/
         ptime_msg = pserver_list;
         while (ptime_msg != NULL){
             if (ptime_msg->pespconn == espconn){
                 ptime_msg->pcommon.timeout = interval;
                 return ESPCONN_OK;
             }
             ptime_msg = ptime_msg->pnext;
         }
     }
     return ESPCONN_ARG;
 }
espconn_regist_write_finish()
sint8 ICACHE_FLASH_ATTR espconn_regist_write_finish (struct espconn * espconn, espconn_connect_callback write_finish_fn)
Definition at line 732 of file espconn.c.
References ESPCONN_ARG, ESPCONN_OK, ESPCONN_UDP, ICACHE_FLASH_ATTR, NULL, espconn::proto, espconn::tcp, espconn::type, and _esp_tcp::write_finish_fn.
 {
     if (espconn == NULL || espconn ->proto.tcp == NULL || espconn->type == ESPCONN_UDP) {
         return ESPCONN_ARG;
     }
     espconn ->proto.tcp->write_finish_fn = write_finish_fn;
     return ESPCONN_OK;
 }
espconn_send()
sint8 espconn_send (struct espconn * espconn, uint8 * psent, uint16 length)
Referenced by espconn_sendto(), mqtt_send_keepalive(), MQTT_Task(), and mqtt_tcpclient_connect_cb().
espconn_sendto()
sint16 ICACHE_FLASH_ATTR espconn_sendto (struct espconn * espconn, uint8 * psent, uint16 length)
Definition at line 448 of file espconn.c.
References __attribute__(), ESPCONN_ARG, espconn_find_connection(), ESPCONN_OK, espconn_send(), ESPCONN_UDP, espconn_udp_sendto(), NULL, and espconn::type.
Referenced by captdnsRecv().
 {
     espconn_msg *pnode = NULL;
     bool value = false;
     err_t error = ESPCONN_OK;
     if (espconn == NULL || psent == NULL || length == 0) {
         return ESPCONN_ARG;
     }
     /*Find the node depend on the espconn message*/
     value = espconn_find_connection(espconn, &pnode);
     if (value && espconn->type == ESPCONN_UDP)
         return espconn_udp_sendto(pnode, psent, length);
     else
         return ESPCONN_ARG;
 }
espconn_sent()
sint8 ICACHE_FLASH_ATTR espconn_sent (struct espconn * espconn, uint8 * psent, uint16 length)
Definition at line 368 of file espconn.c.
References ESPCONN_ARG, espconn_copy_disabled, espconn_copy_enabled, espconn_find_connection(), ESPCONN_MAXNUM, ESPCONN_MEM, ESPCONN_OK, espconn_pbuf_create(), ESPCONN_TCP, espconn_tcp_get_buf_count(), espconn_tcp_write(), ESPCONN_UDP, espconn_udp_sent(), ESPCONN_WRITE, ICACHE_FLASH_ATTR, _espconn_buf::len, NULL, os_zalloc, _espconn_buf::payload, _comon_pkt::pbuf, _comon_pkt::pbuf_num, _comon_pkt::pcb, _espconn_msg::pcommon, _comon_pkt::ptail, _espconn_buf::punsent, espconn::state, TCP_SND_QUEUELEN, _espconn_buf::unsent, and _comon_pkt::write_flag.
Referenced by cgiEspFsHook(), and xmitSendBuff().
 {
     espconn_msg *pnode = NULL;
     bool value = false;
     err_t error = ESPCONN_OK;
     if (espconn == NULL || psent == NULL || length == 0) {
         return ESPCONN_ARG;
     }
     /*Find the node depend on the espconn message*/
     value = espconn_find_connection(espconn, &pnode);
     if (value){
         espconn ->state = ESPCONN_WRITE;
         switch (espconn ->type) {
             case ESPCONN_TCP:
                 /* calling sent function frequently,make sure last packet has been backup or sent fully*/
                 if (pnode->pcommon.write_flag){
                     espconn_buf *pbuf = NULL;
                     /*If total number of espconn_buf on the unsent lists exceeds the set maximum, return an error */
                     if (espconn_copy_enabled(pnode)){
                         if (espconn_tcp_get_buf_count(pnode->pcommon.pbuf) >= pnode ->pcommon.pbuf_num)
                             return ESPCONN_MAXNUM;
                     } else {
                         struct tcp_pcb *pcb = pnode->pcommon.pcb;
                         if (pcb->snd_queuelen >= TCP_SND_QUEUELEN)
                             return ESPCONN_MAXNUM;
                     }
                     pbuf = (espconn_buf*) os_zalloc(sizeof(espconn_buf));
                     if (pbuf == NULL)
                         return ESPCONN_MEM;
                     else {
                         /*Backup the application packet information for send more data*/
                         pbuf->payload = psent;
                         pbuf->punsent = pbuf->payload;
                         pbuf->unsent = length;
                         pbuf->len = length;
                         /*insert the espconn_pbuf to the list*/
                         espconn_pbuf_create(&pnode->pcommon.pbuf, pbuf);
                         if (pnode->pcommon.ptail == NULL)
                             pnode->pcommon.ptail = pbuf;
                     }
                     /*when set the data copy option. change the flag for next packet*/
                     if (espconn_copy_disabled(pnode))
                         pnode->pcommon.write_flag = false;
                     error = espconn_tcp_write(pnode);
 //                  if (error != ESPCONN_OK){
 //                      /*send the application packet fail,
 //                       * ensure that each allocated is deleted*/
 //                      espconn_pbuf_delete(&pnode->pcommon.pbuf, pbuf);
 //                      os_free(pbuf);
 //                      pbuf = NULL;
 //                  }
                     return error;
                 } else
                     return ESPCONN_ARG;
                 break;
             case ESPCONN_UDP:
                 return espconn_udp_sent(pnode, psent, length);
                 break;
             default :
                 break;
         }
     }
     return ESPCONN_ARG;
 }
espconn_set_keepalive()
sint8 ICACHE_FLASH_ATTR espconn_set_keepalive (struct espconn * espconn, uint8 level, void * optarg)
Definition at line 1128 of file espconn.c.
References ESPCONN_ARG, espconn_find_connection(), espconn_keepalive_disabled, ESPCONN_KEEPCNT, ESPCONN_KEEPIDLE, ESPCONN_KEEPINTVL, ESPCONN_OK, ESPCONN_TCP, NULL, _comon_pkt::pcb, _espconn_msg::pcommon, and espconn::type.
Referenced by MQTT_Connect().
 {
     espconn_msg *pnode = NULL;
     bool value = false;
     sint8 ret = ESPCONN_OK;
     if (espconn == NULL || optarg == NULL) {
         return ESPCONN_ARG;;
     } else if (espconn->type != ESPCONN_TCP)
         return ESPCONN_ARG;
     /*Find the node depend on the espconn message*/
     value = espconn_find_connection(espconn, &pnode);
     if (value && espconn_keepalive_disabled(pnode)) {
         struct tcp_pcb *pcb = pnode->pcommon.pcb;
         switch (level){
             case ESPCONN_KEEPIDLE:
                 pcb->keep_idle = 1000 * (u32_t)(*(int*)optarg);
                 ret = ESPCONN_OK;
                 break;
             case ESPCONN_KEEPINTVL:
                 pcb->keep_intvl = 1000 * (u32_t)(*(int*)optarg);
                 ret = ESPCONN_OK;
                 break;
             case ESPCONN_KEEPCNT:
                 pcb->keep_cnt = (u32_t)(*(int*)optarg);
                 ret = ESPCONN_OK;
                 break;
             default:
                 ret = ESPCONN_ARG;
                 break;
         }
         return ret;
     } else
         return ESPCONN_ARG;
 }
espconn_set_opt()
sint8 ICACHE_FLASH_ATTR espconn_set_opt (struct espconn * espconn, uint8 opt)
Definition at line 1056 of file espconn.c.
References ESPCONN_ARG, espconn_delay_disabled, espconn_find_connection(), espconn_keepalive_disabled, espconn_keepalive_enable, ESPCONN_OK, _comon_pkt::espconn_opt, ESPCONN_TCP, ICACHE_FLASH_ATTR, NULL, _comon_pkt::pcb, _espconn_msg::pcommon, and espconn::type.
Referenced by MQTT_Connect().
 {
     espconn_msg *pnode = NULL;
     struct tcp_pcb *tpcb;
     bool value = false;
     if (espconn == NULL) {
         return ESPCONN_ARG;;
     } else if (espconn->type != ESPCONN_TCP)
         return ESPCONN_ARG;
     /*Find the node depend on the espconn message*/
     value = espconn_find_connection(espconn, &pnode);
     if (value) {
         pnode->pcommon.espconn_opt |= opt;
         tpcb = pnode->pcommon.pcb;
         if (espconn_delay_disabled(pnode))
             tcp_nagle_disable(tpcb);
         if (espconn_keepalive_disabled(pnode))
             espconn_keepalive_enable(tpcb);
         return ESPCONN_OK;
     } else
         return ESPCONN_ARG;
 }
espconn_tcp_get_buf_count()
static uint8 ICACHE_FLASH_ATTR espconn_tcp_get_buf_count (espconn_buf * pesp_buf) static
Definition at line 689 of file espconn.c.
References ICACHE_FLASH_ATTR, NULL, and _espconn_buf::pnext.
Referenced by espconn_sent().
 {
     espconn_buf *pbuf_list = pesp_buf;
     uint8 pbuf_num = 0;
     /*polling the list get the count of the current node*/
     while (pbuf_list != NULL){
         pbuf_list = pbuf_list->pnext;
         pbuf_num ++;
     }
     return pbuf_num;
 }
espconn_tcp_get_max_con()
uint8 ICACHE_FLASH_ATTR espconn_tcp_get_max_con (void)
Definition at line 528 of file espconn.c.
References MEMP_NUM_TCP_PCB.
Referenced by espconn_connect().
 {
     uint8 tcp_num = 0;
     tcp_num = MEMP_NUM_TCP_PCB;
     return tcp_num;
 }
espconn_tcp_get_max_con_allow()
sint8 ICACHE_FLASH_ATTR espconn_tcp_get_max_con_allow (struct espconn * espconn)
Definition at line 618 of file espconn.c.
References _espconn_msg::count_opt, ESPCONN_ARG, ESPCONN_UDP, NULL, _espconn_msg::pespconn, _espconn_msg::pnext, pserver_list, and espconn::type.
Referenced by espconn_tcp_accept().
 {
     espconn_msg *pget_msg = NULL;
     if ((espconn == NULL) || (espconn->type == ESPCONN_UDP))
         return ESPCONN_ARG;
     pget_msg = pserver_list;
     while (pget_msg != NULL){
         if (pget_msg->pespconn == espconn){
             return pget_msg->count_opt;
         }
         pget_msg = pget_msg->pnext;
     }
     return ESPCONN_ARG;
 }
espconn_tcp_get_max_retran()
uint8 ICACHE_FLASH_ATTR espconn_tcp_get_max_retran (void)
Definition at line 558 of file espconn.c.
References TCP_MAXRTX.
 {
     uint8 tcp_num = 0;
     tcp_num = TCP_MAXRTX;
     return tcp_num;
 }
espconn_tcp_get_max_syn()
uint8 ICACHE_FLASH_ATTR espconn_tcp_get_max_syn (void)
Definition at line 588 of file espconn.c.
References TCP_SYNMAXRTX.
 {
     uint8 tcp_num = 0;
     tcp_num = TCP_SYNMAXRTX;
     return tcp_num;
 }
espconn_tcp_get_mss()
uint16 ICACHE_FLASH_ATTR espconn_tcp_get_mss (void)
Definition at line 513 of file espconn.c.
References TCP_MSS.
 {
     uint16 tcp_num = 0;
     tcp_num = TCP_MSS;
     return tcp_num;
 }
espconn_tcp_get_wnd()
uint8 ICACHE_FLASH_ATTR espconn_tcp_get_wnd (void)
Definition at line 483 of file espconn.c.
References TCP_MSS, and TCP_WND.
 {
     uint8 tcp_num = 0;
     tcp_num = (TCP_WND / TCP_MSS);
     return tcp_num;
 }
espconn_tcp_set_buf_count()
sint8 ICACHE_FLASH_ATTR espconn_tcp_set_buf_count (struct espconn * espconn, uint8 num)
Definition at line 665 of file espconn.c.
References ESPCONN_ARG, ESPCONN_OK, ESPCONN_TCP, NULL, _comon_pkt::pbuf_num, _espconn_msg::pcommon, _espconn_msg::pespconn, plist, _espconn_msg::pnext, TCP_SND_QUEUELEN, and espconn::type.
Referenced by espconn_client_connect(), and espconn_tcp_accept().
 {
     espconn_msg *plist = NULL;
     if (espconn == NULL || (num > TCP_SND_QUEUELEN))
         return ESPCONN_ARG;
     /*find the node from the active connection list*/
     for (plist = plink_active; plist != NULL; plist = plist->pnext){
         if (plist->pespconn && plist->pespconn == espconn && espconn->type == ESPCONN_TCP){
             plist->pcommon.pbuf_num = num;
             return ESPCONN_OK;
         }
     }
     if (plist == NULL)
         return ESPCONN_ARG;
 }
espconn_tcp_set_max_con()
sint8 ICACHE_FLASH_ATTR espconn_tcp_set_max_con (uint8 num)
Definition at line 543 of file espconn.c.
References ESPCONN_ARG, ESPCONN_OK, linkMax, and MEMP_NUM_TCP_PCB.
 {
     if (num == 0 || num > linkMax)
         return ESPCONN_ARG;
     MEMP_NUM_TCP_PCB = num;
     return ESPCONN_OK;
 }
espconn_tcp_set_max_con_allow()
sint8 ICACHE_FLASH_ATTR espconn_tcp_set_max_con_allow (struct espconn * espconn, uint8 num)
Definition at line 640 of file espconn.c.
References _espconn_msg::count_opt, ESPCONN_ARG, ESPCONN_OK, ESPCONN_UDP, MEMP_NUM_TCP_PCB, NULL, _espconn_msg::pespconn, _espconn_msg::pnext, pserver_list, and espconn::type.
 {
     espconn_msg *pset_msg = NULL;
     if ((espconn == NULL) || (num > MEMP_NUM_TCP_PCB) || (espconn->type == ESPCONN_UDP))
         return ESPCONN_ARG;
     pset_msg = pserver_list;
     while (pset_msg != NULL){
         if (pset_msg->pespconn == espconn){
             pset_msg->count_opt = num;
             return ESPCONN_OK;
         }
         pset_msg = pset_msg->pnext;
     }
     return ESPCONN_ARG;
 }
espconn_tcp_set_max_retran()
sint8 ICACHE_FLASH_ATTR espconn_tcp_set_max_retran (uint8 num)
Definition at line 573 of file espconn.c.
References ESPCONN_ARG, ESPCONN_OK, and TCP_MAXRTX.
 {
     if (num == 0 || num > 12)
         return ESPCONN_ARG;
     TCP_MAXRTX = num;
     return ESPCONN_OK;
 }
espconn_tcp_set_max_syn()
sint8 ICACHE_FLASH_ATTR espconn_tcp_set_max_syn (uint8 num)
Definition at line 603 of file espconn.c.
References ESPCONN_ARG, ESPCONN_OK, and TCP_SYNMAXRTX.
 {
     if (num == 0 || num > 12)
         return ESPCONN_ARG;
     TCP_SYNMAXRTX = num;
     return ESPCONN_OK;
 }
espconn_tcp_set_wnd()
sint8 ICACHE_FLASH_ATTR espconn_tcp_set_wnd (uint8 num)
Definition at line 498 of file espconn.c.
References ESPCONN_ARG, ESPCONN_OK, linkMax, TCP_MSS, and TCP_WND.
 {
     if (num == 0 || num > linkMax)
         return ESPCONN_ARG;
     TCP_WND = (num * TCP_MSS);
     return ESPCONN_OK;
 }
Variable Documentation
pktinfo
struct espconn_packet pktinfo[2]
Definition at line 36 of file espconn.c.
Referenced by espconn_get_packet_info(), espconn_tcp_disconnect_successful(), and espconn_tcp_reconnect().
plink_active
espconn_msg* plink_active = NULL
Definition at line 32 of file espconn.c.
Referenced by espconn_get_connection_info().
premot
remot_info premot[linkMax]
Definition at line 34 of file espconn.c.
Referenced by espconn_get_connection_info().
pserver_list
espconn_msg* pserver_list = NULL
Definition at line 33 of file espconn.c.
Referenced by espconn_regist_time(), espconn_server_poll(), espconn_tcp_delete(), espconn_tcp_get_max_con_allow(), and espconn_tcp_set_max_con_allow().