MeterLogger: esp-open-lwip/include/lwip/app/espconn_tcp.h File Reference
espconn_tcp.h File Reference
#include "lwip/app/espconn.h"
Macros
#define ESPCONN_TCP_DEBUG LWIP_DBG_OFF
#define ESPCONN_TCP_TIMER 40
#define espconn_keepalive_enable(pcb) ((pcb)->so_options |= SOF_KEEPALIVE)
#define espconn_keepalive_disable(pcb) ((pcb)->so_options &= ~SOF_KEEPALIVE)
Functions
void espconn_kill_oldest_pcb (void)
void espconn_tcp_disconnect (espconn_msg *pdiscon, u8 type)
sint8 espconn_tcp_client (struct espconn *espconn)
sint8 espconn_tcp_server (struct espconn *espconn)
Macro Definition Documentation
espconn_keepalive_disable
#define espconn_keepalive_disable (pcb) ((pcb)->so_options &= ~SOF_KEEPALIVE)
Definition at line 14 of file espconn_tcp.h.
Referenced by espconn_clear_opt().
espconn_keepalive_enable
#define espconn_keepalive_enable (pcb) ((pcb)->so_options |= SOF_KEEPALIVE)
Definition at line 13 of file espconn_tcp.h.
Referenced by espconn_client_connect(), espconn_set_opt(), and espconn_tcp_accept().
ESPCONN_TCP_DEBUG
#define ESPCONN_TCP_DEBUG LWIP_DBG_OFF
Definition at line 5 of file espconn_tcp.h.
ESPCONN_TCP_TIMER
#define ESPCONN_TCP_TIMER 40
Definition at line 10 of file espconn_tcp.h.
Function Documentation
espconn_kill_oldest_pcb()
void espconn_kill_oldest_pcb (void)
Definition at line 115 of file espconn_tcp.c.
References espconn_kill_oldest(), MEMP_NUM_TCP_PCB, NULL, and tcp_pcb_lists.
Referenced by espconn_tcp_disconnect_successful(), and espconn_tcp_reconnect().
 {
     struct tcp_pcb *cpcb = NULL;
     uint8 i = 0;
     uint8 num_tcp_fin = 0;
     for(i = 2; i < 4; i ++){
         for (cpcb = *tcp_pcb_lists[i]; cpcb != NULL; cpcb = cpcb->next) {
             if (cpcb->state == TIME_WAIT){
                 num_tcp_fin ++;
                 if (num_tcp_fin == MEMP_NUM_TCP_PCB)
                     break;
             }
             if (cpcb->state == FIN_WAIT_1 || cpcb->state == FIN_WAIT_2 || cpcb->state == LAST_ACK){
                 num_tcp_fin++;
                 if (num_tcp_fin == MEMP_NUM_TCP_PCB)
                     break;
             }
         }
         if (num_tcp_fin == MEMP_NUM_TCP_PCB){
             num_tcp_fin = 0;
             espconn_kill_oldest();
         } else if (cpcb == NULL){
             num_tcp_fin = 0;
         }
     }
 }
espconn_tcp_client()
sint8 espconn_tcp_client (struct espconn * espconn)
Definition at line 878 of file espconn_tcp.c.
References ERR_OK, ERR_RTE, ERR_USE, espconn_client_connect(), espconn_client_err(), espconn_kill_pcb(), espconn_list_creat(), espconn_list_delete(), ESPCONN_MEM, ESPCONN_RTE, ESPCONN_WAIT, ICACHE_FLASH_ATTR, IP4_ADDR, IP_ADDR_ANY, memp_free(), NULL, os_free, os_zalloc, espconn::proto, _esp_tcp::remote_ip, espconn::state, and espconn::tcp.
Referenced by espconn_connect().
 {
     struct tcp_pcb *pcb = NULL;
     struct ip_addr ipaddr;
     espconn_msg *pclient = NULL;
     /*Creates a new client control message*/
     pclient = (espconn_msg *)os_zalloc(sizeof(espconn_msg));
     if (pclient == NULL){
         return ESPCONN_MEM;
     }
     /*Set an IP address given for Little-endian.*/
     IP4_ADDR(&ipaddr, espconn->proto.tcp->remote_ip[0],
             espconn->proto.tcp->remote_ip[1],
             espconn->proto.tcp->remote_ip[2],
             espconn->proto.tcp->remote_ip[3]);
     /*Creates a new TCP protocol control block*/
     pcb = tcp_new();
     if (pcb == NULL) {
         /*to prevent memory leaks, ensure that each allocated is deleted*/
         os_free(pclient);
         pclient = NULL;
         return ESPCONN_MEM;
     } else {
         /*insert the node to the active connection list*/
         espconn_list_creat(&plink_active, pclient);
         tcp_arg(pcb, (void *)pclient);
         tcp_err(pcb, espconn_client_err);
         pclient->preverse = NULL;
         pclient->pespconn = espconn;
         pclient->pespconn->state = ESPCONN_WAIT;
         pclient->pcommon.pcb = pcb;
         tcp_bind(pcb, IP_ADDR_ANY, pclient->pespconn->proto.tcp->local_port);
 #if 0
         pclient->pcommon.err = tcp_bind(pcb, IP_ADDR_ANY, pclient->pespconn->proto.tcp->local_port);
         if (pclient->pcommon.err != ERR_OK){
             /*remove the node from the client's active connection list*/
             espconn_list_delete(&plink_active, pclient);
             memp_free(MEMP_TCP_PCB, pcb);
             os_free(pclient);
             pclient = NULL;
             return ERR_USE;
         }
 #endif
         /*Establish the connection*/
         pclient->pcommon.err = tcp_connect(pcb, &ipaddr,
                 pclient->pespconn->proto.tcp->remote_port, espconn_client_connect);
         if (pclient->pcommon.err == ERR_RTE){
             /*remove the node from the client's active connection list*/
             espconn_list_delete(&plink_active, pclient);
             espconn_kill_pcb(pcb->local_port);
             os_free(pclient);
             pclient = NULL;
             return ESPCONN_RTE;
         }
         return pclient->pcommon.err;
     }
 }
espconn_tcp_disconnect()
void espconn_tcp_disconnect (espconn_msg * pdiscon, u8 type)
Definition at line 498 of file espconn_tcp.c.
References espconn_client_close(), espconn_printf, espconn_server_close(), ICACHE_FLASH_ATTR, NULL, _comon_pkt::pcb, _espconn_msg::pcommon, and _espconn_msg::preverse.
Referenced by espconn_abort(), and espconn_disconnect().
 {
     if (pdiscon != NULL){
         /*disconnect with the host by send the FIN frame*/
         if (pdiscon->preverse != NULL)
             espconn_server_close(pdiscon, pdiscon->pcommon.pcb,type);
         else
             espconn_client_close(pdiscon, pdiscon->pcommon.pcb,type);
     } else{
         espconn_printf("espconn_tcp_disconnect err.\n");
     }
 }
espconn_tcp_server()
sint8 espconn_tcp_server (struct espconn * espconn)
Definition at line 1281 of file espconn_tcp.c.
References _espconn_msg::count_opt, espconn_list_creat(), ESPCONN_LISTEN, ESPCONN_MEM, ESPCONN_OK, espconn_tcp_accept(), IP_ADDR_ANY, _esp_tcp::local_port, memp_free(), MEMP_NUM_TCP_PCB, NULL, os_free, os_zalloc, _espconn_msg::pcommon, _espconn_msg::pespconn, _espconn_msg::preverse, espconn::proto, espconn::state, espconn::tcp, and _comon_pkt::timeout.
Referenced by espconn_accept().
 {
     struct tcp_pcb *pcb = NULL;
     espconn_msg *pserver = NULL;
     /*Creates a new server control message*/
     pserver = (espconn_msg *)os_zalloc(sizeof(espconn_msg));
     if (pserver == NULL){
         return ESPCONN_MEM;
     }
     /*Creates a new TCP protocol control block*/
     pcb = tcp_new();
     if (pcb == NULL) {
         /*to prevent memory leaks, ensure that each allocated is deleted*/
         os_free(pserver);
         pserver = NULL;
         return ESPCONN_MEM;
     } else {
         struct tcp_pcb *lpcb = NULL;
         /*Binds the connection to a local port number and any IP address*/
         tcp_bind(pcb, IP_ADDR_ANY, espconn->proto.tcp->local_port);
         lpcb = pcb;
         /*malloc and set the state of the connection to be LISTEN*/
         pcb = tcp_listen(pcb);
         if (pcb != NULL) {
             /*insert the node to the active connection list*/
             espconn_list_creat(&pserver_list, pserver);
             pserver->preverse = pcb;
             pserver->pespconn = espconn;
             pserver->count_opt = MEMP_NUM_TCP_PCB;
             pserver->pcommon.timeout = 0x0a;
             espconn ->state = ESPCONN_LISTEN;
             /*set the specify argument that should be passed callback function*/
             tcp_arg(pcb, (void *)espconn);
             /*accept callback function to call for this control block*/
             tcp_accept(pcb, espconn_tcp_accept);
             return ESPCONN_OK;
         } else {
             /*to prevent memory leaks, ensure that each allocated is deleted*/
             memp_free(MEMP_TCP_PCB,lpcb);
             os_free(pserver);
             pserver = NULL;
             return ESPCONN_MEM;
         }
     }
 }