MeterLogger: sdk/include/espconn.h File Reference
espconn.h File Reference
Data Structures
struct _esp_tcp
struct _esp_udp
struct _remot_info
struct espconn
Macros
#define ESPCONN_OK 0 /* No error, everything OK. */
#define ESPCONN_MEM -1 /* Out of memory error. */
#define ESPCONN_TIMEOUT -3 /* Timeout. */
#define ESPCONN_RTE -4 /* Routing problem. */
#define ESPCONN_INPROGRESS -5 /* Operation in progress */
#define ESPCONN_ABRT -8 /* Connection aborted. */
#define ESPCONN_RST -9 /* Connection reset. */
#define ESPCONN_CLSD -10 /* Connection closed. */
#define ESPCONN_CONN -11 /* Not connected. */
#define ESPCONN_ARG -12 /* Illegal argument. */
#define ESPCONN_ISCONN -15 /* Already connected. */
Typedefs
typedef sint8 err_t
typedef void * espconn_handle
typedef void(* espconn_connect_callback) (void *arg)
typedef void(* espconn_reconnect_callback) (void *arg, sint8 err)
typedef struct _esp_tcp esp_tcp
typedef struct _esp_udp esp_udp
typedef struct _remot_info remot_info
typedef void(* espconn_recv_callback) (void *arg, char *pdata, unsigned short len)
typedef void(* espconn_sent_callback) (void *arg)
typedef void(* dns_found_callback) (const char *name, ip_addr_t *ipaddr, void *callback_arg)
Enumerations
enum espconn_type { ESPCONN_INVALID = 0, ESPCONN_TCP = 0x10, ESPCONN_UDP = 0x20 }
enum espconn_state {
ESPCONN_NONE, ESPCONN_WAIT, ESPCONN_LISTEN, ESPCONN_CONNECT,
ESPCONN_WRITE, ESPCONN_READ, ESPCONN_CLOSE
}
enum espconn_option { ESPCONN_REUSEADDR = 1, ESPCONN_NODELAY, ESPCONN_END }
Functions
sint8 espconn_connect (struct espconn *espconn)
sint8 espconn_disconnect (struct espconn *espconn)
sint8 espconn_delete (struct espconn *espconn)
sint8 espconn_accept (struct espconn *espconn)
sint8 espconn_create (struct espconn *espconn)
uint8 espconn_tcp_get_max_con (void)
sint8 espconn_tcp_set_max_con (uint8 num)
sint8 espconn_tcp_get_max_con_allow (struct espconn *espconn)
sint8 espconn_tcp_set_max_con_allow (struct espconn *espconn, uint8 num)
sint8 espconn_regist_time (struct espconn *espconn, uint32 interval, uint8 type_flag)
sint8 espconn_get_connection_info (struct espconn *pespconn, remot_info **pcon_info, uint8 typeflags)
sint8 espconn_regist_sentcb (struct espconn *espconn, espconn_sent_callback sent_cb)
sint8 espconn_sent (struct espconn *espconn, uint8 *psent, uint16 length)
sint8 espconn_regist_connectcb (struct espconn *espconn, espconn_connect_callback connect_cb)
sint8 espconn_regist_recvcb (struct espconn *espconn, espconn_recv_callback recv_cb)
sint8 espconn_regist_reconcb (struct espconn *espconn, espconn_reconnect_callback recon_cb)
sint8 espconn_regist_disconcb (struct espconn *espconn, espconn_connect_callback discon_cb)
uint32 espconn_port (void)
sint8 espconn_set_opt (struct espconn *espconn, uint8 opt)
err_t espconn_gethostbyname (struct espconn *pespconn, const char *hostname, ip_addr_t *addr, dns_found_callback found)
sint8 espconn_secure_connect (struct espconn *espconn)
sint8 espconn_secure_disconnect (struct espconn *espconn)
sint8 espconn_secure_sent (struct espconn *espconn, uint8 *psent, uint16 length)
sint8 espconn_secure_accept (struct espconn *espconn)
sint8 espconn_igmp_join (ip_addr_t *host_ip, ip_addr_t *multicast_ip)
sint8 espconn_igmp_leave (ip_addr_t *host_ip, ip_addr_t *multicast_ip)
sint8 espconn_recv_hold (struct espconn *pespconn)
sint8 espconn_recv_unhold (struct espconn *pespconn)
Macro Definition Documentation
ESPCONN_ABRT
#define ESPCONN_ABRT -8 /* Connection aborted. */
Definition at line 18 of file espconn.h.
ESPCONN_ARG
#define ESPCONN_ARG -12 /* Illegal argument. */
Definition at line 23 of file espconn.h.
ESPCONN_CLSD
#define ESPCONN_CLSD -10 /* Connection closed. */
Definition at line 20 of file espconn.h.
ESPCONN_CONN
#define ESPCONN_CONN -11 /* Not connected. */
Definition at line 21 of file espconn.h.
ESPCONN_INPROGRESS
#define ESPCONN_INPROGRESS -5 /* Operation in progress */
Definition at line 16 of file espconn.h.
ESPCONN_ISCONN
#define ESPCONN_ISCONN -15 /* Already connected. */
Definition at line 24 of file espconn.h.
ESPCONN_MEM
#define ESPCONN_MEM -1 /* Out of memory error. */
Definition at line 13 of file espconn.h.
ESPCONN_OK
#define ESPCONN_OK 0 /* No error, everything OK. */
Definition at line 12 of file espconn.h.
Referenced by captdnsRecv(), and mqtt_send_keepalive().
ESPCONN_RST
#define ESPCONN_RST -9 /* Connection reset. */
Definition at line 19 of file espconn.h.
ESPCONN_RTE
#define ESPCONN_RTE -4 /* Routing problem. */
Definition at line 15 of file espconn.h.
ESPCONN_TIMEOUT
#define ESPCONN_TIMEOUT -3 /* Timeout. */
Definition at line 14 of file espconn.h.
Typedef Documentation
dns_found_callback
typedef void(* dns_found_callback) (const char *name, ip_addr_t *ipaddr, void *callback_arg)
Definition at line 295 of file espconn.h.
err_t
typedef sint8 err_t
Definition at line 4 of file espconn.h.
esp_tcp
typedef struct _esp_tcp esp_tcp
esp_udp
typedef struct _esp_udp esp_udp
espconn_connect_callback
typedef void(* espconn_connect_callback) (void *arg)
Definition at line 7 of file espconn.h.
espconn_handle
typedef void* espconn_handle
Definition at line 6 of file espconn.h.
espconn_reconnect_callback
typedef void(* espconn_reconnect_callback) (void *arg, sint8 err)
Definition at line 8 of file espconn.h.
espconn_recv_callback
typedef void(* espconn_recv_callback) (void *arg, char *pdata, unsigned short len)
A callback prototype to inform about events for a espconn
Definition at line 70 of file espconn.h.
espconn_sent_callback
typedef void(* espconn_sent_callback) (void *arg)
Definition at line 71 of file espconn.h.
remot_info
typedef struct _remot_info remot_info
Enumeration Type Documentation
espconn_option
enum espconn_option
Enumerator
ESPCONN_REUSEADDR
ESPCONN_NODELAY
ESPCONN_END
Definition at line 90 of file espconn.h.
                    {
     ESPCONN_REUSEADDR = 1,
     ESPCONN_NODELAY,
     ESPCONN_END
 };
espconn_state
enum espconn_state
Current state of the espconn. Non-TCP espconn are always in state ESPCONN_NONE!
Enumerator
ESPCONN_NONE
ESPCONN_WAIT
ESPCONN_LISTEN
ESPCONN_CONNECT
ESPCONN_WRITE
ESPCONN_READ
ESPCONN_CLOSE
Definition at line 36 of file espconn.h.
                    {
     ESPCONN_NONE,
     ESPCONN_WAIT,
     ESPCONN_LISTEN,
     ESPCONN_CONNECT,
     ESPCONN_WRITE,
     ESPCONN_READ,
     ESPCONN_CLOSE
 };
espconn_type
enum espconn_type
Protocol family and type of the espconn
Enumerator
ESPCONN_INVALID
ESPCONN_TCP
ESPCONN_UDP
Definition at line 27 of file espconn.h.
                   {
     ESPCONN_INVALID    = 0,
     /* ESPCONN_TCP Group */
     ESPCONN_TCP        = 0x10,
     /* ESPCONN_UDP Group */
     ESPCONN_UDP        = 0x20,
 };
Function Documentation
espconn_accept()
sint8 espconn_accept (struct espconn * espconn)
Referenced by httpdInit().
espconn_connect()
sint8 espconn_connect (struct espconn * espconn)
Referenced by MQTT_Connect(), and mqtt_dns_found().
espconn_create()
sint8 espconn_create (struct espconn * espconn)
Referenced by captdnsInit().
espconn_delete()
sint8 espconn_delete (struct espconn * espconn)
Referenced by captdnsStop(), httpdStop(), and mqtt_tcpclient_delete().
espconn_disconnect()
sint8 espconn_disconnect (struct espconn * espconn)
Referenced by httpdConnectCb(), httpdSentCb(), httpdStop(), MQTT_Task(), and mqtt_tcpclient_recv().
espconn_get_connection_info()
sint8 espconn_get_connection_info (struct espconn * pespconn, remot_info ** pcon_info, uint8 typeflags)
Referenced by captdnsRecv().
espconn_gethostbyname()
err_t espconn_gethostbyname (struct espconn * pespconn, const char * hostname, ip_addr_t * addr, dns_found_callback found)
Referenced by MQTT_Connect().
espconn_igmp_join()
sint8 espconn_igmp_join (ip_addr_t * host_ip, ip_addr_t * multicast_ip)
espconn_igmp_leave()
sint8 espconn_igmp_leave (ip_addr_t * host_ip, ip_addr_t * multicast_ip)
espconn_port()
uint32 espconn_port (void)
Referenced by MQTT_Connect().
espconn_recv_hold()
sint8 espconn_recv_hold (struct espconn * pespconn)
espconn_recv_unhold()
sint8 espconn_recv_unhold (struct espconn * pespconn)
espconn_regist_connectcb()
sint8 espconn_regist_connectcb (struct espconn * espconn, espconn_connect_callback connect_cb)
Referenced by httpdInit(), and MQTT_Connect().
espconn_regist_disconcb()
sint8 espconn_regist_disconcb (struct espconn * espconn, espconn_connect_callback discon_cb)
Referenced by httpdConnectCb(), and mqtt_tcpclient_connect_cb().
espconn_regist_reconcb()
sint8 espconn_regist_reconcb (struct espconn * espconn, espconn_reconnect_callback recon_cb)
Referenced by httpdConnectCb(), and MQTT_Connect().
espconn_regist_recvcb()
sint8 espconn_regist_recvcb (struct espconn * espconn, espconn_recv_callback recv_cb)
Referenced by captdnsInit(), httpdConnectCb(), and mqtt_tcpclient_connect_cb().
espconn_regist_sentcb()
sint8 espconn_regist_sentcb (struct espconn * espconn, espconn_sent_callback sent_cb)
Referenced by httpdConnectCb(), and mqtt_tcpclient_connect_cb().
espconn_regist_time()
sint8 espconn_regist_time (struct espconn * espconn, uint32 interval, uint8 type_flag)
espconn_secure_accept()
sint8 espconn_secure_accept (struct espconn * espconn)
espconn_secure_connect()
sint8 espconn_secure_connect (struct espconn * espconn)
Referenced by MQTT_Connect(), and mqtt_dns_found().
espconn_secure_disconnect()
sint8 espconn_secure_disconnect (struct espconn * espconn)
Referenced by MQTT_Task(), and mqtt_tcpclient_recv().
espconn_secure_sent()
sint8 espconn_secure_sent (struct espconn * espconn, uint8 * psent, uint16 length)
espconn_sent()
sint8 espconn_sent (struct espconn * espconn, uint8 * psent, uint16 length)
Referenced by cgiEspFsHook(), and xmitSendBuff().
espconn_set_opt()
sint8 espconn_set_opt (struct espconn * espconn, uint8 opt)
Referenced by MQTT_Connect().
espconn_tcp_get_max_con()
uint8 espconn_tcp_get_max_con (void)
espconn_tcp_get_max_con_allow()
sint8 espconn_tcp_get_max_con_allow (struct espconn * espconn)
espconn_tcp_set_max_con()
sint8 espconn_tcp_set_max_con (uint8 num)
espconn_tcp_set_max_con_allow()
sint8 espconn_tcp_set_max_con_allow (struct espconn * espconn, uint8 num)