MeterLogger: user/espfs.h File Reference
espfs.h File Reference
Typedefs
typedef struct EspFsFile EspFsFile
Functions
EspFsFile * espFsOpen (char *fileName)
int espFsRead (EspFsFile *fh, char *buff, int len)
void espFsClose (EspFsFile *fh)
Typedef Documentation
EspFsFile
typedef struct EspFsFile EspFsFile
Definition at line 6 of file espfs.h.
Function Documentation
espFsClose()
void espFsClose (EspFsFile * fh)
Definition at line 214 of file espfs.c.
References EspFsFile::decompData, EspFsFile::decompressor, heatshrink_decoder_free(), NULL, and os_free.
Referenced by cgiEspFsHook(), and cgiEspFsTemplate().
{
     if (fh==NULL) return;
 #ifdef EFS_HEATSHRINK
     if (fh->decompressor==COMPRESS_HEATSHRINK) {
         heatshrink_decoder *dec=(heatshrink_decoder *)fh->decompData;
         heatshrink_decoder_free(dec);
 //      INFO("Freed %p\n", dec);
     }
 #endif
 //  INFO("Freed %p\n", fh);
     os_free(fh);
 }
espFsOpen()
EspFsFile* espFsOpen (char * fileName)
Definition at line 97 of file espfs.c.
References EspFsFile::decompData, EspFsFile::decompressor, ESPFS_POS, EspFsFile::header, heatshrink_decoder_alloc(), INFO, memcpyAligned(), NULL, os_malloc, os_memcpy, os_strcmp, EspFsFile::posComp, EspFsFile::posDecomp, and EspFsFile::posStart.
Referenced by cgiEspFsHook(), and cgiEspFsTemplate().
{
 #ifdef __ets__
     char *p=(char *)(ESPFS_POS+0x40200000);
 #else
     char *p=espFsData;
 #endif
     char *hpos;
     char namebuf[256];
     EspFsHeader h;
     EspFsFile *r;
     //Strip initial slashes
     while(fileName[0]=='/') fileName++;
     //Go find that file!
     while(1) {
         hpos=p;
         //Grab the next file header.
         os_memcpy(&h, p, sizeof(EspFsHeader));
         if (h.magic!=0x73665345) {
             INFO("Magic mismatch. EspFS image broken.\n");
             return NULL;
         }
         if (h.flags&FLAG_LASTFILE) {
             INFO("End of image.\n");
             return NULL;
         }
         //Grab the name of the file.
         p+=sizeof(EspFsHeader);
         os_memcpy(namebuf, p, sizeof(namebuf));
 //      INFO("Found file '%s'. Namelen=%x fileLenComp=%x, compr=%d flags=%d\n",
 //              namebuf, (unsigned int)h.nameLen, (unsigned int)h.fileLenComp, h.compression, h.flags);
         if (os_strcmp(namebuf, fileName)==0) {
             //Yay, this is the file we need!
             p+=h.nameLen; //Skip to content.
             r=(EspFsFile *)os_malloc(sizeof(EspFsFile)); //Alloc file desc mem
 //          INFO("Alloc %p\n", r);
             if (r==NULL) return NULL;
             r->header=(EspFsHeader *)hpos;
             r->decompressor=h.compression;
             r->posComp=p;
             r->posStart=p;
             r->posDecomp=0;
             if (h.compression==COMPRESS_NONE) {
                 r->decompData=NULL;
 #ifdef EFS_HEATSHRINK
             } else if (h.compression==COMPRESS_HEATSHRINK) {
                 //File is compressed with Heatshrink.
                 char parm;
                 heatshrink_decoder *dec;
                 //Decoder params are stored in 1st byte.
                 memcpyAligned(&parm, r->posComp, 1);
                 r->posComp++;
                 INFO("Heatshrink compressed file; decode parms = %x\n", parm);
                 dec=heatshrink_decoder_alloc(16, (parm>>4)&0xf, parm&0xf);
                 r->decompData=dec;
 #endif
             } else {
                 INFO("Invalid compression: %d\n", h.compression);
                 return NULL;
             }
             return r;
         }
         //We don't need this file. Skip name and file
         p+=h.nameLen+h.fileLenComp;
         if ((int)p&3) p+=4-((int)p&3); //align to next 32bit val
     }
 }
espFsRead()
int espFsRead (EspFsFile * fh, char * buff, int len)
Definition at line 165 of file espfs.c.
References EspFsFile::decompData, EspFsFile::decompressor, EspFsFile::header, heatshrink_decoder_finish(), heatshrink_decoder_poll(), heatshrink_decoder_sink(), memcpyAligned(), NULL, EspFsFile::posComp, EspFsFile::posDecomp, and EspFsFile::posStart.
Referenced by cgiEspFsHook(), and cgiEspFsTemplate().
{
     int flen;
     if (fh==NULL) return 0;
     //Cache file length.
     memcpyAligned((char*)&flen, (char*)&fh->header->fileLenComp, 4);
     //Do stuff depending on the way the file is compressed.
     if (fh->decompressor==COMPRESS_NONE) {
         int toRead;
         toRead=flen-(fh->posComp-fh->posStart);
         if (len>toRead) len=toRead;
 //      INFO("Reading %d bytes from %x\n", len, (unsigned int)fh->posComp);
         memcpyAligned(buff, fh->posComp, len);
         fh->posDecomp+=len;
         fh->posComp+=len;
 //      INFO("Done reading %d bytes, pos=%x\n", len, fh->posComp);
         return len;
 #ifdef EFS_HEATSHRINK
     } else if (fh->decompressor==COMPRESS_HEATSHRINK) {
         int decoded=0;
         unsigned int elen, rlen;
         char ebuff[16];
         heatshrink_decoder *dec=(heatshrink_decoder *)fh->decompData;
 //      INFO("Alloc %p\n", dec);
         while(decoded<len) {
             //Feed data into the decompressor
             //ToDo: Check ret val of heatshrink fns for errors
             elen=flen-(fh->posComp - fh->posStart);
             if (elen==0) return decoded; //file is read
             if (elen>0) {
                 memcpyAligned(ebuff, fh->posComp, 16);
                 heatshrink_decoder_sink(dec, (uint8_t *)ebuff, (elen>16)?16:elen, &rlen);
                 fh->posComp+=rlen;
                 if (rlen==elen) {
                     heatshrink_decoder_finish(dec);
                 }
             }
             //Grab decompressed data and put into buff
             heatshrink_decoder_poll(dec, (uint8_t *)buff, len-decoded, &rlen);
             fh->posDecomp+=rlen;
             buff+=rlen;
             decoded+=rlen;
         }
         return len;
 #endif
     }
     return 0;
 }