MeterLogger: user/espfs.c File Reference
espfs.c File Reference
#include <esp8266.h>
#include "debug.h"
#include "../mkespfsimage/espfsformat.h"
#include "espfs.h"
#include "httpdconfig.h"
Data Structures
struct EspFsFile
Functions
void ICACHE_FLASH_ATTR memcpyAligned (char *dst, char *src, int len)
EspFsFile ICACHE_FLASH_ATTR * espFsOpen (char *fileName)
int ICACHE_FLASH_ATTR espFsRead (EspFsFile *fh, char *buff, int len)
void ICACHE_FLASH_ATTR espFsClose (EspFsFile *fh)
Function Documentation
espFsClose()
void ICACHE_FLASH_ATTR espFsClose (EspFsFile * fh)
Definition at line 214 of file espfs.c.
References EspFsFile::decompData, EspFsFile::decompressor, heatshrink_decoder_free(), NULL, and os_free.
Referenced by cgiEspFsHook(), and cgiEspFsTemplate().
espFsOpen()
EspFsFile ICACHE_FLASH_ATTR* espFsOpen (char * fileName)
Definition at line 97 of file espfs.c.
References EspFsFile::decompData, EspFsFile::decompressor, ESPFS_POS, EspFsFile::header, heatshrink_decoder_alloc(), INFO, memcpyAligned(), NULL, os_malloc, os_memcpy, os_strcmp, EspFsFile::posComp, EspFsFile::posDecomp, and EspFsFile::posStart.
Referenced by cgiEspFsHook(), and cgiEspFsTemplate().
espFsRead()
int ICACHE_FLASH_ATTR espFsRead (EspFsFile * fh, char * buff, int len)
Definition at line 165 of file espfs.c.
References EspFsFile::decompData, EspFsFile::decompressor, EspFsFile::header, heatshrink_decoder_finish(), heatshrink_decoder_poll(), heatshrink_decoder_sink(), memcpyAligned(), NULL, EspFsFile::posComp, EspFsFile::posDecomp, and EspFsFile::posStart.
Referenced by cgiEspFsHook(), and cgiEspFsTemplate().
memcpyAligned()
void ICACHE_FLASH_ATTR memcpyAligned (char * dst, char * src, int len)
Definition at line 81 of file espfs.c.
Referenced by espFsOpen(), and espFsRead().