MeterLogger: include/espmissingincludes.h File Reference
espmissingincludes.h File Reference
#include <stdint.h>
#include <c_types.h>
#include <eagle_soc.h>
#include <ets_sys.h>
Typedefs
typedef struct espconn espconn
Functions
int strcasecmp (const char *a, const char *b)
int atoi (const char *nptr)
void ets_install_putc1 (void *routine)
void ets_isr_attach (int intr, void *handler, void *arg)
void ets_isr_mask (unsigned intr)
void ets_isr_unmask (unsigned intr)
int ets_memcmp (const void *s1, const void *s2, size_t n)
void * ets_memcpy (void *dest, const void *src, size_t n)
void * ets_memset (void *s, int c, size_t n)
int ets_sprintf (char *str, const char *format,...) __attribute__((format(printf
int int ets_str2macaddr (void *, void *)
int ets_strcmp (const char *s1, const char *s2)
char * ets_strcpy (char *dest, const char *src)
size_t ets_strlen (const char *s)
int ets_strncmp (const char *s1, const char *s2, int len)
char * ets_strncpy (char *dest, const char *src, size_t n)
char * ets_strstr (const char *haystack, const char *needle)
void ets_timer_arm_new (os_timer_t *a, int b, int c, int isMstimer)
void ets_timer_disarm (os_timer_t *a)
void ets_timer_setfn (os_timer_t *t, ETSTimerFunc *fn, void *parg)
void ets_update_cpu_frequency (int freqmhz)
int os_printf (const char *format,...) __attribute__((format(printf
int int os_snprintf (char *str, size_t size, const char *format,...) __attribute__((format(printf
int int int os_printf_plus (const char *format,...) __attribute__((format(printf
int int int void uart_div_modify (int no, unsigned int freq)
uint8 wifi_get_opmode (void)
uint32 system_get_time ()
int rand (void)
void ets_bzero (void *s, size_t n)
void ets_delay_us (int ms)
void * pvPortMalloc (size_t xWantedSize)
void * pvPortZalloc (size_t)
void vPortFree (void *ptr)
void * vPortMalloc (size_t xWantedSize)
void pvPortFree (void *ptr)
Typedef Documentation
espconn
typedef struct espconn espconn
Definition at line 14 of file espmissingincludes.h.
Function Documentation
atoi()
int atoi (const char * nptr)
Referenced by cgiLed(), cgiWifiSetMode(), cleanup_decimal_str(), divide_str_by_10(), divide_str_by_100(), en61107_received_task(), httpdParseHeader(), kmp_request_send(), kw_to_w_str(), minute_timer_func(), parse_mc66cde_standard_data_2_frame(), proc_args(), tplSetup(), and w_to_kw_str().
ets_bzero()
void ets_bzero (void * s, size_t n)
ets_delay_us()
void ets_delay_us (int ms)
ets_install_putc1()
void ets_install_putc1 (void * routine)
ets_isr_attach()
void ets_isr_attach (int intr, void * handler, void * arg)
ets_isr_mask()
void ets_isr_mask (unsigned intr)
ets_isr_unmask()
void ets_isr_unmask (unsigned intr)
ets_memcmp()
int ets_memcmp (const void * s1, const void * s2, size_t n)
ets_memcpy()
void* ets_memcpy (void * dest, const void * src, size_t n)
ets_memset()
void* ets_memset (void * s, int c, size_t n)
ets_sprintf()
int ets_sprintf (char * str, const char * format, ...)
ets_str2macaddr()
int int ets_str2macaddr (void * , void *)
ets_strcmp()
int ets_strcmp (const char * s1, const char * s2)
ets_strcpy()
char* ets_strcpy (char * dest, const char * src)
ets_strlen()
size_t ets_strlen (const char * s)
ets_strncmp()
int ets_strncmp (const char * s1, const char * s2, int len)
ets_strncpy()
char* ets_strncpy (char * dest, const char * src, size_t n)
ets_strstr()
char* ets_strstr (const char * haystack, const char * needle)
ets_timer_arm_new()
void ets_timer_arm_new (os_timer_t * a, int b, int c, int isMstimer)
ets_timer_disarm()
void ets_timer_disarm (os_timer_t * a)
ets_timer_setfn()
void ets_timer_setfn (os_timer_t * t, ETSTimerFunc * fn, void * parg)
ets_update_cpu_frequency()
void ets_update_cpu_frequency (int freqmhz)
os_printf()
int os_printf (const char * format, ...)
Referenced by ac_motor_valve_close(), ac_motor_valve_open(), ac_out_off_timer_func(), ac_test(), ac_thermo_close(), ac_thermo_open(), ac_thermo_pwm(), acl_check_packet(), add_cron_job_from_query(), add_watchdog(), cfg_load(), clear_cron_jobs(), cron_init(), dhcps_start(), espconn_client_connect(), espconn_recv_hold(), espconn_recv_unhold(), espconn_tcp_delete(), ext_spi_flash_hexdump(), ext_spi_init(), handle_dhcp(), ip_router(), minute_timer_func(), MQTT_Task(), parse_msg(), parse_options(), patch_netif_ap(), remove_watchdog(), reset_watchdog(), resetTimerCb(), send_ack(), send_nak(), send_offer(), start_watchdog(), stop_watchdog(), watchdog_timer_func(), wifi_default(), wifi_fallback(), wifi_handle_event_cb(), wifi_reconnect_timer_func(), wifi_scan_done_cb(), wifi_scan_timer_func(), and wifi_softap_ip_config().
os_printf_plus()
int int int os_printf_plus (const char * format, ...)
os_snprintf()
int int os_snprintf (char * str, size_t size, const char * format, ...)
pvPortFree()
void pvPortFree (void * ptr)
pvPortMalloc()
void* pvPortMalloc (size_t xWantedSize)
pvPortZalloc()
void* pvPortZalloc (size_t)
rand()
int rand (void)
strcasecmp()
int strcasecmp (const char * a, const char * b)
system_get_time()
uint32 system_get_time ()
uart_div_modify()
int int int void uart_div_modify (int no, unsigned int freq)
Referenced by uart_config(), and uart_set_baudrate().
vPortFree()
void vPortFree (void * ptr)
vPortMalloc()
void* vPortMalloc (size_t xWantedSize)
wifi_get_opmode()
uint8 wifi_get_opmode (void)
Referenced by espconn_connect(), espconn_udp_recv(), espconn_udp_sendto(), espconn_udp_sent(), tplSetup(), wifi_softap_get_dhcps_lease(), wifi_softap_reset_dhcps_lease_time(), wifi_softap_set_dhcps_lease(), and wifi_softap_set_dhcps_lease_time().