MeterLogger: driver/gpio16.c File Reference
gpio16.c File Reference
#include "ets_sys.h"
#include "osapi.h"
#include "driver/gpio16.h"
Functions
void ICACHE_FLASH_ATTR gpio16_output_conf (void)
void ICACHE_FLASH_ATTR gpio16_output_set (uint8 value)
void ICACHE_FLASH_ATTR gpio16_input_conf (void)
uint8 ICACHE_FLASH_ATTR gpio16_input_get (void)
Function Documentation
gpio16_input_conf()
void ICACHE_FLASH_ATTR gpio16_input_conf (void)
Definition at line 26 of file gpio16.c.
References ICACHE_FLASH_ATTR, PAD_XPD_DCDC_CONF, READ_PERI_REG, RTC_GPIO_CONF, RTC_GPIO_ENABLE, and WRITE_PERI_REG.
 {
     WRITE_PERI_REG(PAD_XPD_DCDC_CONF,
                    (READ_PERI_REG(PAD_XPD_DCDC_CONF) & 0xffffffbc) | (uint32)0x1);  // mux configuration for XPD_DCDC and rtc_gpio0 connection
     WRITE_PERI_REG(RTC_GPIO_CONF,
                    (READ_PERI_REG(RTC_GPIO_CONF) & (uint32)0xfffffffe) | (uint32)0x0);  //mux configuration for out enable
     WRITE_PERI_REG(RTC_GPIO_ENABLE,
                    READ_PERI_REG(RTC_GPIO_ENABLE) & (uint32)0xfffffffe);    //out disable
 }
gpio16_input_get()
uint8 ICACHE_FLASH_ATTR gpio16_input_get (void)
Definition at line 39 of file gpio16.c.
References READ_PERI_REG, and RTC_GPIO_IN_DATA.
Referenced by ext_watchdog_timer_func().
 {
     return (uint8)(READ_PERI_REG(RTC_GPIO_IN_DATA) & 1);
 }
gpio16_output_conf()
void ICACHE_FLASH_ATTR gpio16_output_conf (void)
Definition at line 6 of file gpio16.c.
References ICACHE_FLASH_ATTR, PAD_XPD_DCDC_CONF, READ_PERI_REG, RTC_GPIO_CONF, RTC_GPIO_ENABLE, and WRITE_PERI_REG.
Referenced by start_watchdog().
 {
     WRITE_PERI_REG(PAD_XPD_DCDC_CONF,
                    (READ_PERI_REG(PAD_XPD_DCDC_CONF) & 0xffffffbc) | (uint32)0x1);  // mux configuration for XPD_DCDC to output rtc_gpio0
     WRITE_PERI_REG(RTC_GPIO_CONF,
                    (READ_PERI_REG(RTC_GPIO_CONF) & (uint32)0xfffffffe) | (uint32)0x0);  //mux configuration for out enable
     WRITE_PERI_REG(RTC_GPIO_ENABLE,
                    (READ_PERI_REG(RTC_GPIO_ENABLE) & (uint32)0xfffffffe) | (uint32)0x1);    //out enable
 }
gpio16_output_set()
void ICACHE_FLASH_ATTR gpio16_output_set (uint8 value)
Definition at line 19 of file gpio16.c.
References ICACHE_FLASH_ATTR, READ_PERI_REG, RTC_GPIO_OUT, and WRITE_PERI_REG.
Referenced by ext_watchdog_timer_func(), and start_watchdog().
 {
     WRITE_PERI_REG(RTC_GPIO_OUT,
                    (READ_PERI_REG(RTC_GPIO_OUT) & (uint32)0xfffffffe) | (uint32)(value & 1));
 }