MeterLogger: lib/heatshrink/heatshrink_encoder.c File Reference
heatshrink_encoder.c File Reference
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "heatshrink_encoder.h"
Data Structures
struct output_info
Macros
#define LOG(...) /* no-op */
#define ASSERT(X) /* no-op */
#define MATCH_NOT_FOUND ((uint16_t)-1)
Enumerations
enum HSE_state {
HSES_NOT_FULL, HSES_FILLED, HSES_SEARCH, HSES_YIELD_TAG_BIT,
HSES_YIELD_LITERAL, HSES_YIELD_BR_INDEX, HSES_YIELD_BR_LENGTH, HSES_SAVE_BACKLOG,
HSES_FLUSH_BITS, HSES_DONE
}
enum {
FLAG_IS_FINISHING = 0x01, FLAG_HAS_LITERAL = 0x02, FLAG_ON_FINAL_LITERAL = 0x04, FLAG_BACKLOG_IS_PARTIAL = 0x08,
FLAG_BACKLOG_IS_FILLED = 0x10
}
Functions
static uint16_t get_input_offset (heatshrink_encoder *hse)
static uint16_t get_input_buffer_size (heatshrink_encoder *hse)
static uint16_t get_lookahead_size (heatshrink_encoder *hse)
static void add_tag_bit (heatshrink_encoder *hse, output_info *oi, uint8_t tag)
static int can_take_byte (output_info *oi)
static int is_finishing (heatshrink_encoder *hse)
static int backlog_is_partial (heatshrink_encoder *hse)
static int backlog_is_filled (heatshrink_encoder *hse)
static int on_final_literal (heatshrink_encoder *hse)
static void save_backlog (heatshrink_encoder *hse)
static int has_literal (heatshrink_encoder *hse)
static void push_bits (heatshrink_encoder *hse, uint8_t count, uint8_t bits, output_info *oi)
static uint8_t push_outgoing_bits (heatshrink_encoder *hse, output_info *oi)
static void push_literal_byte (heatshrink_encoder *hse, output_info *oi)
heatshrink_encoder * heatshrink_encoder_alloc (uint8_t window_sz2, uint8_t lookahead_sz2)
void heatshrink_encoder_free (heatshrink_encoder *hse)
void heatshrink_encoder_reset (heatshrink_encoder *hse)
HSE_sink_res heatshrink_encoder_sink (heatshrink_encoder *hse, uint8_t *in_buf, size_t size, size_t *input_size)
static uint16_t find_longest_match (heatshrink_encoder *hse, uint16_t start, uint16_t end, const uint16_t maxlen, uint16_t *match_length)
static void do_indexing (heatshrink_encoder *hse)
static HSE_state st_step_search (heatshrink_encoder *hse)
static HSE_state st_yield_tag_bit (heatshrink_encoder *hse, output_info *oi)
static HSE_state st_yield_literal (heatshrink_encoder *hse, output_info *oi)
static HSE_state st_yield_br_index (heatshrink_encoder *hse, output_info *oi)
static HSE_state st_yield_br_length (heatshrink_encoder *hse, output_info *oi)
static HSE_state st_save_backlog (heatshrink_encoder *hse)
static HSE_state st_flush_bit_buffer (heatshrink_encoder *hse, output_info *oi)
HSE_poll_res heatshrink_encoder_poll (heatshrink_encoder *hse, uint8_t *out_buf, size_t out_buf_size, size_t *output_size)
HSE_finish_res heatshrink_encoder_finish (heatshrink_encoder *hse)
Macro Definition Documentation
ASSERT
#define ASSERT (X) /* no-op */
Definition at line 39 of file heatshrink_encoder.c.
Referenced by push_bits(), and st_step_search().
LOG
#define LOG (...) /* no-op */
Definition at line 38 of file heatshrink_encoder.c.
Referenced by add_tag_bit(), find_longest_match(), heatshrink_encoder_alloc(), heatshrink_encoder_finish(), heatshrink_encoder_poll(), heatshrink_encoder_sink(), push_bits(), push_literal_byte(), push_outgoing_bits(), st_flush_bit_buffer(), st_save_backlog(), st_step_search(), st_yield_br_index(), and st_yield_br_length().
MATCH_NOT_FOUND
#define MATCH_NOT_FOUND ((uint16_t)-1)
Definition at line 57 of file heatshrink_encoder.c.
Referenced by find_longest_match(), and st_step_search().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FLAG_IS_FINISHING
FLAG_HAS_LITERAL
FLAG_ON_FINAL_LITERAL
FLAG_BACKLOG_IS_PARTIAL
FLAG_BACKLOG_IS_FILLED
Definition at line 43 of file heatshrink_encoder.c.
      {
     FLAG_IS_FINISHING = 0x01,
     FLAG_HAS_LITERAL = 0x02,
     FLAG_ON_FINAL_LITERAL = 0x04,
     FLAG_BACKLOG_IS_PARTIAL = 0x08,
     FLAG_BACKLOG_IS_FILLED = 0x10,
 };
HSE_state
enum HSE_state
Enumerator
HSES_NOT_FULL
HSES_FILLED
HSES_SEARCH
HSES_YIELD_TAG_BIT
HSES_YIELD_LITERAL
HSES_YIELD_BR_INDEX
HSES_YIELD_BR_LENGTH
HSES_SAVE_BACKLOG
HSES_FLUSH_BITS
HSES_DONE
Definition at line 6 of file heatshrink_encoder.c.
              {
     HSES_NOT_FULL,              /* input buffer not full enough */
     HSES_FILLED,                /* buffer is full */
     HSES_SEARCH,                /* searching for patterns */
     HSES_YIELD_TAG_BIT,         /* yield tag bit */
     HSES_YIELD_LITERAL,         /* emit literal byte */
     HSES_YIELD_BR_INDEX,        /* yielding backref index */
     HSES_YIELD_BR_LENGTH,       /* yielding backref length */
     HSES_SAVE_BACKLOG,          /* copying buffer to backlog */
     HSES_FLUSH_BITS,            /* flush bit buffer */
     HSES_DONE,                  /* done */
 } HSE_state;
Function Documentation
add_tag_bit()
static void add_tag_bit (heatshrink_encoder * hse, output_info * oi, uint8_t tag) static
Definition at line 413 of file heatshrink_encoder.c.
References LOG, and push_bits().
Referenced by st_yield_tag_bit().
{
     LOG("-- adding tag bit: %d\n", tag);
     push_bits(hse, 1, tag, oi);
 }
backlog_is_filled()
static int backlog_is_filled (heatshrink_encoder * hse) static
Definition at line 479 of file heatshrink_encoder.c.
References FLAG_BACKLOG_IS_FILLED, and heatshrink_encoder::flags.
Referenced by st_step_search().
{
     return hse->flags & FLAG_BACKLOG_IS_FILLED;
 }
backlog_is_partial()
static int backlog_is_partial (heatshrink_encoder * hse) static
Definition at line 475 of file heatshrink_encoder.c.
References FLAG_BACKLOG_IS_PARTIAL, and heatshrink_encoder::flags.
Referenced by save_backlog(), and st_step_search().
{
     return hse->flags & FLAG_BACKLOG_IS_PARTIAL;
 }
can_take_byte()
static int can_take_byte (output_info * oi) static
Definition at line 491 of file heatshrink_encoder.c.
References output_info::buf_size, and output_info::output_size.
Referenced by st_flush_bit_buffer(), st_yield_br_index(), st_yield_br_length(), st_yield_literal(), and st_yield_tag_bit().
{
     return *oi->output_size < oi->buf_size;
 }
do_indexing()
static void do_indexing (heatshrink_encoder * hse) static
Definition at line 432 of file heatshrink_encoder.c.
References heatshrink_encoder::buffer, get_input_offset(), HEATSHRINK_ENCODER_INDEX, hs_index::index, heatshrink_encoder::input_size, and memset.
Referenced by heatshrink_encoder_poll(), and heatshrink_encoder_sink().
{
 #if HEATSHRINK_USE_INDEX
     /* Build an index array I that contains flattened linked lists
      * for the previous instances of every byte in the buffer.
      *
      * For example, if buf[200] == 'x', then index[200] will either
      * be an offset i such that buf[i] == 'x', or a negative offset
      * to indicate end-of-list. This significantly speeds up matching,
      * while only using sizeof(uint16_t)*sizeof(buffer) bytes of RAM.
      *
      * Future optimization options:
      * 1. Since any negative value represents end-of-list, the other
      *    15 bits could be used to improve the index dynamically.
      *
      * 2. Likewise, the last lookahead_sz bytes of the index will
      *    not be usable, so temporary data could be stored there to
      *    dynamically improve the index.
      * */
     struct hs_index *hsi = HEATSHRINK_ENCODER_INDEX(hse);
     uint16_t last[256];
     memset(last, 0xFF, sizeof(last));
     uint8_t * const data = hse->buffer;
     int16_t * const index = hsi->index;
     const uint16_t input_offset = get_input_offset(hse);
     const uint16_t end = input_offset + hse->input_size;
     for (uint16_t i=0; i<end; i++) {
         uint8_t v = data[i];
         uint16_t lv = last[v];
         index[i] = lv;
         last[v] = i;
     }
 #else
     (void)hse;
 #endif
 }
find_longest_match()
static uint16_t find_longest_match (heatshrink_encoder * hse, uint16_t start, uint16_t end, const uint16_t maxlen, uint16_t * match_length) static
Definition at line 497 of file heatshrink_encoder.c.
References heatshrink_encoder::buffer, HEATSHRINK_ENCODER_INDEX, hs_index::index, LOG, and MATCH_NOT_FOUND.
Referenced by heatshrink_encoder_sink(), and st_step_search().
{
     LOG("-- scanning for match of buf[%u:%u] between buf[%u:%u] (max %u bytes)\n",
         end, end + maxlen, start, end + maxlen - 1, maxlen);
     uint8_t *buf = hse->buffer;
     uint16_t match_maxlen = 0;
     uint16_t match_index = MATCH_NOT_FOUND;
     const uint16_t break_even_point = 3;
     uint16_t len = 0;
     uint8_t * const needlepoint = &buf[end];
 #if HEATSHRINK_USE_INDEX
     struct hs_index *hsi = HEATSHRINK_ENCODER_INDEX(hse);
     int16_t pos = hsi->index[end];
     while (pos >= start) {
         uint8_t * const pospoint = &buf[pos];
         len = 0;
         /* Only check matches that will potentially beat the current maxlen.
          * This is redundant with the index if match_maxlen is 0, but the
          * added branch overhead to check if it == 0 seems to be worse. */
         if (pospoint[match_maxlen] != needlepoint[match_maxlen]) {
             pos = hsi->index[pos];
             continue;
         }
         for (len = 1; len < maxlen; len++) {
             if (pospoint[len] != needlepoint[len]) break;
         }
         if (len > match_maxlen) {
             match_maxlen = len;
             match_index = pos;
             if (len == maxlen) { break; } /* won't find better */
         }
         pos = hsi->index[pos];
     }
 #else
     for (int16_t pos=end - 1; pos >= start; pos--) {
         uint8_t * const pospoint = &buf[pos];
         if ((pospoint[match_maxlen] == needlepoint[match_maxlen])
             && (*pospoint == *needlepoint)) {
             for (len=1; len<maxlen; len++) {
                 if (0) {
                     LOG("  --> cmp buf[%d] == 0x%02x against %02x (start %u)\n",
                         pos + len, pospoint[len], needlepoint[len], start);
                 }
                 if (pospoint[len] != needlepoint[len]) { break; }
             }
             if (len > match_maxlen) {
                 match_maxlen = len;
                 match_index = pos;
                 if (len == maxlen) { break; } /* don't keep searching */
             }
         }
     }
 #endif
     if (match_maxlen >= break_even_point) {
         LOG("-- best match: %u bytes at -%u\n",
             match_maxlen, end - match_index);
         *match_length = match_maxlen;
         return end - match_index;
     }
     LOG("-- none found\n");
     return MATCH_NOT_FOUND;
 }
get_input_buffer_size()
static uint16_t get_input_buffer_size (heatshrink_encoder * hse) static
Definition at line 422 of file heatshrink_encoder.c.
References HEATSHRINK_ENCODER_WINDOW_BITS.
Referenced by get_input_offset(), heatshrink_encoder_alloc(), heatshrink_encoder_sink(), save_backlog(), and st_step_search().
{
     return (1 << HEATSHRINK_ENCODER_WINDOW_BITS(hse));
     (void)hse;
 }
get_input_offset()
static uint16_t get_input_offset (heatshrink_encoder * hse) static
Definition at line 418 of file heatshrink_encoder.c.
References get_input_buffer_size().
Referenced by do_indexing(), heatshrink_encoder_sink(), push_literal_byte(), and st_step_search().
{
     return get_input_buffer_size(hse);
 }
get_lookahead_size()
static uint16_t get_lookahead_size (heatshrink_encoder * hse) static
Definition at line 427 of file heatshrink_encoder.c.
References HEATSHRINK_ENCODER_LOOKAHEAD_BITS.
Referenced by st_step_search().
{
     return (1 << HEATSHRINK_ENCODER_LOOKAHEAD_BITS(hse));
     (void)hse;
 }
has_literal()
static int has_literal (heatshrink_encoder * hse) static
Definition at line 487 of file heatshrink_encoder.c.
References FLAG_HAS_LITERAL, and heatshrink_encoder::flags.
Referenced by st_save_backlog().
{
     return (hse->flags & FLAG_HAS_LITERAL);
 }
heatshrink_encoder_alloc()
heatshrink_encoder* heatshrink_encoder_alloc (uint8_t window_sz2, uint8_t lookahead_sz2)
Definition at line 78 of file heatshrink_encoder.c.
References get_input_buffer_size(), heatshrink_encoder_reset(), HEATSHRINK_FREE, HEATSHRINK_MALLOC, HEATSHRINK_MAX_WINDOW_BITS, HEATSHRINK_MIN_LOOKAHEAD_BITS, HEATSHRINK_MIN_WINDOW_BITS, hse, LOG, heatshrink_encoder::lookahead_sz2, NULL, heatshrink_encoder::search_index, hs_index::size, and heatshrink_encoder::window_sz2.
Referenced by compress_and_expand_and_check(), data_with_simple_repetition_should_match_with_absurdly_tiny_buffers(), data_without_duplication_should_match_with_absurdly_tiny_buffers(), encode(), encoder_alloc_should_reject_invalid_arguments(), encoder_poll_should_detect_repeated_substring(), encoder_poll_should_detect_repeated_substring_and_preserve_trailing_literal(), encoder_poll_should_indicate_when_no_input_is_provided(), encoder_poll_should_reject_nulls(), encoder_should_emit_data_without_repetitions_as_literal_sequence(), encoder_should_emit_series_of_same_byte_as_literal_then_backref(), encoder_sink_should_accept_input_when_it_will_fit(), encoder_sink_should_accept_partial_input_when_some_will_fit(), encoder_sink_should_reject_nulls(), and gen().
{
     if ((window_sz2 < HEATSHRINK_MIN_WINDOW_BITS) ||
         (window_sz2 > HEATSHRINK_MAX_WINDOW_BITS) ||
         (lookahead_sz2 < HEATSHRINK_MIN_LOOKAHEAD_BITS) ||
         (lookahead_sz2 > window_sz2)) {
         return NULL;
     }
     /* Note: 2 * the window size is used because the buffer needs to fit
      * (1 << window_sz2) bytes for the current input, and an additional
      * (1 << window_sz2) bytes for the previous buffer of input, which
      * will be scanned for useful backreferences. */
     size_t buf_sz = (2 << window_sz2);
     heatshrink_encoder *hse = HEATSHRINK_MALLOC(sizeof(*hse) + buf_sz);
     if (hse == NULL) { return NULL; }
     hse->window_sz2 = window_sz2;
     hse->lookahead_sz2 = lookahead_sz2;
     heatshrink_encoder_reset(hse);
 #if HEATSHRINK_USE_INDEX
     size_t index_sz = buf_sz*sizeof(uint16_t);
     hse->search_index = HEATSHRINK_MALLOC(index_sz + sizeof(struct hs_index));
     if (hse->search_index == NULL) {
         HEATSHRINK_FREE(hse, sizeof(*hse) + buf_sz);
         return NULL;
     }
     hse->search_index->size = index_sz;
 #endif
     LOG("-- allocated encoder with buffer size of %zu (%u byte input size)\n",
         buf_sz, get_input_buffer_size(hse));
     return hse;
 }
heatshrink_encoder_finish()
HSE_finish_res heatshrink_encoder_finish (heatshrink_encoder * hse)
Definition at line 260 of file heatshrink_encoder.c.
References FLAG_IS_FINISHING, heatshrink_encoder::flags, HSER_FINISH_DONE, HSER_FINISH_ERROR_NULL, HSER_FINISH_MORE, HSES_DONE, HSES_FILLED, HSES_NOT_FULL, LOG, NULL, and heatshrink_encoder::state.
Referenced by compress_and_expand_and_check(), data_with_simple_repetition_should_match_with_absurdly_tiny_buffers(), data_without_duplication_should_match_with_absurdly_tiny_buffers(), encoder_finish_should_reject_nulls(), encoder_poll_should_detect_repeated_substring(), encoder_poll_should_detect_repeated_substring_and_preserve_trailing_literal(), encoder_should_emit_data_without_repetitions_as_literal_sequence(), encoder_should_emit_series_of_same_byte_as_literal_then_backref(), encoder_sink_read(), and gen().
{
     if (hse == NULL) { return HSER_FINISH_ERROR_NULL; }
     LOG("-- setting is_finishing flag\n");
     hse->flags |= FLAG_IS_FINISHING;
     if (hse->state == HSES_NOT_FULL) { hse->state = HSES_FILLED; }
     return hse->state == HSES_DONE ? HSER_FINISH_DONE : HSER_FINISH_MORE;
 }
heatshrink_encoder_free()
void heatshrink_encoder_free (heatshrink_encoder * hse)
Definition at line 114 of file heatshrink_encoder.c.
References HEATSHRINK_ENCODER_WINDOW_BITS, and HEATSHRINK_FREE.
Referenced by compress_and_expand_and_check(), data_with_simple_repetition_should_match_with_absurdly_tiny_buffers(), data_without_duplication_should_match_with_absurdly_tiny_buffers(), encode(), encoder_poll_should_detect_repeated_substring(), encoder_poll_should_detect_repeated_substring_and_preserve_trailing_literal(), encoder_poll_should_indicate_when_no_input_is_provided(), encoder_poll_should_reject_nulls(), encoder_should_emit_data_without_repetitions_as_literal_sequence(), encoder_should_emit_series_of_same_byte_as_literal_then_backref(), encoder_sink_should_accept_input_when_it_will_fit(), encoder_sink_should_accept_partial_input_when_some_will_fit(), encoder_sink_should_reject_nulls(), and gen().
{
     size_t buf_sz = (2 << HEATSHRINK_ENCODER_WINDOW_BITS(hse));
 #if HEATSHRINK_USE_INDEX
     size_t index_sz = sizeof(struct hs_index) + hse->search_index->size;
     HEATSHRINK_FREE(hse->search_index, index_sz);
     (void)index_sz;
 #endif
     HEATSHRINK_FREE(hse, sizeof(heatshrink_encoder) + buf_sz);
     (void)buf_sz;
 }
heatshrink_encoder_poll()
HSE_poll_res heatshrink_encoder_poll (heatshrink_encoder * hse, uint8_t * out_buf, size_t out_buf_size, size_t * output_size)
Definition at line 198 of file heatshrink_encoder.c.
References output_info::buf, output_info::buf_size, do_indexing(), heatshrink_encoder::flags, HSER_POLL_EMPTY, HSER_POLL_ERROR_MISUSE, HSER_POLL_ERROR_NULL, HSER_POLL_MORE, HSES_DONE, HSES_FILLED, HSES_FLUSH_BITS, HSES_NOT_FULL, HSES_SAVE_BACKLOG, HSES_SEARCH, HSES_YIELD_BR_INDEX, HSES_YIELD_BR_LENGTH, HSES_YIELD_LITERAL, HSES_YIELD_TAG_BIT, LOG, NULL, output_info::output_size, st_flush_bit_buffer(), st_save_backlog(), st_step_search(), st_yield_br_index(), st_yield_br_length(), st_yield_literal(), st_yield_tag_bit(), and heatshrink_encoder::state.
Referenced by compress_and_expand_and_check(), data_with_simple_repetition_should_match_with_absurdly_tiny_buffers(), data_without_duplication_should_match_with_absurdly_tiny_buffers(), encoder_poll_should_detect_repeated_substring(), encoder_poll_should_detect_repeated_substring_and_preserve_trailing_literal(), encoder_poll_should_indicate_when_no_input_is_provided(), encoder_poll_should_reject_nulls(), encoder_should_emit_data_without_repetitions_as_literal_sequence(), encoder_should_emit_series_of_same_byte_as_literal_then_backref(), encoder_sink_read(), and gen().
{
     if ((hse == NULL) || (out_buf == NULL) || (output_size == NULL)) {
         return HSER_POLL_ERROR_NULL;
     }
     if (out_buf_size == 0) {
         LOG("-- MISUSE: output buffer size is 0\n");
         return HSER_POLL_ERROR_MISUSE;
     }
     *output_size = 0;
     output_info oi;
     oi.buf = out_buf;
     oi.buf_size = out_buf_size;
     oi.output_size = output_size;
     while (1) {
         LOG("-- polling, state %u (%s), flags 0x%02x\n",
             hse->state, state_names[hse->state], hse->flags);
         uint8_t in_state = hse->state;
         switch (in_state) {
         case HSES_NOT_FULL:
             return HSER_POLL_EMPTY;
         case HSES_FILLED:
             do_indexing(hse);
             hse->state = HSES_SEARCH;
             break;
         case HSES_SEARCH:
             hse->state = st_step_search(hse);
             break;
         case HSES_YIELD_TAG_BIT:
             hse->state = st_yield_tag_bit(hse, &oi);
             break;
         case HSES_YIELD_LITERAL:
             hse->state = st_yield_literal(hse, &oi);
             break;
         case HSES_YIELD_BR_INDEX:
             hse->state = st_yield_br_index(hse, &oi);
             break;
         case HSES_YIELD_BR_LENGTH:
             hse->state = st_yield_br_length(hse, &oi);
             break;
         case HSES_SAVE_BACKLOG:
             hse->state = st_save_backlog(hse);
             break;
         case HSES_FLUSH_BITS:
             hse->state = st_flush_bit_buffer(hse, &oi);
         case HSES_DONE:
             return HSER_POLL_EMPTY;
         default:
             LOG("-- bad state %s\n", state_names[hse->state]);
             return HSER_POLL_ERROR_MISUSE;
         }
         if (hse->state == in_state) {
             /* Check if output buffer is exhausted. */
             if (*output_size == out_buf_size) return HSER_POLL_MORE;
         }
     }
 }
heatshrink_encoder_reset()
void heatshrink_encoder_reset (heatshrink_encoder * hse)
Definition at line 126 of file heatshrink_encoder.c.
References heatshrink_encoder::bit_index, heatshrink_encoder::buffer, heatshrink_encoder::current_byte, heatshrink_encoder::flags, HEATSHRINK_ENCODER_WINDOW_BITS, HSES_NOT_FULL, heatshrink_encoder::input_size, heatshrink_encoder::match_length, heatshrink_encoder::match_scan_index, memset, heatshrink_encoder::outgoing_bits, heatshrink_encoder::outgoing_bits_count, and heatshrink_encoder::state.
Referenced by compress_and_expand_and_check(), and heatshrink_encoder_alloc().
{
     size_t buf_sz = (2 << HEATSHRINK_ENCODER_WINDOW_BITS(hse));
     memset(hse->buffer, 0, buf_sz);
     hse->input_size = 0;
     hse->state = HSES_NOT_FULL;
     hse->match_scan_index = 0;
     hse->flags = 0;
     hse->bit_index = 0x80;
     hse->current_byte = 0x00;
     hse->match_length = 0;
     hse->outgoing_bits = 0x0000;
     hse->outgoing_bits_count = 0;
     #ifdef LOOP_DETECT
     hse->loop_detect = (uint32_t)-1;
     #endif
 }
heatshrink_encoder_sink()
HSE_sink_res heatshrink_encoder_sink (heatshrink_encoder * hse, uint8_t * in_buf, size_t size, size_t * input_size)
Definition at line 145 of file heatshrink_encoder.c.
References heatshrink_encoder::buffer, do_indexing(), find_longest_match(), get_input_buffer_size(), get_input_offset(), hse, HSER_SINK_ERROR_MISUSE, HSER_SINK_ERROR_NULL, HSER_SINK_OK, HSES_FILLED, HSES_NOT_FULL, heatshrink_encoder::input_size, is_finishing(), LOG, memcpy, NULL, hs_index::size, st_flush_bit_buffer(), st_save_backlog(), st_step_search(), st_yield_br_index(), st_yield_br_length(), st_yield_literal(), st_yield_tag_bit(), and heatshrink_encoder::state.
Referenced by compress_and_expand_and_check(), data_with_simple_repetition_should_match_with_absurdly_tiny_buffers(), data_without_duplication_should_match_with_absurdly_tiny_buffers(), encoder_poll_should_detect_repeated_substring(), encoder_poll_should_detect_repeated_substring_and_preserve_trailing_literal(), encoder_should_emit_data_without_repetitions_as_literal_sequence(), encoder_should_emit_series_of_same_byte_as_literal_then_backref(), encoder_sink_read(), encoder_sink_should_accept_input_when_it_will_fit(), encoder_sink_should_accept_partial_input_when_some_will_fit(), encoder_sink_should_reject_nulls(), and gen().
{
     if ((hse == NULL) || (in_buf == NULL) || (input_size == NULL)) {
         return HSER_SINK_ERROR_NULL;
     }
     /* Sinking more content after saying the content is done, tsk tsk */
     if (is_finishing(hse)) { return HSER_SINK_ERROR_MISUSE; }
     /* Sinking more content before processing is done */
     if (hse->state != HSES_NOT_FULL) { return HSER_SINK_ERROR_MISUSE; }
     uint16_t write_offset = get_input_offset(hse) + hse->input_size;
     uint16_t ibs = get_input_buffer_size(hse);
     uint16_t rem = ibs - hse->input_size;
     uint16_t cp_sz = rem < size ? rem : size;
     memcpy(&hse->buffer[write_offset], in_buf, cp_sz);
     *input_size = cp_sz;
     hse->input_size += cp_sz;
     LOG("-- sunk %u bytes (of %zu) into encoder at %d, input buffer now has %u\n",
         cp_sz, size, write_offset, hse->input_size);
     if (cp_sz == rem) {
         LOG("-- internal buffer is now full\n");
         hse->state = HSES_FILLED;
     }
     return HSER_SINK_OK;
 }
is_finishing()
static int is_finishing (heatshrink_encoder * hse) static
Definition at line 471 of file heatshrink_encoder.c.
References FLAG_IS_FINISHING, and heatshrink_encoder::flags.
Referenced by heatshrink_encoder_sink(), st_save_backlog(), and st_step_search().
{
     return hse->flags & FLAG_IS_FINISHING;
 }
on_final_literal()
static int on_final_literal (heatshrink_encoder * hse) static
Definition at line 483 of file heatshrink_encoder.c.
References FLAG_ON_FINAL_LITERAL, and heatshrink_encoder::flags.
Referenced by st_yield_literal().
{
     return hse->flags & FLAG_ON_FINAL_LITERAL;
 }
push_bits()
static void push_bits (heatshrink_encoder * hse, uint8_t count, uint8_t bits, output_info * oi) static
Definition at line 587 of file heatshrink_encoder.c.
References ASSERT, heatshrink_encoder::bit_index, output_info::buf, heatshrink_encoder::current_byte, LOG, and output_info::output_size.
Referenced by add_tag_bit(), push_literal_byte(), and push_outgoing_bits().
{
     ASSERT(count <= 8);
     LOG("++ push_bits: %d bits, input of 0x%02x\n", count, bits);
     /* If adding a whole byte and at the start of a new output byte,
      * just push it through whole and skip the bit IO loop. */
     if (count == 8 && hse->bit_index == 0x80) {
         oi->buf[(*oi->output_size)++] = bits;
     } else {
         for (int i=count - 1; i>=0; i--) {
             bool bit = bits & (1 << i);
             if (bit) { hse->current_byte |= hse->bit_index; }
             if (0) {
                 LOG("  -- setting bit %d at bit index 0x%02x, byte => 0x%02x\n",
                     bit ? 1 : 0, hse->bit_index, hse->current_byte);
             }
             hse->bit_index >>= 1;
             if (hse->bit_index == 0x00) {
                 hse->bit_index = 0x80;
                 LOG(" > pushing byte 0x%02x\n", hse->current_byte);
                 oi->buf[(*oi->output_size)++] = hse->current_byte;
                 hse->current_byte = 0x00;
             }
         }
     }
 }
push_literal_byte()
static void push_literal_byte (heatshrink_encoder * hse, output_info * oi) static
Definition at line 615 of file heatshrink_encoder.c.
References heatshrink_encoder::buffer, get_input_offset(), isprint, LOG, heatshrink_encoder::match_scan_index, and push_bits().
Referenced by st_yield_literal().
{
     uint16_t processed_offset = hse->match_scan_index - 1;
     uint16_t input_offset = get_input_offset(hse) + processed_offset;
     uint8_t c = hse->buffer[input_offset];
     LOG("-- yielded literal byte 0x%02x ('%c') from +%d\n",
         c, isprint(c) ? c : '.', input_offset);
     push_bits(hse, 8, c, oi);
 }
push_outgoing_bits()
static uint8_t push_outgoing_bits (heatshrink_encoder * hse, output_info * oi) static
Definition at line 566 of file heatshrink_encoder.c.
References LOG, heatshrink_encoder::outgoing_bits, heatshrink_encoder::outgoing_bits_count, and push_bits().
Referenced by st_yield_br_index(), and st_yield_br_length().
{
     uint8_t count = 0;
     uint8_t bits = 0;
     if (hse->outgoing_bits_count > 8) {
         count = 8;
         bits = hse->outgoing_bits >> (hse->outgoing_bits_count - 8);
     } else {
         count = hse->outgoing_bits_count;
         bits = hse->outgoing_bits;
     }
     if (count > 0) {
         LOG("-- pushing %d outgoing bits: 0x%02x\n", count, bits);
         push_bits(hse, count, bits, oi);
         hse->outgoing_bits_count -= count;
     }
     return count;
 }
save_backlog()
static void save_backlog (heatshrink_encoder * hse) static
Definition at line 624 of file heatshrink_encoder.c.
References backlog_is_partial(), heatshrink_encoder::buffer, FLAG_BACKLOG_IS_FILLED, FLAG_BACKLOG_IS_PARTIAL, heatshrink_encoder::flags, get_input_buffer_size(), heatshrink_encoder::input_size, and heatshrink_encoder::match_scan_index.
Referenced by st_save_backlog().
{
     size_t input_buf_sz = get_input_buffer_size(hse);
     uint16_t msi = hse->match_scan_index;
     /* Copy processed data to beginning of buffer, so it can be
      * used for future matches. Don't bother checking whether the
      * input is less than the maximum size, because if it isn't,
      * we're done anyway. */
     uint16_t rem = input_buf_sz - msi; // unprocessed bytes
     uint16_t shift_sz = input_buf_sz + rem;
     memmove(&hse->buffer[0],
         &hse->buffer[input_buf_sz - rem],
         shift_sz);
     if (backlog_is_partial(hse)) {
         /* The whole backlog is filled in now, so include it in scans. */
         hse->flags |= FLAG_BACKLOG_IS_FILLED;
     } else {
         /* Include backlog, except for the first lookahead_sz bytes, which
          * are still undefined. */
         hse->flags |= FLAG_BACKLOG_IS_PARTIAL;
     }
     hse->match_scan_index = 0;
     hse->input_size -= input_buf_sz - rem;
 }
st_flush_bit_buffer()
static HSE_state st_flush_bit_buffer (heatshrink_encoder * hse, output_info * oi) static
Definition at line 398 of file heatshrink_encoder.c.
References heatshrink_encoder::bit_index, output_info::buf, can_take_byte(), heatshrink_encoder::current_byte, HSES_DONE, HSES_FLUSH_BITS, LOG, and output_info::output_size.
Referenced by heatshrink_encoder_poll(), and heatshrink_encoder_sink().
{
     if (hse->bit_index == 0x80) {
         LOG("-- done!\n");
         return HSES_DONE;
     } else if (can_take_byte(oi)) {
         LOG("-- flushing remaining byte (bit_index == 0x%02x)\n", hse->bit_index);
         oi->buf[(*oi->output_size)++] = hse->current_byte;
         LOG("-- done!\n");
         return HSES_DONE;
     } else {
         return HSES_FLUSH_BITS;
     }
 }
st_save_backlog()
static HSE_state st_save_backlog (heatshrink_encoder * hse) static
Definition at line 382 of file heatshrink_encoder.c.
References FLAG_ON_FINAL_LITERAL, heatshrink_encoder::flags, has_literal(), HSES_FLUSH_BITS, HSES_NOT_FULL, HSES_YIELD_TAG_BIT, is_finishing(), LOG, and save_backlog().
Referenced by heatshrink_encoder_poll(), and heatshrink_encoder_sink().
{
     if (is_finishing(hse)) {
         /* copy remaining literal (if necessary) */
         if (has_literal(hse)) {
             hse->flags |= FLAG_ON_FINAL_LITERAL;
             return HSES_YIELD_TAG_BIT;
         } else {
             return HSES_FLUSH_BITS;
         }
     } else {
         LOG("-- saving backlog\n");
         save_backlog(hse);
         return HSES_NOT_FULL;
     }
 }
st_step_search()
static HSE_state st_step_search (heatshrink_encoder * hse) static
Definition at line 268 of file heatshrink_encoder.c.
References ASSERT, backlog_is_filled(), backlog_is_partial(), find_longest_match(), FLAG_HAS_LITERAL, heatshrink_encoder::flags, get_input_buffer_size(), get_input_offset(), get_lookahead_size(), HSES_SAVE_BACKLOG, HSES_YIELD_TAG_BIT, heatshrink_encoder::input_size, is_finishing(), LOG, heatshrink_encoder::match_length, MATCH_NOT_FOUND, heatshrink_encoder::match_pos, heatshrink_encoder::match_scan_index, and heatshrink_encoder::window_sz2.
Referenced by heatshrink_encoder_poll(), and heatshrink_encoder_sink().
{
     uint16_t window_length = get_input_buffer_size(hse);
     uint16_t lookahead_sz = get_lookahead_size(hse);
     uint16_t msi = hse->match_scan_index;
     LOG("## step_search, scan @ +%d (%d/%d), input size %d\n",
         msi, hse->input_size + msi, 2*window_length, hse->input_size);
     bool fin = is_finishing(hse);
     if (msi >= hse->input_size - (fin ? 0 : lookahead_sz)) {
         /* Current search buffer is exhausted, copy it into the
          * backlog and await more input. */
         LOG("-- end of search @ %d, saving backlog\n", msi);
         return HSES_SAVE_BACKLOG;
     }
     uint16_t input_offset = get_input_offset(hse);
     uint16_t end = input_offset + msi;
     uint16_t start = 0;
     if (backlog_is_filled(hse)) { /* last WINDOW_LENGTH bytes */
         start = end - window_length + 1;
     } else if (backlog_is_partial(hse)) { /* clamp to available data */
         start = end - window_length + 1;
         if (start < lookahead_sz) { start = lookahead_sz; }
     } else {              /* only scan available input */
         start = input_offset;
     }
     uint16_t max_possible = lookahead_sz;
     if (hse->input_size - msi < lookahead_sz) {
         max_possible = hse->input_size - msi;
     }
     uint16_t match_length = 0;
     uint16_t match_pos = find_longest_match(hse,
         start, end, max_possible, &match_length);
     if (match_pos == MATCH_NOT_FOUND) {
         LOG("ss Match not found\n");
         hse->match_scan_index++;
         hse->flags |= FLAG_HAS_LITERAL;
         hse->match_length = 0;
         return HSES_YIELD_TAG_BIT;
     } else {
         LOG("ss Found match of %d bytes at %d\n", match_length, match_pos);
         hse->match_pos = match_pos;
         hse->match_length = match_length;
         ASSERT(match_pos < 1 << hse->window_sz2 /*window_length*/);
         return HSES_YIELD_TAG_BIT;
     }
 }
st_yield_br_index()
static HSE_state st_yield_br_index (heatshrink_encoder * hse, output_info * oi) static
Definition at line 350 of file heatshrink_encoder.c.
References can_take_byte(), HEATSHRINK_ENCODER_LOOKAHEAD_BITS, HSES_YIELD_BR_INDEX, HSES_YIELD_BR_LENGTH, LOG, heatshrink_encoder::match_length, heatshrink_encoder::match_pos, heatshrink_encoder::outgoing_bits, heatshrink_encoder::outgoing_bits_count, and push_outgoing_bits().
Referenced by heatshrink_encoder_poll(), and heatshrink_encoder_sink().
{
     if (can_take_byte(oi)) {
         LOG("-- yielding backref index %u\n", hse->match_pos);
         if (push_outgoing_bits(hse, oi) > 0) {
             return HSES_YIELD_BR_INDEX; /* continue */
         } else {
             hse->outgoing_bits = hse->match_length - 1;
             hse->outgoing_bits_count = HEATSHRINK_ENCODER_LOOKAHEAD_BITS(hse);
             return HSES_YIELD_BR_LENGTH; /* done */
         }
     } else {
         return HSES_YIELD_BR_INDEX; /* continue */
     }
 }
st_yield_br_length()
static HSE_state st_yield_br_length (heatshrink_encoder * hse, output_info * oi) static
Definition at line 366 of file heatshrink_encoder.c.
References can_take_byte(), HSES_SEARCH, HSES_YIELD_BR_LENGTH, LOG, heatshrink_encoder::match_length, heatshrink_encoder::match_scan_index, and push_outgoing_bits().
Referenced by heatshrink_encoder_poll(), and heatshrink_encoder_sink().
{
     if (can_take_byte(oi)) {
         LOG("-- yielding backref length %u\n", hse->match_length);
         if (push_outgoing_bits(hse, oi) > 0) {
             return HSES_YIELD_BR_LENGTH;
         } else {
             hse->match_scan_index += hse->match_length;
             hse->match_length = 0;
             return HSES_SEARCH;
         }
     } else {
         return HSES_YIELD_BR_LENGTH;
     }
 }
st_yield_literal()
static HSE_state st_yield_literal (heatshrink_encoder * hse, output_info * oi) static
Definition at line 338 of file heatshrink_encoder.c.
References can_take_byte(), FLAG_HAS_LITERAL, heatshrink_encoder::flags, HSES_FLUSH_BITS, HSES_SEARCH, HSES_YIELD_LITERAL, HSES_YIELD_TAG_BIT, heatshrink_encoder::match_length, on_final_literal(), and push_literal_byte().
Referenced by heatshrink_encoder_poll(), and heatshrink_encoder_sink().
{
     if (can_take_byte(oi)) {
         push_literal_byte(hse, oi);
         hse->flags &= ~FLAG_HAS_LITERAL;
         if (on_final_literal(hse)) { return HSES_FLUSH_BITS; }
         return hse->match_length > 0 ? HSES_YIELD_TAG_BIT : HSES_SEARCH;
     } else {
         return HSES_YIELD_LITERAL;
     }
 }
st_yield_tag_bit()
static HSE_state st_yield_tag_bit (heatshrink_encoder * hse, output_info * oi) static
Definition at line 321 of file heatshrink_encoder.c.
References add_tag_bit(), can_take_byte(), HEATSHRINK_BACKREF_MARKER, HEATSHRINK_ENCODER_WINDOW_BITS, HEATSHRINK_LITERAL_MARKER, HSES_YIELD_BR_INDEX, HSES_YIELD_LITERAL, HSES_YIELD_TAG_BIT, heatshrink_encoder::match_length, heatshrink_encoder::match_pos, heatshrink_encoder::outgoing_bits, and heatshrink_encoder::outgoing_bits_count.
Referenced by heatshrink_encoder_poll(), and heatshrink_encoder_sink().
{
     if (can_take_byte(oi)) {
         if (hse->match_length == 0) {
             add_tag_bit(hse, oi, HEATSHRINK_LITERAL_MARKER);
             return HSES_YIELD_LITERAL;
         } else {
             add_tag_bit(hse, oi, HEATSHRINK_BACKREF_MARKER);
             hse->outgoing_bits = hse->match_pos - 1;
             hse->outgoing_bits_count = HEATSHRINK_ENCODER_WINDOW_BITS(hse);
             return HSES_YIELD_BR_INDEX;
         }
     } else {
         return HSES_YIELD_TAG_BIT; /* output is full, continue */
     }
 }