MeterLogger: lib/heatshrink/heatshrink_encoder.h File Reference
heatshrink_encoder.h File Reference
#include <stddef.h>
#include "heatshrink_common.h"
#include "heatshrink_config.h"
Data Structures
struct hs_index
struct heatshrink_encoder
Macros
#define HEATSHRINK_ENCODER_WINDOW_BITS(HSE) ((HSE)->window_sz2)
#define HEATSHRINK_ENCODER_LOOKAHEAD_BITS(HSE) ((HSE)->lookahead_sz2)
#define HEATSHRINK_ENCODER_INDEX(HSE) ((HSE)->search_index)
Enumerations
enum HSE_sink_res { HSER_SINK_OK, HSER_SINK_ERROR_NULL =-1, HSER_SINK_ERROR_MISUSE =-2 }
enum HSE_poll_res { HSER_POLL_EMPTY, HSER_POLL_MORE, HSER_POLL_ERROR_NULL =-1, HSER_POLL_ERROR_MISUSE =-2 }
enum HSE_finish_res { HSER_FINISH_DONE, HSER_FINISH_MORE, HSER_FINISH_ERROR_NULL =-1 }
Functions
heatshrink_encoder * heatshrink_encoder_alloc (uint8_t window_sz2, uint8_t lookahead_sz2)
void heatshrink_encoder_free (heatshrink_encoder *hse)
void heatshrink_encoder_reset (heatshrink_encoder *hse)
HSE_sink_res heatshrink_encoder_sink (heatshrink_encoder *hse, uint8_t *in_buf, size_t size, size_t *input_size)
HSE_poll_res heatshrink_encoder_poll (heatshrink_encoder *hse, uint8_t *out_buf, size_t out_buf_size, size_t *output_size)
HSE_finish_res heatshrink_encoder_finish (heatshrink_encoder *hse)
Macro Definition Documentation
HEATSHRINK_ENCODER_INDEX
#define HEATSHRINK_ENCODER_INDEX (HSE) ((HSE)->search_index)
Definition at line 32 of file heatshrink_encoder.h.
Referenced by do_indexing(), and find_longest_match().
HEATSHRINK_ENCODER_LOOKAHEAD_BITS
#define HEATSHRINK_ENCODER_LOOKAHEAD_BITS (HSE) ((HSE)->lookahead_sz2)
Definition at line 30 of file heatshrink_encoder.h.
Referenced by get_lookahead_size(), and st_yield_br_index().
HEATSHRINK_ENCODER_WINDOW_BITS
#define HEATSHRINK_ENCODER_WINDOW_BITS (HSE) ((HSE)->window_sz2)
Definition at line 28 of file heatshrink_encoder.h.
Referenced by get_input_buffer_size(), heatshrink_encoder_free(), heatshrink_encoder_reset(), and st_yield_tag_bit().
Enumeration Type Documentation
HSE_finish_res
enum HSE_finish_res
Enumerator
HSER_FINISH_DONE
HSER_FINISH_MORE
HSER_FINISH_ERROR_NULL
Definition at line 21 of file heatshrink_encoder.h.
              {
     HSER_FINISH_DONE,           /* encoding is complete */
     HSER_FINISH_MORE,           /* more output remaining; use poll */
     HSER_FINISH_ERROR_NULL=-1,  /* NULL argument */
 } HSE_finish_res;
HSE_poll_res
enum HSE_poll_res
Enumerator
HSER_POLL_EMPTY
HSER_POLL_MORE
HSER_POLL_ERROR_NULL
HSER_POLL_ERROR_MISUSE
Definition at line 14 of file heatshrink_encoder.h.
              {
     HSER_POLL_EMPTY,            /* input exhausted */
     HSER_POLL_MORE,             /* poll again for more output  */
     HSER_POLL_ERROR_NULL=-1,    /* NULL argument */
     HSER_POLL_ERROR_MISUSE=-2,  /* API misuse */
 } HSE_poll_res;
HSE_sink_res
enum HSE_sink_res
Enumerator
HSER_SINK_OK
HSER_SINK_ERROR_NULL
HSER_SINK_ERROR_MISUSE
Definition at line 8 of file heatshrink_encoder.h.
              {
     HSER_SINK_OK,               /* data sunk into input buffer */
     HSER_SINK_ERROR_NULL=-1,    /* NULL argument */
     HSER_SINK_ERROR_MISUSE=-2,  /* API misuse */
 } HSE_sink_res;
Function Documentation
heatshrink_encoder_alloc()
heatshrink_encoder* heatshrink_encoder_alloc (uint8_t window_sz2, uint8_t lookahead_sz2)
Definition at line 78 of file heatshrink_encoder.c.
References get_input_buffer_size(), heatshrink_encoder_reset(), HEATSHRINK_FREE, HEATSHRINK_MALLOC, HEATSHRINK_MAX_WINDOW_BITS, HEATSHRINK_MIN_LOOKAHEAD_BITS, HEATSHRINK_MIN_WINDOW_BITS, hse, LOG, heatshrink_encoder::lookahead_sz2, NULL, heatshrink_encoder::search_index, hs_index::size, and heatshrink_encoder::window_sz2.
Referenced by compress_and_expand_and_check(), data_with_simple_repetition_should_match_with_absurdly_tiny_buffers(), data_without_duplication_should_match_with_absurdly_tiny_buffers(), encode(), encoder_alloc_should_reject_invalid_arguments(), encoder_poll_should_detect_repeated_substring(), encoder_poll_should_detect_repeated_substring_and_preserve_trailing_literal(), encoder_poll_should_indicate_when_no_input_is_provided(), encoder_poll_should_reject_nulls(), encoder_should_emit_data_without_repetitions_as_literal_sequence(), encoder_should_emit_series_of_same_byte_as_literal_then_backref(), encoder_sink_should_accept_input_when_it_will_fit(), encoder_sink_should_accept_partial_input_when_some_will_fit(), encoder_sink_should_reject_nulls(), and gen().
{
     if ((window_sz2 < HEATSHRINK_MIN_WINDOW_BITS) ||
         (window_sz2 > HEATSHRINK_MAX_WINDOW_BITS) ||
         (lookahead_sz2 < HEATSHRINK_MIN_LOOKAHEAD_BITS) ||
         (lookahead_sz2 > window_sz2)) {
         return NULL;
     }
     /* Note: 2 * the window size is used because the buffer needs to fit
      * (1 << window_sz2) bytes for the current input, and an additional
      * (1 << window_sz2) bytes for the previous buffer of input, which
      * will be scanned for useful backreferences. */
     size_t buf_sz = (2 << window_sz2);
     heatshrink_encoder *hse = HEATSHRINK_MALLOC(sizeof(*hse) + buf_sz);
     if (hse == NULL) { return NULL; }
     hse->window_sz2 = window_sz2;
     hse->lookahead_sz2 = lookahead_sz2;
     heatshrink_encoder_reset(hse);
 #if HEATSHRINK_USE_INDEX
     size_t index_sz = buf_sz*sizeof(uint16_t);
     hse->search_index = HEATSHRINK_MALLOC(index_sz + sizeof(struct hs_index));
     if (hse->search_index == NULL) {
         HEATSHRINK_FREE(hse, sizeof(*hse) + buf_sz);
         return NULL;
     }
     hse->search_index->size = index_sz;
 #endif
     LOG("-- allocated encoder with buffer size of %zu (%u byte input size)\n",
         buf_sz, get_input_buffer_size(hse));
     return hse;
 }
heatshrink_encoder_finish()
HSE_finish_res heatshrink_encoder_finish (heatshrink_encoder * hse)
Definition at line 260 of file heatshrink_encoder.c.
References FLAG_IS_FINISHING, heatshrink_encoder::flags, HSER_FINISH_DONE, HSER_FINISH_ERROR_NULL, HSER_FINISH_MORE, HSES_DONE, HSES_FILLED, HSES_NOT_FULL, LOG, NULL, and heatshrink_encoder::state.
Referenced by compress_and_expand_and_check(), data_with_simple_repetition_should_match_with_absurdly_tiny_buffers(), data_without_duplication_should_match_with_absurdly_tiny_buffers(), encoder_finish_should_reject_nulls(), encoder_poll_should_detect_repeated_substring(), encoder_poll_should_detect_repeated_substring_and_preserve_trailing_literal(), encoder_should_emit_data_without_repetitions_as_literal_sequence(), encoder_should_emit_series_of_same_byte_as_literal_then_backref(), encoder_sink_read(), and gen().
{
     if (hse == NULL) { return HSER_FINISH_ERROR_NULL; }
     LOG("-- setting is_finishing flag\n");
     hse->flags |= FLAG_IS_FINISHING;
     if (hse->state == HSES_NOT_FULL) { hse->state = HSES_FILLED; }
     return hse->state == HSES_DONE ? HSER_FINISH_DONE : HSER_FINISH_MORE;
 }
heatshrink_encoder_free()
void heatshrink_encoder_free (heatshrink_encoder * hse)
Definition at line 114 of file heatshrink_encoder.c.
References HEATSHRINK_ENCODER_WINDOW_BITS, and HEATSHRINK_FREE.
Referenced by compress_and_expand_and_check(), data_with_simple_repetition_should_match_with_absurdly_tiny_buffers(), data_without_duplication_should_match_with_absurdly_tiny_buffers(), encode(), encoder_poll_should_detect_repeated_substring(), encoder_poll_should_detect_repeated_substring_and_preserve_trailing_literal(), encoder_poll_should_indicate_when_no_input_is_provided(), encoder_poll_should_reject_nulls(), encoder_should_emit_data_without_repetitions_as_literal_sequence(), encoder_should_emit_series_of_same_byte_as_literal_then_backref(), encoder_sink_should_accept_input_when_it_will_fit(), encoder_sink_should_accept_partial_input_when_some_will_fit(), encoder_sink_should_reject_nulls(), and gen().
{
     size_t buf_sz = (2 << HEATSHRINK_ENCODER_WINDOW_BITS(hse));
 #if HEATSHRINK_USE_INDEX
     size_t index_sz = sizeof(struct hs_index) + hse->search_index->size;
     HEATSHRINK_FREE(hse->search_index, index_sz);
     (void)index_sz;
 #endif
     HEATSHRINK_FREE(hse, sizeof(heatshrink_encoder) + buf_sz);
     (void)buf_sz;
 }
heatshrink_encoder_poll()
HSE_poll_res heatshrink_encoder_poll (heatshrink_encoder * hse, uint8_t * out_buf, size_t out_buf_size, size_t * output_size)
Definition at line 198 of file heatshrink_encoder.c.
References output_info::buf, output_info::buf_size, do_indexing(), heatshrink_encoder::flags, HSER_POLL_EMPTY, HSER_POLL_ERROR_MISUSE, HSER_POLL_ERROR_NULL, HSER_POLL_MORE, HSES_DONE, HSES_FILLED, HSES_FLUSH_BITS, HSES_NOT_FULL, HSES_SAVE_BACKLOG, HSES_SEARCH, HSES_YIELD_BR_INDEX, HSES_YIELD_BR_LENGTH, HSES_YIELD_LITERAL, HSES_YIELD_TAG_BIT, LOG, NULL, output_info::output_size, st_flush_bit_buffer(), st_save_backlog(), st_step_search(), st_yield_br_index(), st_yield_br_length(), st_yield_literal(), st_yield_tag_bit(), and heatshrink_encoder::state.
Referenced by compress_and_expand_and_check(), data_with_simple_repetition_should_match_with_absurdly_tiny_buffers(), data_without_duplication_should_match_with_absurdly_tiny_buffers(), encoder_poll_should_detect_repeated_substring(), encoder_poll_should_detect_repeated_substring_and_preserve_trailing_literal(), encoder_poll_should_indicate_when_no_input_is_provided(), encoder_poll_should_reject_nulls(), encoder_should_emit_data_without_repetitions_as_literal_sequence(), encoder_should_emit_series_of_same_byte_as_literal_then_backref(), encoder_sink_read(), and gen().
{
     if ((hse == NULL) || (out_buf == NULL) || (output_size == NULL)) {
         return HSER_POLL_ERROR_NULL;
     }
     if (out_buf_size == 0) {
         LOG("-- MISUSE: output buffer size is 0\n");
         return HSER_POLL_ERROR_MISUSE;
     }
     *output_size = 0;
     output_info oi;
     oi.buf = out_buf;
     oi.buf_size = out_buf_size;
     oi.output_size = output_size;
     while (1) {
         LOG("-- polling, state %u (%s), flags 0x%02x\n",
             hse->state, state_names[hse->state], hse->flags);
         uint8_t in_state = hse->state;
         switch (in_state) {
         case HSES_NOT_FULL:
             return HSER_POLL_EMPTY;
         case HSES_FILLED:
             do_indexing(hse);
             hse->state = HSES_SEARCH;
             break;
         case HSES_SEARCH:
             hse->state = st_step_search(hse);
             break;
         case HSES_YIELD_TAG_BIT:
             hse->state = st_yield_tag_bit(hse, &oi);
             break;
         case HSES_YIELD_LITERAL:
             hse->state = st_yield_literal(hse, &oi);
             break;
         case HSES_YIELD_BR_INDEX:
             hse->state = st_yield_br_index(hse, &oi);
             break;
         case HSES_YIELD_BR_LENGTH:
             hse->state = st_yield_br_length(hse, &oi);
             break;
         case HSES_SAVE_BACKLOG:
             hse->state = st_save_backlog(hse);
             break;
         case HSES_FLUSH_BITS:
             hse->state = st_flush_bit_buffer(hse, &oi);
         case HSES_DONE:
             return HSER_POLL_EMPTY;
         default:
             LOG("-- bad state %s\n", state_names[hse->state]);
             return HSER_POLL_ERROR_MISUSE;
         }
         if (hse->state == in_state) {
             /* Check if output buffer is exhausted. */
             if (*output_size == out_buf_size) return HSER_POLL_MORE;
         }
     }
 }
heatshrink_encoder_reset()
void heatshrink_encoder_reset (heatshrink_encoder * hse)
Definition at line 126 of file heatshrink_encoder.c.
References heatshrink_encoder::bit_index, heatshrink_encoder::buffer, heatshrink_encoder::current_byte, heatshrink_encoder::flags, HEATSHRINK_ENCODER_WINDOW_BITS, HSES_NOT_FULL, heatshrink_encoder::input_size, heatshrink_encoder::match_length, heatshrink_encoder::match_scan_index, memset, heatshrink_encoder::outgoing_bits, heatshrink_encoder::outgoing_bits_count, and heatshrink_encoder::state.
Referenced by compress_and_expand_and_check(), and heatshrink_encoder_alloc().
{
     size_t buf_sz = (2 << HEATSHRINK_ENCODER_WINDOW_BITS(hse));
     memset(hse->buffer, 0, buf_sz);
     hse->input_size = 0;
     hse->state = HSES_NOT_FULL;
     hse->match_scan_index = 0;
     hse->flags = 0;
     hse->bit_index = 0x80;
     hse->current_byte = 0x00;
     hse->match_length = 0;
     hse->outgoing_bits = 0x0000;
     hse->outgoing_bits_count = 0;
     #ifdef LOOP_DETECT
     hse->loop_detect = (uint32_t)-1;
     #endif
 }
heatshrink_encoder_sink()
HSE_sink_res heatshrink_encoder_sink (heatshrink_encoder * hse, uint8_t * in_buf, size_t size, size_t * input_size)
Definition at line 145 of file heatshrink_encoder.c.
References heatshrink_encoder::buffer, do_indexing(), find_longest_match(), get_input_buffer_size(), get_input_offset(), hse, HSER_SINK_ERROR_MISUSE, HSER_SINK_ERROR_NULL, HSER_SINK_OK, HSES_FILLED, HSES_NOT_FULL, heatshrink_encoder::input_size, is_finishing(), LOG, memcpy, NULL, hs_index::size, st_flush_bit_buffer(), st_save_backlog(), st_step_search(), st_yield_br_index(), st_yield_br_length(), st_yield_literal(), st_yield_tag_bit(), and heatshrink_encoder::state.
Referenced by compress_and_expand_and_check(), data_with_simple_repetition_should_match_with_absurdly_tiny_buffers(), data_without_duplication_should_match_with_absurdly_tiny_buffers(), encoder_poll_should_detect_repeated_substring(), encoder_poll_should_detect_repeated_substring_and_preserve_trailing_literal(), encoder_should_emit_data_without_repetitions_as_literal_sequence(), encoder_should_emit_series_of_same_byte_as_literal_then_backref(), encoder_sink_read(), encoder_sink_should_accept_input_when_it_will_fit(), encoder_sink_should_accept_partial_input_when_some_will_fit(), encoder_sink_should_reject_nulls(), and gen().
{
     if ((hse == NULL) || (in_buf == NULL) || (input_size == NULL)) {
         return HSER_SINK_ERROR_NULL;
     }
     /* Sinking more content after saying the content is done, tsk tsk */
     if (is_finishing(hse)) { return HSER_SINK_ERROR_MISUSE; }
     /* Sinking more content before processing is done */
     if (hse->state != HSES_NOT_FULL) { return HSER_SINK_ERROR_MISUSE; }
     uint16_t write_offset = get_input_offset(hse) + hse->input_size;
     uint16_t ibs = get_input_buffer_size(hse);
     uint16_t rem = ibs - hse->input_size;
     uint16_t cp_sz = rem < size ? rem : size;
     memcpy(&hse->buffer[write_offset], in_buf, cp_sz);
     *input_size = cp_sz;
     hse->input_size += cp_sz;
     LOG("-- sunk %u bytes (of %zu) into encoder at %d, input buffer now has %u\n",
         cp_sz, size, write_offset, hse->input_size);
     if (cp_sz == rem) {
         LOG("-- internal buffer is now full\n");
         hse->state = HSES_FILLED;
     }
     return HSER_SINK_OK;
 }