MeterLogger: user/httpdespfs.h File Reference
httpdespfs.h File Reference
#include "httpd.h"
#include "espfs.h"
Functions
int cgiEspFsHook (HttpdConnData *connData)
int ICACHE_FLASH_ATTR cgiEspFsTemplate (HttpdConnData *connData)
Function Documentation
cgiEspFsHook()
int cgiEspFsHook (HttpdConnData * connData)
Definition at line 39 of file httpdespfs.c.
References HttpdConnData::cgiData, HttpdConnData::conn, espconn_sent(), espFsClose(), espFsOpen(), espFsRead(), HTTPD_CGI_DONE, HTTPD_CGI_MORE, HTTPD_CGI_NOTFOUND, httpdEndHeaders(), httpdGetMimetype(), httpdHeader(), httpdStartResponse(), NULL, and HttpdConnData::url.
{
     EspFsFile *file=connData->cgiData;
     int len;
     char buff[1024];
     if (connData->conn==NULL) {
         //Connection aborted. Clean up.
         espFsClose(file);
         return HTTPD_CGI_DONE;
     }
     if (file==NULL) {
         //First call to this cgi. Open the file so we can read it.
         file=espFsOpen(connData->url);
         if (file==NULL) {
             return HTTPD_CGI_NOTFOUND;
         }
         connData->cgiData=file;
         httpdStartResponse(connData, 200);
         httpdHeader(connData, "Content-Type", httpdGetMimetype(connData->url));
         httpdHeader(connData, "Cache-Control", "max-age=3600, must-revalidate");
         httpdEndHeaders(connData);
         return HTTPD_CGI_MORE;
     }
     len=espFsRead(file, buff, 1024);
     if (len>0) espconn_sent(connData->conn, (uint8 *)buff, len);
     if (len!=1024) {
         //We're done.
         espFsClose(file);
         return HTTPD_CGI_DONE;
     } else {
         //Ok, till next time.
         return HTTPD_CGI_MORE;
     }
 }
cgiEspFsTemplate()
int ICACHE_FLASH_ATTR cgiEspFsTemplate (HttpdConnData * connData)
Definition at line 88 of file httpdespfs.c.
References HttpdConnData::cgiArg, HttpdConnData::cgiData, HttpdConnData::conn, espFsClose(), espFsOpen(), espFsRead(), TplData::file, HTTPD_CGI_DONE, HTTPD_CGI_MORE, HTTPD_CGI_NOTFOUND, httpdEndHeaders(), httpdGetMimetype(), httpdHeader(), httpdSend(), httpdStartResponse(), NULL, os_free, os_malloc, TplData::token, TplData::tokenPos, TplData::tplArg, and HttpdConnData::url.
{
     TplData *tpd=connData->cgiData;
     int len;
     int x, sp=0;
     char *e=NULL;
     char buff[1025];
     if (connData->conn==NULL) {
         //Connection aborted. Clean up.
         ((TplCallback)(connData->cgiArg))(connData, NULL, &tpd->tplArg);
         espFsClose(tpd->file);
         os_free(tpd);
         return HTTPD_CGI_DONE;
     }
     if (tpd==NULL) {
         //First call to this cgi. Open the file so we can read it.
         tpd=(TplData *)os_malloc(sizeof(TplData));
         tpd->file=espFsOpen(connData->url);
         tpd->tplArg=NULL;
         tpd->tokenPos=-1;
         if (tpd->file==NULL) {
             return HTTPD_CGI_NOTFOUND;
         }
         connData->cgiData=tpd;
         httpdStartResponse(connData, 200);
         httpdHeader(connData, "Content-Type", httpdGetMimetype(connData->url));
         httpdEndHeaders(connData);
         return HTTPD_CGI_MORE;
     }
     len=espFsRead(tpd->file, buff, 1024);
     if (len>0) {
         sp=0;
         e=buff;
         for (x=0; x<len; x++) {
             if (tpd->tokenPos==-1) {
                 //Inside ordinary text.
                 if (buff[x]=='%') {
                     //Send raw data up to now
                     if (sp!=0) httpdSend(connData, e, sp);
                     sp=0;
                     //Go collect token chars.
                     tpd->tokenPos=0;
                 } else {
                     sp++;
                 }
             } else {
                 if (buff[x]=='%') {
                     if (tpd->tokenPos==0) {
                         //This is the second % of a %% escape string.
                         //Send a single % and resume with the normal program flow.
                         httpdSend(connData, "%", 1);
                     } else {
                         //This is an actual token.
                         tpd->token[tpd->tokenPos++]=0; //zero-terminate token
                         ((TplCallback)(connData->cgiArg))(connData, tpd->token, &tpd->tplArg);
                     }
                     //Go collect normal chars again.
                     e=&buff[x+1];
                     tpd->tokenPos=-1;
                 } else {
                     if (tpd->tokenPos<(sizeof(tpd->token)-1)) tpd->token[tpd->tokenPos++]=buff[x];
                 }
             }
         }
     }
     //Send remaining bit.
     if (sp!=0) httpdSend(connData, e, sp);
     if (len!=1024) {
         //We're done.
         ((TplCallback)(connData->cgiArg))(connData, NULL, &tpd->tplArg);
         espFsClose(tpd->file);
         return HTTPD_CGI_DONE;
     } else {
         //Ok, till next time.
         return HTTPD_CGI_MORE;
     }
 }