MeterLogger: user/httpd.c File Reference
httpd.c File Reference
#include <esp8266.h>
#include <lwip/ip.h>
#include <lwip/udp.h>
#include <lwip/tcp_impl.h>
#include <netif/etharp.h>
#include <lwip/netif.h>
#include <lwip/lwip_napt.h>
#include <lwip/dns.h>
#include <lwip/app/dhcpserver.h>
#include <lwip/opt.h>
#include <espconn.h>
#include "httpd.h"
#include "espfs.h"
#include "debug.h"
#include "tinyprintf.h"
Data Structures
struct HttpdPriv
struct MimeMap
Macros
#define MAX_HEAD_LEN 1024
#define MAX_CONN 4
#define MAX_POST 1024
#define MAX_SENDBUFF_LEN 2048
Functions
ICACHE_FLASH_ATTR const char * httpdGetMimetype (char *url)
static ICACHE_FLASH_ATTR HttpdConnData * httpdFindConnData (void *arg)
static ICACHE_FLASH_ATTR void httpdRetireConn (HttpdConnData *conn)
static int httpdHexVal (char c)
int httpdUrlDecode (char *val, int valLen, char *ret, int retLen)
ICACHE_FLASH_ATTR int httpdFindArg (char *line, char *arg, char *buff, int buffLen)
ICACHE_FLASH_ATTR int httpdGetHeader (HttpdConnData *conn, char *header, char *ret, int retLen)
ICACHE_FLASH_ATTR void httpdStartResponse (HttpdConnData *conn, int code)
ICACHE_FLASH_ATTR void httpdHeader (HttpdConnData *conn, const char *field, const char *val)
ICACHE_FLASH_ATTR void httpdEndHeaders (HttpdConnData *conn)
ICACHE_FLASH_ATTR void httpdRedirect (HttpdConnData *conn, char *newUrl)
ICACHE_FLASH_ATTR int cgiRedirect (HttpdConnData *connData)
ICACHE_FLASH_ATTR int httpdSend (HttpdConnData *conn, const char *data, int len)
static ICACHE_FLASH_ATTR void xmitSendBuff (HttpdConnData *conn)
static ICACHE_FLASH_ATTR void httpdSentCb (void *arg)
static ICACHE_FLASH_ATTR void httpdSendResp (HttpdConnData *conn)
static ICACHE_FLASH_ATTR void httpdParseHeader (char *h, HttpdConnData *conn)
static ICACHE_FLASH_ATTR void httpdRecvCb (void *arg, char *data, unsigned short len)
static ICACHE_FLASH_ATTR void httpdReconCb (void *arg, sint8 err)
static ICACHE_FLASH_ATTR void httpdDisconCb (void *arg)
static ICACHE_FLASH_ATTR void httpdConnectCb (void *arg)
ICACHE_FLASH_ATTR void httpdInit (HttpdBuiltInUrl *fixedUrls, int port)
ICACHE_FLASH_ATTR static void httpdDisconnectTimerFunc (void *arg)
ICACHE_FLASH_ATTR void httpdStop ()
Variables
static HttpdBuiltInUrl * builtInUrls
static HttpdPriv * connPrivData
static HttpdConnData connData [MAX_CONN]
static struct espconn httpdConn = (struct espconn){ 0 }
static esp_tcp httpdTcp
static const MimeMap mimeTypes []
static os_timer_t httpdDisconnectTimer
static const char * httpNotFoundHeader ="HTTP/1.0 404 Not Found\r\nServer: esp8266-httpd/0.1\r\nContent-Type: text/plain\r\n\r\nNot Found.\r\n"
Macro Definition Documentation
MAX_CONN
#define MAX_CONN 4
Definition at line 41 of file httpd.c.
Referenced by httpdConnectCb(), httpdDisconCb(), httpdFindConnData(), and httpdInit().
MAX_HEAD_LEN
#define MAX_HEAD_LEN 1024
Definition at line 39 of file httpd.c.
Referenced by httpdRecvCb().
MAX_POST
#define MAX_POST 1024
Definition at line 43 of file httpd.c.
Referenced by httpdParseHeader().
MAX_SENDBUFF_LEN
#define MAX_SENDBUFF_LEN 2048
Definition at line 45 of file httpd.c.
Referenced by httpdRecvCb(), httpdSend(), and httpdSentCb().
Function Documentation
cgiRedirect()
ICACHE_FLASH_ATTR int cgiRedirect (HttpdConnData * connData)
Definition at line 256 of file httpd.c.
References HttpdConnData::cgiArg, HttpdConnData::conn, HTTPD_CGI_DONE, httpdRedirect(), ICACHE_FLASH_ATTR, and NULL.
{
     if (connData->conn==NULL) {
         //Connection aborted. Clean up.
         return HTTPD_CGI_DONE;
     }
     httpdRedirect(connData, (char*)connData->cgiArg);
     return HTTPD_CGI_DONE;
 }
httpdConnectCb()
static ICACHE_FLASH_ATTR void httpdConnectCb (void * arg) static
Definition at line 483 of file httpd.c.
References conn, HttpdConnData::conn, espconn_disconnect(), espconn_regist_disconcb(), espconn_regist_reconcb(), espconn_regist_recvcb(), espconn_regist_sentcb(), HttpdPriv::headPos, httpdDisconCb(), httpdReconCb(), httpdRecvCb(), httpdSentCb(), ICACHE_FLASH_ATTR, INFO, MAX_CONN, NULL, HttpdConnData::postBuff, HttpdConnData::postLen, HttpdPriv::postPos, and HttpdConnData::priv.
Referenced by httpdInit().
{
     struct espconn *conn=arg;
     int i;
     //Find empty conndata in pool
     for (i=0; i<MAX_CONN; i++) if (connData[i].conn==NULL) break;
     INFO("Con req, conn=%p, pool slot %d\n", conn, i);
     if (i==MAX_CONN) {
         INFO("Aiee, conn pool overflow!\n");
         espconn_disconnect(conn);
         return;
     }
     connData[i].priv=&connPrivData[i];
     connData[i].conn=conn;
     connData[i].priv->headPos=0;
     connData[i].postBuff=NULL;
     connData[i].priv->postPos=0;
     connData[i].postLen=-1;
     espconn_regist_recvcb(conn, httpdRecvCb);
     espconn_regist_reconcb(conn, httpdReconCb);
     espconn_regist_disconcb(conn, httpdDisconCb);
     espconn_regist_sentcb(conn, httpdSentCb);
 }
httpdDisconCb()
static ICACHE_FLASH_ATTR void httpdDisconCb (void * arg) static
Definition at line 454 of file httpd.c.
References HttpdConnData::cgi, conn, HttpdConnData::conn, ESPCONN_CLOSE, ESPCONN_NONE, httpdFindConnData(), httpdRetireConn(), ICACHE_FLASH_ATTR, INFO, MAX_CONN, NULL, and espconn::state.
Referenced by httpdConnectCb().
{
 #if 0
     //Stupid esp sdk passes through wrong arg here, namely the one of the *listening* socket.
     //If it ever gets fixed, be sure to update the code in this snippet; it's probably out-of-date.
     HttpdConnData *conn=httpdFindConnData(arg);
     INFO("Disconnected, conn=%p\n", conn);
     if (conn==NULL) return;
     conn->conn=NULL;
     if (conn->cgi!=NULL) conn->cgi(conn); //flush cgi data
 #endif
     //Just look at all the sockets and kill the slot if needed.
     int i;
     for (i=0; i<MAX_CONN; i++) {
         if (connData[i].conn!=NULL) {
             //Why the >=ESPCONN_CLOSE and not ==? Well, seems the stack sometimes de-allocates
             //espconns under our noses, especially when connections are interrupted. The memory
             //is then used for something else, and we can use that to capture *most* of the
             //disconnect cases.
             if (connData[i].conn->state==ESPCONN_NONE || connData[i].conn->state>=ESPCONN_CLOSE) {
                 connData[i].conn=NULL;
                 if (connData[i].cgi!=NULL) connData[i].cgi(&connData[i]); //flush cgi data
                 httpdRetireConn(&connData[i]);
             }
         }
     }
 }
httpdDisconnectTimerFunc()
ICACHE_FLASH_ATTR static void httpdDisconnectTimerFunc (void * arg) static
Definition at line 529 of file httpd.c.
References httpdStop(), and ICACHE_FLASH_ATTR.
Referenced by httpdStop().
{
     httpdStop();
 }
httpdEndHeaders()
ICACHE_FLASH_ATTR void httpdEndHeaders (HttpdConnData * conn)
Definition at line 240 of file httpd.c.
References httpdSend(), and ICACHE_FLASH_ATTR.
Referenced by authBasic(), cgiEspFsHook(), cgiEspFsTemplate(), and cgiWiFiScan().
{
     httpdSend(conn, "\r\n", -1);
 }
httpdFindArg()
ICACHE_FLASH_ATTR int httpdFindArg (char * line, char * arg, char * buff, int buffLen)
Definition at line 167 of file httpd.c.
References httpdUrlDecode(), ICACHE_FLASH_ATTR, INFO, NULL, os_strlen, os_strncmp, os_strstr, and strlen.
Referenced by cgiSetup(), and cgiWifiSetMode().
{
     char *p, *e;
     if (line==NULL) return 0;
     p=line;
     while(p!=NULL && *p!='\n' && *p!='\r' && *p!=0) {
         INFO("findArg: %s\n", p);
         if (os_strncmp(p, arg, os_strlen(arg))==0 && p[strlen(arg)]=='=') {
             p+=os_strlen(arg)+1; //move p to start of value
             e=(char*)os_strstr(p, "&");
             if (e==NULL) e=p+os_strlen(p);
             INFO("findArg: val %s len %d\n", p, (e-p));
             return httpdUrlDecode(p, (e-p), buff, buffLen);
         }
         p=(char*)os_strstr(p, "&");
         if (p!=NULL) p+=1;
     }
     INFO("Finding %s in %s: Not found :/\n", arg, line);
     return -1; //not found
 }
httpdFindConnData()
static ICACHE_FLASH_ATTR HttpdConnData* httpdFindConnData (void * arg) static
Definition at line 107 of file httpd.c.
References conn, ICACHE_FLASH_ATTR, INFO, MAX_CONN, and NULL.
Referenced by httpdDisconCb(), httpdReconCb(), httpdRecvCb(), and httpdSentCb().
{
     int i;
     for (i=0; i<MAX_CONN; i++) {
         if (connData[i].conn==(struct espconn *)arg) return &connData[i];
     }
     INFO("FindConnData: Huh? Couldn't find connection for %p\n", arg);
     return NULL; //WtF?
 }
httpdGetHeader()
ICACHE_FLASH_ATTR int httpdGetHeader (HttpdConnData * conn, char * header, char * ret, int retLen)
Definition at line 189 of file httpd.c.
References HttpdPriv::head, HttpdPriv::headPos, ICACHE_FLASH_ATTR, os_strncmp, HttpdConnData::priv, and strlen.
Referenced by authBasic().
{
     char *p=conn->priv->head;
     p=p+strlen(p)+1; //skip GET/POST part
     p=p+strlen(p)+1; //skip HTTP part
     while (p<(conn->priv->head+conn->priv->headPos)) {
         while(*p<=32 && *p!=0) p++; //skip crap at start
 //      INFO("Looking for %s, Header: '%s'\n", header, p);
         //See if this is the header
         if (os_strncmp(p, header, strlen(header))==0 && p[strlen(header)]==':') {
             //Skip 'key:' bit of header line
             p=p+strlen(header)+1;
             //Skip past spaces after the colon
             while(*p==' ') p++;
             //Copy from p to end
             while (*p!=0 && *p!='\r' && *p!='\n' && retLen>1) {
                 *ret++=*p++;
                 retLen--;
             }
             //Zero-terminate string
             *ret=0;
             //All done :)
             return 1;
         }
         p+=strlen(p)+1; //Skip past end of string and \0 terminator
     }
     return 0;
 }
httpdGetMimetype()
ICACHE_FLASH_ATTR const char* httpdGetMimetype (char * url)
Definition at line 93 of file httpd.c.
References ICACHE_FLASH_ATTR, MimeMap::mimetype, NULL, os_strcmp, and strlen.
Referenced by cgiEspFsHook(), and cgiEspFsTemplate().
{
     int i=0;
     //Go find the extension
     char *ext=url+(strlen(url)-1);
     while (ext!=url && *ext!='.') ext--;
     if (*ext=='.') ext++;
     //ToDo: os_strcmp is case sensitive; we may want to do case-intensive matching here...
     while (mimeTypes[i].ext!=NULL && os_strcmp(ext, mimeTypes[i].ext)!=0) i++;
     return mimeTypes[i].mimetype;
 }
httpdHeader()
ICACHE_FLASH_ATTR void httpdHeader (HttpdConnData * conn, const char * field, const char * val)
Definition at line 229 of file httpd.c.
References httpdSend(), ICACHE_FLASH_ATTR, strlen, and tfp_snprintf().
Referenced by authBasic(), cgiEspFsHook(), cgiEspFsTemplate(), and cgiWiFiScan().
{
     char buff[256];
     int l;
     tfp_snprintf(buff, 256, "%s: %s\r\n", field, val);
     l = strlen(buff);
     httpdSend(conn, buff, l);
 }
httpdHexVal()
static int httpdHexVal (char c) static
Definition at line 126 of file httpd.c.
Referenced by httpdUrlDecode().
{
     if (c>='0' && c<='9') return c-'0';
     if (c>='A' && c<='F') return c-'A'+10;
     if (c>='a' && c<='f') return c-'a'+10;
     return 0;
 }
httpdInit()
ICACHE_FLASH_ATTR void httpdInit (HttpdBuiltInUrl * fixedUrls, int port)
Definition at line 509 of file httpd.c.
References HttpdConnData::conn, espconn_accept(), ESPCONN_NONE, espconn_regist_connectcb(), ESPCONN_TCP, httpdConnectCb(), httpdTcp, ICACHE_FLASH_ATTR, INFO, _esp_tcp::local_port, malloc, MAX_CONN, NULL, espconn::proto, espconn::state, espconn::tcp, and espconn::type.
Referenced by httpd_user_init().
{
     int i;
     connPrivData = malloc(sizeof(HttpdPriv) * MAX_CONN);
     for (i=0; i<MAX_CONN; i++) {
         connData[i].conn=NULL;
     }
     httpdConn.type=ESPCONN_TCP;
     httpdConn.state=ESPCONN_NONE;
     httpdTcp.local_port=port;
     httpdConn.proto.tcp=&httpdTcp;
     builtInUrls=fixedUrls;
     INFO("Httpd init, conn=%p\n", &httpdConn);
     espconn_regist_connectcb(&httpdConn, httpdConnectCb);
     espconn_accept(&httpdConn);
 }
httpdParseHeader()
static ICACHE_FLASH_ATTR void httpdParseHeader (char * h, HttpdConnData * conn) static
Definition at line 350 of file httpd.c.
References HttpdConnData::getArgs, ICACHE_FLASH_ATTR, INFO, MAX_POST, NULL, os_malloc, os_strncmp, os_strstr, HttpdConnData::postBuff, HttpdConnData::postLen, HttpdPriv::postPos, HttpdConnData::priv, and HttpdConnData::url.
Referenced by httpdRecvCb().
{
     int i;
 //  INFO("Got header %s\n", h);
     if (os_strncmp(h, "GET ", 4)==0 || os_strncmp(h, "POST ", 5)==0) {
         char *e;
         //Skip past the space after POST/GET
         i=0;
         while (h[i]!=' ') i++;
         conn->url=h+i+1;
         //Figure out end of url.
         e=(char*)os_strstr(conn->url, " ");
         if (e==NULL) return; //wtf?
         *e=0; //terminate url part
         INFO("URL = %s\n", conn->url);
         //Parse out the URL part before the GET parameters.
         conn->getArgs=(char*)os_strstr(conn->url, "?");
         if (conn->getArgs!=0) {
             *conn->getArgs=0;
             conn->getArgs++;
             INFO("GET args = %s\n", conn->getArgs);
         } else {
             conn->getArgs=NULL;
         }
     } else if (os_strncmp(h, "Content-Length: ", 16)==0) {
         i=0;
         //Skip trailing spaces
         while (h[i]!=' ') i++;
         //Get POST data length
         conn->postLen=atoi(h+i+1);
         //Clamp if too big. Hmm, maybe we should error out instead?
         if (conn->postLen>MAX_POST) conn->postLen=MAX_POST;
         INFO("Mallocced buffer for %d bytes of post data.\n", conn->postLen);
         //Alloc the memory.
         conn->postBuff=(char*)os_malloc(conn->postLen+1);
         conn->priv->postPos=0;
     }
 }
httpdReconCb()
static ICACHE_FLASH_ATTR void httpdReconCb (void * arg, sint8 err) static
Definition at line 446 of file httpd.c.
References conn, httpdFindConnData(), ICACHE_FLASH_ATTR, INFO, and NULL.
Referenced by httpdConnectCb().
{
     HttpdConnData *conn=httpdFindConnData(arg);
     INFO("ReconCb\n");
     if (conn==NULL) return;
     //Yeah... No idea what to do here. ToDo: figure something out.
 }
httpdRecvCb()
static ICACHE_FLASH_ATTR void httpdRecvCb (void * arg, char * data, unsigned short len) static
Definition at line 394 of file httpd.c.
References conn, HttpdPriv::head, HttpdPriv::headPos, httpdFindConnData(), httpdParseHeader(), httpdSendResp(), ICACHE_FLASH_ATTR, INFO, MAX_HEAD_LEN, MAX_SENDBUFF_LEN, NULL, os_strstr, HttpdConnData::postBuff, HttpdConnData::postLen, HttpdPriv::postPos, HttpdConnData::priv, HttpdPriv::sendBuff, HttpdPriv::sendBuffLen, HttpdConnData::url, and xmitSendBuff().
Referenced by httpdConnectCb().
{
     int x;
     char *p, *e;
     char sendBuff[MAX_SENDBUFF_LEN];
     HttpdConnData *conn=httpdFindConnData(arg);
     if (conn==NULL) return;
     conn->priv->sendBuff=sendBuff;
     conn->priv->sendBuffLen=0;
     for (x=0; x<len; x++) {
         if (conn->postLen<0) {
             //This byte is a header byte.
             if (conn->priv->headPos!=MAX_HEAD_LEN) conn->priv->head[conn->priv->headPos++]=data[x];
             conn->priv->head[conn->priv->headPos]=0;
             //Scan for /r/n/r/n
             if (data[x]=='\n' && (char *)os_strstr(conn->priv->head, "\r\n\r\n")!=NULL) {
                 //Indicate we're done with the headers.
                 conn->postLen=0;
                 //Reset url data
                 conn->url=NULL;
                 //Find end of next header line
                 p=conn->priv->head;
                 while(p<(&conn->priv->head[conn->priv->headPos-4])) {
                     e=(char *)os_strstr(p, "\r\n");
                     if (e==NULL) break;
                     e[0]=0;
                     httpdParseHeader(p, conn);
                     p=e+2;
                 }
                 //If we don't need to receive post data, we can send the response now.
                 if (conn->postLen==0) {
                     httpdSendResp(conn);
                 }
             }
         } else if (conn->priv->postPos!=-1 && conn->postLen!=0 && conn->priv->postPos <= conn->postLen) {
             //This byte is a POST byte.
             conn->postBuff[conn->priv->postPos++]=data[x];
             if (conn->priv->postPos>=conn->postLen) {
                 //Received post stuff.
                 conn->postBuff[conn->priv->postPos]=0; //zero-terminate
                 conn->priv->postPos=-1;
                 INFO("Post data: %s\n", conn->postBuff);
                 //Send the response.
                 httpdSendResp(conn);
                 break;
             }
         }
     }
     xmitSendBuff(conn);
 }
httpdRedirect()
ICACHE_FLASH_ATTR void httpdRedirect (HttpdConnData * conn, char * newUrl)
Definition at line 246 of file httpd.c.
References httpdSend(), ICACHE_FLASH_ATTR, strlen, and tfp_snprintf().
Referenced by cgiRedirect(), cgiSetup(), and cgiWifiSetMode().
{
     char buff[1024];
     int l;
     tfp_snprintf(buff, 1024, "HTTP/1.1 302 Found\r\nLocation: %s\r\n\r\nMoved to %s\r\n", newUrl, newUrl);
     l = strlen(buff);
     httpdSend(conn, buff, l);
 }
httpdRetireConn()
static ICACHE_FLASH_ATTR void httpdRetireConn (HttpdConnData * conn) static
Definition at line 118 of file httpd.c.
References HttpdConnData::cgi, HttpdConnData::conn, NULL, os_free, and HttpdConnData::postBuff.
Referenced by httpdDisconCb(), httpdSentCb(), and httpdStop().
{
     if (conn->postBuff!=NULL) os_free(conn->postBuff);
     conn->postBuff=NULL;
     conn->cgi=NULL;
     conn->conn=NULL;
 }
httpdSend()
ICACHE_FLASH_ATTR int httpdSend (HttpdConnData * conn, const char * data, int len)
Definition at line 270 of file httpd.c.
References ICACHE_FLASH_ATTR, MAX_SENDBUFF_LEN, os_memcpy, HttpdConnData::priv, HttpdPriv::sendBuff, HttpdPriv::sendBuffLen, and strlen.
Referenced by authBasic(), cgiEspFsTemplate(), cgiWiFiScan(), httpdEndHeaders(), httpdHeader(), httpdRedirect(), httpdSendResp(), httpdStartResponse(), and tplSetup().
{
     if (len<0) len=strlen(data);
     if (conn->priv->sendBuffLen+len>MAX_SENDBUFF_LEN) return 0;
     os_memcpy(conn->priv->sendBuff+conn->priv->sendBuffLen, data, len);
     conn->priv->sendBuffLen+=len;
     return 1;
 }
httpdSendResp()
static ICACHE_FLASH_ATTR void httpdSendResp (HttpdConnData * conn) static
Definition at line 319 of file httpd.c.
References HttpdConnData::cgi, HttpdConnData::cgiArg, HttpdBuiltInUrl::cgiArg, HttpdBuiltInUrl::cgiCb, HttpdConnData::cgiData, HTTPD_CGI_DONE, HTTPD_CGI_NOTFOUND, httpdSend(), httpNotFoundHeader, ICACHE_FLASH_ATTR, INFO, NULL, os_strcmp, os_strlen, os_strncmp, HttpdConnData::url, and url.
Referenced by httpdRecvCb().
{
     int i=0;
     int r;
     //See if the url is somewhere in our internal url table.
     while (builtInUrls[i].url!=NULL && conn->url!=NULL) {
         int match=0;
 //      INFO("%s == %s?\n", builtInUrls[i].url, conn->url);
         if (os_strcmp(builtInUrls[i].url, conn->url)==0) match=1;
         if (builtInUrls[i].url[os_strlen(builtInUrls[i].url)-1]=='*' &&
                 os_strncmp(builtInUrls[i].url, conn->url, os_strlen(builtInUrls[i].url)-1)==0) match=1;
         if (match) {
             INFO("Is url index %d\n", i);
             conn->cgiData=NULL;
             conn->cgi=builtInUrls[i].cgiCb;
             conn->cgiArg=builtInUrls[i].cgiArg;
             r=conn->cgi(conn);
             if (r!=HTTPD_CGI_NOTFOUND) {
                 if (r==HTTPD_CGI_DONE) conn->cgi=NULL;  //If cgi finishes immediately: mark conn for destruction.
                 return;
             }
         }
         i++;
     }
     //Can't find :/
     INFO("%s not found. 404!\n", conn->url);
     httpdSend(conn, httpNotFoundHeader, -1);
     conn->cgi=NULL; //mark for destruction
 }
httpdSentCb()
static ICACHE_FLASH_ATTR void httpdSentCb (void * arg) static
Definition at line 290 of file httpd.c.
References HttpdConnData::cgi, conn, HttpdConnData::conn, espconn_disconnect(), HTTPD_CGI_DONE, httpdFindConnData(), httpdRetireConn(), INFO, MAX_SENDBUFF_LEN, NULL, HttpdConnData::priv, HttpdPriv::sendBuff, HttpdPriv::sendBuffLen, and xmitSendBuff().
Referenced by httpdConnectCb().
{
     int r;
     HttpdConnData *conn=httpdFindConnData(arg);
     char sendBuff[MAX_SENDBUFF_LEN];
 //  INFO("Sent callback on conn %p\n", conn);
     if (conn==NULL) return;
     conn->priv->sendBuff=sendBuff;
     conn->priv->sendBuffLen=0;
     if (conn->cgi==NULL) { //Marked for destruction?
         INFO("Conn %p is done. Closing.\n", conn->conn);
         espconn_disconnect(conn->conn);
         httpdRetireConn(conn);
         return; //No need to call xmitSendBuff.
     }
     r=conn->cgi(conn); //Execute cgi fn.
     if (r==HTTPD_CGI_DONE) {
         conn->cgi=NULL; //mark for destruction.
     }
     xmitSendBuff(conn);
 }
httpdStartResponse()
ICACHE_FLASH_ATTR void httpdStartResponse (HttpdConnData * conn, int code)
Definition at line 219 of file httpd.c.
References httpdSend(), HTTPDVER, ICACHE_FLASH_ATTR, strlen, and tfp_snprintf().
Referenced by authBasic(), cgiEspFsHook(), cgiEspFsTemplate(), and cgiWiFiScan().
{
     char buff[128];
     int l;
     tfp_snprintf(buff, 128, "HTTP/1.0 %d OK\r\nServer: esp8266-httpd/"HTTPDVER"\r\n", code);
     l = strlen(buff);
     httpdSend(conn, buff, l);
 }
httpdStop()
ICACHE_FLASH_ATTR void httpdStop ()
Definition at line 534 of file httpd.c.
References espconn_delete(), espconn_disconnect(), ESPCONN_NONE, free, httpdDisconnectTimer, httpdDisconnectTimerFunc(), httpdRetireConn(), INFO, NULL, os_timer_arm, os_timer_disarm, os_timer_func_t, os_timer_setfn, and espconn::state.
Referenced by httpdDisconnectTimerFunc().
                  {
     INFO("Httpd stopping, state=%d conn=%p\n", httpdConn.state, &httpdConn);
     if (httpdConn.state != ESPCONN_NONE) {
         if (espconn_delete(&httpdConn) == 0) {
             os_timer_disarm(&httpdDisconnectTimer);
             httpdRetireConn(connData);
             free(connPrivData);
             INFO("Httpd stopped\n");
         }
         else {
             espconn_disconnect(&httpdConn);
             os_timer_disarm(&httpdDisconnectTimer);
             os_timer_setfn(&httpdDisconnectTimer, (os_timer_func_t *)httpdDisconnectTimerFunc, NULL);
             os_timer_arm(&httpdDisconnectTimer, 1000, 0);
             INFO("Httpd still running rescheduling httpdStop\n");
         }
     }
 }
httpdUrlDecode()
int httpdUrlDecode (char * val, int valLen, char * ret, int retLen)
Definition at line 137 of file httpd.c.
References httpdHexVal(), and ICACHE_FLASH_ATTR.
Referenced by httpdFindArg().
{
     int s=0, d=0;
     int esced=0, escVal=0;
     while (s<valLen && d<retLen) {
         if (esced==1)  {
             escVal=httpdHexVal(val[s])<<4;
             esced=2;
         } else if (esced==2) {
             escVal+=httpdHexVal(val[s]);
             ret[d++]=escVal;
             esced=0;
         } else if (val[s]=='%') {
             esced=1;
         } else if (val[s]=='+') {
             ret[d++]=' ';
         } else {
             ret[d++]=val[s];
         }
         s++;
     }
     if (d<retLen) ret[d]=0;
     return d;
 }
xmitSendBuff()
static ICACHE_FLASH_ATTR void xmitSendBuff (HttpdConnData * conn) static
Definition at line 280 of file httpd.c.
References HttpdConnData::conn, espconn_sent(), ICACHE_FLASH_ATTR, HttpdConnData::priv, HttpdPriv::sendBuff, and HttpdPriv::sendBuffLen.
Referenced by httpdRecvCb(), and httpdSentCb().
{
     if (conn->priv->sendBuffLen!=0) {
         espconn_sent(conn->conn, (uint8_t*)conn->priv->sendBuff, conn->priv->sendBuffLen);
         conn->priv->sendBuffLen=0;
     }
 }
Variable Documentation
builtInUrls
HttpdBuiltInUrl* builtInUrls static
Definition at line 49 of file httpd.c.
connData
HttpdConnData connData[MAX_CONN] static
Definition at line 63 of file httpd.c.
connPrivData
HttpdPriv* connPrivData static
Definition at line 62 of file httpd.c.
httpdConn
struct espconn httpdConn = (struct espconn){ 0 } static
Definition at line 66 of file httpd.c.
httpdDisconnectTimer
os_timer_t httpdDisconnectTimer static
Definition at line 89 of file httpd.c.
Referenced by httpdStop().
httpdTcp
esp_tcp httpdTcp static
Definition at line 67 of file httpd.c.
Referenced by httpdInit().
httpNotFoundHeader
const char* httpNotFoundHeader ="HTTP/1.0 404 Not Found\r\nServer: esp8266-httpd/0.1\r\nContent-Type: text/plain\r\n\r\nNot Found.\r\n" static
Definition at line 314 of file httpd.c.
Referenced by httpdSendResp().
mimeTypes
const MimeMap mimeTypes[] static
Initial value:
={
    {"htm", "text/htm"},
    {"html", "text/html"},
    {"css", "text/css"},
    {"js", "text/javascript"},
    {"txt", "text/plain"},
    {"jpg", "image/jpeg"},
    {"jpeg", "image/jpeg"},
    {"png", "image/png"},
    {NULL, "text/html"},
}
Definition at line 77 of file httpd.c.