MeterLogger: user/httpdespfs.c File Reference
httpdespfs.c File Reference
#include <esp8266.h>
#include "httpd.h"
#include "espfs.h"
#include "httpdespfs.h"
Data Structures
struct TplData
Typedefs
typedef void(* TplCallback) (HttpdConnData *connData, char *token, void **arg)
Functions
int ICACHE_FLASH_ATTR cgiEspFsHook (HttpdConnData *connData)
int ICACHE_FLASH_ATTR cgiEspFsTemplate (HttpdConnData *connData)
Typedef Documentation
typedef void(* TplCallback) (HttpdConnData *connData, char *token, void **arg)
Definition at line 71 of file httpdespfs.c.
Function Documentation
int ICACHE_FLASH_ATTR cgiEspFsHook (HttpdConnData * connData)
Definition at line 24 of file httpdespfs.c.
References HttpdConnData::cgiData, HttpdConnData::conn, espFsClose(), espFsOpen(), espFsRead(), HTTPD_CGI_DONE, HTTPD_CGI_MORE, HTTPD_CGI_NOTFOUND, httpdEndHeaders(), httpdGetMimetype(), httpdHeader(), httpdStartResponse(), and HttpdConnData::url.
int ICACHE_FLASH_ATTR cgiEspFsTemplate (HttpdConnData * connData)
Definition at line 73 of file httpdespfs.c.
References HttpdConnData::cgiArg, HttpdConnData::cgiData, HttpdConnData::conn, espFsClose(), espFsOpen(), espFsRead(), TplData::file, HTTPD_CGI_DONE, HTTPD_CGI_MORE, HTTPD_CGI_NOTFOUND, httpdEndHeaders(), httpdGetMimetype(), httpdHeader(), httpdSend(), httpdStartResponse(), os_free, os_malloc, TplData::token, TplData::tokenPos, TplData::tplArg, and HttpdConnData::url.