MeterLogger: esp-open-lwip/lwip/core/init.c File Reference
init.c File Reference
#include "lwip/opt.h"
#include "lwip/init.h"
#include "lwip/stats.h"
#include "lwip/sys.h"
#include "lwip/mem.h"
#include "lwip/memp.h"
#include "lwip/pbuf.h"
#include "lwip/netif.h"
#include "lwip/sockets.h"
#include "lwip/ip.h"
#include "lwip/raw.h"
#include "lwip/udp.h"
#include "lwip/tcp_impl.h"
#include "lwip/snmp_msg.h"
#include "lwip/autoip.h"
#include "lwip/igmp.h"
#include "lwip/dns.h"
#include "lwip/timers.h"
#include "netif/etharp.h"
#include "lwip/lwip_napt.h"
Macros
#define lwip_sanity_check()
Functions
void lwip_init (void)
Detailed Description
Modules initialization
Definition in file init.c.
Macro Definition Documentation
lwip_sanity_check
#define lwip_sanity_check ()
Definition at line 254 of file init.c.
Referenced by lwip_init().
Function Documentation
lwip_init()
void lwip_init (void)
Perform Sanity check of user-configurable values, and initialize all modules.
Definition at line 261 of file init.c.
References ip_init, lwip_sanity_check, mem_init(), memp_init(), MEMP_NUM_TCP_PCB, netif_init(), pbuf_init, stats_init, sys_init(), sys_timeouts_init(), TCP_MAXRTX, TCP_MSS, TCP_SYNMAXRTX, and TCP_WND.
Referenced by tcpip_init().
 {
   MEMP_NUM_TCP_PCB = 5;
   TCP_WND = (4 * TCP_MSS);
   TCP_MAXRTX = 12;
   TCP_SYNMAXRTX = 6;
   /* Sanity check user-configurable values */
   lwip_sanity_check();
   /* Modules initialization */
   stats_init();
 #if !NO_SYS
   sys_init();
 #endif /* !NO_SYS */
 #if 0
   mem_init(&_bss_end);
 #endif
   memp_init();
   pbuf_init();
   netif_init();
 #if LWIP_SOCKET
   lwip_socket_init();
 #endif /* LWIP_SOCKET */
   ip_init();
 #if LWIP_ARP
   etharp_init();
 #endif /* LWIP_ARP */
 #if LWIP_RAW
   raw_init();
 #endif /* LWIP_RAW */
 #if LWIP_UDP
   udp_init();
 #endif /* LWIP_UDP */
 #if LWIP_TCP
   tcp_init();
 #endif /* LWIP_TCP */
 #if LWIP_SNMP
   snmp_init();
 #endif /* LWIP_SNMP */
 #if LWIP_AUTOIP
   autoip_init();
 #endif /* LWIP_AUTOIP */
 #if LWIP_IGMP
   igmp_init();
 #endif /* LWIP_IGMP */
 #if LWIP_DNS
   dns_init();
 #endif /* LWIP_DNS */
 #if LWIP_TIMERS
   sys_timeouts_init();
 #endif /* LWIP_TIMERS */
 #if IP_NAPT && !IP_NAPT_DYNAMIC
   ip_napt_init(IP_NAPT_MAX, IP_PORTMAP_MAX);
 #endif /* IP_NAPT */
 }