MeterLogger: esp-open-lwip/include/lwip/init.h File Reference
init.h File Reference
#include "lwip/opt.h"
Macros
#define LWIP_VERSION_MAJOR 1U
#define LWIP_VERSION_MINOR 4U
#define LWIP_VERSION_REVISION 0U
#define LWIP_VERSION_RC 2U
#define LWIP_RC_RELEASE 255U
#define LWIP_RC_DEVELOPMENT 0U
#define LWIP_VERSION_IS_RELEASE (LWIP_VERSION_RC == LWIP_RC_RELEASE)
#define LWIP_VERSION_IS_DEVELOPMENT (LWIP_VERSION_RC == LWIP_RC_DEVELOPMENT)
#define LWIP_VERSION_IS_RC ((LWIP_VERSION_RC != LWIP_RC_RELEASE) && (LWIP_VERSION_RC != LWIP_RC_DEVELOPMENT))
#define LWIP_VERSION
Functions
void lwip_init (void) ICACHE_FLASH_ATTR
Macro Definition Documentation
LWIP_RC_DEVELOPMENT
#define LWIP_RC_DEVELOPMENT 0U
LWIP_VERSION_RC is set to LWIP_RC_DEVELOPMENT for CVS versions
Definition at line 55 of file init.h.
LWIP_RC_RELEASE
#define LWIP_RC_RELEASE 255U
LWIP_VERSION_RC is set to LWIP_RC_RELEASE for official releases
Definition at line 53 of file init.h.
LWIP_VERSION
#define LWIP_VERSION
Value:
(LWIP_VERSION_MAJOR << 24   | LWIP_VERSION_MINOR << 16 | \
                        LWIP_VERSION_REVISION << 8 | LWIP_VERSION_RC)
Provides the version of the stack
Definition at line 62 of file init.h.
LWIP_VERSION_IS_DEVELOPMENT
#define LWIP_VERSION_IS_DEVELOPMENT (LWIP_VERSION_RC == LWIP_RC_DEVELOPMENT)
Definition at line 58 of file init.h.
LWIP_VERSION_IS_RC
#define LWIP_VERSION_IS_RC ((LWIP_VERSION_RC != LWIP_RC_RELEASE) && (LWIP_VERSION_RC != LWIP_RC_DEVELOPMENT))
Definition at line 59 of file init.h.
LWIP_VERSION_IS_RELEASE
#define LWIP_VERSION_IS_RELEASE (LWIP_VERSION_RC == LWIP_RC_RELEASE)
Definition at line 57 of file init.h.
LWIP_VERSION_MAJOR
#define LWIP_VERSION_MAJOR 1U
X.x.x: Major version of the stack
Definition at line 42 of file init.h.
LWIP_VERSION_MINOR
#define LWIP_VERSION_MINOR 4U
x.X.x: Minor version of the stack
Definition at line 44 of file init.h.
LWIP_VERSION_RC
#define LWIP_VERSION_RC 2U
For release candidates, this is set to 1..254 For official releases, this is set to 255 (LWIP_RC_RELEASE) For development versions (CVS), this is set to 0 (LWIP_RC_DEVELOPMENT)
Definition at line 50 of file init.h.
LWIP_VERSION_REVISION
#define LWIP_VERSION_REVISION 0U
x.x.X: Revision of the stack
Definition at line 46 of file init.h.
Function Documentation
lwip_init()
void lwip_init (void)
Perform Sanity check of user-configurable values, and initialize all modules.
Definition at line 261 of file init.c.
References ip_init, lwip_sanity_check, mem_init(), memp_init(), MEMP_NUM_TCP_PCB, netif_init(), pbuf_init, stats_init, sys_init(), sys_timeouts_init(), TCP_MAXRTX, TCP_MSS, TCP_SYNMAXRTX, and TCP_WND.
Referenced by tcpip_init().
 {
   MEMP_NUM_TCP_PCB = 5;
   TCP_WND = (4 * TCP_MSS);
   TCP_MAXRTX = 12;
   TCP_SYNMAXRTX = 6;
   /* Sanity check user-configurable values */
   lwip_sanity_check();
   /* Modules initialization */
   stats_init();
 #if !NO_SYS
   sys_init();
 #endif /* !NO_SYS */
 #if 0
   mem_init(&_bss_end);
 #endif
   memp_init();
   pbuf_init();
   netif_init();
 #if LWIP_SOCKET
   lwip_socket_init();
 #endif /* LWIP_SOCKET */
   ip_init();
 #if LWIP_ARP
   etharp_init();
 #endif /* LWIP_ARP */
 #if LWIP_RAW
   raw_init();
 #endif /* LWIP_RAW */
 #if LWIP_UDP
   udp_init();
 #endif /* LWIP_UDP */
 #if LWIP_TCP
   tcp_init();
 #endif /* LWIP_TCP */
 #if LWIP_SNMP
   snmp_init();
 #endif /* LWIP_SNMP */
 #if LWIP_AUTOIP
   autoip_init();
 #endif /* LWIP_AUTOIP */
 #if LWIP_IGMP
   igmp_init();
 #endif /* LWIP_IGMP */
 #if LWIP_DNS
   dns_init();
 #endif /* LWIP_DNS */
 #if LWIP_TIMERS
   sys_timeouts_init();
 #endif /* LWIP_TIMERS */
 #if IP_NAPT && !IP_NAPT_DYNAMIC
   ip_napt_init(IP_NAPT_MAX, IP_PORTMAP_MAX);
 #endif /* IP_NAPT */
 }