MeterLogger: user/kamstrup/kmp_request.h File Reference
kmp_request.h File Reference
#include "mqtt.h"
Macros
#define kmp_received_task_prio USER_TASK_PRIO_2
#define kmp_received_task_queue_length 64
Functions
ICACHE_FLASH_ATTR void kmp_request_init ()
ICACHE_FLASH_ATTR void kmp_set_mqtt_client (MQTT_Client *client)
ICACHE_FLASH_ATTR unsigned int kmp_get_received_serial ()
ICACHE_FLASH_ATTR unsigned int kmp_get_received_energy_kwh ()
ICACHE_FLASH_ATTR void kmp_request_send ()
unsigned int kmp_fifo_in_use ()
unsigned char kmp_fifo_put (unsigned char c)
unsigned char kmp_fifo_get (unsigned char *c)
unsigned char kmp_fifo_snoop (unsigned char *c, unsigned int pos)
Variables
os_event_t kmp_received_task_queue [kmp_received_task_queue_length]
Macro Definition Documentation
kmp_received_task_prio
#define kmp_received_task_prio USER_TASK_PRIO_2
Definition at line 3 of file kmp_request.h.
Referenced by kmp_request_init(), and uart0_rx_intr_handler().
kmp_received_task_queue_length
#define kmp_received_task_queue_length 64
Definition at line 4 of file kmp_request.h.
Referenced by kmp_request_init().
Function Documentation
kmp_fifo_get()
unsigned char kmp_fifo_get (unsigned char * c)
Definition at line 356 of file kmp_request.c.
References fifo_buffer, fifo_tail, kmp_fifo_in_use(), and QUEUE_SIZE.
Referenced by kmp_received_task().
{
     if (kmp_fifo_in_use() != 0) {
         *c = fifo_buffer[fifo_tail++ % QUEUE_SIZE];
         // wrap
         if (fifo_tail == QUEUE_SIZE) {
             fifo_tail = 0;
         }
         return 1;
     }
     else {
         return 0;
     }
 }
kmp_fifo_in_use()
unsigned int kmp_fifo_in_use ()
Definition at line 338 of file kmp_request.c.
References fifo_head, and fifo_tail.
Referenced by kmp_fifo_get(), kmp_fifo_put(), and kmp_fifo_snoop().
{
     return fifo_head - fifo_tail;
 }
kmp_fifo_put()
unsigned char kmp_fifo_put (unsigned char c)
Definition at line 342 of file kmp_request.c.
References fifo_buffer, fifo_head, kmp_fifo_in_use(), and QUEUE_SIZE.
Referenced by uart0_rx_intr_handler().
{
     if (kmp_fifo_in_use() != QUEUE_SIZE) {
         fifo_buffer[fifo_head++ % QUEUE_SIZE] = c;
         // wrap
         if (fifo_head == QUEUE_SIZE) {
             fifo_head = 0;
         }
         return 1;
     }
     else {
         return 0;
     }
 }
kmp_fifo_snoop()
unsigned char kmp_fifo_snoop (unsigned char * c, unsigned int pos)
Definition at line 370 of file kmp_request.c.
References fifo_buffer, fifo_tail, kmp_fifo_in_use(), and QUEUE_SIZE.
{
     if (kmp_fifo_in_use() > (pos)) {
         *c = fifo_buffer[(fifo_tail + pos) % QUEUE_SIZE];
         return 1;
     }
     else {
         return 0;
     }
 }
kmp_get_received_energy_kwh()
ICACHE_FLASH_ATTR unsigned int kmp_get_received_energy_kwh ()
Definition at line 192 of file kmp_request.c.
References atoi(), ICACHE_FLASH_ATTR, kmp_response_t::kmp_response_register_list, kmp_unit_to_string(), kmp_value_to_string(), mw_to_w_str(), and strncmp.
{
     unsigned char kmp_unit_string[16];
     unsigned char kmp_value_string[64];
     char e1_kwh[64];
     kmp_value_to_string(response.kmp_response_register_list[0].value, response.kmp_response_register_list[0].si_ex, kmp_value_string);
     kmp_unit_to_string(response.kmp_response_register_list[0].unit, kmp_unit_string);
     if (strncmp(kmp_unit_string, "MWh", 16) == 0) {
         mw_to_w_str(kmp_unit_string, e1_kwh);
     }
 #ifdef DEBUG_NO_METER
     return pseudo_data_debug_no_meter;
 #else
     return atoi(e1_kwh);
 #endif
 }
kmp_get_received_serial()
ICACHE_FLASH_ATTR unsigned int kmp_get_received_serial ()
Definition at line 186 of file kmp_request.c.
References ICACHE_FLASH_ATTR, and kmp_serial.
{
     return kmp_serial;
 }
kmp_request_init()
ICACHE_FLASH_ATTR void kmp_request_init ()
Definition at line 169 of file kmp_request.c.
References fifo_head, fifo_tail, ICACHE_FLASH_ATTR, kmp_received_task(), kmp_received_task_prio, kmp_received_task_queue, kmp_received_task_queue_length, kmp_requests_sent, and system_os_task().
{
     fifo_head = 0;
     fifo_tail = 0;
     kmp_requests_sent = 0;
     system_os_task(kmp_received_task, kmp_received_task_prio, kmp_received_task_queue, kmp_received_task_queue_length);
 }
kmp_request_send()
ICACHE_FLASH_ATTR void kmp_request_send ()
Definition at line 247 of file kmp_request.c.
References atoi(), DEFAULT_METER_SERIAL, encrypt_aes_hmac_combined(), get_unix_time(), KMP_FRAME_L, kmp_get_register_timer, kmp_get_register_timer_func(), kmp_get_serial_timer, kmp_get_serial_timer_func(), kmp_receive_timeout_timer, kmp_receive_timeout_timer_func(), kmp_requests_sent, kmp_serial, memset, MQTT_MESSAGE_L, MQTT_Publish(), MQTT_TOPIC_L, NULL, os_timer_arm, os_timer_disarm, os_timer_func_t, os_timer_setfn, strlen, system_get_free_heap_size(), and tfp_snprintf().
Referenced by kmp_receive_timeout_timer_func().
{
 #ifdef DEBUG_NO_METER
     char cleartext[MQTT_MESSAGE_L];
     char topic[MQTT_TOPIC_L];
     char message[KMP_FRAME_L];
     int message_l;
     uint8_t sine_wave[256] = {
         0x80, 0x83, 0x86, 0x89, 0x8C, 0x90, 0x93, 0x96,
         0x99, 0x9C, 0x9F, 0xA2, 0xA5, 0xA8, 0xAB, 0xAE,
         0xB1, 0xB3, 0xB6, 0xB9, 0xBC, 0xBF, 0xC1, 0xC4,
         0xC7, 0xC9, 0xCC, 0xCE, 0xD1, 0xD3, 0xD5, 0xD8,
         0xDA, 0xDC, 0xDE, 0xE0, 0xE2, 0xE4, 0xE6, 0xE8,
         0xEA, 0xEB, 0xED, 0xEF, 0xF0, 0xF1, 0xF3, 0xF4,
         0xF5, 0xF6, 0xF8, 0xF9, 0xFA, 0xFA, 0xFB, 0xFC,
         0xFD, 0xFD, 0xFE, 0xFE, 0xFE, 0xFF, 0xFF, 0xFF,
         0xFF, 0xFF, 0xFF, 0xFF, 0xFE, 0xFE, 0xFE, 0xFD,
         0xFD, 0xFC, 0xFB, 0xFA, 0xFA, 0xF9, 0xF8, 0xF6,
         0xF5, 0xF4, 0xF3, 0xF1, 0xF0, 0xEF, 0xED, 0xEB,
         0xEA, 0xE8, 0xE6, 0xE4, 0xE2, 0xE0, 0xDE, 0xDC,
         0xDA, 0xD8, 0xD5, 0xD3, 0xD1, 0xCE, 0xCC, 0xC9,
         0xC7, 0xC4, 0xC1, 0xBF, 0xBC, 0xB9, 0xB6, 0xB3,
         0xB1, 0xAE, 0xAB, 0xA8, 0xA5, 0xA2, 0x9F, 0x9C,
         0x99, 0x96, 0x93, 0x90, 0x8C, 0x89, 0x86, 0x83,
         0x80, 0x7D, 0x7A, 0x77, 0x74, 0x70, 0x6D, 0x6A,
         0x67, 0x64, 0x61, 0x5E, 0x5B, 0x58, 0x55, 0x52,
         0x4F, 0x4D, 0x4A, 0x47, 0x44, 0x41, 0x3F, 0x3C,
         0x39, 0x37, 0x34, 0x32, 0x2F, 0x2D, 0x2B, 0x28,
         0x26, 0x24, 0x22, 0x20, 0x1E, 0x1C, 0x1A, 0x18,
         0x16, 0x15, 0x13, 0x11, 0x10, 0x0F, 0x0D, 0x0C,
         0x0B, 0x0A, 0x08, 0x07, 0x06, 0x06, 0x05, 0x04,
         0x03, 0x03, 0x02, 0x02, 0x02, 0x01, 0x01, 0x01,
         0x01, 0x01, 0x01, 0x01, 0x02, 0x02, 0x02, 0x03,
         0x03, 0x04, 0x05, 0x06, 0x06, 0x07, 0x08, 0x0A,
         0x0B, 0x0C, 0x0D, 0x0F, 0x10, 0x11, 0x13, 0x15,
         0x16, 0x18, 0x1A, 0x1C, 0x1E, 0x20, 0x22, 0x24,
         0x26, 0x28, 0x2B, 0x2D, 0x2F, 0x32, 0x34, 0x37,
         0x39, 0x3C, 0x3F, 0x41, 0x44, 0x47, 0x4A, 0x4D,
         0x4F, 0x52, 0x55, 0x58, 0x5B, 0x5E, 0x61, 0x64,
         0x67, 0x6A, 0x6D, 0x70, 0x74, 0x77, 0x7A, 0x7D
     };
 #endif
     os_timer_disarm(&kmp_get_serial_timer);
     os_timer_setfn(&kmp_get_serial_timer, (os_timer_func_t *)kmp_get_serial_timer_func, NULL);
     os_timer_arm(&kmp_get_serial_timer, 0, 0);      // now
     os_timer_disarm(&kmp_get_register_timer);
     os_timer_setfn(&kmp_get_register_timer, (os_timer_func_t *)kmp_get_register_timer_func, NULL);
     os_timer_arm(&kmp_get_register_timer, 400, 0);      // after 0.4 seconds
     // start retransmission timeout timer
     os_timer_disarm(&kmp_receive_timeout_timer);
     os_timer_setfn(&kmp_receive_timeout_timer, (os_timer_func_t *)kmp_receive_timeout_timer_func, NULL);
     os_timer_arm(&kmp_receive_timeout_timer, 2000, 0);      // after 2 seconds
     kmp_requests_sent++;
 #ifdef DEBUG_NO_METER
     // clear data
     memset(message, 0, sizeof(message));
     memset(topic, 0, sizeof(topic));
     // fake serial for testing without meter
     kmp_serial = atoi(DEFAULT_METER_SERIAL);
     tfp_snprintf(topic, MQTT_TOPIC_L, "/sample/v2/%u/%u", kmp_serial, get_unix_time());
     memset(cleartext, 0, sizeof(cleartext));
     tfp_snprintf(cleartext, KMP_FRAME_L, "heap=%u&t1=%u.00 C&t2=%u.00 C&tdif=%u.00 K&flow1=%u l/h&effect1=%u.0 kW&hr=%u h&v1=%u.00 m3&e1=%u kWh&",
         system_get_free_heap_size(),
         65 + ((sine_wave[pseudo_data_debug_no_meter] * 10) >> 8),       // t1
         45 + ((sine_wave[(pseudo_data_debug_no_meter + 128) & 0xff] * 10) >> 8),    // t2
         10,                                                             // tdif
         100 + ((sine_wave[((pseudo_data_debug_no_meter + 64) * 7) & 0xff] * 50) >> 8),  // flow
         15 + ((sine_wave[pseudo_data_debug_no_meter] * 10) >> 8),       // effect1
         pseudo_data_debug_no_meter / 60,                                // hr
         pseudo_data_debug_no_meter,                                     // v1
         pseudo_data_debug_no_meter                                      // e1
     );
     pseudo_data_debug_no_meter++;   // let it wrap around
     // encrypt and send
     message_l = encrypt_aes_hmac_combined(message, topic, strlen(topic), cleartext, strlen(cleartext) + 1);
     if (mqtt_client) {
         // if mqtt_client is initialized
         MQTT_Publish(mqtt_client, topic, message, message_l, 2, 0); // QoS level 2
     }
 #endif
     kmp_requests_sent = 0;  // reset retry counter
 }
kmp_set_mqtt_client()
ICACHE_FLASH_ATTR void kmp_set_mqtt_client (MQTT_Client * client)
Definition at line 180 of file kmp_request.c.
References ICACHE_FLASH_ATTR.
{
     mqtt_client = client;
 }
Variable Documentation
kmp_received_task_queue
os_event_t kmp_received_task_queue[kmp_received_task_queue_length]
Definition at line 6 of file kmp_request.h.
Referenced by kmp_request_init().