MeterLogger: user/kamstrup/kmp.c File Reference
kmp.c File Reference
#include <esp8266.h>
#include <utils.h>
#include "tinyprintf.h"
#include "kmp.h"
Macros
#define KMP_START_BYTE_IDX 0
#define KMP_DST_IDX 1
#define KMP_CID_IDX 2
#define KMP_DATA_IDX 3
Functions
ICACHE_FLASH_ATTR unsigned int kmp_get_type (unsigned char *frame)
ICACHE_FLASH_ATTR unsigned int kmp_get_serial (unsigned char *frame)
ICACHE_FLASH_ATTR unsigned int kmp_set_clock (unsigned char *frame, uint64_t unix_time)
ICACHE_FLASH_ATTR unsigned int kmp_get_register (unsigned char *frame, uint16_t *register_list, uint16_t register_list_length)
ICACHE_FLASH_ATTR int kmp_decode_frame (unsigned char *frame, unsigned char frame_length, kmp_response_t *response)
ICACHE_FLASH_ATTR uint16_t kmp_crc16 ()
ICACHE_FLASH_ATTR double kmp_value_to_double (int32_t value, uint8_t si_ex)
ICACHE_FLASH_ATTR void kmp_value_to_string (int32_t value, uint8_t si_ex, unsigned char *value_string)
ICACHE_FLASH_ATTR void kmp_unit_to_string (uint8_t unit, unsigned char *unit_string)
ICACHE_FLASH_ATTR void kmp_byte_stuff ()
ICACHE_FLASH_ATTR void kmp_byte_unstuff ()
Variables
unsigned char * kmp_frame
unsigned int kmp_frame_length
unsigned int kmp_data_length
kmp_response_t * kmp_response
Macro Definition Documentation
KMP_CID_IDX
#define KMP_CID_IDX 2
Definition at line 91 of file kmp.c.
Referenced by kmp_decode_frame(), kmp_get_register(), kmp_get_serial(), and kmp_get_type().
KMP_DATA_IDX
#define KMP_DATA_IDX 3
Definition at line 92 of file kmp.c.
Referenced by kmp_decode_frame(), and kmp_get_register().
KMP_DST_IDX
#define KMP_DST_IDX 1
Definition at line 90 of file kmp.c.
Referenced by kmp_byte_stuff(), kmp_byte_unstuff(), kmp_crc16(), kmp_get_register(), kmp_get_serial(), and kmp_get_type().
KMP_START_BYTE_IDX
#define KMP_START_BYTE_IDX 0
Definition at line 89 of file kmp.c.
Referenced by kmp_get_register(), kmp_get_serial(), and kmp_get_type().
Function Documentation
kmp_byte_stuff()
ICACHE_FLASH_ATTR void kmp_byte_stuff ()
Definition at line 580 of file kmp.c.
References ICACHE_FLASH_ATTR, kmp_data_length, KMP_DST_IDX, kmp_frame, KMP_FRAME_L, kmp_frame_length, memcpy, and memset.
Referenced by kmp_get_register(), kmp_get_serial(), and kmp_get_type().
                       {
     unsigned char stuffed_data[KMP_FRAME_L];
     unsigned int i;
     unsigned int j = 0;
     memset(stuffed_data, 0x00, KMP_FRAME_L);
     for (i = KMP_DST_IDX; i < (kmp_frame_length); i++) {
         if ((kmp_frame[i] == 0x80) || (kmp_frame[i] == 0x40) || (kmp_frame[i] == 0x0d) || (kmp_frame[i] == 0x06) || (kmp_frame[i] == 0x1b)) {
             stuffed_data[j++] = 0x1b;
             stuffed_data[j++] = kmp_frame[i] ^ 0xff;
         }
         else {
             stuffed_data[j++] = kmp_frame[i];
         }
     }
     memcpy(kmp_frame + KMP_DST_IDX, stuffed_data, j);
     kmp_frame_length = j + KMP_DST_IDX;
     kmp_data_length = j;
 }
kmp_byte_unstuff()
ICACHE_FLASH_ATTR void kmp_byte_unstuff ()
Definition at line 602 of file kmp.c.
References kmp_data_length, KMP_DST_IDX, kmp_frame, KMP_FRAME_L, kmp_frame_length, and memcpy.
Referenced by kmp_decode_frame().
{
     unsigned char unstuffed_data[KMP_FRAME_L];
     unsigned int i;
     unsigned int j = 0;
     for (i = KMP_DST_IDX; i < kmp_frame_length; i++) {
         if (kmp_frame[i] == 0x1b) {       // byte unstuffing special char
             unstuffed_data[j++] = kmp_frame[i + 1] ^ 0xff;
             i++;
          }
         else {
             unstuffed_data[j++] = kmp_frame[i];
         }
     }
     memcpy(kmp_frame + KMP_DST_IDX, unstuffed_data, j);
     kmp_frame_length = j + KMP_DST_IDX;
     kmp_data_length = j;
 }
kmp_crc16()
ICACHE_FLASH_ATTR uint16_t kmp_crc16 ()
Definition at line 352 of file kmp.c.
References ccit_crc16(), ICACHE_FLASH_ATTR, kmp_data_length, KMP_DST_IDX, and kmp_frame.
Referenced by kmp_decode_frame(), kmp_get_register(), kmp_get_serial(), and kmp_get_type().
                      {
     //uint16_t crc16;
     //int i;
     //crc16 = 0;
     //for (i = KMP_DST_IDX; i < (kmp_data_length + KMP_DST_IDX); i++) {
     //    crc16 = (crc16 << 8) ^ kmp_crc16_table[((crc16 >> 8) ^ kmp_frame[i]) & 0x00FF];
     //}
     //return crc16;
     return ccit_crc16(0x0000, kmp_frame + KMP_DST_IDX, kmp_data_length);
 }
kmp_decode_frame()
ICACHE_FLASH_ATTR int kmp_decode_frame (unsigned char * frame, unsigned char frame_length, kmp_response_t * response)
Definition at line 239 of file kmp.c.
References frame, frame_length, ICACHE_FLASH_ATTR, kmp_byte_unstuff(), KMP_CID_IDX, kmp_crc16(), KMP_DATA_IDX, kmp_data_length, kmp_frame, kmp_frame_length, kmp_response_t::kmp_response_meter_type, kmp_response_t::kmp_response_register_list, kmp_response_t::kmp_response_serial, kmp_response_t::kmp_response_sw_revision, memset, and response.
Referenced by kmp_received_task().
{
     uint16_t kmp_frame_crc16;
     uint16_t crc16;
     unsigned int i;
     unsigned int kmp_register_idx;
     kmp_frame = frame;
     kmp_frame_length = frame_length;
     kmp_response = response;
     memset(kmp_response, 0x00, sizeof(kmp_response_t));
     if (kmp_frame_length == 0) {
         return 0;
     }
     if (kmp_frame_length == 1) {
         // no data returned from Kamstrup meter
         if (kmp_frame[kmp_frame_length - 1] == 0x06) {
             return 0;
         }
         else {
             // Kamstrup: device said: no valid reply from kamstrup meter
             return 0;
         }
     }
     if (kmp_frame_length < 6) {
         // valid packets are at least 1) start byte, 2) dst, 3) cid, 4) crc high, 5) crc low and 6) stop byte
         return 0;
     }
     if (kmp_frame[kmp_frame_length - 1] == 0x0d) {
         // end of data - get params from frame
         // no need to set start and stop bytes
         // unstuff data
         kmp_byte_unstuff();
         // calculate crc
         kmp_data_length = kmp_frame_length - 4; // not included 1) start_byte, 2) crc high, 3) crc low and 4) stop byte
         crc16 = kmp_crc16();
         // get crc from frame
         kmp_frame_crc16 = (kmp_frame[kmp_frame_length - 2] | kmp_frame[kmp_frame_length - 3] << 8);
         if (kmp_frame_crc16 == crc16) {
             //crc ok
         }
         else {
             //crc error
             return -1;
         }
         // decode application layer
         if (kmp_frame[KMP_CID_IDX] == 0x01) {
             // kmp_get_type
             kmp_response->kmp_response_meter_type = (kmp_frame[KMP_DATA_IDX + 0] << 8) + kmp_frame[KMP_DATA_IDX + 1];
             kmp_response->kmp_response_sw_revision = (kmp_frame[KMP_DATA_IDX + 2] << 8) + kmp_frame[KMP_DATA_IDX + 3];
             return 1;
         }
         else if (kmp_frame[KMP_CID_IDX] == 0x02) {
             // kmp_get_serial
             kmp_response->kmp_response_serial = (kmp_frame[KMP_DATA_IDX + 0] << 24) + (kmp_frame[KMP_DATA_IDX + 1] << 16) + (kmp_frame[KMP_DATA_IDX + 2] << 8) + kmp_frame[KMP_DATA_IDX + 3];
             return 1;
         }
         else if (kmp_frame[KMP_CID_IDX] == 0x10) {
             // kmp_get_register
             if (kmp_data_length > 2) {
                 for (i = 0; i < ((kmp_data_length - 2) / 9); i++) {  // 9 bytes per register. BUG here if length != 4?
                     kmp_register_idx = 9 * i + KMP_DATA_IDX;
                     // rid
                     kmp_response->kmp_response_register_list[i].rid = (kmp_frame[kmp_register_idx + 0] << 8) + kmp_frame[kmp_register_idx + 1];
                     // unit
                     kmp_response->kmp_response_register_list[i].unit = kmp_frame[kmp_register_idx + 2];
                     // length
                     kmp_response->kmp_response_register_list[i].length = kmp_frame[kmp_register_idx + 3];
                     // si_ex
                     kmp_response->kmp_response_register_list[i].si_ex = kmp_frame[kmp_register_idx + 4];
                     // value
                     kmp_response->kmp_response_register_list[i].value = (kmp_frame[kmp_register_idx + 5] << 24) + (kmp_frame[kmp_register_idx + 6] << 16) + (kmp_frame[kmp_register_idx + 7] << 8) + kmp_frame[kmp_register_idx + 8];
                 }
                 return 1;
             }
             else {
                 // No registers in reply
                 return 0;
             }
         }
         else if (kmp_frame[KMP_CID_IDX] == 0x11) {
             // kmp_put_register
             //range = NSMakeRange(2, data.length - 2);
             //NSLog(@"%@", [data subdataWithRange:range]);
             return 1;
         }
 //
     }
     else if (kmp_frame[kmp_frame_length - 1] == 0x06) {
         // kmp_set_clock no CRC
         return 0;
     }
     return 0;
 }
kmp_get_register()
ICACHE_FLASH_ATTR unsigned int kmp_get_register (unsigned char * frame, uint16_t * register_list, uint16_t register_list_length)
Definition at line 181 of file kmp.c.
References frame, ICACHE_FLASH_ATTR, kmp_byte_stuff(), KMP_CID_IDX, kmp_crc16(), KMP_DATA_IDX, kmp_data_length, KMP_DST_IDX, kmp_frame, KMP_FRAME_L, kmp_frame_length, KMP_START_BYTE_IDX, and memset.
Referenced by kmp_get_register_timer_func().
{
     unsigned int i;
     uint8_t register_high;
     uint8_t register_low;
     uint16_t crc16;
     if (register_list_length > 8) {
         // maximal number of 8 registers can be read with one request, last ones ommitted
         register_list_length = 8;
     }
     // clear frame
     kmp_frame = frame;
     memset(kmp_frame, 0x00, KMP_FRAME_L);
     kmp_frame_length = 0;
     kmp_data_length = 0;
     // start byte
     kmp_frame[KMP_START_BYTE_IDX] = 0x80;
     // data
     kmp_frame[KMP_DST_IDX] = 0x3f;
     kmp_frame[KMP_CID_IDX] = 0x10;
     // number of registers
     kmp_frame[KMP_DATA_IDX] = register_list_length;
     kmp_frame_length = 4;
     kmp_data_length = 3;
     // registers
     for (i = 0; i < register_list_length; i++) {
         register_high = (uint8_t)(register_list[i] >> 8);
         register_low = (uint8_t)(register_list[i] & 0xff);
         kmp_frame[KMP_DATA_IDX + 2 * i + 1] = register_high;
         kmp_frame[KMP_DATA_IDX + 2 * i + 2] = register_low;
     }
     kmp_frame_length += 2 * i;
     kmp_data_length += 2 * i;
     // put crc 16 in frame
     crc16 = kmp_crc16();
     kmp_frame[kmp_frame_length] = crc16 >> 8;       // high bits of crc16
     kmp_frame[kmp_frame_length + 1] = crc16 & 0xff; // low bits
     kmp_frame_length += 2;
     // stuff data
     kmp_byte_stuff();
     // stop byte
     kmp_frame[kmp_frame_length] = 0x0d;
     kmp_frame_length++;
     return kmp_frame_length;
 }
kmp_get_serial()
ICACHE_FLASH_ATTR unsigned int kmp_get_serial (unsigned char * frame)
Definition at line 139 of file kmp.c.
References frame, ICACHE_FLASH_ATTR, kmp_byte_stuff(), KMP_CID_IDX, kmp_crc16(), kmp_data_length, KMP_DST_IDX, kmp_frame, KMP_FRAME_L, kmp_frame_length, KMP_START_BYTE_IDX, and memset.
Referenced by kmp_get_serial_timer_func().
{
     uint16_t crc16;
     // clear frame
     kmp_frame = frame;
     memset(kmp_frame, 0x00, KMP_FRAME_L);
     kmp_frame_length = 0;
     kmp_data_length = 0;
     // start byte
     kmp_frame[KMP_START_BYTE_IDX] = 0x80;
     // data
     kmp_frame[KMP_DST_IDX] = 0x3f;
     kmp_frame[KMP_CID_IDX] = 0x02;
     kmp_frame_length = 3;
     kmp_data_length = 2;
     // put crc 16 in frame
     crc16 = kmp_crc16();
     kmp_frame[kmp_frame_length] = crc16 >> 8;       // high bits of crc16
     kmp_frame[kmp_frame_length + 1] = crc16 & 0xff; // low bits
     kmp_frame_length += 2;
     kmp_data_length += 2;
     // stuff data
     kmp_byte_stuff();
     // stop byte
     kmp_frame[kmp_frame_length] = 0x0d;
     kmp_frame_length++;
     return kmp_frame_length;
 }
kmp_get_type()
ICACHE_FLASH_ATTR unsigned int kmp_get_type (unsigned char * frame)
Definition at line 103 of file kmp.c.
References frame, ICACHE_FLASH_ATTR, kmp_byte_stuff(), KMP_CID_IDX, kmp_crc16(), kmp_data_length, KMP_DST_IDX, kmp_frame, KMP_FRAME_L, kmp_frame_length, KMP_START_BYTE_IDX, and memset.
{
     uint16_t crc16;
     // clear frame
     kmp_frame = frame;
     memset(kmp_frame, 0x00, KMP_FRAME_L);
     kmp_frame_length = 0;
     kmp_data_length = 0;
     // start byte
     kmp_frame[KMP_START_BYTE_IDX] = 0x80;
     // data
     kmp_frame[KMP_DST_IDX] = 0x3f;
     kmp_frame[KMP_CID_IDX] = 0x01;
     kmp_frame_length = 3;
     kmp_data_length = 2;
     // put crc 16 in frame
     crc16 = kmp_crc16();
     kmp_frame[kmp_frame_length] = crc16 >> 8;       // high bits of crc16
     kmp_frame[kmp_frame_length + 1] = crc16 & 0xff; // low bits
     kmp_frame_length += 2;
     kmp_data_length +=2;
     // stuff data
     kmp_byte_stuff();
     // stop byte
     kmp_frame[kmp_frame_length] = 0x0d;
     kmp_frame_length++;
     return kmp_frame_length;
 }
kmp_set_clock()
ICACHE_FLASH_ATTR unsigned int kmp_set_clock (unsigned char * frame, uint64_t unix_time)
Definition at line 175 of file kmp.c.
References ICACHE_FLASH_ATTR.
{
     // DEBUG: not implemented
     return 0;
 }
kmp_unit_to_string()
ICACHE_FLASH_ATTR void kmp_unit_to_string (uint8_t unit, unsigned char * unit_string)
Definition at line 442 of file kmp.c.
References ICACHE_FLASH_ATTR, and strcpy.
Referenced by kmp_get_received_energy_kwh(), and kmp_received_task().
{
     switch (unit) {
         case 0x01:
             strcpy(unit_string, "Wh");
             break;
         case 0x02:
             strcpy(unit_string, "kWh");
             break;
         case 0x03:
             strcpy(unit_string, "MWh");
             break;
         case 0x08:
             strcpy(unit_string, "Gj");
             break;
         case 0x0c:
             strcpy(unit_string, "Gcal");
             break;
         case 0x16:
             strcpy(unit_string, "kW");
             break;
         case 0x17:
             strcpy(unit_string, "MW");
             break;
         case 0x25:
             strcpy(unit_string, "C");
             break;
         case 0x26:
             strcpy(unit_string, "K");
             break;
         case 0x27:
             strcpy(unit_string, "l");
             break;
         case 0x28:
             strcpy(unit_string, "m3");
             break;
         case 0x29:
             strcpy(unit_string, "l/h");
             break;
         case 0x2a:
             strcpy(unit_string, "m3/h");
             break;
         case 0x2b:
             strcpy(unit_string, "m3xC");
             break;
         case 0x2c:
             strcpy(unit_string, "ton");
             break;
         case 0x2d:
             strcpy(unit_string, "ton/h");
             break;
         case 0x2e:
             strcpy(unit_string, "h");
             break;
         case 0x2f:
             strcpy(unit_string, "clock");
             break;
         case 0x30:
             strcpy(unit_string, "date1");
             break;
         case 0x32:
             strcpy(unit_string, "date3");
             break;
         case 0x33:
             strcpy(unit_string, "number");
             break;
         case 0x34:
             strcpy(unit_string, "bar");
             break;
         default:
             break;
     }
 }
kmp_value_to_double()
ICACHE_FLASH_ATTR double kmp_value_to_double (int32_t value, uint8_t si_ex)
Definition at line 366 of file kmp.c.
References ICACHE_FLASH_ATTR, and int_pow().
{
     double result;
     int8_t sign_i = (si_ex & 0x80) >> 7;
     int8_t sign_e = (si_ex & 0x40) >> 6;
     int8_t exponent = (si_ex & 0x3f);
     // powf(-1, (double)sign_i) * value * powf(10, (powf(-1, (double)sign_e) * exponent));
     if (sign_i) {
         if (sign_e) {
             result = -1 * value / int_pow(10, exponent);
         }
         else {
             result = -1 * value * int_pow(10, exponent);
         }
     }
     else {
         if (sign_e) {
             result = value / (double)int_pow(10, exponent);
         }
         else {
             result = value * (double)int_pow(10, exponent);
         }
     }
     return result;
 }
kmp_value_to_string()
ICACHE_FLASH_ATTR void kmp_value_to_string (int32_t value, uint8_t si_ex, unsigned char * value_string)
Definition at line 394 of file kmp.c.
References decimal_number_length(), ICACHE_FLASH_ATTR, int_pow(), strcat, strcpy, and tfp_snprintf().
Referenced by kmp_get_received_energy_kwh(), and kmp_received_task().
{
     double result;
     uint32_t result_int, result_frac;
     int8_t sign_i = (si_ex & 0x80) >> 7;
     int8_t sign_e = (si_ex & 0x40) >> 6;
     int8_t exponent = (si_ex & 0x3f);
     uint32_t factor;
     unsigned char leading_zeroes[16];
     unsigned int i;
     factor = int_pow(10, exponent);
     if (sign_i) {
         if (sign_e) {
             result = value / int_pow(10, exponent);
             result_int = (int32_t)result;
             result_frac = value - result_int * int_pow(10, exponent);
             // prepare decimal string
             strcpy(leading_zeroes, "");
             for (i = 0; i < (exponent - decimal_number_length(result_frac)); i++) {
                 strcat(leading_zeroes, "0");
             }
             tfp_snprintf(value_string, 23 + i, "-%u.%s%u", result_int, leading_zeroes, result_frac);
         }
         else {
             tfp_snprintf(value_string, 12, "-%u", value * factor);
         }
     }
     else {
         if (sign_e) {
             result = value / int_pow(10, exponent);
             result_int = (int32_t)result;
             result_frac = value - result_int * int_pow(10, exponent);
             // prepare decimal string
             strcpy(leading_zeroes, "");
             for (i = 0; i < (exponent - decimal_number_length(result_frac)); i++) {
                 strcat(leading_zeroes, "0");
             }
             tfp_snprintf(value_string, 22 + i, "%u.%s%u", result_int, leading_zeroes, result_frac);
         }
         else {
             tfp_snprintf(value_string, 11, "%u", value * factor);
         }
     }
 }
Variable Documentation
kmp_data_length
unsigned int kmp_data_length
Definition at line 96 of file kmp.c.
Referenced by kmp_byte_stuff(), kmp_byte_unstuff(), kmp_crc16(), kmp_decode_frame(), kmp_get_register(), kmp_get_serial(), and kmp_get_type().
kmp_frame
unsigned char* kmp_frame
Definition at line 94 of file kmp.c.
Referenced by kmp_byte_stuff(), kmp_byte_unstuff(), kmp_crc16(), kmp_decode_frame(), kmp_get_register(), kmp_get_serial(), and kmp_get_type().
kmp_frame_length
unsigned int kmp_frame_length
Definition at line 95 of file kmp.c.
Referenced by kmp_byte_stuff(), kmp_byte_unstuff(), kmp_decode_frame(), kmp_get_register(), kmp_get_serial(), and kmp_get_type().
kmp_response
kmp_response_t* kmp_response
Definition at line 99 of file kmp.c.