MeterLogger: user/led.h File Reference
led.h File Reference
Functions
ICACHE_FLASH_ATTR void led_init (void)
ICACHE_FLASH_ATTR void led_on (void)
ICACHE_FLASH_ATTR void led_off (void)
ICACHE_FLASH_ATTR void led_blink (void)
ICACHE_FLASH_ATTR void led_pattern_a (void)
ICACHE_FLASH_ATTR void led_pattern_b (void)
ICACHE_FLASH_ATTR void led_pattern_c (void)
ICACHE_FLASH_ATTR void led_stop_pattern (void)
Function Documentation
led_blink()
ICACHE_FLASH_ATTR void led_blink (void)
Definition at line 83 of file led.c.
References led_on(), led_single_blink_off_timer, led_single_blink_off_timer_func(), NULL, os_timer_arm, os_timer_disarm, os_timer_func_t, and os_timer_setfn.
Referenced by en61107_receive_timeout_timer_func().
{
     led_on();
     os_timer_disarm(&led_single_blink_off_timer);
     os_timer_setfn(&led_single_blink_off_timer, (os_timer_func_t *)led_single_blink_off_timer_func, NULL);
     os_timer_arm(&led_single_blink_off_timer, 1000, 0);
 }
led_init()
ICACHE_FLASH_ATTR void led_init (void)
Definition at line 64 of file led.c.
References BIT2, FUNC_GPIO2, gpio_output_set(), PERIPHS_IO_MUX_GPIO2_U, and PIN_FUNC_SELECT.
{
     //Set GPIO2 to output mode
     PIN_FUNC_SELECT(PERIPHS_IO_MUX_GPIO2_U, FUNC_GPIO2);
     // Set GPIO2 to HIGH (turn blue led off)
     gpio_output_set(BIT2, 0, BIT2, 0);
 }
led_off()
ICACHE_FLASH_ATTR void led_off (void)
Definition at line 77 of file led.c.
References BIT2, and gpio_output_set().
Referenced by ac_out_off_timer_func(), ac_pwm_timer_func(), led_blinker_timer_func(), led_double_blink_timer_func(), led_single_blink_off_timer_func(), and led_stop_pattern().
{
     // Set GPIO2 to HIGH
     gpio_output_set(BIT2, 0, BIT2, 0);
 }
led_on()
ICACHE_FLASH_ATTR void led_on (void)
Definition at line 72 of file led.c.
References BIT2, and gpio_output_set().
Referenced by ac_pwm_timer_func(), led_blink(), led_blinker_timer_func(), and led_double_blink_timer_func().
{
     //Set GPIO2 to LOW
     gpio_output_set(0, BIT2, BIT2, 0);
 }
led_pattern_a()
ICACHE_FLASH_ATTR void led_pattern_a (void)
Definition at line 90 of file led.c.
References led_blinker_timer, led_blinker_timer_func(), NULL, os_timer_arm, os_timer_disarm, os_timer_func_t, and os_timer_setfn.
Referenced by ac_motor_valve_open(), ac_test(), ac_test_timer_func(), ac_thermo_close(), and wifi_scan_done_cb().
{
     os_timer_disarm(&led_blinker_timer);
     os_timer_setfn(&led_blinker_timer, (os_timer_func_t *)led_blinker_timer_func, NULL);
     os_timer_arm(&led_blinker_timer, 1000, 1);
 }
led_pattern_b()
ICACHE_FLASH_ATTR void led_pattern_b (void)
Definition at line 96 of file led.c.
References led_blinker_timer, led_blinker_timer_func(), NULL, os_timer_arm, os_timer_disarm, os_timer_func_t, and os_timer_setfn.
Referenced by ac_motor_valve_close(), ac_test_timer_func(), and ac_thermo_open().
{
     os_timer_disarm(&led_blinker_timer);
     os_timer_setfn(&led_blinker_timer, (os_timer_func_t *)led_blinker_timer_func, NULL);
     os_timer_arm(&led_blinker_timer, 200, 1);
 }
led_pattern_c()
ICACHE_FLASH_ATTR void led_pattern_c (void)
Definition at line 102 of file led.c.
References led_double_blink_timer, led_double_blink_timer_func(), NULL, os_timer_arm, os_timer_disarm, os_timer_func_t, and os_timer_setfn.
{
     // blink fast two times every 5th second
     os_timer_disarm(&led_double_blink_timer);
     os_timer_setfn(&led_double_blink_timer, (os_timer_func_t *)led_double_blink_timer_func, NULL);
     os_timer_arm(&led_double_blink_timer, 3000, 1);
 }
led_stop_pattern()
ICACHE_FLASH_ATTR void led_stop_pattern (void)
Definition at line 109 of file led.c.
References led_blinker_timer, led_double_blink_timer, led_off(), and os_timer_disarm.
Referenced by ac_out_off_timer_func(), ac_thermo_pwm(), wifi_connect(), and wifi_scan_done_cb().
{
     os_timer_disarm(&led_blinker_timer);
     os_timer_disarm(&led_double_blink_timer);
     led_off();
 }