MeterLogger: user/led.c File Reference
led.c File Reference
#include <esp8266.h>
#include "debug.h"
#include "led.h"
Functions
ICACHE_FLASH_ATTR static void led_blinker_timer_func (void *arg)
ICACHE_FLASH_ATTR static void led_single_blink_off_timer_func (void *arg)
ICACHE_FLASH_ATTR static void led_double_blink_timer_func (void *arg)
ICACHE_FLASH_ATTR void led_init (void)
ICACHE_FLASH_ATTR void led_on (void)
ICACHE_FLASH_ATTR void led_off (void)
ICACHE_FLASH_ATTR void led_blink (void)
ICACHE_FLASH_ATTR void led_pattern_a (void)
ICACHE_FLASH_ATTR void led_pattern_b (void)
ICACHE_FLASH_ATTR void led_pattern_c (void)
ICACHE_FLASH_ATTR void led_stop_pattern (void)
Variables
static os_timer_t led_blinker_timer
static os_timer_t led_single_blink_off_timer
static os_timer_t led_double_blink_timer
static os_timer_t led_sub_pattern_timer
static volatile bool led_blinker_timer_running = false
static volatile bool led_double_blinker_timer_running = false
static uint8_t led_sub_pattern_state = 0
Function Documentation
led_blink()
ICACHE_FLASH_ATTR void led_blink (void)
Definition at line 99 of file led.c.
References led_on(), led_single_blink_off_timer, led_single_blink_off_timer_func(), NULL, os_timer_arm, os_timer_disarm, os_timer_func_t, and os_timer_setfn.
Referenced by en61107_receive_timeout_timer_func().
{
     led_on();
     os_timer_disarm(&led_single_blink_off_timer);
     os_timer_setfn(&led_single_blink_off_timer, (os_timer_func_t *)led_single_blink_off_timer_func, NULL);
     os_timer_arm(&led_single_blink_off_timer, 1000, 0);
 }
led_blinker_timer_func()
ICACHE_FLASH_ATTR static void led_blinker_timer_func (void * arg) static
Definition at line 16 of file led.c.
References BIT2, GPIO_OUT_ADDRESS, GPIO_REG_READ, led_blinker_timer, led_blinker_timer_running, led_off(), led_on(), and os_timer_disarm.
Referenced by led_pattern_a(), and led_pattern_b().
{
     if (led_blinker_timer_running == false) {
         // stop blinking if asked to stop via state variable led_blinker_timer_running
         os_timer_disarm(&led_blinker_timer);
         return;
     }
     // do blinky stuff
     if (GPIO_REG_READ(GPIO_OUT_ADDRESS) & BIT2) {
         led_on();
     }
     else {
         led_off();
     }
 }
led_double_blink_timer_func()
ICACHE_FLASH_ATTR static void led_double_blink_timer_func (void * arg) static
Definition at line 36 of file led.c.
References led_double_blink_timer, led_double_blinker_timer_running, led_off(), led_on(), led_sub_pattern_state, led_sub_pattern_timer, NULL, os_timer_arm, os_timer_disarm, os_timer_func_t, and os_timer_setfn.
Referenced by led_pattern_c().
{
     // blink fast two times
     if (led_double_blinker_timer_running == false) {
         // stop blinking if asked to stop via state variable led_double_blinker_timer_running
         os_timer_disarm(&led_double_blink_timer);
         return;
     }
     led_off();
     switch (led_sub_pattern_state) {
         case 0:
             led_on();
             led_sub_pattern_state++;
             os_timer_disarm(&led_sub_pattern_timer);
             os_timer_setfn(&led_sub_pattern_timer, (os_timer_func_t *)led_double_blink_timer_func, NULL);
             os_timer_arm(&led_sub_pattern_timer, 100, 0);
             break;
         case 1:
             led_off();
             led_sub_pattern_state++;
             os_timer_disarm(&led_sub_pattern_timer);
             os_timer_setfn(&led_sub_pattern_timer, (os_timer_func_t *)led_double_blink_timer_func, NULL);
             os_timer_arm(&led_sub_pattern_timer, 100, 0);
             break;
         case 2:
             led_on();
             led_sub_pattern_state++;
             os_timer_disarm(&led_sub_pattern_timer);
             os_timer_setfn(&led_sub_pattern_timer, (os_timer_func_t *)led_double_blink_timer_func, NULL);
             os_timer_arm(&led_sub_pattern_timer, 100, 0);
             break;
         case 3:
             led_off();
             os_timer_disarm(&led_sub_pattern_timer);
             led_sub_pattern_state = 0;
             break;
     }
 }
led_init()
ICACHE_FLASH_ATTR void led_init (void)
Definition at line 80 of file led.c.
References BIT2, FUNC_GPIO2, gpio_output_set(), PERIPHS_IO_MUX_GPIO2_U, and PIN_FUNC_SELECT.
{
     //Set GPIO2 to output mode
     PIN_FUNC_SELECT(PERIPHS_IO_MUX_GPIO2_U, FUNC_GPIO2);
     // Set GPIO2 to HIGH (turn blue led off)
     gpio_output_set(BIT2, 0, BIT2, 0);
 }
led_off()
ICACHE_FLASH_ATTR void led_off (void)
Definition at line 93 of file led.c.
References BIT2, and gpio_output_set().
Referenced by ac_out_off_timer_func(), ac_pwm_timer_func(), led_blinker_timer_func(), led_double_blink_timer_func(), led_single_blink_off_timer_func(), and led_stop_pattern().
{
     // Set GPIO2 to HIGH
     gpio_output_set(BIT2, 0, BIT2, 0);
 }
led_on()
ICACHE_FLASH_ATTR void led_on (void)
Definition at line 88 of file led.c.
References BIT2, and gpio_output_set().
Referenced by ac_pwm_timer_func(), led_blink(), led_blinker_timer_func(), and led_double_blink_timer_func().
{
     //Set GPIO2 to LOW
     gpio_output_set(0, BIT2, BIT2, 0);
 }
led_pattern_a()
ICACHE_FLASH_ATTR void led_pattern_a (void)
Definition at line 106 of file led.c.
References led_blinker_timer, led_blinker_timer_func(), led_blinker_timer_running, NULL, os_timer_arm, os_timer_disarm, os_timer_func_t, and os_timer_setfn.
Referenced by ac_motor_valve_open(), ac_test(), ac_test_timer_func(), ac_thermo_close(), and wifi_scan_done_cb().
{
     os_timer_disarm(&led_blinker_timer);
     os_timer_setfn(&led_blinker_timer, (os_timer_func_t *)led_blinker_timer_func, NULL);
     led_blinker_timer_running = true;   // state variable to control stopping after pattern is done
     os_timer_arm(&led_blinker_timer, 1000, 1);
 }
led_pattern_b()
ICACHE_FLASH_ATTR void led_pattern_b (void)
Definition at line 113 of file led.c.
References led_blinker_timer, led_blinker_timer_func(), led_blinker_timer_running, NULL, os_timer_arm, os_timer_disarm, os_timer_func_t, and os_timer_setfn.
Referenced by ac_motor_valve_close(), ac_test_timer_func(), ac_thermo_open(), and wifi_scan_timer_func().
{
     os_timer_disarm(&led_blinker_timer);
     os_timer_setfn(&led_blinker_timer, (os_timer_func_t *)led_blinker_timer_func, NULL);
     led_blinker_timer_running = true;   // state variable to control stopping after pattern is done
     os_timer_arm(&led_blinker_timer, 200, 1);
 }
led_pattern_c()
ICACHE_FLASH_ATTR void led_pattern_c (void)
Definition at line 120 of file led.c.
References led_double_blink_timer, led_double_blink_timer_func(), led_double_blinker_timer_running, NULL, os_timer_arm, os_timer_disarm, os_timer_func_t, and os_timer_setfn.
{
     // blink fast two times every 5th second
     os_timer_disarm(&led_double_blink_timer);
     os_timer_setfn(&led_double_blink_timer, (os_timer_func_t *)led_double_blink_timer_func, NULL);
     led_double_blinker_timer_running = true;    // state variable to control stopping after pattern is done
     os_timer_arm(&led_double_blink_timer, 3000, 1);
 }
led_single_blink_off_timer_func()
ICACHE_FLASH_ATTR static void led_single_blink_off_timer_func (void * arg) static
Definition at line 32 of file led.c.
References led_off().
Referenced by led_blink().
{
     led_off();
 }
led_stop_pattern()
ICACHE_FLASH_ATTR void led_stop_pattern (void)
Definition at line 128 of file led.c.
References led_blinker_timer_running, led_double_blinker_timer_running, and led_off().
Referenced by ac_out_off_timer_func(), ac_thermo_pwm(), wifi_connect(), and wifi_scan_done_cb().
{
     led_blinker_timer_running = false;
     led_double_blinker_timer_running = false;
     led_off();
 }
Variable Documentation
led_blinker_timer
os_timer_t led_blinker_timer static
Definition at line 5 of file led.c.
Referenced by led_blinker_timer_func(), led_pattern_a(), and led_pattern_b().
led_blinker_timer_running
volatile bool led_blinker_timer_running = false static
Definition at line 11 of file led.c.
Referenced by led_blinker_timer_func(), led_pattern_a(), led_pattern_b(), and led_stop_pattern().
led_double_blink_timer
os_timer_t led_double_blink_timer static
Definition at line 8 of file led.c.
Referenced by led_double_blink_timer_func(), and led_pattern_c().
led_double_blinker_timer_running
volatile bool led_double_blinker_timer_running = false static
Definition at line 12 of file led.c.
Referenced by led_double_blink_timer_func(), led_pattern_c(), and led_stop_pattern().
led_single_blink_off_timer
os_timer_t led_single_blink_off_timer static
Definition at line 6 of file led.c.
Referenced by led_blink().
led_sub_pattern_state
uint8_t led_sub_pattern_state = 0 static
Definition at line 14 of file led.c.
Referenced by led_double_blink_timer_func().
led_sub_pattern_timer
os_timer_t led_sub_pattern_timer static
Definition at line 9 of file led.c.
Referenced by led_double_blink_timer_func().