MeterLogger: esp-open-lwip/lwip/core/memp.c File Reference
memp.c File Reference
#include "lwip/opt.h"
#include "lwip/memp.h"
#include "lwip/pbuf.h"
#include "lwip/udp.h"
#include "lwip/raw.h"
#include "lwip/tcp_impl.h"
#include "lwip/igmp.h"
#include "lwip/api.h"
#include "lwip/api_msg.h"
#include "lwip/tcpip.h"
#include "lwip/sys.h"
#include "lwip/timers.h"
#include "lwip/stats.h"
#include "netif/etharp.h"
#include "lwip/ip_frag.h"
#include "lwip/snmp_structs.h"
#include "lwip/snmp_msg.h"
#include "lwip/dns.h"
#include "netif/ppp_oe.h"
#include <string.h>
#include "lwip/memp_std.h"
Data Structures
struct memp
Macros
#define MEMP_SIZE 0
#define MEMP_ALIGN_SIZE(x) (LWIP_MEM_ALIGN_SIZE(x))
#define LWIP_MEMPOOL(name, num, size, desc, attr) LWIP_MEM_ALIGN_SIZE(size),
#define LWIP_MEMPOOL(name, num, size, desc, attr) (num),
#define LWIP_MEMPOOL(name, num, size, desc, attr) (desc),
#define LWIP_MEMPOOL(name, num, size, desc, attr) + ((num) * (MEMP_SIZE + MEMP_ALIGN_SIZE(size)))
Functions
void memp_init (void)
void * memp_malloc (memp_t type)
void memp_free (memp_t type, void *mem)
Variables
static struct memp * memp_tab [MEMP_MAX]
static const u32_t memp_sizes [MEMP_MAX] ICACHE_RODATA_ATTR
u16_t memp_sizes_test [1] = {PBUF_POOL_BUFSIZE,}
static const u16_t memp_num [MEMP_MAX]
const char * memp_desc [MEMP_MAX]
static u8_t memp_memory [MEM_ALIGNMENT - 1 #define LWIP_MEMPOOL(name, num, size, desc, attr)]
Detailed Description
Dynamic pool memory manager
lwIP has dedicated pools for many structures (netconn, protocol control blocks, packet buffers, ...). All these pools are managed here.
Definition in file memp.c.
Macro Definition Documentation
LWIP_MEMPOOL [1/4]
#define LWIP_MEMPOOL (name, num, size, desc, attr) LWIP_MEM_ALIGN_SIZE(size),
LWIP_MEMPOOL [2/4]
#define LWIP_MEMPOOL (name, num, size, desc, attr) (num),
LWIP_MEMPOOL [3/4]
#define LWIP_MEMPOOL (name, num, size, desc, attr) (desc),
LWIP_MEMPOOL [4/4]
#define LWIP_MEMPOOL (name, num, size, desc, attr) + ((num) * (MEMP_SIZE + MEMP_ALIGN_SIZE(size)))
MEMP_ALIGN_SIZE
#define MEMP_ALIGN_SIZE (x) (LWIP_MEM_ALIGN_SIZE(x))
Definition at line 111 of file memp.c.
MEMP_SIZE
#define MEMP_SIZE 0
Definition at line 110 of file memp.c.
Referenced by memp_free(), memp_init(), and memp_malloc().
Function Documentation
memp_free()
void memp_free (memp_t type, void * mem)
Put an element back into its pool.
Parameters
type the pool where to put mem
mem the memp element to free
Definition at line 438 of file memp.c.
References ETH_PAD_SIZE, LWIP_ASSERT, MEM_ALIGNMENT, memp_desc, memp_memory_PBUF_POOL_base, MEMP_SIZE, memp_sizes_test, MEMP_STATS_DEC, memp::next, NULL, PBUF_LINK_HLEN, PBUF_POOL_BUFSIZE, printf, SYS_ARCH_DECL_PROTECT, SYS_ARCH_PROTECT, SYS_ARCH_UNPROTECT, and TCP_MSS.
Referenced by espconn_kill_oldest(), espconn_kill_pcb(), espconn_tcp_client(), espconn_tcp_disconnect_successful(), espconn_tcp_server(), pbuf_free(), tcpip_callback_with_block(), tcpip_input(), and tcpip_thread().
 {
   struct memp *memp;
   SYS_ARCH_DECL_PROTECT(old_level);
   if (mem == NULL) {
     return;
   }
   LWIP_ASSERT("memp_free: mem properly aligned",
                 ((mem_ptr_t)mem % MEM_ALIGNMENT) == 0);
   memp = (struct memp *)(void *)((u8_t*)mem - MEMP_SIZE);
   SYS_ARCH_PROTECT(old_level);
 #if MEMP_OVERFLOW_CHECK
 #if MEMP_OVERFLOW_CHECK >= 2
   memp_overflow_check_all();
 #else
   memp_overflow_check_element_overflow(memp, type);
   memp_overflow_check_element_underflow(memp, type);
 #endif /* MEMP_OVERFLOW_CHECK >= 2 */
 #endif /* MEMP_OVERFLOW_CHECK */
   MEMP_STATS_DEC(used, type);
   memp->next = memp_tab[type];
   memp_tab[type] = memp;
 #if MEMP_SANITY_CHECK
   LWIP_ASSERT("memp sanity", memp_sanity());
 #endif /* MEMP_SANITY_CHECK */
   SYS_ARCH_UNPROTECT(old_level);
 }
memp_init()
void memp_init (void)
Initialize this module.
Carves out memp_memory into linked lists for each pool-type.
Definition at line 341 of file memp.c.
References LWIP_MEM_ALIGN, MEMP_MAX, memp_memory, memp_num, MEMP_OVERFLOW_CHECK, MEMP_SIZE, MEMP_STATS_AVAIL, memp::next, and NULL.
Referenced by lwip_init().
 {
   struct memp *memp;
   u16_t i, j;
   for (i = 0; i < MEMP_MAX; ++i) {
     MEMP_STATS_AVAIL(used, i, 0);
     MEMP_STATS_AVAIL(max, i, 0);
     MEMP_STATS_AVAIL(err, i, 0);
     MEMP_STATS_AVAIL(avail, i, memp_num[i]);
   }
 #if !MEMP_SEPARATE_POOLS
   memp = (struct memp *)LWIP_MEM_ALIGN(memp_memory);
 #endif /* !MEMP_SEPARATE_POOLS */
   /* for every pool: */
   for (i = 0; i < MEMP_MAX; ++i) {
     memp_tab[i] = NULL;
 #if MEMP_SEPARATE_POOLS
     memp = (struct memp*)memp_bases[i];
 #endif /* MEMP_SEPARATE_POOLS */
     /* create a linked list of memp elements */
     for (j = 0; j < memp_num[i]; ++j) {
       memp->next = (struct memp *)memp_tab[i];
       memp_tab[i] = memp;
       memp = (struct memp *)(void *)((u8_t *)memp + MEMP_SIZE + memp_sizes[i]
 #if MEMP_OVERFLOW_CHECK
         + MEMP_SANITY_REGION_AFTER_ALIGNED
 #endif
       );
     }
   }
 #if MEMP_OVERFLOW_CHECK
   memp_overflow_init();
   /* check everything a first time to see if it worked */
   memp_overflow_check_all();
 #endif /* MEMP_OVERFLOW_CHECK */
 }
memp_malloc()
void* memp_malloc (memp_t type)
Get an element from a specific pool.
Parameters
type the pool to get an element from
the debug version has two more parameters:
Parameters
file file name calling this function
line number of line where this function is called
Returns
a pointer to the allocated memory or a NULL pointer on error
Definition at line 393 of file memp.c.
References LWIP_ASSERT, LWIP_DBG_LEVEL_SERIOUS, LWIP_DEBUGF, LWIP_ERROR, MEM_ALIGNMENT, MEMP_DEBUG, memp_desc, MEMP_MAX, MEMP_SIZE, MEMP_STATS_INC, MEMP_STATS_INC_USED, memp::next, NULL, SYS_ARCH_DECL_PROTECT, SYS_ARCH_PROTECT, and SYS_ARCH_UNPROTECT.
Referenced by pbuf_alloc(), tcpip_callback_with_block(), and tcpip_input().
 {
   struct memp *memp;
   SYS_ARCH_DECL_PROTECT(old_level);
   LWIP_ERROR("memp_malloc: type < MEMP_MAX", (type < MEMP_MAX), return NULL;);
   SYS_ARCH_PROTECT(old_level);
 #if MEMP_OVERFLOW_CHECK >= 2
   memp_overflow_check_all();
 #endif /* MEMP_OVERFLOW_CHECK >= 2 */
   memp = memp_tab[type];
   if (memp != NULL) {
     memp_tab[type] = memp->next;
 #if MEMP_OVERFLOW_CHECK
     memp->next = NULL;
     memp->file = file;
     memp->line = line;
 #endif /* MEMP_OVERFLOW_CHECK */
     MEMP_STATS_INC_USED(used, type);
     LWIP_ASSERT("memp_malloc: memp properly aligned",
                 ((mem_ptr_t)memp % MEM_ALIGNMENT) == 0);
     memp = (struct memp*)(void *)((u8_t*)memp + MEMP_SIZE);
   } else {
     LWIP_DEBUGF(MEMP_DEBUG | LWIP_DBG_LEVEL_SERIOUS, ("memp_malloc: out of memory in pool %s\n", memp_desc[type]));
     MEMP_STATS_INC(err, type);
   }
   SYS_ARCH_UNPROTECT(old_level);
   return memp;
 }
Variable Documentation
ICACHE_RODATA_ATTR
const u32_t memp_sizes [MEMP_MAX] ICACHE_RODATA_ATTR static
Initial value:
= {
#define LWIP_MEMPOOL(name,num,size,desc,attr)
}
This array holds the element sizes of each pool.
Definition at line 129 of file memp.c.
memp_desc
const char* memp_desc[MEMP_MAX]
Initial value:
= {
#define LWIP_MEMPOOL(name,num,size,desc,attr)
}
This array holds a textual description of each pool.
Definition at line 147 of file memp.c.
Referenced by memp_free(), and memp_malloc().
memp_memory
u8_t memp_memory[MEM_ALIGNMENT - 1 #define LWIP_MEMPOOL(name, num, size, desc, attr)] static
This is the actual memory used by the pools (all pools in one big block).
Definition at line 176 of file memp.c.
Referenced by memp_init().
memp_num
const u16_t memp_num[MEMP_MAX] static
Initial value:
= {
#define LWIP_MEMPOOL(name,num,size,desc,attr)
}
This array holds the number of elements in each pool.
Definition at line 139 of file memp.c.
Referenced by memp_init().
memp_sizes_test
u16_t memp_sizes_test[1] = {PBUF_POOL_BUFSIZE,}
Definition at line 134 of file memp.c.
Referenced by memp_free().
memp_tab
struct memp* memp_tab[MEMP_MAX] static
This array holds the first free element of each pool. Elements form a linked list.
Definition at line 117 of file memp.c.