MeterLogger: esp-open-lwip/lwip/core/netif.c File Reference
netif.c File Reference
#include "lwip/opt.h"
#include "lwip/def.h"
#include "lwip/ip_addr.h"
#include "lwip/netif.h"
#include "lwip/tcp_impl.h"
#include "lwip/snmp.h"
#include "lwip/igmp.h"
#include "netif/etharp.h"
#include "lwip/stats.h"
Macros
#define NETIF_STATUS_CALLBACK(n)
#define NETIF_LINK_CALLBACK(n)
Functions
void netif_init (void)
struct netif * netif_add (struct netif *netif, ip_addr_t *ipaddr, ip_addr_t *netmask, ip_addr_t *gw, void *state, netif_init_fn init, netif_input_fn input)
void netif_set_addr (struct netif *netif, ip_addr_t *ipaddr, ip_addr_t *netmask, ip_addr_t *gw)
void netif_remove (struct netif *netif)
struct netif * netif_find (char *name)
void netif_set_ipaddr (struct netif *netif, ip_addr_t *ipaddr)
void netif_set_gw (struct netif *netif, ip_addr_t *gw)
void netif_set_netmask (struct netif *netif, ip_addr_t *netmask)
void netif_set_default (struct netif *netif)
void netif_set_up (struct netif *netif)
void netif_set_down (struct netif *netif)
void netif_set_link_up (struct netif *netif)
void netif_set_link_down (struct netif *netif)
Variables
struct netif * netif_list
struct netif * netif_default
Detailed Description
lwIP network interface abstraction
Definition in file netif.c.
Macro Definition Documentation
NETIF_LINK_CALLBACK
#define NETIF_LINK_CALLBACK (n)
Definition at line 72 of file netif.c.
Referenced by netif_set_link_down(), and netif_set_link_up().
NETIF_STATUS_CALLBACK
#define NETIF_STATUS_CALLBACK (n)
Definition at line 66 of file netif.c.
Referenced by netif_set_down(), and netif_set_up().
Function Documentation
netif_add()
struct netif* netif_add (struct netif * netif, ip_addr_t * ipaddr, ip_addr_t * netmask, ip_addr_t * gw, void * state, netif_init_fn init, netif_input_fn input)
Add a network interface to the list of lwIP netifs.
Parameters
netif a pre-allocated netif structure
ipaddr IP address for the new netif
netmask network mask for the new netif
gw default gateway IP address for the new netif
state opaque data passed to the new netif
init callback function that initializes the interface
input callback function that is called to pass ingress packets up in the protocol layer stack.
Returns
netif, or NULL if failed.
Definition at line 137 of file netif.c.
References ERR_OK, netif::flags, netif::gw, netif::input, netif::ip_addr, ip_addr_debug_print, ip_addr_set_zero, LWIP_ASSERT, LWIP_DEBUGF, netif::name, NETIF_DEBUG, NETIF_FLAG_IGMP, netif_list, netif_set_addr(), netif::netmask, netif::next, NULL, netif::num, snmp_inc_iflist, state, and netif::state.
Referenced by netif_init().
 {
   static u8_t netifnum = 0;
   LWIP_ASSERT("No init function given", init != NULL);
   /* reset new interface configuration state */
   ip_addr_set_zero(&netif->ip_addr);
   ip_addr_set_zero(&netif->netmask);
   ip_addr_set_zero(&netif->gw);
   netif->flags = 0;
 #if LWIP_DHCP
   /* netif not under DHCP control by default */
   netif->dhcp = NULL;
   netif->dhcps_pcb = NULL;
 #endif /* LWIP_DHCP */
 #if LWIP_AUTOIP
   /* netif not under AutoIP control by default */
   netif->autoip = NULL;
 #endif /* LWIP_AUTOIP */
 #if LWIP_NETIF_STATUS_CALLBACK
   netif->status_callback = NULL;
 #endif /* LWIP_NETIF_STATUS_CALLBACK */
 #if LWIP_NETIF_LINK_CALLBACK
   netif->link_callback = NULL;
 #endif /* LWIP_NETIF_LINK_CALLBACK */
 #if LWIP_IGMP
   netif->igmp_mac_filter = NULL;
 #endif /* LWIP_IGMP */
 #if ENABLE_LOOPBACK
   netif->loop_first = NULL;
   netif->loop_last = NULL;
 #endif /* ENABLE_LOOPBACK */
   /* remember netif specific state information data */
   netif->state = state;
   netif->num = netifnum++;
   netif->input = input;
 #if LWIP_NETIF_HWADDRHINT
   netif->addr_hint = NULL;
 #endif /* LWIP_NETIF_HWADDRHINT*/
 #if ENABLE_LOOPBACK && LWIP_LOOPBACK_MAX_PBUFS
   netif->loop_cnt_current = 0;
 #endif /* ENABLE_LOOPBACK && LWIP_LOOPBACK_MAX_PBUFS */
 #if IP_NAPT
   netif->napt = 0;
 #endif /* IP_NAPT */
   netif_set_addr(netif, ipaddr, netmask, gw);
   /* call user specified initialization function for netif */
   if (init(netif) != ERR_OK) {
     return NULL;
   }
   /* add this netif to the list */
   netif->next = netif_list;
   netif_list = netif;
   snmp_inc_iflist();
 #if LWIP_IGMP
   /* start IGMP processing */
   if (netif->flags & NETIF_FLAG_IGMP) {
     igmp_start(netif);
   }
 #endif /* LWIP_IGMP */
   LWIP_DEBUGF(NETIF_DEBUG, ("netif: added interface %c%c IP addr ",
     netif->name[0], netif->name[1]));
   ip_addr_debug_print(NETIF_DEBUG, ipaddr);
   LWIP_DEBUGF(NETIF_DEBUG, (" netmask "));
   ip_addr_debug_print(NETIF_DEBUG, netmask);
   LWIP_DEBUGF(NETIF_DEBUG, (" gw "));
   ip_addr_debug_print(NETIF_DEBUG, gw);
   LWIP_DEBUGF(NETIF_DEBUG, ("\n"));
   return netif;
 }
netif_find()
struct netif* netif_find (char * name)
Find a network interface by searching for its name
Parameters
name the name of the netif (like netif->name) plus concatenated number in ascii representation (e.g. 'en0')
Definition at line 291 of file netif.c.
References LWIP_DEBUGF, netif::name, NETIF_DEBUG, netif::next, NULL, and netif::num.
 {
   struct netif *netif;
   u8_t num;
   if (name == NULL) {
     return NULL;
   }
   num = name[2] - '0';
   for(netif = netif_list; netif != NULL; netif = netif->next) {
     if (num == netif->num &&
        name[0] == netif->name[0] &&
        name[1] == netif->name[1]) {
       LWIP_DEBUGF(NETIF_DEBUG, ("netif_find: found %c%c\n", name[0], name[1]));
       return netif;
     }
   }
   LWIP_DEBUGF(NETIF_DEBUG, ("netif_find: didn't find %c%c\n", name[0], name[1]));
   return NULL;
 }
netif_init()
void netif_init (void)
Definition at line 104 of file netif.c.
References IP4_ADDR, ip_input(), netif_add(), netif_set_up(), NULL, and tcpip_input().
Referenced by lwip_init().
 {
 #if LWIP_HAVE_LOOPIF
   ip_addr_t loop_ipaddr, loop_netmask, loop_gw;
   IP4_ADDR(&loop_gw, 127,0,0,1);
   IP4_ADDR(&loop_ipaddr, 127,0,0,1);
   IP4_ADDR(&loop_netmask, 255,0,0,0);
 #if NO_SYS
   netif_add(&loop_netif, &loop_ipaddr, &loop_netmask, &loop_gw, NULL, netif_loopif_init, ip_input);
 #else  /* NO_SYS */
   netif_add(&loop_netif, &loop_ipaddr, &loop_netmask, &loop_gw, NULL, netif_loopif_init, tcpip_input);
 #endif /* NO_SYS */
   netif_set_up(&loop_netif);
 #endif /* LWIP_HAVE_LOOPIF */
 }
netif_remove()
void netif_remove (struct netif * netif)
Remove a network interface from the list of lwIP netifs.
Parameters
netif the network interface to remove
Definition at line 241 of file netif.c.
References netif::flags, LWIP_DEBUGF, NETIF_DEBUG, NETIF_FLAG_IGMP, netif_is_up, netif_set_default(), netif_set_down(), netif::next, NULL, snmp_dec_iflist, and snmp_delete_ipaddridx_tree.
 {
   if (netif == NULL) {
     return;
   }
 #if LWIP_IGMP
   /* stop IGMP processing */
   if (netif->flags & NETIF_FLAG_IGMP) {
     igmp_stop(netif);
   }
 #endif /* LWIP_IGMP */
   if (netif_is_up(netif)) {
     /* set netif down before removing (call callback function) */
     netif_set_down(netif);
   }
   snmp_delete_ipaddridx_tree(netif);
   /*  is it the first netif? */
   if (netif_list == netif) {
     netif_list = netif->next;
   } else {
     /*  look for netif further down the list */
     struct netif * tmpNetif;
     for (tmpNetif = netif_list; tmpNetif != NULL; tmpNetif = tmpNetif->next) {
       if (tmpNetif->next == netif) {
         tmpNetif->next = netif->next;
         break;
       }
     }
     if (tmpNetif == NULL)
       return; /*  we didn't find any netif today */
   }
   snmp_dec_iflist();
   /* this netif is default? */
   if (netif_default == netif) {
     /* reset default netif */
     netif_set_default(NULL);
   }
   LWIP_DEBUGF( NETIF_DEBUG, ("netif_remove: removed netif\n") );
 }
netif_set_addr()
void netif_set_addr (struct netif * netif, ip_addr_t * ipaddr, ip_addr_t * netmask, ip_addr_t * gw)
Change IP address configuration for a network interface (including netmask and default gateway).
Parameters
netif the network interface to change
ipaddr the new IP address
netmask the new netmask
gw the new default gateway
Definition at line 227 of file netif.c.
References netif_set_gw(), netif_set_ipaddr(), and netif_set_netmask().
Referenced by netif_add().
 {
   netif_set_ipaddr(netif, ipaddr);
   netif_set_netmask(netif, netmask);
   netif_set_gw(netif, gw);
 }
netif_set_default()
void netif_set_default (struct netif * netif)
Set a network interface as the default network interface (used to output all packets for which no specific route is found)
Parameters
netif the default network interface
Definition at line 431 of file netif.c.
References LWIP_DEBUGF, netif::name, NETIF_DEBUG, NULL, snmp_delete_iprteidx_tree, and snmp_insert_iprteidx_tree.
Referenced by espconn_udp_sendto(), espconn_udp_sent(), and netif_remove().
 {
   if (netif == NULL) {
     /* remove default route */
     snmp_delete_iprteidx_tree(1, netif);
   } else {
     /* install default route */
     snmp_insert_iprteidx_tree(1, netif);
   }
   netif_default = netif;
   LWIP_DEBUGF(NETIF_DEBUG, ("netif: setting default interface %c%c\n",
            netif ? netif->name[0] : '\'', netif ? netif->name[1] : '\''));
 }
netif_set_down()
void netif_set_down (struct netif * netif)
Bring an interface down, disabling any traffic processing.
Note
: Enabling DHCP on a down interface will make it come up once configured.
See also
dhcp_start()
Definition at line 491 of file netif.c.
References netif::flags, NETIF_FLAG_ETHARP, NETIF_FLAG_UP, NETIF_STATUS_CALLBACK, and snmp_get_sysuptime.
Referenced by netif_remove().
 {
   if (netif->flags & NETIF_FLAG_UP) {
     netif->flags &= ~NETIF_FLAG_UP;
 #if LWIP_SNMP
     snmp_get_sysuptime(&netif->ts);
 #endif
 #if LWIP_ARP
     if (netif->flags & NETIF_FLAG_ETHARP) {
       etharp_cleanup_netif(netif);
     }
 #endif /* LWIP_ARP */
     NETIF_STATUS_CALLBACK(netif);
   }
 }
netif_set_gw()
void netif_set_gw (struct netif * netif, ip_addr_t * gw)
Change the default gateway for a network interface
Parameters
netif the network interface to change
gw the new default gateway
Note
call netif_set_addr() if you also want to change ip address and netmask
Definition at line 389 of file netif.c.
References netif::gw, ip4_addr1_16, ip4_addr2_16, ip4_addr3_16, ip4_addr4_16, ip_addr_set, LWIP_DBG_STATE, LWIP_DBG_TRACE, LWIP_DEBUGF, netif::name, NETIF_DEBUG, and U16_F.
Referenced by netif_set_addr().
 {
   ip_addr_set(&(netif->gw), gw);
   LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE | LWIP_DBG_STATE, ("netif: GW address of interface %c%c set to %"U16_F".%"U16_F".%"U16_F".%"U16_F"\n",
     netif->name[0], netif->name[1],
     ip4_addr1_16(&netif->gw),
     ip4_addr2_16(&netif->gw),
     ip4_addr3_16(&netif->gw),
     ip4_addr4_16(&netif->gw)));
 }
netif_set_ipaddr()
void netif_set_ipaddr (struct netif * netif, ip_addr_t * ipaddr)
Change the IP address of a network interface
Parameters
netif the network interface to change
ipaddr the new IP address
Note
call netif_set_addr() if you also want to change netmask and default gateway
Definition at line 324 of file netif.c.
References ip4_addr1_16, ip4_addr2_16, ip4_addr3_16, ip4_addr4_16, netif::ip_addr, ip_addr_cmp, ip_addr_isany, ip_addr_islinklocal, ip_addr_set, LWIP_AUTOIP, LWIP_DBG_STATE, LWIP_DBG_TRACE, LWIP_DEBUGF, netif::name, NETIF_DEBUG, NULL, snmp_delete_ipaddridx_tree, snmp_delete_iprteidx_tree, snmp_insert_ipaddridx_tree, snmp_insert_iprteidx_tree, and U16_F.
Referenced by netif_set_addr().
 {
   /* TODO: Handling of obsolete pcbs */
   /* See:  http://mail.gnu.org/archive/html/lwip-users/2003-03/msg00118.html */
 #if LWIP_TCP
   struct tcp_pcb *pcb;
   struct tcp_pcb_listen *lpcb;
   /* address is actually being changed? */
   if (ipaddr && (ip_addr_cmp(ipaddr, &(netif->ip_addr))) == 0) {
     /* extern struct tcp_pcb *tcp_active_pcbs; defined by tcp.h */
     LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_STATE, ("netif_set_ipaddr: netif address being changed\n"));
     pcb = tcp_active_pcbs;
     while (pcb != NULL) {
       /* PCB bound to current local interface address? */
       if (ip_addr_cmp(&(pcb->local_ip), &(netif->ip_addr))
 #if LWIP_AUTOIP
         /* connections to link-local addresses must persist (RFC3927 ch. 1.9) */
         && !ip_addr_islinklocal(&(pcb->local_ip))
 #endif /* LWIP_AUTOIP */
         ) {
         /* this connection must be aborted */
         struct tcp_pcb *next = pcb->next;
         LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_STATE, ("netif_set_ipaddr: aborting TCP pcb %p\n", (void *)pcb));
         tcp_abort(pcb);
         pcb = next;
       } else {
         pcb = pcb->next;
       }
     }
     for (lpcb = tcp_listen_pcbs.listen_pcbs; lpcb != NULL; lpcb = lpcb->next) {
       /* PCB bound to current local interface address? */
       if ((!(ip_addr_isany(&(lpcb->local_ip)))) &&
           (ip_addr_cmp(&(lpcb->local_ip), &(netif->ip_addr)))) {
         /* The PCB is listening to the old ipaddr and
          * is set to listen to the new one instead */
         ip_addr_set(&(lpcb->local_ip), ipaddr);
       }
     }
   }
 #endif
   snmp_delete_ipaddridx_tree(netif);
   snmp_delete_iprteidx_tree(0,netif);
   /* set new IP address to netif */
   ip_addr_set(&(netif->ip_addr), ipaddr);
   snmp_insert_ipaddridx_tree(netif);
   snmp_insert_iprteidx_tree(0,netif);
   LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE | LWIP_DBG_STATE, ("netif: IP address of interface %c%c set to %"U16_F".%"U16_F".%"U16_F".%"U16_F"\n",
     netif->name[0], netif->name[1],
     ip4_addr1_16(&netif->ip_addr),
     ip4_addr2_16(&netif->ip_addr),
     ip4_addr3_16(&netif->ip_addr),
     ip4_addr4_16(&netif->ip_addr)));
 }
netif_set_link_down()
void netif_set_link_down (struct netif * netif)
Called by a driver when its link goes down
Definition at line 562 of file netif.c.
References ERR_MEM, ERR_OK, netif::flags, ip_input(), pbuf::len, LINK_STATS_INC, LWIP_ASSERT, LWIP_LOOPBACK_MAX_PBUFS, LWIP_UNUSED_ARG, NETIF_FLAG_LINK_UP, NETIF_LINK_CALLBACK, netif_list, pbuf::next, netif::next, NULL, pbuf_alloc(), pbuf_clen(), pbuf_copy(), pbuf_free(), PBUF_LINK, PBUF_RAM, snmp_add_ifinoctets, snmp_add_ifoutoctets, snmp_inc_ifinucastpkts, snmp_inc_ifoutdiscards, snmp_inc_ifoutucastpkts, SYS_ARCH_DECL_PROTECT, SYS_ARCH_PROTECT, SYS_ARCH_UNPROTECT, tcpip_callback, and pbuf::tot_len.
 {
   if (netif->flags & NETIF_FLAG_LINK_UP) {
     netif->flags &= ~NETIF_FLAG_LINK_UP;
     NETIF_LINK_CALLBACK(netif);
   }
 }
netif_set_link_up()
void netif_set_link_up (struct netif * netif)
Called by a driver when its link goes up
Definition at line 523 of file netif.c.
References netif::flags, NETIF_FLAG_ETHARP, NETIF_FLAG_IGMP, NETIF_FLAG_LINK_UP, NETIF_FLAG_UP, and NETIF_LINK_CALLBACK.
 {
   if (!(netif->flags & NETIF_FLAG_LINK_UP)) {
     netif->flags |= NETIF_FLAG_LINK_UP;
 #if LWIP_DHCP
     if (netif->dhcp) {
       dhcp_network_changed(netif);
     }
 #endif /* LWIP_DHCP */
 #if LWIP_AUTOIP
     if (netif->autoip) {
       autoip_network_changed(netif);
     }
 #endif /* LWIP_AUTOIP */
     if (netif->flags & NETIF_FLAG_UP) {
 #if LWIP_ARP
       /* For Ethernet network interfaces, we would like to send a "gratuitous ARP" */
       if (netif->flags & NETIF_FLAG_ETHARP) {
         etharp_gratuitous(netif);
       }
 #endif /* LWIP_ARP */
 #if LWIP_IGMP
       /* resend IGMP memberships */
       if (netif->flags & NETIF_FLAG_IGMP) {
         igmp_report_groups( netif);
       }
 #endif /* LWIP_IGMP */
     }
     NETIF_LINK_CALLBACK(netif);
   }
 }
netif_set_netmask()
void netif_set_netmask (struct netif * netif, ip_addr_t * netmask)
Change the netmask of a network interface
Parameters
netif the network interface to change
netmask the new netmask
Note
call netif_set_addr() if you also want to change ip address and default gateway
Definition at line 410 of file netif.c.
References ip4_addr1_16, ip4_addr2_16, ip4_addr3_16, ip4_addr4_16, ip_addr_set, LWIP_DBG_STATE, LWIP_DBG_TRACE, LWIP_DEBUGF, netif::name, NETIF_DEBUG, netif::netmask, snmp_delete_iprteidx_tree, snmp_insert_iprteidx_tree, and U16_F.
Referenced by netif_set_addr().
 {
   snmp_delete_iprteidx_tree(0, netif);
   /* set new netmask to netif */
   ip_addr_set(&(netif->netmask), netmask);
   snmp_insert_iprteidx_tree(0, netif);
   LWIP_DEBUGF(NETIF_DEBUG | LWIP_DBG_TRACE | LWIP_DBG_STATE, ("netif: netmask of interface %c%c set to %"U16_F".%"U16_F".%"U16_F".%"U16_F"\n",
     netif->name[0], netif->name[1],
     ip4_addr1_16(&netif->netmask),
     ip4_addr2_16(&netif->netmask),
     ip4_addr3_16(&netif->netmask),
     ip4_addr4_16(&netif->netmask)));
 }
netif_set_up()
void netif_set_up (struct netif * netif)
Bring an interface up, available for processing traffic.
Note
: Enabling DHCP on a down interface will make it come up once configured.
See also
dhcp_start()
Definition at line 454 of file netif.c.
References netif::flags, NETIF_FLAG_ETHARP, NETIF_FLAG_IGMP, NETIF_FLAG_LINK_UP, NETIF_FLAG_UP, NETIF_STATUS_CALLBACK, and snmp_get_sysuptime.
Referenced by netif_init().
 {
   if (!(netif->flags & NETIF_FLAG_UP)) {
     netif->flags |= NETIF_FLAG_UP;
 #if LWIP_SNMP
     snmp_get_sysuptime(&netif->ts);
 #endif /* LWIP_SNMP */
     NETIF_STATUS_CALLBACK(netif);
     if (netif->flags & NETIF_FLAG_LINK_UP) {
 #if LWIP_ARP
       /* For Ethernet network interfaces, we would like to send a "gratuitous ARP" */
       if (netif->flags & (NETIF_FLAG_ETHARP)) {
         etharp_gratuitous(netif);
       }
 #endif /* LWIP_ARP */
 #if LWIP_IGMP
       /* resend IGMP memberships */
       if (netif->flags & NETIF_FLAG_IGMP) {
         igmp_report_groups( netif);
       }
 #endif /* LWIP_IGMP */
     }
   }
 }
Variable Documentation
netif_default
struct netif* netif_default
The default network interface.
Definition at line 76 of file netif.c.
Referenced by ip_route(), and ip_router().
netif_list
struct netif* netif_list
The list of network interfaces.
Definition at line 75 of file netif.c.
Referenced by ip_input(), ip_route(), ip_router(), netif_add(), netif_set_link_down(), patch_netif_ap(), and wifi_softap_ip_config().