MeterLogger: esp-open-lwip/include/lwip/pbuf.h File Reference
pbuf.h File Reference
#include "lwip/opt.h"
#include "lwip/err.h"
Data Structures
struct pbuf
Macros
#define LWIP_SUPPORT_CUSTOM_PBUF (IP_FRAG && !IP_FRAG_USES_STATIC_BUF && !LWIP_NETIF_TX_SINGLE_PBUF)
#define PBUF_TRANSPORT_HLEN 20
#define PBUF_IP_HLEN 20
#define PBUF_FLAG_PUSH 0x01U
#define PBUF_FLAG_IS_CUSTOM 0x02U
#define PBUF_FLAG_MCASTLOOP 0x04U
#define pbuf_init()
Enumerations
enum pbuf_layer { PBUF_TRANSPORT, PBUF_IP, PBUF_LINK, PBUF_RAW }
enum pbuf_type { PBUF_RAM, PBUF_ROM, PBUF_REF, PBUF_POOL }
Functions
struct pbuf * pbuf_alloc (pbuf_layer l, u16_t length, pbuf_type type) ICACHE_FLASH_ATTR
void pbuf_realloc (struct pbuf *p, u16_t size) ICACHE_FLASH_ATTR
u8_t pbuf_header (struct pbuf *p, s16_t header_size) ICACHE_FLASH_ATTR
void pbuf_ref (struct pbuf *p) ICACHE_FLASH_ATTR
u8_t pbuf_free (struct pbuf *p) ICACHE_FLASH_ATTR
u8_t pbuf_clen (struct pbuf *p) ICACHE_FLASH_ATTR
void pbuf_cat (struct pbuf *head, struct pbuf *tail) ICACHE_FLASH_ATTR
void pbuf_chain (struct pbuf *head, struct pbuf *tail) ICACHE_FLASH_ATTR
struct pbuf * pbuf_dechain (struct pbuf *p) ICACHE_FLASH_ATTR
err_t pbuf_copy (struct pbuf *p_to, struct pbuf *p_from) ICACHE_FLASH_ATTR
u16_t pbuf_copy_partial (struct pbuf *p, void *dataptr, u16_t len, u16_t offset) ICACHE_FLASH_ATTR
err_t pbuf_take (struct pbuf *buf, const void *dataptr, u16_t len) ICACHE_FLASH_ATTR
struct pbuf * pbuf_coalesce (struct pbuf *p, pbuf_layer layer) ICACHE_FLASH_ATTR
u8_t pbuf_get_at (struct pbuf *p, u16_t offset) ICACHE_FLASH_ATTR
u16_t pbuf_memcmp (struct pbuf *p, u16_t offset, const void *s2, u16_t n) ICACHE_FLASH_ATTR
u16_t pbuf_memfind (struct pbuf *p, const void *mem, u16_t mem_len, u16_t start_offset) ICACHE_FLASH_ATTR
u16_t pbuf_strstr (struct pbuf *p, const char *substr) ICACHE_FLASH_ATTR
Macro Definition Documentation
LWIP_SUPPORT_CUSTOM_PBUF
#define LWIP_SUPPORT_CUSTOM_PBUF (IP_FRAG && !IP_FRAG_USES_STATIC_BUF && !LWIP_NETIF_TX_SINGLE_PBUF)
Currently, the pbuf_custom code is only needed for one specific configuration of IP_FRAG
Definition at line 45 of file pbuf.h.
PBUF_FLAG_IS_CUSTOM
#define PBUF_FLAG_IS_CUSTOM 0x02U
indicates this is a custom pbuf: pbuf_free and pbuf_header handle such a a pbuf differently
Definition at line 72 of file pbuf.h.
Referenced by pbuf_alloc(), and pbuf_free().
PBUF_FLAG_MCASTLOOP
#define PBUF_FLAG_MCASTLOOP 0x04U
indicates this pbuf is UDP multicast to be looped back
Definition at line 74 of file pbuf.h.
Referenced by ip_output_if().
PBUF_FLAG_PUSH
#define PBUF_FLAG_PUSH 0x01U
indicates this packet's data should be immediately passed to the application
Definition at line 69 of file pbuf.h.
pbuf_init
#define pbuf_init ()
Definition at line 126 of file pbuf.h.
Referenced by lwip_init().
PBUF_IP_HLEN
#define PBUF_IP_HLEN 20
Definition at line 48 of file pbuf.h.
Referenced by pbuf_alloc().
PBUF_TRANSPORT_HLEN
#define PBUF_TRANSPORT_HLEN 20
Definition at line 47 of file pbuf.h.
Referenced by pbuf_alloc().
Enumeration Type Documentation
pbuf_layer
enum pbuf_layer
Enumerator
PBUF_TRANSPORT
PBUF_IP
PBUF_LINK
PBUF_RAW
Definition at line 50 of file pbuf.h.
              {
   PBUF_TRANSPORT,
   PBUF_IP,
   PBUF_LINK,
   PBUF_RAW
 } pbuf_layer;
pbuf_type
enum pbuf_type
Enumerator
PBUF_RAM
PBUF_ROM
PBUF_REF
PBUF_POOL
Definition at line 57 of file pbuf.h.
              {
   PBUF_RAM, /* pbuf data is stored in RAM */
   PBUF_ROM, /* pbuf data is stored in ROM */
   PBUF_REF, /* pbuf comes from the pbuf pool */
   PBUF_POOL, /* pbuf payload refers to RAM */
 #ifdef EBUF_LWIP
   PBUF_ESF_RX /* pbuf payload is from WLAN */
 #endif /* ESF_LWIP */
 } pbuf_type;
Function Documentation
pbuf_alloc()
struct pbuf* pbuf_alloc (pbuf_layer layer, u16_t length, pbuf_type type)
Allocates a pbuf of the given type (possibly a chain for PBUF_POOL type).
The actual memory allocated for the pbuf is determined by the layer at which the pbuf is allocated and the requested size (from the size parameter).
Parameters
layer flag to define header size
length size of the pbuf's payload
type this parameter decides how and where the pbuf should be allocated as follows:
PBUF_RAM: buffer memory for pbuf is allocated as one large chunk. This includes protocol headers as well.
PBUF_ROM: no buffer memory is allocated for the pbuf, even for protocol headers. Additional headers must be prepended by allocating another pbuf and chain in to the front of the ROM pbuf. It is assumed that the memory used is really similar to ROM in that it is immutable and will not be changed. Memory which is dynamic should generally not be attached to PBUF_ROM pbufs. Use PBUF_REF instead.
PBUF_REF: no buffer memory is allocated for the pbuf, even for protocol headers. It is assumed that the pbuf is only being used in a single thread. If the pbuf gets queued, then pbuf_take should be called to copy the buffer.
PBUF_POOL: the pbuf is allocated as a pbuf chain, with pbufs from the pbuf pool that is allocated during pbuf_init().
Returns
the allocated pbuf. If multiple pbufs where allocated, this is the first pbuf of a pbuf chain.
Definition at line 234 of file pbuf.c.
References EP_OFFSET, pbuf::flags, pbuf::len, LWIP_ASSERT, LWIP_DBG_LEVEL_SERIOUS, LWIP_DBG_LEVEL_WARNING, LWIP_DBG_TRACE, LWIP_DEBUGF, LWIP_MEM_ALIGN, LWIP_MEM_ALIGN_SIZE, LWIP_MIN, MEM_ALIGNMENT, mem_malloc(), memp_malloc(), pbuf::next, NULL, pbuf::payload, PBUF_DEBUG, PBUF_FLAG_IS_CUSTOM, pbuf_free(), PBUF_IP, PBUF_IP_HLEN, PBUF_LINK, PBUF_LINK_HLEN, PBUF_POOL, PBUF_POOL_BUFSIZE_ALIGNED, PBUF_POOL_IS_EMPTY, PBUF_RAM, PBUF_RAW, PBUF_REF, PBUF_ROM, PBUF_TRANSPORT, PBUF_TRANSPORT_HLEN, pbuf::ref, SIZEOF_STRUCT_PBUF, pbuf::tot_len, pbuf::type, and U16_F.
Referenced by espconn_udp_sendto(), espconn_udp_sent(), netif_set_link_down(), pbuf_coalesce(), send_ack(), send_nak(), and send_offer().
 {
   struct pbuf *p, *q, *r;
   u16_t offset;
   s32_t rem_len; /* remaining length */
   LWIP_DEBUGF(PBUF_DEBUG | LWIP_DBG_TRACE, ("pbuf_alloc(length=%"U16_F")\n", length));
   /* determine header offset */
   offset = 0;
   switch (layer) {
   case PBUF_TRANSPORT:
     /* add room for transport (often TCP) layer header */
     offset += PBUF_TRANSPORT_HLEN;
     /* FALLTHROUGH */
   case PBUF_IP:
     /* add room for IP layer header */
     offset += PBUF_IP_HLEN;
     /* FALLTHROUGH */
   case PBUF_LINK:
     /* add room for link layer header */
     offset += PBUF_LINK_HLEN;
 #ifdef PBUF_RSV_FOR_WLAN
     /*
      * 1. LINK_HLEN 14Byte will be remove in WLAN layer
      * 2. IEEE80211_HDR_MAX_LEN needs 40 bytes.
      * 3. encryption needs exra 4 bytes ahead of actual data payload, and require
      *     DAddr and SAddr to be 4-byte aligned.
      * 4. TRANSPORT and IP are all 20, 4 bytes aligned, nice...
      * 5. LCC add 6 bytes more, We don't consider WAPI yet...
      * 6. define LWIP_MEM_ALIGN to be 4 Byte aligned, pbuf struct is 16B, Only thing may be
      *     matter is ether_hdr is not 4B aligned.
      *
      * So, we need extra (40 + 4 - 14) = 30 and it's happen to be 4-Byte aligned
      *
      *    1. lwip
      *         | empty 30B    | eth_hdr (14B)  | payload ...|
      *              total: 44B ahead payload
      *    2. net80211
      *         | max 80211 hdr, 32B | ccmp/tkip iv (8B) | sec rsv(4B) | payload ...|
      *              total: 40B ahead sec_rsv and 44B ahead payload
      *
      */
     offset += EP_OFFSET; //remove LINK hdr in wlan
 #endif /* PBUF_RSV_FOR_WLAN */
     break;
   case PBUF_RAW:
 #ifdef PBUF_RSV_FOR_WLAN
       /*
        *   RAW pbuf suppose
        */
     offset += EP_OFFSET; //remove LINK hdr in wlan
 #endif /* PBUF_RAW */
     break;
   default:
     LWIP_ASSERT("pbuf_alloc: bad pbuf layer", 0);
     return NULL;
   }
   switch (type) {
   case PBUF_POOL:
     /* allocate head of pbuf chain into p */
     p = (struct pbuf *)memp_malloc(MEMP_PBUF_POOL);
     LWIP_DEBUGF(PBUF_DEBUG | LWIP_DBG_TRACE, ("pbuf_alloc: allocated pbuf %p\n", (void *)p));
     if (p == NULL) {
       PBUF_POOL_IS_EMPTY();
       return NULL;
     }
     p->type = type;
     p->next = NULL;
     /* make the payload pointer point 'offset' bytes into pbuf data memory */
     p->payload = LWIP_MEM_ALIGN((void *)((u8_t *)p + (SIZEOF_STRUCT_PBUF + offset)));
     LWIP_ASSERT("pbuf_alloc: pbuf p->payload properly aligned",
             ((mem_ptr_t)p->payload % MEM_ALIGNMENT) == 0);
     /* the total length of the pbuf chain is the requested size */
     p->tot_len = length;
     /* set the length of the first pbuf in the chain */
     p->len = LWIP_MIN(length, PBUF_POOL_BUFSIZE_ALIGNED - LWIP_MEM_ALIGN_SIZE(offset));
     LWIP_ASSERT("check p->payload + p->len does not overflow pbuf",
                 ((u8_t*)p->payload + p->len <=
                  (u8_t*)p + SIZEOF_STRUCT_PBUF + PBUF_POOL_BUFSIZE_ALIGNED));
     LWIP_ASSERT("PBUF_POOL_BUFSIZE must be bigger than MEM_ALIGNMENT",
       (PBUF_POOL_BUFSIZE_ALIGNED - LWIP_MEM_ALIGN_SIZE(offset)) > 0 );
     /* set reference count (needed here in case we fail) */
     p->ref = 1;
     /* now allocate the tail of the pbuf chain */
     /* remember first pbuf for linkage in next iteration */
     r = p;
     /* remaining length to be allocated */
     rem_len = length - p->len;
     /* any remaining pbufs to be allocated? */
     while (rem_len > 0) {
       q = (struct pbuf *)memp_malloc(MEMP_PBUF_POOL);
       if (q == NULL) {
         PBUF_POOL_IS_EMPTY();
         /* free chain so far allocated */
         pbuf_free(p);
         /* bail out unsuccesfully */
         return NULL;
       }
       q->type = type;
       q->flags = 0;
       q->next = NULL;
       /* make previous pbuf point to this pbuf */
       r->next = q;
       /* set total length of this pbuf and next in chain */
       LWIP_ASSERT("rem_len < max_u16_t", rem_len < 0xffff);
       q->tot_len = (u16_t)rem_len;
       /* this pbuf length is pool size, unless smaller sized tail */
       q->len = LWIP_MIN((u16_t)rem_len, PBUF_POOL_BUFSIZE_ALIGNED);
       q->payload = (void *)((u8_t *)q + SIZEOF_STRUCT_PBUF);
       LWIP_ASSERT("pbuf_alloc: pbuf q->payload properly aligned",
               ((mem_ptr_t)q->payload % MEM_ALIGNMENT) == 0);
       LWIP_ASSERT("check p->payload + p->len does not overflow pbuf",
                   ((u8_t*)p->payload + p->len <=
                    (u8_t*)p + SIZEOF_STRUCT_PBUF + PBUF_POOL_BUFSIZE_ALIGNED));
       q->ref = 1;
       /* calculate remaining length to be allocated */
       rem_len -= q->len;
       /* remember this pbuf for linkage in next iteration */
       r = q;
     }
     /* end of chain */
     /*r->next = NULL;*/
     break;
   case PBUF_RAM:
     /* If pbuf is to be allocated in RAM, allocate memory for it. */
     p = (struct pbuf*)mem_malloc(LWIP_MEM_ALIGN_SIZE(SIZEOF_STRUCT_PBUF + offset) + LWIP_MEM_ALIGN_SIZE(length));
     if (p == NULL) {
       return NULL;
     }
     /* Set up internal structure of the pbuf. */
     p->payload = LWIP_MEM_ALIGN((void *)((u8_t *)p + SIZEOF_STRUCT_PBUF + offset));
     p->len = p->tot_len = length;
     p->next = NULL;
     p->type = type;
     p->eb = NULL;
     LWIP_ASSERT("pbuf_alloc: pbuf->payload properly aligned",
            ((mem_ptr_t)p->payload % MEM_ALIGNMENT) == 0);
     break;
 #ifdef EBUF_LWIP
   case PBUF_ESF_RX:
 #endif /* ESF_LWIP */
   /* pbuf references existing (non-volatile static constant) ROM payload? */
   case PBUF_ROM:
   /* pbuf references existing (externally allocated) RAM payload? */
   case PBUF_REF:
     /* only allocate memory for the pbuf structure */
     p = (struct pbuf *)memp_malloc(MEMP_PBUF);
     if (p == NULL) {
       LWIP_DEBUGF(PBUF_DEBUG | LWIP_DBG_LEVEL_SERIOUS,
                   ("pbuf_alloc: Could not allocate MEMP_PBUF for PBUF_%s.\n",
                   (type == PBUF_ROM) ? "ROM" : "REF"));
       return NULL;
     }
     /* caller must set this field properly, afterwards */
     p->payload = NULL;
     p->len = p->tot_len = length;
     p->next = NULL;
     p->type = type;
     break;
   default:
     LWIP_ASSERT("pbuf_alloc: erroneous type", 0);
     return NULL;
   }
   /* set reference count */
   p->ref = 1;
   /* set flags */
   p->flags = 0;
   LWIP_DEBUGF(PBUF_DEBUG | LWIP_DBG_TRACE, ("pbuf_alloc(length=%"U16_F") == %p\n", length, (void *)p));
   return p;
 }
pbuf_cat()
void pbuf_cat (struct pbuf * h, struct pbuf * t)
Concatenate two pbufs (each may be a pbuf chain) and take over the caller's reference of the tail pbuf.
Note
The caller MAY NOT reference the tail pbuf afterwards. Use pbuf_chain() for that purpose.
See also
pbuf_chain()
Definition at line 823 of file pbuf.c.
References pbuf::len, LWIP_ASSERT, LWIP_ERROR, pbuf::next, NULL, and pbuf::tot_len.
Referenced by pbuf_chain().
 {
   struct pbuf *p;
   LWIP_ERROR("(h != NULL) && (t != NULL) (programmer violates API)",
              ((h != NULL) && (t != NULL)), return;);
   /* proceed to last pbuf of chain */
   for (p = h; p->next != NULL; p = p->next) {
     /* add total length of second chain to all totals of first chain */
     p->tot_len += t->tot_len;
   }
   /* { p is last pbuf of first h chain, p->next == NULL } */
   LWIP_ASSERT("p->tot_len == p->len (of last pbuf in chain)", p->tot_len == p->len);
   LWIP_ASSERT("p->next == NULL", p->next == NULL);
   /* add total length of second chain to last pbuf total of first chain */
   p->tot_len += t->tot_len;
   /* chain last pbuf of head (p) with first of tail (t) */
   p->next = t;
   /* p->next now references t, but the caller will drop its reference to t,
    * so netto there is no change to the reference count of t.
    */
 }
pbuf_chain()
void pbuf_chain (struct pbuf * h, struct pbuf * t)
Chain two pbufs (or pbuf chains) together.
The caller MUST call pbuf_free(t) once it has stopped using it. Use pbuf_cat() instead if you no longer use t.
Parameters
h head pbuf (chain)
t tail pbuf (chain)
Note
The pbufs MUST belong to the same packet.
MAY NOT be called on a packet queue.
The ->tot_len fields of all pbufs of the head chain are adjusted. The ->next field of the last pbuf of the head chain is adjusted. The ->ref field of the first pbuf of the tail chain is adjusted.
Definition at line 864 of file pbuf.c.
References LWIP_DBG_TRACE, LWIP_DEBUGF, pbuf_cat(), PBUF_DEBUG, and pbuf_ref().
 {
   pbuf_cat(h, t);
   /* t is now referenced by h */
   pbuf_ref(t);
   LWIP_DEBUGF(PBUF_DEBUG | LWIP_DBG_TRACE, ("pbuf_chain: %p references %p\n", (void *)h, (void *)t));
 }
pbuf_clen()
u8_t pbuf_clen (struct pbuf * p)
Count number of pbufs in a chain
Parameters
p first pbuf of chain
Returns
the number of pbufs in a chain
Definition at line 782 of file pbuf.c.
References pbuf::next, and NULL.
Referenced by netif_set_link_down().
 {
   u8_t len;
   len = 0;
   while (p != NULL) {
     ++len;
     p = p->next;
   }
   return len;
 }
pbuf_coalesce()
struct pbuf* pbuf_coalesce (struct pbuf * p, pbuf_layer layer)
Creates a single pbuf out of a queue of pbufs.
Remarks
: Either the source pbuf 'p' is freed by this function or the original pbuf 'p' is returned, therefore the caller has to check the result!
Parameters
p the source pbuf
layer pbuf_layer of the new pbuf
Returns
a new, single pbuf (p->next is NULL) or the old pbuf if allocation fails
Definition at line 1088 of file pbuf.c.
References ERR_ARG, ERR_OK, FOLD_U32T, pbuf::len, LWIP_ASSERT, pbuf::next, NULL, pbuf::payload, pbuf_alloc(), pbuf_copy(), pbuf_free(), PBUF_RAM, SWAP_BYTES_IN_WORD, and pbuf::tot_len.
 {
   struct pbuf *q;
   err_t err;
   if (p->next == NULL) {
     return p;
   }
   q = pbuf_alloc(layer, p->tot_len, PBUF_RAM);
   if (q == NULL) {
     /* @todo: what do we do now? */
     return p;
   }
   err = pbuf_copy(q, p);
   LWIP_ASSERT("pbuf_copy failed", err == ERR_OK);
   pbuf_free(p);
   return q;
 }
pbuf_copy()
err_t pbuf_copy (struct pbuf * p_to, struct pbuf * p_from)
Create PBUF_RAM copies of pbufs.
Used to queue packets on behalf of the lwIP stack, such as ARP based queueing.
Note
You MUST explicitly use p = pbuf_take(p);
Only one packet is copied, no packet queue!
Parameters
p_to pbuf destination of the copy
p_from pbuf source of the copy
Returns
ERR_OK if pbuf was copied ERR_ARG if one of the pbufs is NULL or p_to is not big enough to hold p_from
Definition at line 930 of file pbuf.c.
References ERR_ARG, ERR_OK, ERR_VAL, pbuf::len, LWIP_ASSERT, LWIP_DBG_TRACE, LWIP_DEBUGF, LWIP_ERROR, MEMCPY, NULL, and PBUF_DEBUG.
Referenced by espconn_udp_sendto(), espconn_udp_sent(), netif_set_link_down(), and pbuf_coalesce().
 {
   u16_t offset_to=0, offset_from=0, len;
   LWIP_DEBUGF(PBUF_DEBUG | LWIP_DBG_TRACE, ("pbuf_copy(%p, %p)\n",
     (void*)p_to, (void*)p_from));
   /* is the target big enough to hold the source? */
   LWIP_ERROR("pbuf_copy: target not big enough to hold source", ((p_to != NULL) &&
              (p_from != NULL) && (p_to->tot_len >= p_from->tot_len)), return ERR_ARG;);
   /* iterate through pbuf chain */
   do
   {
     LWIP_ASSERT("p_to != NULL", p_to != NULL);
     /* copy one part of the original chain */
     if ((p_to->len - offset_to) >= (p_from->len - offset_from)) {
       /* complete current p_from fits into current p_to */
       len = p_from->len - offset_from;
     } else {
       /* current p_from does not fit into current p_to */
       len = p_to->len - offset_to;
     }
     MEMCPY((u8_t*)p_to->payload + offset_to, (u8_t*)p_from->payload + offset_from, len);
     offset_to += len;
     offset_from += len;
     LWIP_ASSERT("offset_to <= p_to->len", offset_to <= p_to->len);
     if (offset_to == p_to->len) {
       /* on to next p_to (if any) */
       offset_to = 0;
       p_to = p_to->next;
     }
     LWIP_ASSERT("offset_from <= p_from->len", offset_from <= p_from->len);
     if (offset_from >= p_from->len) {
       /* on to next p_from (if any) */
       offset_from = 0;
       p_from = p_from->next;
     }
     if((p_from != NULL) && (p_from->len == p_from->tot_len)) {
       /* don't copy more than one packet! */
       LWIP_ERROR("pbuf_copy() does not allow packet queues!\n",
                  (p_from->next == NULL), return ERR_VAL;);
     }
     if((p_to != NULL) && (p_to->len == p_to->tot_len)) {
       /* don't copy more than one packet! */
       LWIP_ERROR("pbuf_copy() does not allow packet queues!\n",
                   (p_to->next == NULL), return ERR_VAL;);
     }
   } while (p_from);
   LWIP_DEBUGF(PBUF_DEBUG | LWIP_DBG_TRACE, ("pbuf_copy: end of chain reached.\n"));
   return ERR_OK;
 }
pbuf_copy_partial()
u16_t pbuf_copy_partial (struct pbuf * buf, void * dataptr, u16_t len, u16_t offset)
Copy (part of) the contents of a packet buffer to an application supplied buffer.
Parameters
buf the pbuf from which to copy data
dataptr the application supplied buffer
len length of data to copy (dataptr must be big enough). No more than buf->tot_len will be copied, irrespective of len
offset offset into the packet buffer from where to begin copying len bytes
Returns
the number of bytes copied, or 0 on failure
Definition at line 996 of file pbuf.c.
References pbuf::len, LWIP_ERROR, MEMCPY, pbuf::next, NULL, and pbuf::payload.
Referenced by espconn_client_recv(), espconn_server_recv(), and espconn_udp_recv().
 {
   struct pbuf *p;
   u16_t left;
   u16_t buf_copy_len;
   u16_t copied_total = 0;
   LWIP_ERROR("pbuf_copy_partial: invalid buf", (buf != NULL), return 0;);
   LWIP_ERROR("pbuf_copy_partial: invalid dataptr", (dataptr != NULL), return 0;);
   left = 0;
   if((buf == NULL) || (dataptr == NULL)) {
     return 0;
   }
   /* Note some systems use byte copy if dataptr or one of the pbuf payload pointers are unaligned. */
   for(p = buf; len != 0 && p != NULL; p = p->next) {
     if ((offset != 0) && (offset >= p->len)) {
       /* don't copy from this buffer -> on to the next */
       offset -= p->len;
     } else {
       /* copy from this buffer. maybe only partially. */
       buf_copy_len = p->len - offset;
       if (buf_copy_len > len)
           buf_copy_len = len;
       /* copy the necessary parts of the buffer */
       MEMCPY(&((char*)dataptr)[left], &((char*)p->payload)[offset], buf_copy_len);
       copied_total += buf_copy_len;
       left += buf_copy_len;
       len -= buf_copy_len;
       offset = 0;
     }
   }
   return copied_total;
 }
pbuf_dechain()
struct pbuf* pbuf_dechain (struct pbuf * p)
Dechains the first pbuf from its succeeding pbufs in the chain.
Makes p->tot_len field equal to p->len.
Parameters
p pbuf to dechain
Returns
remainder of the pbuf chain, or NULL if it was de-allocated.
Note
May not be called on a packet queue.
Definition at line 881 of file pbuf.c.
References pbuf::len, LWIP_ASSERT, LWIP_DBG_TRACE, LWIP_DEBUGF, pbuf::next, NULL, PBUF_DEBUG, pbuf_free(), and pbuf::tot_len.
 {
   struct pbuf *q;
   u8_t tail_gone = 1;
   /* tail */
   q = p->next;
   /* pbuf has successor in chain? */
   if (q != NULL) {
     /* assert tot_len invariant: (p->tot_len == p->len + (p->next? p->next->tot_len: 0) */
     LWIP_ASSERT("p->tot_len == p->len + q->tot_len", q->tot_len == p->tot_len - p->len);
     /* enforce invariant if assertion is disabled */
     q->tot_len = p->tot_len - p->len;
     /* decouple pbuf from remainder */
     p->next = NULL;
     /* total length of pbuf p is its own length only */
     p->tot_len = p->len;
     /* q is no longer referenced by p, free it */
     LWIP_DEBUGF(PBUF_DEBUG | LWIP_DBG_TRACE, ("pbuf_dechain: unreferencing %p\n", (void *)q));
     tail_gone = pbuf_free(q);
     if (tail_gone > 0) {
       LWIP_DEBUGF(PBUF_DEBUG | LWIP_DBG_TRACE,
                   ("pbuf_dechain: deallocated %p (as it is no longer referenced)\n", (void *)q));
     }
     /* return remaining tail or NULL if deallocated */
   }
   /* assert tot_len invariant: (p->tot_len == p->len + (p->next? p->next->tot_len: 0) */
   LWIP_ASSERT("p->tot_len == p->len", p->tot_len == p->len);
   return ((tail_gone > 0) ? NULL : q);
 }
pbuf_free()
u8_t pbuf_free (struct pbuf * p)
Dereference a pbuf chain or queue and deallocate any no-longer-used pbufs at the head of this chain or queue.
Decrements the pbuf reference count. If it reaches zero, the pbuf is deallocated.
For a pbuf chain, this is repeated for each pbuf in the chain, up to the first pbuf which has a non-zero reference count after decrementing. So, when all reference counts are one, the whole chain is free'd.
Parameters
p The pbuf (chain) to be dereferenced.
Returns
the number of pbufs that were de-allocated from the head of the chain.
Note
MUST NOT be called on a packet queue (Not verified to work yet).
the reference counter of a pbuf equals the number of pointers that refer to the pbuf (or into the pbuf).
Definition at line 685 of file pbuf.c.
References LWIP_ASSERT, LWIP_DBG_LEVEL_SERIOUS, LWIP_DBG_TRACE, LWIP_DEBUGF, mem_free(), memp_free(), pbuf::next, NULL, PBUF_DEBUG, PBUF_FLAG_IS_CUSTOM, PBUF_POOL, PBUF_RAM, PBUF_REF, PBUF_ROM, PERF_START, PERF_STOP, pbuf::ref, SYS_ARCH_DECL_PROTECT, SYS_ARCH_PROTECT, SYS_ARCH_UNPROTECT, pbuf::type, and U16_F.
Referenced by espconn_client_recv(), espconn_server_recv(), espconn_udp_recv(), espconn_udp_sendto(), espconn_udp_sent(), handle_dhcp(), ip_input(), my_input_ap(), netif_set_link_down(), pbuf_alloc(), pbuf_coalesce(), pbuf_dechain(), pbuf_free_int(), pbuf_realloc(), send_ack(), send_nak(), and send_offer().
 {
   u16_t type;
   struct pbuf *q;
   u8_t count;
   if (p == NULL) {
     LWIP_ASSERT("p != NULL", p != NULL);
     /* if assertions are disabled, proceed with debug output */
     LWIP_DEBUGF(PBUF_DEBUG | LWIP_DBG_LEVEL_SERIOUS,
       ("pbuf_free(p == NULL) was called.\n"));
     return 0;
   }
   LWIP_DEBUGF(PBUF_DEBUG | LWIP_DBG_TRACE, ("pbuf_free(%p)\n", (void *)p));
   PERF_START;
   LWIP_ASSERT("pbuf_free: sane type",
     p->type == PBUF_RAM || p->type == PBUF_ROM ||
     p->type == PBUF_REF || p->type == PBUF_POOL
 #ifdef EBUF_LWIP
     || p->type == PBUF_ESF_RX
 #endif  //EBUF_LWIP
   );
   count = 0;
   /* de-allocate all consecutive pbufs from the head of the chain that
    * obtain a zero reference count after decrementing*/
   while (p != NULL) {
     u16_t ref;
     SYS_ARCH_DECL_PROTECT(old_level);
     /* Since decrementing ref cannot be guaranteed to be a single machine operation
      * we must protect it. We put the new ref into a local variable to prevent
      * further protection. */
     SYS_ARCH_PROTECT(old_level);
     /* all pbufs in a chain are referenced at least once */
     LWIP_ASSERT("pbuf_free: p->ref > 0", p->ref > 0);
     /* decrease reference count (number of pointers to pbuf) */
     ref = --(p->ref);
     SYS_ARCH_UNPROTECT(old_level);
     /* this pbuf is no longer referenced to? */
     if (ref == 0) {
       /* remember next pbuf in chain for next iteration */
       q = p->next;
       LWIP_DEBUGF( PBUF_DEBUG | LWIP_DBG_TRACE, ("pbuf_free: deallocating %p\n", (void *)p));
       type = p->type;
 #if LWIP_SUPPORT_CUSTOM_PBUF
       /* is this a custom pbuf? */
       if ((p->flags & PBUF_FLAG_IS_CUSTOM) != 0) {
         struct pbuf_custom *pc = (struct pbuf_custom*)p;
         LWIP_ASSERT("pc->custom_free_function != NULL", pc->custom_free_function != NULL);
         pc->custom_free_function(p);
       } else
 #endif /* LWIP_SUPPORT_CUSTOM_PBUF */
       {
       /* is this a pbuf from the pool? */
       if (type == PBUF_POOL) {
         memp_free(MEMP_PBUF_POOL, p);
       /* is this a ROM or RAM referencing pbuf? */
       } else if (type == PBUF_ROM || type == PBUF_REF
 #ifdef EBUF_LWIP
               || type == PBUF_ESF_RX
 #endif //EBUF_LWIP
       ) {
 #ifdef EBUF_LWIP
         system_pp_recycle_rx_pkt(p->eb);
 #endif //EBUF_LWIP
         memp_free(MEMP_PBUF, p);
       /* type == PBUF_RAM */
       } else {
         mem_free(p);
       }
       }
       count++;
       /* proceed to next pbuf */
       p = q;
     /* p->ref > 0, this pbuf is still referenced to */
     /* (and so the remaining pbufs in chain as well) */
     } else {
       LWIP_DEBUGF( PBUF_DEBUG | LWIP_DBG_TRACE, ("pbuf_free: %p has ref %"U16_F", ending here.\n", (void *)p, ref));
       /* stop walking through the chain */
       p = NULL;
     }
   }
   PERF_STOP("pbuf_free");
   /* return number of de-allocated pbufs */
   return count;
 }
pbuf_get_at()
u8_t pbuf_get_at (struct pbuf * p, u16_t offset)
Get one byte from the specified position in a pbuf WARNING: returns zero for offset >= p->tot_len
Parameters
p pbuf to parse
offset offset into p of the byte to return
Returns
byte at an offset into p OR ZERO IF 'offset' >= p->tot_len
Definition at line 1155 of file pbuf.c.
References pbuf::len, pbuf::next, NULL, and pbuf::payload.
Referenced by pbuf_memcmp().
 {
   u16_t copy_from = offset;
   struct pbuf* q = p;
   /* get the correct pbuf */
   while ((q != NULL) && (q->len <= copy_from)) {
     copy_from -= q->len;
     q = q->next;
   }
   /* return requested data if pbuf is OK */
   if ((q != NULL) && (q->len > copy_from)) {
     return ((u8_t*)q->payload)[copy_from];
   }
   return 0;
 }
pbuf_header()
u8_t pbuf_header (struct pbuf * p, s16_t header_size_increment)
Adjusts the payload pointer to hide or reveal headers in the payload.
Adjusts the ->payload pointer so that space for a header (dis)appears in the pbuf payload.
The ->payload, ->tot_len and ->len fields are adjusted.
Parameters
p pbuf to change the header size.
header_size_increment Number of bytes to increment header size which increases the size of the pbuf. New space is on the front. (Using a negative value decreases the header size.) If hdr_size_inc is 0, this function does nothing and returns succesful.
PBUF_ROM and PBUF_REF type buffers cannot have their sizes increased, so the call will fail. A check is made that the increase in header size does not move the payload pointer in front of the start of the buffer.
Returns
non-zero on failure, zero on success.
Definition at line 573 of file pbuf.c.
References EP_OFFSET, pbuf::len, LWIP_ASSERT, LWIP_DBG_LEVEL_SERIOUS, LWIP_DBG_TRACE, LWIP_DEBUGF, LWIP_ERROR, NULL, pbuf::payload, PBUF_DEBUG, PBUF_POOL, PBUF_RAM, PBUF_REF, PBUF_ROM, S16_F, SIZEOF_STRUCT_PBUF, pbuf::tot_len, and pbuf::type.
Referenced by ip_output_if().
 {
   u16_t type;
   void *payload;
   u16_t increment_magnitude;
   LWIP_ASSERT("p != NULL", p != NULL);
   if ((header_size_increment == 0) || (p == NULL)) {
     return 0;
   }
   if (header_size_increment < 0){
     increment_magnitude = -header_size_increment;
     /* Check that we aren't going to move off the end of the pbuf */
     LWIP_ERROR("increment_magnitude <= p->len", (increment_magnitude <= p->len), return 1;);
   } else {
     increment_magnitude = header_size_increment;
 #if 0
     /* Can't assert these as some callers speculatively call
          pbuf_header() to see if it's OK.  Will return 1 below instead. */
     /* Check that we've got the correct type of pbuf to work with */
     LWIP_ASSERT("p->type == PBUF_RAM || p->type == PBUF_POOL",
                 p->type == PBUF_RAM || p->type == PBUF_POOL);
     /* Check that we aren't going to move off the beginning of the pbuf */
     LWIP_ASSERT("p->payload - increment_magnitude >= p + SIZEOF_STRUCT_PBUF",
                 (u8_t *)p->payload - increment_magnitude >= (u8_t *)p + SIZEOF_STRUCT_PBUF);
 #endif
   }
   type = p->type;
   /* remember current payload pointer */
   payload = p->payload;
   /* pbuf types containing payloads? */
   if (type == PBUF_RAM || type == PBUF_POOL) {
     /* set new payload pointer */
     p->payload = (u8_t *)p->payload - header_size_increment;
     /* boundary check fails? */
     if ((u8_t *)p->payload < (u8_t *)p + SIZEOF_STRUCT_PBUF + EP_OFFSET) {
       LWIP_DEBUGF( PBUF_DEBUG | LWIP_DBG_LEVEL_SERIOUS,
         ("pbuf_header: failed as %p < %p (not enough space for new header size)\n",
         (void *)p->payload, (void *)(p + 1)));
       /* restore old payload pointer */
       p->payload = payload;
       /* bail out unsuccesfully */
       return 1;
     }
   /* pbuf types refering to external payloads? */
   } else if (type == PBUF_REF || type == PBUF_ROM) {
     /* hide a header in the payload? */
     if ((header_size_increment < 0) && (increment_magnitude <= p->len)) {
       /* increase payload pointer */
       p->payload = (u8_t *)p->payload - header_size_increment;
     } else {
       /* cannot expand payload to front (yet!)
        * bail out unsuccesfully */
       if (type == PBUF_REF) {
           /* increase payload pointer */
         p->payload = (u8_t *)p->payload - header_size_increment;
       } else {
         return 1;
       }
     }
   } else {
     /* Unknown type */
     LWIP_ASSERT("bad pbuf type", 0);
     return 1;
   }
   /* modify pbuf length fields */
   p->len += header_size_increment;
   p->tot_len += header_size_increment;
   LWIP_DEBUGF(PBUF_DEBUG | LWIP_DBG_TRACE, ("pbuf_header: old %p new %p (%"S16_F")\n",
     (void *)payload, (void *)p->payload, header_size_increment));
   return 0;
 }
pbuf_memcmp()
u16_t pbuf_memcmp (struct pbuf * p, u16_t offset, const void * s2, u16_t n)
Compare pbuf contents at specified offset with memory s2, both of length n
Parameters
p pbuf to compare
offset offset into p at wich to start comparing
s2 buffer to compare
n length of buffer to compare
Returns
zero if equal, nonzero otherwise (0xffff if p is too short, diffoffset+1 otherwise)
Definition at line 1182 of file pbuf.c.
References pbuf::len, pbuf::next, NULL, and pbuf_get_at().
Referenced by pbuf_memfind().
 {
   u16_t start = offset;
   struct pbuf* q = p;
   /* get the correct pbuf */
   while ((q != NULL) && (q->len <= start)) {
     start -= q->len;
     q = q->next;
   }
   /* return requested data if pbuf is OK */
   if ((q != NULL) && (q->len > start)) {
     u16_t i;
     for(i = 0; i < n; i++) {
       u8_t a = pbuf_get_at(q, start + i);
       u8_t b = ((u8_t*)s2)[i];
       if (a != b) {
         return i+1;
       }
     }
     return 0;
   }
   return 0xffff;
 }
pbuf_memfind()
u16_t pbuf_memfind (struct pbuf * p, const void * mem, u16_t mem_len, u16_t start_offset)
Find occurrence of mem (with length mem_len) in pbuf p, starting at offset start_offset.
Parameters
p pbuf to search, maximum length is 0xFFFE since 0xFFFF is used as return value 'not found'
mem search for the contents of this buffer
mem_len length of 'mem'
start_offset offset into p at which to start searching
Returns
0xFFFF if substr was not found in p or the index where it was found
Definition at line 1218 of file pbuf.c.
References pbuf_memcmp(), and pbuf::tot_len.
Referenced by pbuf_strstr().
 {
   u16_t i;
   u16_t max = p->tot_len - mem_len;
   if (p->tot_len >= mem_len + start_offset) {
     for(i = start_offset; i <= max; ) {
       u16_t plus = pbuf_memcmp(p, i, mem, mem_len);
       if (plus == 0) {
         return i;
       } else {
         i += plus;
       }
     }
   }
   return 0xFFFF;
 }
pbuf_realloc()
void pbuf_realloc (struct pbuf * p, u16_t new_len)
Shrink a pbuf chain to a desired length.
Parameters
p pbuf to shrink.
new_len desired new length of pbuf chain
Depending on the desired length, the first few pbufs in a chain might be skipped and left unchanged. The new last pbuf in the chain will be resized, and any remaining pbufs will be freed.
Note
If the pbuf is ROM/REF, only the ->tot_len and ->len fields are adjusted.
May not be called on a packet queue.
Despite its name, pbuf_realloc cannot grow the size of a pbuf (chain).
Definition at line 492 of file pbuf.c.
References pbuf::len, LWIP_ASSERT, mem_trim(), pbuf::next, NULL, pbuf::payload, pbuf_free(), PBUF_POOL, PBUF_RAM, PBUF_REF, PBUF_ROM, pbuf::tot_len, and pbuf::type.
Referenced by ip_input().
 {
   struct pbuf *q;
   u16_t rem_len; /* remaining length */
   s32_t grow;
   LWIP_ASSERT("pbuf_realloc: p != NULL", p != NULL);
   LWIP_ASSERT("pbuf_realloc: sane p->type", p->type == PBUF_POOL ||
               p->type == PBUF_ROM ||
               p->type == PBUF_RAM ||
               p->type == PBUF_REF);
   /* desired length larger than current length? */
   if (new_len >= p->tot_len) {
     /* enlarging not yet supported */
     return;
   }
   /* the pbuf chain grows by (new_len - p->tot_len) bytes
    * (which may be negative in case of shrinking) */
   grow = new_len - p->tot_len;
   /* first, step over any pbufs that should remain in the chain */
   rem_len = new_len;
   q = p;
   /* should this pbuf be kept? */
   while (rem_len > q->len) {
     /* decrease remaining length by pbuf length */
     rem_len -= q->len;
     /* decrease total length indicator */
     LWIP_ASSERT("grow < max_u16_t", grow < 0xffff);
     q->tot_len += (u16_t)grow;
     /* proceed to next pbuf in chain */
     q = q->next;
     LWIP_ASSERT("pbuf_realloc: q != NULL", q != NULL);
   }
   /* we have now reached the new last pbuf (in q) */
   /* rem_len == desired length for pbuf q */
   /* shrink allocated memory for PBUF_RAM */
   /* (other types merely adjust their length fields */
   if ((q->type == PBUF_RAM) && (rem_len != q->len)) {
     /* reallocate and adjust the length of the pbuf that will be split */
     q = (struct pbuf *)mem_trim(q, (u16_t)((u8_t *)q->payload - (u8_t *)q) + rem_len);
     LWIP_ASSERT("mem_trim returned q == NULL", q != NULL);
   }
   /* adjust length fields for new last pbuf */
   q->len = rem_len;
   q->tot_len = q->len;
   /* any remaining pbufs in chain? */
   if (q->next != NULL) {
     /* free remaining pbufs in chain */
     pbuf_free(q->next);
   }
   /* q is last packet in chain */
   q->next = NULL;
 }
pbuf_ref()
void pbuf_ref (struct pbuf * p)
Increment the reference count of the pbuf.
Parameters
p pbuf to increase reference counter of
Definition at line 801 of file pbuf.c.
References NULL, pbuf::ref, SYS_ARCH_DECL_PROTECT, SYS_ARCH_PROTECT, and SYS_ARCH_UNPROTECT.
Referenced by pbuf_chain().
 {
   SYS_ARCH_DECL_PROTECT(old_level);
   /* pbuf given? */
   if (p != NULL) {
     SYS_ARCH_PROTECT(old_level);
     ++(p->ref);
     SYS_ARCH_UNPROTECT(old_level);
   }
 }
pbuf_strstr()
u16_t pbuf_strstr (struct pbuf * p, const char * substr)
Find occurrence of substr with length substr_len in pbuf p, start at offset start_offset WARNING: in contrast to strstr(), this one does not stop at the first \0 in the pbuf/source string!
Parameters
p pbuf to search, maximum length is 0xFFFE since 0xFFFF is used as return value 'not found'
substr string to search for in p, maximum length is 0xFFFE
Returns
0xFFFF if substr was not found in p or the index where it was found
Definition at line 1246 of file pbuf.c.
References NULL, os_strlen, pbuf_memfind(), and pbuf::tot_len.
 {
   size_t substr_len;
   if ((substr == NULL) || (substr[0] == 0) || (p->tot_len == 0xFFFF)) {
     return 0xFFFF;
   }
   substr_len = os_strlen(substr);
   if (substr_len >= 0xFFFF) {
     return 0xFFFF;
   }
   return pbuf_memfind(p, substr, (u16_t)substr_len, 0);
 }
pbuf_take()
err_t pbuf_take (struct pbuf * buf, const void * dataptr, u16_t len)
Copy application supplied data into a pbuf. This function can only be used to copy the equivalent of buf->tot_len data.
Parameters
buf pbuf to fill with data
dataptr application supplied data buffer
len length of the application supplied data buffer
Returns
ERR_OK if successful, ERR_MEM if the pbuf is not big enough
Definition at line 1044 of file pbuf.c.
References ERR_ARG, ERR_OK, pbuf::len, LWIP_ASSERT, LWIP_ERROR, MEMCPY, pbuf::next, NULL, pbuf::payload, and pbuf::tot_len.
 {
   struct pbuf *p;
   u16_t buf_copy_len;
   u16_t total_copy_len = len;
   u16_t copied_total = 0;
   LWIP_ERROR("pbuf_take: invalid buf", (buf != NULL), return 0;);
   LWIP_ERROR("pbuf_take: invalid dataptr", (dataptr != NULL), return 0;);
   if ((buf == NULL) || (dataptr == NULL) || (buf->tot_len < len)) {
     return ERR_ARG;
   }
   /* Note some systems use byte copy if dataptr or one of the pbuf payload pointers are unaligned. */
   for(p = buf; total_copy_len != 0; p = p->next) {
     LWIP_ASSERT("pbuf_take: invalid pbuf", p != NULL);
     buf_copy_len = total_copy_len;
     if (buf_copy_len > p->len) {
       /* this pbuf cannot hold all remaining data */
       buf_copy_len = p->len;
     }
     /* copy the necessary parts of the buffer */
     MEMCPY(p->payload, &((char*)dataptr)[copied_total], buf_copy_len);
     total_copy_len -= buf_copy_len;
     copied_total += buf_copy_len;
   }
   LWIP_ASSERT("did not copy all data", total_copy_len == 0 && copied_total == len);
   return ERR_OK;
 }