MeterLogger: mqtt/proto.c File Reference
proto.c File Reference
#include "proto.h"
#include "ringbuf.h"
Functions
I8 ICACHE_FLASH_ATTR PROTO_Init (PROTO_PARSER *parser, PROTO_PARSE_CALLBACK *completeCallback, U8 *buf, U16 bufSize)
I8 ICACHE_FLASH_ATTR PROTO_ParseByte (PROTO_PARSER *parser, U8 value)
I8 ICACHE_FLASH_ATTR PROTO_Parse (PROTO_PARSER *parser, U8 *buf, U16 len)
I16 ICACHE_FLASH_ATTR PROTO_ParseRb (RINGBUF *rb, U8 *bufOut, U16 *len, U16 maxBufLen)
I16 ICACHE_FLASH_ATTR PROTO_Add (U8 *buf, const U8 *packet, I16 bufSize)
I16 ICACHE_FLASH_ATTR PROTO_AddRb (RINGBUF *rb, const U8 *packet, I16 len)
Function Documentation
PROTO_Add()
I16 ICACHE_FLASH_ATTR PROTO_Add (U8 * buf, const U8 * packet, I16 bufSize)
Definition at line 70 of file proto.c.
PROTO_AddRb()
I16 ICACHE_FLASH_ATTR PROTO_AddRb (RINGBUF * rb, const U8 * packet, I16 len)
Definition at line 106 of file proto.c.
References RINGBUF_Put().
Referenced by QUEUE_Puts().
PROTO_Init()
I8 ICACHE_FLASH_ATTR PROTO_Init (PROTO_PARSER * parser, PROTO_PARSE_CALLBACK * completeCallback, U8 * buf, U16 bufSize)
Definition at line 3 of file proto.c.
References PROTO_PARSER::buf, PROTO_PARSER::bufSize, PROTO_PARSER::callback, PROTO_PARSER::dataLen, and PROTO_PARSER::isEsc.
Referenced by PROTO_ParseRb().
PROTO_Parse()
I8 ICACHE_FLASH_ATTR PROTO_Parse (PROTO_PARSER * parser, U8 * buf, U16 len)
Definition at line 49 of file proto.c.
References PROTO_ParseByte().
PROTO_ParseByte()
I8 ICACHE_FLASH_ATTR PROTO_ParseByte (PROTO_PARSER * parser, U8 value)
Definition at line 13 of file proto.c.
References PROTO_PARSER::buf, PROTO_PARSER::bufSize, PROTO_PARSER::callback, PROTO_PARSER::dataLen, PROTO_PARSER::isBegin, PROTO_PARSER::isEsc, and NULL.
Referenced by PROTO_Parse(), and PROTO_ParseRb().
PROTO_ParseRb()
I16 ICACHE_FLASH_ATTR PROTO_ParseRb (RINGBUF * rb, U8 * bufOut, U16 * len, U16 maxBufLen)
Definition at line 56 of file proto.c.
References PROTO_PARSER::dataLen, NULL, PROTO_Init(), PROTO_ParseByte(), and RINGBUF_Get().
Referenced by QUEUE_Gets().