MeterLogger: mqtt/include/proto.h File Reference
proto.h File Reference
#include <stdlib.h>
#include "typedef.h"
#include "ringbuf.h"
Data Structures
struct PROTO_PARSER
Typedefs
typedef void() PROTO_PARSE_CALLBACK()
Functions
I8 ICACHE_FLASH_ATTR PROTO_Init (PROTO_PARSER *parser, PROTO_PARSE_CALLBACK *completeCallback, U8 *buf, U16 bufSize)
I8 ICACHE_FLASH_ATTR PROTO_Parse (PROTO_PARSER *parser, U8 *buf, U16 len)
I16 ICACHE_FLASH_ATTR PROTO_Add (U8 *buf, const U8 *packet, I16 bufSize)
I16 ICACHE_FLASH_ATTR PROTO_AddRb (RINGBUF *rb, const U8 *packet, I16 len)
I8 ICACHE_FLASH_ATTR PROTO_ParseByte (PROTO_PARSER *parser, U8 value)
I16 ICACHE_FLASH_ATTR PROTO_ParseRb (RINGBUF *rb, U8 *bufOut, U16 *len, U16 maxBufLen)
Typedef Documentation
PROTO_PARSE_CALLBACK
typedef void() PROTO_PARSE_CALLBACK()
Definition at line 14 of file proto.h.
Function Documentation
PROTO_Add()
I16 ICACHE_FLASH_ATTR PROTO_Add (U8 * buf, const U8 * packet, I16 bufSize)
Definition at line 70 of file proto.c.
 {
     U16 i = 2;
     U16 len = *(U16*) packet;
     if (bufSize < 1) return -1;
     *buf++ = 0x7E;
     bufSize--;
     while (len--) {
         switch (*packet) {
         case 0x7D:
         case 0x7E:
         case 0x7F:
             if (bufSize < 2) return -1;
             *buf++ = 0x7D;
             *buf++ = *packet++ ^ 0x20;
             i += 2;
             bufSize -= 2;
             break;
         default:
             if (bufSize < 1) return -1;
             *buf++ = *packet++;
             i++;
             bufSize--;
             break;
         }
     }
     if (bufSize < 1) return -1;
     *buf++ = 0x7F;
     return i;
 }
PROTO_AddRb()
I16 ICACHE_FLASH_ATTR PROTO_AddRb (RINGBUF * rb, const U8 * packet, I16 len)
Definition at line 106 of file proto.c.
References RINGBUF_Put().
Referenced by QUEUE_Puts().
 {
     U16 i = 2;
     if(RINGBUF_Put(rb, 0x7E) == -1) return -1;
     while (len--) {
         switch (*packet) {
         case 0x7D:
         case 0x7E:
         case 0x7F:
             if(RINGBUF_Put(rb, 0x7D) == -1) return -1;
             if(RINGBUF_Put(rb, *packet++ ^ 0x20) == -1) return -1;
             i += 2;
             break;
         default:
             if(RINGBUF_Put(rb, *packet++) == -1) return -1;
             i++;
             break;
         }
     }
     if(RINGBUF_Put(rb, 0x7F) == -1) return -1;
     return i;
 }
PROTO_Init()
I8 ICACHE_FLASH_ATTR PROTO_Init (PROTO_PARSER * parser, PROTO_PARSE_CALLBACK * completeCallback, U8 * buf, U16 bufSize)
Definition at line 3 of file proto.c.
References PROTO_PARSER::buf, PROTO_PARSER::bufSize, PROTO_PARSER::callback, PROTO_PARSER::dataLen, and PROTO_PARSER::isEsc.
Referenced by PROTO_ParseRb().
 {
     parser->buf = buf;
     parser->bufSize = bufSize;
     parser->dataLen = 0;
     parser->callback = completeCallback;
     parser->isEsc = 0;
     return 0;
 }
PROTO_Parse()
I8 ICACHE_FLASH_ATTR PROTO_Parse (PROTO_PARSER * parser, U8 * buf, U16 len)
Definition at line 49 of file proto.c.
References PROTO_ParseByte().
 {
     while(len--)
         PROTO_ParseByte(parser, *buf++);
     return 0;
 }
PROTO_ParseByte()
I8 ICACHE_FLASH_ATTR PROTO_ParseByte (PROTO_PARSER * parser, U8 value)
Definition at line 13 of file proto.c.
References PROTO_PARSER::buf, PROTO_PARSER::bufSize, PROTO_PARSER::callback, PROTO_PARSER::dataLen, PROTO_PARSER::isBegin, PROTO_PARSER::isEsc, and NULL.
Referenced by PROTO_Parse(), and PROTO_ParseRb().
 {
     switch(value){
         case 0x7D:
             parser->isEsc = 1;
             break;
         case 0x7E:
             parser->dataLen = 0;
             parser->isEsc = 0;
             parser->isBegin = 1;
             break;
         case 0x7F:
             if (parser->callback != NULL)
                 parser->callback();
             parser->isBegin = 0;
             return 0;
             break;
         default:
             if(parser->isBegin == 0) break;
             if(parser->isEsc){
                 value ^= 0x20;
                 parser->isEsc = 0;
             }
             if(parser->dataLen < parser->bufSize)
                 parser->buf[parser->dataLen++] = value;
             break;
     }
     return -1;
 }
PROTO_ParseRb()
I16 ICACHE_FLASH_ATTR PROTO_ParseRb (RINGBUF * rb, U8 * bufOut, U16 * len, U16 maxBufLen)
Definition at line 56 of file proto.c.
References PROTO_PARSER::dataLen, NULL, PROTO_Init(), PROTO_ParseByte(), and RINGBUF_Get().
Referenced by QUEUE_Gets().
 {
     U8 c;
     PROTO_PARSER proto;
     PROTO_Init(&proto, NULL, bufOut, maxBufLen);
     while(RINGBUF_Get(rb, &c) == 0){
         if(PROTO_ParseByte(&proto, c) == 0){
             *len = proto.dataLen;
             return 0;
         }
     }
     return -1;
 }