MeterLogger: mqtt/queue.c File Reference
queue.c File Reference
#include "queue.h"
#include "proto.h"
#include <esp8266.h>
Functions
void ICACHE_FLASH_ATTR QUEUE_Init (QUEUE *queue, int bufferSize)
int32_t ICACHE_FLASH_ATTR QUEUE_Puts (QUEUE *queue, uint8_t *buffer, uint16_t len)
int32_t ICACHE_FLASH_ATTR QUEUE_Gets (QUEUE *queue, uint8_t *buffer, uint16_t *len, uint16_t maxLen)
BOOL ICACHE_FLASH_ATTR QUEUE_IsEmpty (QUEUE *queue)
Variables
uint8_t * last_rb_p_r
uint8_t * last_rb_p_w
uint32_t last_fill_cnt
Function Documentation
QUEUE_Gets()
int32_t ICACHE_FLASH_ATTR QUEUE_Gets (QUEUE * queue, uint8_t * buffer, uint16_t * len, uint16_t maxLen)
Definition at line 61 of file queue.c.
References PROTO_ParseRb(), and QUEUE::rb.
Referenced by MQTT_Ping(), MQTT_Publish(), MQTT_Subscribe(), MQTT_Task(), and MQTT_UnSubscribe().
 {
     return PROTO_ParseRb(&queue->rb, buffer, len, maxLen);
 }
QUEUE_Init()
void ICACHE_FLASH_ATTR QUEUE_Init (QUEUE * queue, int bufferSize)
Definition at line 39 of file queue.c.
References QUEUE::buf, os_zalloc, QUEUE::rb, and RINGBUF_Init().
Referenced by MQTT_InitClient().
 {
     queue->buf = (uint8_t*)os_zalloc(bufferSize);
     RINGBUF_Init(&queue->rb, queue->buf, bufferSize);
 }
QUEUE_IsEmpty()
BOOL ICACHE_FLASH_ATTR QUEUE_IsEmpty (QUEUE * queue)
Definition at line 66 of file queue.c.
References FALSE, RINGBUF::fill_cnt, QUEUE::rb, and TRUE.
Referenced by MQTT_Task().
 {
     if(queue->rb.fill_cnt<=0)
         return TRUE;
     return FALSE;
 }
QUEUE_Puts()
int32_t ICACHE_FLASH_ATTR QUEUE_Puts (QUEUE * queue, uint8_t * buffer, uint16_t len)
Definition at line 44 of file queue.c.
References RINGBUF::fill_cnt, last_fill_cnt, last_rb_p_r, last_rb_p_w, RINGBUF::p_r, RINGBUF::p_w, PROTO_AddRb(), and QUEUE::rb.
Referenced by MQTT_Ping(), MQTT_Publish(), MQTT_Subscribe(), mqtt_tcpclient_recv(), and MQTT_UnSubscribe().
 {
     uint32_t ret;
     last_rb_p_r = queue->rb.p_r;
     last_rb_p_w = queue->rb.p_w;
     last_fill_cnt = queue->rb.fill_cnt;
     ret = PROTO_AddRb(&queue->rb, buffer, len);
     if (ret == -1) {
         // rolling ring buffer back
         queue->rb.p_r = last_rb_p_r;
         queue->rb.p_w = last_rb_p_w;
         queue->rb.fill_cnt = last_fill_cnt;
     }
     return ret;
 }
Variable Documentation
last_fill_cnt
uint32_t last_fill_cnt
Definition at line 37 of file queue.c.
Referenced by QUEUE_Puts().
last_rb_p_r
uint8_t* last_rb_p_r
Definition at line 35 of file queue.c.
Referenced by QUEUE_Puts().
last_rb_p_w
uint8_t* last_rb_p_w
Definition at line 36 of file queue.c.
Referenced by QUEUE_Puts().