MeterLogger: mqtt/include/queue.h File Reference
queue.h File Reference
#include "os_type.h"
#include "ringbuf.h"
Data Structures
struct QUEUE
Functions
void ICACHE_FLASH_ATTR QUEUE_Init (QUEUE *queue, int bufferSize)
int32_t ICACHE_FLASH_ATTR QUEUE_Puts (QUEUE *queue, uint8_t *buffer, uint16_t len)
int32_t ICACHE_FLASH_ATTR QUEUE_Gets (QUEUE *queue, uint8_t *buffer, uint16_t *len, uint16_t maxLen)
BOOL ICACHE_FLASH_ATTR QUEUE_IsEmpty (QUEUE *queue)
Function Documentation
QUEUE_Gets()
int32_t ICACHE_FLASH_ATTR QUEUE_Gets (QUEUE * queue, uint8_t * buffer, uint16_t * len, uint16_t maxLen)
Definition at line 61 of file queue.c.
References PROTO_ParseRb(), and QUEUE::rb.
Referenced by MQTT_Ping(), MQTT_Publish(), MQTT_Subscribe(), MQTT_Task(), and MQTT_UnSubscribe().
QUEUE_Init()
void ICACHE_FLASH_ATTR QUEUE_Init (QUEUE * queue, int bufferSize)
Definition at line 39 of file queue.c.
References QUEUE::buf, QUEUE::rb, and RINGBUF_Init().
Referenced by MQTT_InitClient().
QUEUE_IsEmpty()
BOOL ICACHE_FLASH_ATTR QUEUE_IsEmpty (QUEUE * queue)
Definition at line 66 of file queue.c.
References RINGBUF::fill_cnt, and QUEUE::rb.
Referenced by MQTT_Task().
QUEUE_Puts()
int32_t ICACHE_FLASH_ATTR QUEUE_Puts (QUEUE * queue, uint8_t * buffer, uint16_t len)
Definition at line 44 of file queue.c.
References RINGBUF::fill_cnt, last_fill_cnt, last_rb_p_r, last_rb_p_w, RINGBUF::p_r, RINGBUF::p_w, PROTO_AddRb(), and QUEUE::rb.
Referenced by MQTT_Ping(), MQTT_Publish(), MQTT_Subscribe(), mqtt_tcpclient_recv(), and MQTT_UnSubscribe().