MeterLogger: user/rfinit.c File Reference
rfinit.c File Reference
#include "ets_sys.h"
#include "osapi.h"
#include "user_interface.h"
Functions
uint32 ICACHE_FLASH_ATTR __attribute__ ((weak))
Function Documentation
__attribute__()
void __attribute__ ((weak))
Definition at line 28 of file rfinit.c.
References FLASH_SIZE_16M_MAP_1024_1024, FLASH_SIZE_16M_MAP_512_512, FLASH_SIZE_32M_MAP_1024_1024, FLASH_SIZE_32M_MAP_512_512, FLASH_SIZE_4M_MAP_256_256, FLASH_SIZE_8M_MAP_512_512, system_get_flash_size_map(), system_phy_set_max_tpw(), and system_phy_set_rfoption().
 {
   enum flash_size_map size_map = system_get_flash_size_map();
   uint32 rf_cal_sec = 0;
   switch (size_map) {
     case FLASH_SIZE_4M_MAP_256_256:
       rf_cal_sec = 128 - 5;
       break;
     case FLASH_SIZE_8M_MAP_512_512:
       rf_cal_sec = 256 - 5;
       break;
     case FLASH_SIZE_16M_MAP_512_512:
     case FLASH_SIZE_16M_MAP_1024_1024:
       rf_cal_sec = 512 - 5;
       break;
     case FLASH_SIZE_32M_MAP_512_512:
     case FLASH_SIZE_32M_MAP_1024_1024:
       rf_cal_sec = 1024 - 5;
       break;
     default:
       rf_cal_sec = 0;
       break;
   }
   return rf_cal_sec;
 }