MeterLogger: mqtt/include/ringbuf.h File Reference
ringbuf.h File Reference
#include <esp8266.h>
#include "typedef.h"
Data Structures
struct RINGBUF
Functions
I16 ICACHE_FLASH_ATTR RINGBUF_Init (RINGBUF *r, U8 *buf, I32 size)
init a RINGBUF object
I16 ICACHE_FLASH_ATTR RINGBUF_Put (RINGBUF *r, U8 c)
put a character into ring buffer
I16 ICACHE_FLASH_ATTR RINGBUF_Get (RINGBUF *r, U8 *c)
get a character from ring buffer
Function Documentation
RINGBUF_Get()
I16 ICACHE_FLASH_ATTR RINGBUF_Get (RINGBUF * r, U8 * c)
get a character from ring buffer
Parameters
r pointer to a ringbuf object
c read character
Returns
0 if successfull, otherwise failed
Definition at line 53 of file ringbuf.c.
References RINGBUF::fill_cnt, RINGBUF::p_o, RINGBUF::p_r, and RINGBUF::size.
Referenced by PROTO_ParseRb().
RINGBUF_Init()
I16 ICACHE_FLASH_ATTR RINGBUF_Init (RINGBUF * r, U8 * buf, I32 size)
init a RINGBUF object
Parameters
r pointer to a RINGBUF object
buf pointer to a byte array
size size of buf
Returns
0 if successfull, otherwise failed
Definition at line 16 of file ringbuf.c.
References RINGBUF::fill_cnt, NULL, RINGBUF::p_o, RINGBUF::p_r, RINGBUF::p_w, and RINGBUF::size.
Referenced by QUEUE_Init().
RINGBUF_Put()
I16 ICACHE_FLASH_ATTR RINGBUF_Put (RINGBUF * r, U8 c)
put a character into ring buffer
Parameters
r pointer to a ringbuf object
c character to be put
Returns
0 if successfull, otherwise failed
Definition at line 32 of file ringbuf.c.
References RINGBUF::fill_cnt, RINGBUF::p_o, RINGBUF::p_w, and RINGBUF::size.
Referenced by PROTO_AddRb().