MeterLogger: mqtt/ringbuf.c File Reference
ringbuf.c File Reference
#include "ringbuf.h"
Functions
I16 ICACHE_FLASH_ATTR RINGBUF_Init (RINGBUF *r, U8 *buf, I32 size)
init a RINGBUF object
I16 ICACHE_FLASH_ATTR RINGBUF_Put (RINGBUF *r, U8 c)
put a character into ring buffer
I16 ICACHE_FLASH_ATTR RINGBUF_Get (RINGBUF *r, U8 *c)
get a character from ring buffer
Detailed Description
Ring Buffer library
Definition in file ringbuf.c.
Function Documentation
RINGBUF_Get()
I16 ICACHE_FLASH_ATTR RINGBUF_Get (RINGBUF * r, U8 * c)
get a character from ring buffer
Parameters
r pointer to a ringbuf object
c read character
Returns
0 if successfull, otherwise failed
Definition at line 53 of file ringbuf.c.
References RINGBUF::fill_cnt, RINGBUF::p_o, RINGBUF::p_r, and RINGBUF::size.
Referenced by PROTO_ParseRb().
 {
     if(r->fill_cnt<=0)return -1;                // ring buffer is empty, this should be atomic operation
     r->fill_cnt--;                              // decrease filled slots count
     *c = *r->p_r++;                             // get the character out
     if(r->p_r >= r->p_o + r->size)              // rollback if write pointer go pass
         r->p_r = r->p_o;                        // the physical boundary
     return 0;
 }
RINGBUF_Init()
I16 ICACHE_FLASH_ATTR RINGBUF_Init (RINGBUF * r, U8 * buf, I32 size)
init a RINGBUF object
Parameters
r pointer to a RINGBUF object
buf pointer to a byte array
size size of buf
Returns
0 if successfull, otherwise failed
Definition at line 16 of file ringbuf.c.
References RINGBUF::fill_cnt, NULL, RINGBUF::p_o, RINGBUF::p_r, RINGBUF::p_w, and RINGBUF::size.
Referenced by QUEUE_Init().
 {
     if(r == NULL || buf == NULL || size < 2) return -1;
     r->p_o = r->p_r = r->p_w = buf;
     r->fill_cnt = 0;
     r->size = size;
     return 0;
 }
RINGBUF_Put()
I16 ICACHE_FLASH_ATTR RINGBUF_Put (RINGBUF * r, U8 c)
put a character into ring buffer
Parameters
r pointer to a ringbuf object
c character to be put
Returns
0 if successfull, otherwise failed
Definition at line 32 of file ringbuf.c.
References RINGBUF::fill_cnt, RINGBUF::p_o, RINGBUF::p_w, and RINGBUF::size.
Referenced by PROTO_AddRb().
 {
     if(r->fill_cnt>=r->size)return -1;      // ring buffer is full, this should be atomic operation
     r->fill_cnt++;                          // increase filled slots count, this should be atomic operation
     *r->p_w++ = c;                          // put character into buffer
     if(r->p_w >= r->p_o + r->size)          // rollback if write pointer go pass
         r->p_w = r->p_o;                    // the physical boundary
     return 0;
 }