MeterLogger: sdk/include/espconn.h File Reference
espconn.h File Reference
Data Structures
struct _esp_tcp
struct _esp_udp
struct _remot_info
struct espconn
struct espconn_packet
struct mdns_info
Macros
#define ESPCONN_OK 0 /* No error, everything OK. */
#define ESPCONN_MEM -1 /* Out of memory error. */
#define ESPCONN_TIMEOUT -3 /* Timeout. */
#define ESPCONN_RTE -4 /* Routing problem. */
#define ESPCONN_INPROGRESS -5 /* Operation in progress */
#define ESPCONN_MAXNUM -7 /* Total number exceeds the set maximum*/
#define ESPCONN_ABRT -8 /* Connection aborted. */
#define ESPCONN_RST -9 /* Connection reset. */
#define ESPCONN_CLSD -10 /* Connection closed. */
#define ESPCONN_CONN -11 /* Not connected. */
#define ESPCONN_ARG -12 /* Illegal argument. */
#define ESPCONN_IF -14 /* UDP send error */
#define ESPCONN_ISCONN -15 /* Already connected. */
#define ESPCONN_HANDSHAKE -28 /* ssl handshake failed */
#define ESPCONN_SSL_INVALID_DATA -61 /* ssl application invalid */
Typedefs
typedef sint8 err_t
typedef void * espconn_handle
typedef void(* espconn_connect_callback) (void *arg)
typedef void(* espconn_reconnect_callback) (void *arg, sint8 err)
typedef struct _esp_tcp esp_tcp
typedef struct _esp_udp esp_udp
typedef struct _remot_info remot_info
typedef void(* espconn_recv_callback) (void *arg, char *pdata, unsigned short len)
typedef void(* espconn_sent_callback) (void *arg)
typedef void(* dns_found_callback) (const char *name, ip_addr_t *ipaddr, void *callback_arg)
Enumerations
enum espconn_type {
ESPCONN_INVALID = 0, ESPCONN_TCP = 0x10, ESPCONN_UDP = 0x20, ESPCONN_INVALID = 0,
ESPCONN_TCP = 0x10, ESPCONN_UDP = 0x20
}
enum espconn_state {
ESPCONN_NONE, ESPCONN_WAIT, ESPCONN_LISTEN, ESPCONN_CONNECT,
ESPCONN_WRITE, ESPCONN_READ, ESPCONN_CLOSE, ESPCONN_NONE,
ESPCONN_WAIT, ESPCONN_LISTEN, ESPCONN_CONNECT, ESPCONN_WRITE,
ESPCONN_READ, ESPCONN_CLOSE
}
enum espconn_option {
ESPCONN_START = 0x00, ESPCONN_REUSEADDR = 0x01, ESPCONN_NODELAY = 0x02, ESPCONN_COPY = 0x04,
ESPCONN_KEEPALIVE = 0x08, ESPCONN_END, ESPCONN_START = 0x00, ESPCONN_REUSEADDR = 0x01,
ESPCONN_NODELAY = 0x02, ESPCONN_COPY = 0x04, ESPCONN_KEEPALIVE = 0x08, ESPCONN_END
}
enum espconn_level {
ESPCONN_KEEPIDLE, ESPCONN_KEEPINTVL, ESPCONN_KEEPCNT, ESPCONN_KEEPIDLE,
ESPCONN_KEEPINTVL, ESPCONN_KEEPCNT
}
enum {
ESPCONN_IDLE = 0, ESPCONN_CLIENT, ESPCONN_SERVER, ESPCONN_BOTH,
ESPCONN_MAX
}
Functions
sint8 espconn_connect (struct espconn *espconn)
sint8 espconn_disconnect (struct espconn *espconn)
sint8 espconn_delete (struct espconn *espconn)
sint8 espconn_accept (struct espconn *espconn)
sint8 espconn_create (struct espconn *espconn)
uint8 espconn_tcp_get_max_con (void)
sint8 espconn_tcp_set_max_con (uint8 num)
sint8 espconn_tcp_get_max_con_allow (struct espconn *espconn)
sint8 espconn_tcp_set_max_con_allow (struct espconn *espconn, uint8 num)
sint8 espconn_regist_time (struct espconn *espconn, uint32 interval, uint8 type_flag)
sint8 espconn_get_connection_info (struct espconn *pespconn, remot_info **pcon_info, uint8 typeflags)
sint8 espconn_get_packet_info (struct espconn *espconn, struct espconn_packet *infoarg)
sint8 espconn_regist_sentcb (struct espconn *espconn, espconn_sent_callback sent_cb)
sint8 espconn_regist_write_finish (struct espconn *espconn, espconn_connect_callback write_finish_fn)
sint8 espconn_send (struct espconn *espconn, uint8 *psent, uint16 length)
sint8 espconn_sent (struct espconn *espconn, uint8 *psent, uint16 length)
sint16 espconn_sendto (struct espconn *espconn, uint8 *psent, uint16 length)
sint8 espconn_regist_connectcb (struct espconn *espconn, espconn_connect_callback connect_cb)
sint8 espconn_regist_recvcb (struct espconn *espconn, espconn_recv_callback recv_cb)
sint8 espconn_regist_reconcb (struct espconn *espconn, espconn_reconnect_callback recon_cb)
sint8 espconn_regist_disconcb (struct espconn *espconn, espconn_connect_callback discon_cb)
uint32 espconn_port (void)
sint8 espconn_set_opt (struct espconn *espconn, uint8 opt)
sint8 espconn_clear_opt (struct espconn *espconn, uint8 opt)
sint8 espconn_set_keepalive (struct espconn *espconn, uint8 level, void *optarg)
sint8 espconn_get_keepalive (struct espconn *espconn, uint8 level, void *optarg)
err_t espconn_gethostbyname (struct espconn *pespconn, const char *hostname, ip_addr_t *addr, dns_found_callback found)
sint8 espconn_abort (struct espconn *espconn)
sint8 espconn_secure_connect (struct espconn *espconn)
sint8 espconn_secure_disconnect (struct espconn *espconn)
sint8 espconn_secure_send (struct espconn *espconn, uint8 *psent, uint16 length)
sint8 espconn_secure_sent (struct espconn *espconn, uint8 *psent, uint16 length)
bool espconn_secure_set_size (uint8 level, uint16 size)
sint16 espconn_secure_get_size (uint8 level)
bool espconn_secure_ca_enable (uint8 level, uint32 flash_sector)
bool espconn_secure_ca_disable (uint8 level)
bool espconn_secure_cert_req_enable (uint8 level, uint32 flash_sector)
bool espconn_secure_cert_req_disable (uint8 level)
bool espconn_secure_set_default_certificate (const uint8 *certificate, uint16 length)
bool espconn_secure_set_default_private_key (const uint8 *private_key, uint16 length)
sint8 espconn_secure_accept (struct espconn *espconn)
sint8 espconn_secure_delete (struct espconn *espconn)
sint8 espconn_igmp_join (ip_addr_t *host_ip, ip_addr_t *multicast_ip)
sint8 espconn_igmp_leave (ip_addr_t *host_ip, ip_addr_t *multicast_ip)
sint8 espconn_recv_hold (struct espconn *pespconn)
sint8 espconn_recv_unhold (struct espconn *pespconn)
void espconn_mdns_init (struct mdns_info *info)
void espconn_mdns_close (void)
void espconn_mdns_server_register (void)
void espconn_mdns_server_unregister (void)
char * espconn_mdns_get_servername (void)
void espconn_mdns_set_servername (const char *name)
void espconn_mdns_set_hostname (char *name)
char * espconn_mdns_get_hostname (void)
void espconn_mdns_disable (void)
void espconn_mdns_enable (void)
void espconn_dns_setserver (char numdns, ip_addr_t *dnsserver)
Macro Definition Documentation
ESPCONN_ABRT
#define ESPCONN_ABRT -8 /* Connection aborted. */
Definition at line 43 of file espconn.h.
ESPCONN_ARG
#define ESPCONN_ARG -12 /* Illegal argument. */
Definition at line 48 of file espconn.h.
ESPCONN_CLSD
#define ESPCONN_CLSD -10 /* Connection closed. */
Definition at line 45 of file espconn.h.
ESPCONN_CONN
#define ESPCONN_CONN -11 /* Not connected. */
Definition at line 46 of file espconn.h.
ESPCONN_HANDSHAKE
#define ESPCONN_HANDSHAKE -28 /* ssl handshake failed */
Definition at line 52 of file espconn.h.
ESPCONN_IF
#define ESPCONN_IF -14 /* UDP send error */
Definition at line 49 of file espconn.h.
ESPCONN_INPROGRESS
#define ESPCONN_INPROGRESS -5 /* Operation in progress */
Definition at line 40 of file espconn.h.
ESPCONN_ISCONN
#define ESPCONN_ISCONN -15 /* Already connected. */
Definition at line 50 of file espconn.h.
ESPCONN_MAXNUM
#define ESPCONN_MAXNUM -7 /* Total number exceeds the set maximum*/
Definition at line 41 of file espconn.h.
ESPCONN_MEM
#define ESPCONN_MEM -1 /* Out of memory error. */
Definition at line 37 of file espconn.h.
ESPCONN_OK
#define ESPCONN_OK 0 /* No error, everything OK. */
Definition at line 36 of file espconn.h.
ESPCONN_RST
#define ESPCONN_RST -9 /* Connection reset. */
Definition at line 44 of file espconn.h.
ESPCONN_RTE
#define ESPCONN_RTE -4 /* Routing problem. */
Definition at line 39 of file espconn.h.
ESPCONN_SSL_INVALID_DATA
#define ESPCONN_SSL_INVALID_DATA -61 /* ssl application invalid */
Definition at line 53 of file espconn.h.
ESPCONN_TIMEOUT
#define ESPCONN_TIMEOUT -3 /* Timeout. */
Definition at line 38 of file espconn.h.
Typedef Documentation
dns_found_callback
typedef void(* dns_found_callback) (const char *name, ip_addr_t *ipaddr, void *callback_arg)
Definition at line 437 of file espconn.h.
err_t
typedef sint8 err_t
Definition at line 28 of file espconn.h.
esp_tcp
typedef struct _esp_tcp esp_tcp
esp_udp
typedef struct _esp_udp esp_udp
espconn_connect_callback
typedef void(* espconn_connect_callback) (void *arg)
Definition at line 31 of file espconn.h.
espconn_handle
typedef void* espconn_handle
Definition at line 30 of file espconn.h.
espconn_reconnect_callback
typedef void(* espconn_reconnect_callback) (void *arg, sint8 err)
Definition at line 32 of file espconn.h.
espconn_recv_callback
typedef void(* espconn_recv_callback) (void *arg, char *pdata, unsigned short len)
A callback prototype to inform about events for a espconn
Definition at line 100 of file espconn.h.
espconn_sent_callback
typedef void(* espconn_sent_callback) (void *arg)
Definition at line 101 of file espconn.h.
remot_info
typedef struct _remot_info remot_info
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ESPCONN_IDLE
ESPCONN_CLIENT
ESPCONN_SERVER
ESPCONN_BOTH
ESPCONN_MAX
Definition at line 135 of file espconn.h.
      {
     ESPCONN_IDLE = 0,
     ESPCONN_CLIENT,
     ESPCONN_SERVER,
     ESPCONN_BOTH,
     ESPCONN_MAX
 };
espconn_level
enum espconn_level
Enumerator
ESPCONN_KEEPIDLE
ESPCONN_KEEPINTVL
ESPCONN_KEEPCNT
ESPCONN_KEEPIDLE
ESPCONN_KEEPINTVL
ESPCONN_KEEPCNT
Definition at line 129 of file espconn.h.
                   {
     ESPCONN_KEEPIDLE,
     ESPCONN_KEEPINTVL,
     ESPCONN_KEEPCNT
 };
espconn_option
enum espconn_option
Enumerator
ESPCONN_START
ESPCONN_REUSEADDR
ESPCONN_NODELAY
ESPCONN_COPY
ESPCONN_KEEPALIVE
ESPCONN_END
ESPCONN_START
ESPCONN_REUSEADDR
ESPCONN_NODELAY
ESPCONN_COPY
ESPCONN_KEEPALIVE
ESPCONN_END
Definition at line 120 of file espconn.h.
                    {
     ESPCONN_START = 0x00,
     ESPCONN_REUSEADDR = 0x01,
     ESPCONN_NODELAY = 0x02,
     ESPCONN_COPY = 0x04,
     ESPCONN_KEEPALIVE = 0x08,
     ESPCONN_END
 };
espconn_state
enum espconn_state
Current state of the espconn. Non-TCP espconn are always in state ESPCONN_NONE!
Enumerator
ESPCONN_NONE
ESPCONN_WAIT
ESPCONN_LISTEN
ESPCONN_CONNECT
ESPCONN_WRITE
ESPCONN_READ
ESPCONN_CLOSE
ESPCONN_NONE
ESPCONN_WAIT
ESPCONN_LISTEN
ESPCONN_CONNECT
ESPCONN_WRITE
ESPCONN_READ
ESPCONN_CLOSE
Definition at line 65 of file espconn.h.
                    {
     ESPCONN_NONE,
     ESPCONN_WAIT,
     ESPCONN_LISTEN,
     ESPCONN_CONNECT,
     ESPCONN_WRITE,
     ESPCONN_READ,
     ESPCONN_CLOSE
 };
espconn_type
enum espconn_type
Protocol family and type of the espconn
Enumerator
ESPCONN_INVALID
ESPCONN_TCP
ESPCONN_UDP
ESPCONN_INVALID
ESPCONN_TCP
ESPCONN_UDP
Definition at line 56 of file espconn.h.
                   {
     ESPCONN_INVALID    = 0,
     /* ESPCONN_TCP Group */
     ESPCONN_TCP        = 0x10,
     /* ESPCONN_UDP Group */
     ESPCONN_UDP        = 0x20,
 };
Function Documentation
espconn_abort()
sint8 espconn_abort (struct espconn * espconn)
Definition at line 972 of file espconn.c.
References ESPCONN_ARG, ESPCONN_CLOSE, espconn_find_connection(), ESPCONN_INPROGRESS, ESPCONN_OK, ESPCONN_TCP, espconn_tcp_disconnect(), ICACHE_FLASH_ATTR, NULL, and espconn::state.
Referenced by mqtt_tcpclient_delete().
 {
     espconn_msg *pnode = NULL;
     bool value = false;
     if (espconn == NULL) {
         return ESPCONN_ARG;;
     } else if (espconn ->type != ESPCONN_TCP)
         return ESPCONN_ARG;
     /*Find the node depend on the espconn message*/
     value = espconn_find_connection(espconn, &pnode);
     if (value){
         /*protect for redisconnection*/
         if (espconn->state == ESPCONN_CLOSE)
             return ESPCONN_INPROGRESS;
         espconn_tcp_disconnect(pnode,1);    //1 force, 0 normal
         return ESPCONN_OK;
     } else
         return ESPCONN_ARG;
 }
espconn_accept()
sint8 espconn_accept (struct espconn * espconn)
Definition at line 875 of file espconn.c.
References ESPCONN_ARG, ESPCONN_ISCONN, ESPCONN_OK, ESPCONN_TCP, espconn_tcp_server(), _esp_tcp::local_port, NULL, _espconn_msg::pespconn, plist, _espconn_msg::pnext, espconn::proto, espconn::tcp, and espconn::type.
 {
     sint8 value = ESPCONN_OK;
     espconn_msg *plist = NULL;
     if (espconn == NULL) {
         return ESPCONN_ARG;
     } else if (espconn ->type != ESPCONN_TCP)
         return ESPCONN_ARG;
     /*check the active node information whether is the same as the entity or not*/
     for (plist = plink_active; plist != NULL; plist = plist->pnext){
         if (plist->pespconn && plist->pespconn->type == ESPCONN_TCP){
             if (espconn->proto.tcp->local_port == plist->pespconn->proto.tcp->local_port){
                 return ESPCONN_ISCONN;
             }
         }
     }
     value = espconn_tcp_server(espconn);
     return value;
 }
espconn_clear_opt()
sint8 espconn_clear_opt (struct espconn * espconn, uint8 opt)
Definition at line 1092 of file espconn.c.
References ESPCONN_ARG, espconn_delay_enabled, espconn_find_connection(), espconn_keepalive_disable, espconn_keepalive_enabled, ESPCONN_OK, _comon_pkt::espconn_opt, ESPCONN_TCP, NULL, _comon_pkt::pcb, _espconn_msg::pcommon, and espconn::type.
 {
     espconn_msg *pnode = NULL;
     struct tcp_pcb *tpcb;
     bool value = false;
     if (espconn == NULL) {
         return ESPCONN_ARG;;
     } else if (espconn->type != ESPCONN_TCP)
         return ESPCONN_ARG;
     /*Find the node depend on the espconn message*/
     value = espconn_find_connection(espconn, &pnode);
     if (value) {
         pnode->pcommon.espconn_opt &= ~opt;
         tpcb = pnode->pcommon.pcb;
         if (espconn_keepalive_enabled(pnode))
             espconn_keepalive_disable(tpcb);
         if (espconn_delay_enabled(pnode))
             tcp_nagle_enable(tpcb);
         return ESPCONN_OK;
     } else
         return ESPCONN_ARG;
 }
espconn_connect()
sint8 espconn_connect (struct espconn * espconn)
Definition at line 260 of file espconn.c.
References ip_addr::addr, AP_NETIF, ESPCONN_AP, ESPCONN_AP_STA, ESPCONN_ARG, espconn_get_acticve_num(), ESPCONN_ISCONN, ESPCONN_OK, espconn_printf, ESPCONN_RTE, ESPCONN_STA, ESPCONN_TCP, espconn_tcp_client(), espconn_tcp_get_max_con(), ICACHE_FLASH_ATTR, ip_info::ip, IP4_ADDR, _esp_tcp::local_port, NULL, _espconn_msg::pespconn, plist, _espconn_msg::pnext, espconn::proto, _esp_tcp::remote_ip, STA_NETIF, STATION_GOT_IP, STATION_IDLE, espconn::tcp, espconn::type, wifi_get_ip_info(), wifi_get_opmode(), and wifi_station_get_connect_status().
 {
     struct ip_addr ipaddr;
     struct ip_info ipinfo;
     uint8 connect_status = 0;
     sint8 value = ESPCONN_OK;
     espconn_msg *plist = NULL;
     remot_info *pinfo = NULL;
     if (espconn == NULL) {
         return ESPCONN_ARG;
     } else if (espconn ->type != ESPCONN_TCP)
         return ESPCONN_ARG;
     /*Check the active node count whether is the limit or not*/
     if (espconn_get_acticve_num(ESPCONN_TCP) >= espconn_tcp_get_max_con())
         return ESPCONN_ISCONN;
     /*Check the IP address whether is zero or not in different mode*/
     if (wifi_get_opmode() == ESPCONN_STA){
         wifi_get_ip_info(STA_NETIF,&ipinfo);
         if (ipinfo.ip.addr == 0){
             return ESPCONN_RTE;
         }
     } else if(wifi_get_opmode() == ESPCONN_AP){
         wifi_get_ip_info(AP_NETIF,&ipinfo);
         if (ipinfo.ip.addr == 0){
             return ESPCONN_RTE;
         }
     } else if(wifi_get_opmode() == ESPCONN_AP_STA){
         IP4_ADDR(&ipaddr, espconn->proto.tcp->remote_ip[0],
                             espconn->proto.tcp->remote_ip[1],
                             espconn->proto.tcp->remote_ip[2],
                             espconn->proto.tcp->remote_ip[3]);
         ipaddr.addr <<= 8;
         wifi_get_ip_info(AP_NETIF,&ipinfo);
         ipinfo.ip.addr <<= 8;
         espconn_printf("softap_addr = %x, remote_addr = %x\n", ipinfo.ip.addr, ipaddr.addr);
         if (ipaddr.addr != ipinfo.ip.addr){
             connect_status = wifi_station_get_connect_status();
             if (connect_status == STATION_GOT_IP){
                 wifi_get_ip_info(STA_NETIF,&ipinfo);
                 if (ipinfo.ip.addr == 0)
                     return ESPCONN_RTE;
             } else if (connect_status == STATION_IDLE){
                 return ESPCONN_RTE;
             } else {
                 return connect_status;
             }
         }
     }
     /*check the active node information whether is the same as the entity or not*/
     for (plist = plink_active; plist != NULL; plist = plist->pnext){
         if (plist->pespconn && plist->pespconn->type == ESPCONN_TCP){
             if (espconn->proto.tcp->local_port == plist->pespconn->proto.tcp->local_port){
                 return ESPCONN_ISCONN;
             }
         }
     }
     value = espconn_tcp_client(espconn);
     return value;
 }
espconn_create()
sint8 espconn_create (struct espconn * espconn)
Definition at line 334 of file espconn.c.
References ESPCONN_ARG, ESPCONN_ISCONN, ESPCONN_OK, ESPCONN_UDP, espconn_udp_server(), ICACHE_FLASH_ATTR, _esp_udp::local_port, NULL, _espconn_msg::pespconn, plist, _espconn_msg::pnext, espconn::proto, espconn::type, and espconn::udp.
 {
     sint8 value = ESPCONN_OK;
     espconn_msg *plist = NULL;
     if (espconn == NULL) {
         return ESPCONN_ARG;
     } else if (espconn ->type != ESPCONN_UDP){
         return ESPCONN_ARG;
     }
     /*check the active node information whether is the same as the entity or not*/
     for (plist = plink_active; plist != NULL; plist = plist->pnext){
         if (plist->pespconn && plist->pespconn->type == ESPCONN_UDP){
             if (espconn->proto.udp->local_port == plist->pespconn->proto.udp->local_port){
                 return ESPCONN_ISCONN;
             }
         }
     }
     value = espconn_udp_server(espconn);
     return value;
 }
espconn_delete()
sint8 espconn_delete (struct espconn * espconn)
Definition at line 1217 of file espconn.c.
References ESPCONN_ARG, espconn_find_connection(), ESPCONN_OK, espconn_tcp_delete(), ESPCONN_UDP, espconn_udp_disconnect(), ICACHE_FLASH_ATTR, and NULL.
 {
     espconn_msg *pnode = NULL;
     bool value = false;
     if (espconn == NULL) {
         return ESPCONN_ARG;
     } else if (espconn ->type != ESPCONN_UDP)
         return espconn_tcp_delete(espconn);
     /*Find the node depend on the espconn message*/
     value = espconn_find_connection(espconn, &pnode);
     if (value){
         espconn_udp_disconnect(pnode);
         return ESPCONN_OK;
     } else
         return ESPCONN_ARG;
 }
espconn_disconnect()
sint8 espconn_disconnect (struct espconn * espconn)
Definition at line 942 of file espconn.c.
References ESPCONN_ARG, ESPCONN_CLOSE, espconn_find_connection(), ESPCONN_INPROGRESS, ESPCONN_OK, ESPCONN_TCP, espconn_tcp_disconnect(), ICACHE_FLASH_ATTR, NULL, and espconn::state.
 {
     espconn_msg *pnode = NULL;
     bool value = false;
     if (espconn == NULL) {
         return ESPCONN_ARG;;
     } else if (espconn ->type != ESPCONN_TCP)
         return ESPCONN_ARG;
     /*Find the node depend on the espconn message*/
     value = espconn_find_connection(espconn, &pnode);
     if (value){
         /*protect for redisconnection*/
         if (espconn->state == ESPCONN_CLOSE)
             return ESPCONN_INPROGRESS;
         espconn_tcp_disconnect(pnode,0);    //1 force, 0 normal
         return ESPCONN_OK;
     } else
         return ESPCONN_ARG;
 }
espconn_dns_setserver()
void espconn_dns_setserver (char numdns, ip_addr_t * dnsserver)
espconn_get_connection_info()
sint8 espconn_get_connection_info (struct espconn * pespconn, remot_info ** pcon_info, uint8 typeflags)
Definition at line 825 of file espconn.c.
References ESPCONN_ARG, ESPCONN_OK, ESPCONN_TCP, ESPCONN_UDP, ICACHE_FLASH_ATTR, espconn::link_cnt, NULL, os_memcpy, os_memset, _espconn_msg::pcommon, _espconn_msg::pespconn, plink_active, plist, _espconn_msg::pnext, premot, _espconn_msg::preverse, _remot_info::remote_ip, _comon_pkt::remote_ip, _remot_info::remote_port, _comon_pkt::remote_port, _remot_info::state, espconn::state, and espconn::type.
 {
     espconn_msg *plist = NULL;
     if (pespconn == NULL)
         return ESPCONN_ARG;
     os_memset(premot, 0, sizeof(premot));
     pespconn->link_cnt = 0;
     plist = plink_active;
     switch (pespconn->type){
         case ESPCONN_TCP:
             while(plist != NULL){
                 if (plist->preverse == pespconn){
                     premot[pespconn->link_cnt].state = plist->pespconn->state;
                     premot[pespconn->link_cnt].remote_port = plist->pcommon.remote_port;
                     os_memcpy(premot[pespconn->link_cnt].remote_ip, plist->pcommon.remote_ip, 4);
                     pespconn->link_cnt ++;
                 }
                 plist = plist->pnext;
             }
             break;
         case ESPCONN_UDP:
             while(plist != NULL){
                 if (plist->pespconn == pespconn){
                     premot[pespconn->link_cnt].state = plist->pespconn->state;
                     premot[pespconn->link_cnt].remote_port = plist->pcommon.remote_port;
                     os_memcpy(premot[pespconn->link_cnt].remote_ip, plist->pcommon.remote_ip, 4);
                     pespconn->link_cnt ++;
                 }
                 plist = plist->pnext;
             }
             break;
         default:
             break;
     }
     *pcon_info = premot;
     if (pespconn->link_cnt == 0)
         return ESPCONN_ARG;
     return ESPCONN_OK;
 }
espconn_get_keepalive()
sint8 espconn_get_keepalive (struct espconn * espconn, uint8 level, void * optarg)
Definition at line 1173 of file espconn.c.
References ESPCONN_ARG, espconn_find_connection(), espconn_keepalive_disabled, ESPCONN_KEEPCNT, ESPCONN_KEEPIDLE, ESPCONN_KEEPINTVL, ESPCONN_OK, ESPCONN_TCP, ICACHE_FLASH_ATTR, NULL, _comon_pkt::pcb, _espconn_msg::pcommon, and espconn::type.
 {
     espconn_msg *pnode = NULL;
     bool value = false;
     sint8 ret = ESPCONN_OK;
     if (espconn == NULL || optarg == NULL) {
         return ESPCONN_ARG;;
     } else if (espconn->type != ESPCONN_TCP)
         return ESPCONN_ARG;
     /*Find the node depend on the espconn message*/
     value = espconn_find_connection(espconn, &pnode);
     if (value && espconn_keepalive_disabled(pnode)) {
         struct tcp_pcb *pcb = pnode->pcommon.pcb;
         switch (level) {
         case ESPCONN_KEEPIDLE:
             *(int*)optarg = (int)(pcb->keep_idle/1000);
             ret = ESPCONN_OK;
             break;
         case ESPCONN_KEEPINTVL:
             *(int*)optarg = (int)(pcb->keep_intvl/1000);
             ret = ESPCONN_OK;
             break;
         case ESPCONN_KEEPCNT:
             *(int*)optarg = (int)(pcb->keep_cnt);
             ret = ESPCONN_OK;
             break;
         default:
             ret = ESPCONN_ARG;
             break;
         }
         return ret;
     } else
         return ESPCONN_ARG;
 }
espconn_get_packet_info()
sint8 espconn_get_packet_info (struct espconn * espconn, struct espconn_packet * infoarg)
Definition at line 1004 of file espconn.c.
References ESPCONN_ARG, ESPCONN_CLOSE, espconn_find_connection(), ESPCONN_NONE, ESPCONN_OK, ESPCONN_TCP, ICACHE_FLASH_ATTR, NULL, os_memcpy, _comon_pkt::packet_info, espconn_packet::packseq_nxt, espconn_packet::packseqno, _comon_pkt::pcb, _espconn_msg::pcommon, pktinfo, espconn_packet::snd_buf_size, espconn_packet::snd_queuelen, espconn::state, TCP_SND_QUEUELEN, espconn_packet::total_queuelen, and espconn::type.
 {
     espconn_msg *pnode = NULL;
     err_t err;
     bool value = false;
     if (espconn == NULL || infoarg == NULL) {
         return ESPCONN_ARG;;
     } else if (espconn->type != ESPCONN_TCP)
         return ESPCONN_ARG;
     /*Find the node depend on the espconn message*/
     value = espconn_find_connection(espconn, &pnode);
     if (value) {
         struct tcp_pcb *pcb = pnode->pcommon.pcb;
         if (pcb == NULL)
             return ESPCONN_ARG;
         pnode->pcommon.packet_info.packseq_nxt = pcb->rcv_nxt;
         pnode->pcommon.packet_info.packseqno = pcb->snd_nxt;
         pnode->pcommon.packet_info.snd_buf_size = pcb->snd_buf;
         pnode->pcommon.packet_info.total_queuelen = TCP_SND_QUEUELEN;
         pnode->pcommon.packet_info.snd_queuelen = pnode->pcommon.packet_info.total_queuelen - pcb->snd_queuelen;
         os_memcpy(infoarg,(void*)&pnode->pcommon.packet_info, sizeof(struct espconn_packet));
         return ESPCONN_OK;
     } else {
         switch (espconn->state){
             case ESPCONN_CLOSE:
                 os_memcpy(infoarg,(void*)&pktinfo[0], sizeof(struct espconn_packet));
                 err = ESPCONN_OK;
                 break;
             case ESPCONN_NONE:
                 os_memcpy(infoarg,(void*)&pktinfo[1], sizeof(struct espconn_packet));
                 err = ESPCONN_OK;
                 break;
             default:
                 err = ESPCONN_ARG;
                 break;
         }
         return err;
     }
 }
espconn_gethostbyname()
err_t espconn_gethostbyname (struct espconn * pespconn, const char * hostname, ip_addr_t * addr, dns_found_callback found)
Definition at line 1288 of file espconn.c.
References ICACHE_FLASH_ATTR.
 {
     return dns_gethostbyname(hostname, addr, found, pespconn);
 }
espconn_igmp_join()
sint8 espconn_igmp_join (ip_addr_t * host_ip, ip_addr_t * multicast_ip)
Definition at line 414 of file espconn_udp.c.
References ERR_OK, ESPCONN_OK, ESPCONN_UDP_DEBUG, and LWIP_DEBUGF.
 {
     if (igmp_joingroup(host_ip, multicast_ip) != ERR_OK) {
         LWIP_DEBUGF(ESPCONN_UDP_DEBUG, ("udp_join_multigrup failed!\n"));
         return -1;
     };
     /* join to any IP address at the port  */
     return ESPCONN_OK;
 }
espconn_igmp_leave()
sint8 espconn_igmp_leave (ip_addr_t * host_ip, ip_addr_t * multicast_ip)
Definition at line 396 of file espconn_udp.c.
References ERR_OK, ESPCONN_OK, ESPCONN_UDP_DEBUG, ICACHE_FLASH_ATTR, and LWIP_DEBUGF.
 {
     if (igmp_leavegroup(host_ip, multicast_ip) != ERR_OK) {
         LWIP_DEBUGF(ESPCONN_UDP_DEBUG, ("udp_leave_multigrup failed!\n"));
         return -1;
     };
     return ESPCONN_OK;
 }
espconn_mdns_close()
void espconn_mdns_close (void)
Definition at line 119 of file espconn_mdns.c.
References ICACHE_FLASH_ATTR.
 {
     mdns_close();
 }
espconn_mdns_disable()
void espconn_mdns_disable (void)
Definition at line 37 of file espconn_mdns.c.
References ICACHE_FLASH_ATTR.
 {
     mdns_disable();
 }
espconn_mdns_enable()
void espconn_mdns_enable (void)
Definition at line 25 of file espconn_mdns.c.
References ICACHE_FLASH_ATTR.
 {
     mdns_enable();
 }
espconn_mdns_get_hostname()
char* espconn_mdns_get_hostname (void)
Definition at line 63 of file espconn_mdns.c.
References ICACHE_FLASH_ATTR.
 {
     return (char *)mdns_get_hostname();
 }
espconn_mdns_get_servername()
char* espconn_mdns_get_servername (void)
Definition at line 85 of file espconn_mdns.c.
References ICACHE_FLASH_ATTR.
 {
     return (char *)mdns_get_servername();
 }
espconn_mdns_init()
void espconn_mdns_init (struct mdns_info * info)
Definition at line 131 of file espconn_mdns.c.
 {
     mdns_init(info);
 }
espconn_mdns_server_register()
void espconn_mdns_server_register (void)
Definition at line 96 of file espconn_mdns.c.
References ICACHE_FLASH_ATTR.
 {
     mdns_server_register();
 }
espconn_mdns_server_unregister()
void espconn_mdns_server_unregister (void)
Definition at line 107 of file espconn_mdns.c.
References ICACHE_FLASH_ATTR.
 {
     mdns_server_unregister();
 }
espconn_mdns_set_hostname()
void espconn_mdns_set_hostname (char * name)
Definition at line 50 of file espconn_mdns.c.
References ICACHE_FLASH_ATTR.
 {
     mdns_set_hostname(name);
 }
espconn_mdns_set_servername()
void espconn_mdns_set_servername (const char * name)
Definition at line 74 of file espconn_mdns.c.
References ICACHE_FLASH_ATTR.
 {
     mdns_set_servername(name);
 }
espconn_port()
uint32 espconn_port (void)
Definition at line 1245 of file espconn.c.
References ICACHE_FLASH_ATTR, and os_random().
 {
     uint32 port = 0;
     static uint32 randnum = 0;
     do {
         port = os_random();
         if (port < 0) {
             port = os_random() - port;
         }
         port %= 0xc350;
         if (port < 0x400) {
             port += 0x400;
         }
     } while (port == randnum);
     randnum = port;
     return port;
 }
espconn_recv_hold()
sint8 espconn_recv_hold (struct espconn * pespconn)
Definition at line 549 of file espconn_tcp.c.
References ESPCONN_ARG, espconn_find_connection(), ESPCONN_OK, ICACHE_FLASH_ATTR, NULL, os_printf, _espconn_msg::recv_hold_flag, and _espconn_msg::recv_holded_buf_Len.
 {
     //1st, according to espconn code, have to find out the escpconn_msg by pespconn;
     espconn_msg *pnode = NULL;
     bool value = false;
     if (pespconn == NULL) {
         return ESPCONN_ARG;
     }
     value = espconn_find_connection(pespconn, &pnode);
     if(value != true)
     {
         os_printf("RecvHold, By pespconn,find conn_msg fail\n");
         return ESPCONN_ARG;
     }
     //2nd, the actual operation
     if(pnode->recv_hold_flag == 0)
     {
         pnode->recv_hold_flag = 1;
         pnode->recv_holded_buf_Len = 0;
     }
     return ESPCONN_OK;
 }
espconn_recv_unhold()
sint8 espconn_recv_unhold (struct espconn * pespconn)
Definition at line 574 of file espconn_tcp.c.
References ESPCONN_ARG, espconn_find_connection(), ESPCONN_OK, ESPCONN_TCP, ICACHE_FLASH_ATTR, NULL, os_printf, _comon_pkt::pcb, _espconn_msg::pcommon, _espconn_msg::recv_hold_flag, _espconn_msg::recv_holded_buf_Len, and espconn::type.
 {
     //1st, according to espconn code, have to find out the escpconn_msg by pespconn;
     espconn_msg *pnode = NULL;
     bool value = false;
     if (pespconn == NULL) {
         return ESPCONN_ARG;
     }
     value = espconn_find_connection(pespconn, &pnode);
     if(value != true)
     {
         os_printf("RecvHold, By pespconn,find conn_msg fail\n");
         return ESPCONN_ARG;
     }
     //2nd, the actual operation
     if(pnode->recv_hold_flag == 1)
     {
         if(pespconn->type == ESPCONN_TCP) {
             tcp_recved(pnode->pcommon.pcb, pnode->recv_holded_buf_Len);
         }
         pnode->recv_holded_buf_Len = 0;
         pnode->recv_hold_flag = 0;
     }
     return ESPCONN_OK;
 }
espconn_regist_connectcb()
sint8 espconn_regist_connectcb (struct espconn * espconn, espconn_connect_callback connect_cb)
Definition at line 751 of file espconn.c.
References _esp_tcp::connect_callback, ESPCONN_ARG, ESPCONN_OK, ICACHE_FLASH_ATTR, NULL, espconn::proto, and espconn::tcp.
 {
     if (espconn == NULL) {
         return ESPCONN_ARG;
     }
     espconn->proto.tcp->connect_callback = connect_cb;
     return ESPCONN_OK;
 }
espconn_regist_disconcb()
sint8 espconn_regist_disconcb (struct espconn * espconn, espconn_connect_callback discon_cb)
Definition at line 807 of file espconn.c.
References _esp_tcp::disconnect_callback, ESPCONN_ARG, ESPCONN_OK, ICACHE_FLASH_ATTR, NULL, espconn::proto, and espconn::tcp.
 {
     if (espconn == NULL) {
         return ESPCONN_ARG;
     }
     espconn ->proto.tcp->disconnect_callback = discon_cb;
     return ESPCONN_OK;
 }
espconn_regist_reconcb()
sint8 espconn_regist_reconcb (struct espconn * espconn, espconn_reconnect_callback recon_cb)
Definition at line 789 of file espconn.c.
References ESPCONN_ARG, ESPCONN_OK, ICACHE_FLASH_ATTR, NULL, espconn::proto, _esp_tcp::reconnect_callback, and espconn::tcp.
 {
     if (espconn == NULL) {
         return ESPCONN_ARG;
     }
     espconn ->proto.tcp->reconnect_callback = recon_cb;
     return ESPCONN_OK;
 }
espconn_regist_recvcb()
sint8 espconn_regist_recvcb (struct espconn * espconn, espconn_recv_callback recv_cb)
Definition at line 770 of file espconn.c.
References ESPCONN_ARG, ESPCONN_OK, ICACHE_FLASH_ATTR, NULL, and espconn::recv_callback.
 {
     if (espconn == NULL) {
         return ESPCONN_ARG;
     }
     espconn ->recv_callback = recv_cb;
     return ESPCONN_OK;
 }
espconn_regist_sentcb()
sint8 espconn_regist_sentcb (struct espconn * espconn, espconn_sent_callback sent_cb)
Definition at line 712 of file espconn.c.
References ESPCONN_ARG, ESPCONN_OK, ICACHE_FLASH_ATTR, NULL, and espconn::sent_callback.
 {
     if (espconn == NULL) {
         return ESPCONN_ARG;
     }
     espconn ->sent_callback = sent_cb;
     return ESPCONN_OK;
 }
espconn_regist_time()
sint8 espconn_regist_time (struct espconn * espconn, uint32 interval, uint8 type_flag)
Definition at line 905 of file espconn.c.
References ESPCONN_ARG, espconn_find_connection(), ESPCONN_OK, ICACHE_FLASH_ATTR, NULL, _espconn_msg::pcommon, _espconn_msg::pespconn, _espconn_msg::pnext, pserver_list, and _comon_pkt::timeout.
 {
     espconn_msg *pnode = NULL;
     espconn_msg *ptime_msg = NULL;
     bool value = false;
     if ((espconn == NULL) || (type_flag > 0x01))
         return ESPCONN_ARG;
     if (type_flag == 0x01){
         /*set the timeout time for one active connection of the server*/
         value = espconn_find_connection(espconn, &pnode);
         if (value){
             pnode->pcommon.timeout = interval;
             return ESPCONN_OK;
         } else
             return ESPCONN_ARG;
     } else {
         /*set the timeout time for all active connection of the server*/
         ptime_msg = pserver_list;
         while (ptime_msg != NULL){
             if (ptime_msg->pespconn == espconn){
                 ptime_msg->pcommon.timeout = interval;
                 return ESPCONN_OK;
             }
             ptime_msg = ptime_msg->pnext;
         }
     }
     return ESPCONN_ARG;
 }
espconn_regist_write_finish()
sint8 espconn_regist_write_finish (struct espconn * espconn, espconn_connect_callback write_finish_fn)
Definition at line 732 of file espconn.c.
References ESPCONN_ARG, ESPCONN_OK, ESPCONN_UDP, ICACHE_FLASH_ATTR, NULL, espconn::proto, espconn::tcp, espconn::type, and _esp_tcp::write_finish_fn.
 {
     if (espconn == NULL || espconn ->proto.tcp == NULL || espconn->type == ESPCONN_UDP) {
         return ESPCONN_ARG;
     }
     espconn ->proto.tcp->write_finish_fn = write_finish_fn;
     return ESPCONN_OK;
 }
espconn_secure_accept()
sint8 espconn_secure_accept (struct espconn * espconn)
espconn_secure_ca_disable()
bool espconn_secure_ca_disable (uint8 level)
espconn_secure_ca_enable()
bool espconn_secure_ca_enable (uint8 level, uint32 flash_sector)
espconn_secure_cert_req_disable()
bool espconn_secure_cert_req_disable (uint8 level)
espconn_secure_cert_req_enable()
bool espconn_secure_cert_req_enable (uint8 level, uint32 flash_sector)
espconn_secure_connect()
sint8 espconn_secure_connect (struct espconn * espconn)
Referenced by MQTT_Connect(), and mqtt_dns_found().
espconn_secure_delete()
sint8 espconn_secure_delete (struct espconn * espconn)
espconn_secure_disconnect()
sint8 espconn_secure_disconnect (struct espconn * espconn)
Referenced by MQTT_Task(), and mqtt_tcpclient_recv().
espconn_secure_get_size()
sint16 espconn_secure_get_size (uint8 level)
espconn_secure_send()
sint8 espconn_secure_send (struct espconn * espconn, uint8 * psent, uint16 length)
Referenced by mqtt_send_keepalive(), MQTT_Task(), and mqtt_tcpclient_connect_cb().
espconn_secure_sent()
sint8 espconn_secure_sent (struct espconn * espconn, uint8 * psent, uint16 length)
espconn_secure_set_default_certificate()
bool espconn_secure_set_default_certificate (const uint8 * certificate, uint16 length)
espconn_secure_set_default_private_key()
bool espconn_secure_set_default_private_key (const uint8 * private_key, uint16 length)
espconn_secure_set_size()
bool espconn_secure_set_size (uint8 level, uint16 size)
espconn_send()
sint8 espconn_send (struct espconn * espconn, uint8 * psent, uint16 length)
espconn_sendto()
sint16 espconn_sendto (struct espconn * espconn, uint8 * psent, uint16 length)
Definition at line 448 of file espconn.c.
References __attribute__(), ESPCONN_ARG, espconn_find_connection(), ESPCONN_OK, espconn_send(), ESPCONN_UDP, espconn_udp_sendto(), NULL, and espconn::type.
Referenced by captdnsRecv().
 {
     espconn_msg *pnode = NULL;
     bool value = false;
     err_t error = ESPCONN_OK;
     if (espconn == NULL || psent == NULL || length == 0) {
         return ESPCONN_ARG;
     }
     /*Find the node depend on the espconn message*/
     value = espconn_find_connection(espconn, &pnode);
     if (value && espconn->type == ESPCONN_UDP)
         return espconn_udp_sendto(pnode, psent, length);
     else
         return ESPCONN_ARG;
 }
espconn_sent()
sint8 espconn_sent (struct espconn * espconn, uint8 * psent, uint16 length)
Definition at line 368 of file espconn.c.
References ESPCONN_ARG, espconn_copy_disabled, espconn_copy_enabled, espconn_find_connection(), ESPCONN_MAXNUM, ESPCONN_MEM, ESPCONN_OK, espconn_pbuf_create(), ESPCONN_TCP, espconn_tcp_get_buf_count(), espconn_tcp_write(), ESPCONN_UDP, espconn_udp_sent(), ESPCONN_WRITE, ICACHE_FLASH_ATTR, _espconn_buf::len, NULL, os_zalloc, _espconn_buf::payload, _comon_pkt::pbuf, _comon_pkt::pbuf_num, _comon_pkt::pcb, _espconn_msg::pcommon, _comon_pkt::ptail, _espconn_buf::punsent, espconn::state, TCP_SND_QUEUELEN, _espconn_buf::unsent, and _comon_pkt::write_flag.
 {
     espconn_msg *pnode = NULL;
     bool value = false;
     err_t error = ESPCONN_OK;
     if (espconn == NULL || psent == NULL || length == 0) {
         return ESPCONN_ARG;
     }
     /*Find the node depend on the espconn message*/
     value = espconn_find_connection(espconn, &pnode);
     if (value){
         espconn ->state = ESPCONN_WRITE;
         switch (espconn ->type) {
             case ESPCONN_TCP:
                 /* calling sent function frequently,make sure last packet has been backup or sent fully*/
                 if (pnode->pcommon.write_flag){
                     espconn_buf *pbuf = NULL;
                     /*If total number of espconn_buf on the unsent lists exceeds the set maximum, return an error */
                     if (espconn_copy_enabled(pnode)){
                         if (espconn_tcp_get_buf_count(pnode->pcommon.pbuf) >= pnode ->pcommon.pbuf_num)
                             return ESPCONN_MAXNUM;
                     } else {
                         struct tcp_pcb *pcb = pnode->pcommon.pcb;
                         if (pcb->snd_queuelen >= TCP_SND_QUEUELEN)
                             return ESPCONN_MAXNUM;
                     }
                     pbuf = (espconn_buf*) os_zalloc(sizeof(espconn_buf));
                     if (pbuf == NULL)
                         return ESPCONN_MEM;
                     else {
                         /*Backup the application packet information for send more data*/
                         pbuf->payload = psent;
                         pbuf->punsent = pbuf->payload;
                         pbuf->unsent = length;
                         pbuf->len = length;
                         /*insert the espconn_pbuf to the list*/
                         espconn_pbuf_create(&pnode->pcommon.pbuf, pbuf);
                         if (pnode->pcommon.ptail == NULL)
                             pnode->pcommon.ptail = pbuf;
                     }
                     /*when set the data copy option. change the flag for next packet*/
                     if (espconn_copy_disabled(pnode))
                         pnode->pcommon.write_flag = false;
                     error = espconn_tcp_write(pnode);
 //                  if (error != ESPCONN_OK){
 //                      /*send the application packet fail,
 //                       * ensure that each allocated is deleted*/
 //                      espconn_pbuf_delete(&pnode->pcommon.pbuf, pbuf);
 //                      os_free(pbuf);
 //                      pbuf = NULL;
 //                  }
                     return error;
                 } else
                     return ESPCONN_ARG;
                 break;
             case ESPCONN_UDP:
                 return espconn_udp_sent(pnode, psent, length);
                 break;
             default :
                 break;
         }
     }
     return ESPCONN_ARG;
 }
espconn_set_keepalive()
sint8 espconn_set_keepalive (struct espconn * espconn, uint8 level, void * optarg)
Definition at line 1128 of file espconn.c.
References ESPCONN_ARG, espconn_find_connection(), espconn_keepalive_disabled, ESPCONN_KEEPCNT, ESPCONN_KEEPIDLE, ESPCONN_KEEPINTVL, ESPCONN_OK, ESPCONN_TCP, NULL, _comon_pkt::pcb, _espconn_msg::pcommon, and espconn::type.
 {
     espconn_msg *pnode = NULL;
     bool value = false;
     sint8 ret = ESPCONN_OK;
     if (espconn == NULL || optarg == NULL) {
         return ESPCONN_ARG;;
     } else if (espconn->type != ESPCONN_TCP)
         return ESPCONN_ARG;
     /*Find the node depend on the espconn message*/
     value = espconn_find_connection(espconn, &pnode);
     if (value && espconn_keepalive_disabled(pnode)) {
         struct tcp_pcb *pcb = pnode->pcommon.pcb;
         switch (level){
             case ESPCONN_KEEPIDLE:
                 pcb->keep_idle = 1000 * (u32_t)(*(int*)optarg);
                 ret = ESPCONN_OK;
                 break;
             case ESPCONN_KEEPINTVL:
                 pcb->keep_intvl = 1000 * (u32_t)(*(int*)optarg);
                 ret = ESPCONN_OK;
                 break;
             case ESPCONN_KEEPCNT:
                 pcb->keep_cnt = (u32_t)(*(int*)optarg);
                 ret = ESPCONN_OK;
                 break;
             default:
                 ret = ESPCONN_ARG;
                 break;
         }
         return ret;
     } else
         return ESPCONN_ARG;
 }
espconn_set_opt()
sint8 espconn_set_opt (struct espconn * espconn, uint8 opt)
Definition at line 1056 of file espconn.c.
References ESPCONN_ARG, espconn_delay_disabled, espconn_find_connection(), espconn_keepalive_disabled, espconn_keepalive_enable, ESPCONN_OK, _comon_pkt::espconn_opt, ESPCONN_TCP, ICACHE_FLASH_ATTR, NULL, _comon_pkt::pcb, _espconn_msg::pcommon, and espconn::type.
 {
     espconn_msg *pnode = NULL;
     struct tcp_pcb *tpcb;
     bool value = false;
     if (espconn == NULL) {
         return ESPCONN_ARG;;
     } else if (espconn->type != ESPCONN_TCP)
         return ESPCONN_ARG;
     /*Find the node depend on the espconn message*/
     value = espconn_find_connection(espconn, &pnode);
     if (value) {
         pnode->pcommon.espconn_opt |= opt;
         tpcb = pnode->pcommon.pcb;
         if (espconn_delay_disabled(pnode))
             tcp_nagle_disable(tpcb);
         if (espconn_keepalive_disabled(pnode))
             espconn_keepalive_enable(tpcb);
         return ESPCONN_OK;
     } else
         return ESPCONN_ARG;
 }
espconn_tcp_get_max_con()
uint8 espconn_tcp_get_max_con (void)
Definition at line 528 of file espconn.c.
References MEMP_NUM_TCP_PCB.
Referenced by espconn_connect().
 {
     uint8 tcp_num = 0;
     tcp_num = MEMP_NUM_TCP_PCB;
     return tcp_num;
 }
espconn_tcp_get_max_con_allow()
sint8 espconn_tcp_get_max_con_allow (struct espconn * espconn)
Definition at line 618 of file espconn.c.
References _espconn_msg::count_opt, ESPCONN_ARG, ESPCONN_UDP, NULL, _espconn_msg::pespconn, _espconn_msg::pnext, pserver_list, and espconn::type.
 {
     espconn_msg *pget_msg = NULL;
     if ((espconn == NULL) || (espconn->type == ESPCONN_UDP))
         return ESPCONN_ARG;
     pget_msg = pserver_list;
     while (pget_msg != NULL){
         if (pget_msg->pespconn == espconn){
             return pget_msg->count_opt;
         }
         pget_msg = pget_msg->pnext;
     }
     return ESPCONN_ARG;
 }
espconn_tcp_set_max_con()
sint8 espconn_tcp_set_max_con (uint8 num)
Definition at line 543 of file espconn.c.
References ESPCONN_ARG, ESPCONN_OK, linkMax, and MEMP_NUM_TCP_PCB.
 {
     if (num == 0 || num > linkMax)
         return ESPCONN_ARG;
     MEMP_NUM_TCP_PCB = num;
     return ESPCONN_OK;
 }
espconn_tcp_set_max_con_allow()
sint8 espconn_tcp_set_max_con_allow (struct espconn * espconn, uint8 num)
Definition at line 640 of file espconn.c.
References _espconn_msg::count_opt, ESPCONN_ARG, ESPCONN_OK, ESPCONN_UDP, MEMP_NUM_TCP_PCB, NULL, _espconn_msg::pespconn, _espconn_msg::pnext, pserver_list, and espconn::type.
 {
     espconn_msg *pset_msg = NULL;
     if ((espconn == NULL) || (num > MEMP_NUM_TCP_PCB) || (espconn->type == ESPCONN_UDP))
         return ESPCONN_ARG;
     pset_msg = pserver_list;
     while (pset_msg != NULL){
         if (pset_msg->pespconn == espconn){
             pset_msg->count_opt = num;
             return ESPCONN_OK;
         }
         pset_msg = pset_msg->pnext;
     }
     return ESPCONN_ARG;
 }