MeterLogger: esp-open-lwip/lwip/core/sys.c File Reference
sys.c File Reference
#include "lwip/opt.h"
#include "lwip/sys.h"
Functions
void sys_msleep (u32_t ms)
Detailed Description
lwIP Operating System abstraction
Definition in file sys.c.
Function Documentation
sys_msleep()
void sys_msleep (u32_t ms)
Sleep for some ms. Timeouts are NOT processed while sleeping.
Parameters
ms number of milliseconds to sleep
Definition at line 54 of file sys.c.
References ERR_OK, sys_arch_sem_wait(), sys_sem_free(), and sys_sem_new().
 {
   if (ms > 0) {
     sys_sem_t delaysem;
     err_t err = sys_sem_new(&delaysem, 0);
     if (err == ERR_OK) {
       sys_arch_sem_wait(&delaysem, ms);
       sys_sem_free(&delaysem);
     }
   }
 }