MeterLogger: lib/heatshrink/test_heatshrink_dynamic.c File Reference
test_heatshrink_dynamic.c File Reference
#include <ctype.h>
#include <assert.h>
#include "heatshrink_encoder.h"
#include "heatshrink_decoder.h"
#include "greatest.h"
Data Structures
struct cfg_info
Functions
SUITE (encoding)
SUITE (decoding)
SUITE (integration)
static void dump_buf (char *name, uint8_t *buf, uint16_t count)
TEST encoder_alloc_should_reject_invalid_arguments (void)
TEST encoder_sink_should_reject_nulls (void)
TEST encoder_poll_should_reject_nulls (void)
TEST encoder_finish_should_reject_nulls (void)
TEST encoder_sink_should_accept_input_when_it_will_fit (void)
TEST encoder_sink_should_accept_partial_input_when_some_will_fit (void)
TEST encoder_poll_should_indicate_when_no_input_is_provided (void)
TEST encoder_should_emit_data_without_repetitions_as_literal_sequence (void)
TEST encoder_should_emit_series_of_same_byte_as_literal_then_backref (void)
TEST encoder_poll_should_detect_repeated_substring (void)
TEST encoder_poll_should_detect_repeated_substring_and_preserve_trailing_literal (void)
TEST decoder_alloc_should_reject_excessively_small_window (void)
TEST decoder_alloc_should_reject_zero_byte_input_buffer (void)
TEST decoder_sink_should_reject_null_hsd_pointer (void)
TEST decoder_sink_should_reject_null_input_pointer (void)
TEST decoder_sink_should_reject_null_count_pointer (void)
TEST decoder_sink_should_reject_excessively_large_input (void)
TEST decoder_sink_should_sink_data_when_preconditions_hold (void)
TEST decoder_poll_should_return_empty_if_empty (void)
TEST decoder_poll_should_reject_null_hsd (void)
TEST decoder_poll_should_reject_null_output_buffer (void)
TEST decoder_poll_should_reject_null_output_size_pointer (void)
TEST decoder_poll_should_expand_short_literal (void)
TEST decoder_poll_should_expand_short_literal_and_backref (void)
TEST decoder_poll_should_expand_short_self_overlapping_backref (void)
TEST decoder_poll_should_suspend_if_out_of_space_in_output_buffer_during_literal_expansion (void)
TEST decoder_poll_should_suspend_if_out_of_space_in_output_buffer_during_backref_expansion (void)
TEST decoder_poll_should_expand_short_literal_and_backref_when_fed_input_byte_by_byte (void)
TEST decoder_finish_should_reject_null_input (void)
TEST decoder_finish_should_note_when_done (void)
TEST gen (void)
TEST decoder_should_not_get_stuck_with_finish_yielding_MORE_but_0_bytes_output_from_poll (void)
static int compress_and_expand_and_check (uint8_t *input, uint32_t input_size, cfg_info *cfg)
TEST data_without_duplication_should_match (void)
TEST data_with_simple_repetition_should_compress_and_decompress_properly (void)
TEST data_without_duplication_should_match_with_absurdly_tiny_buffers (void)
TEST data_with_simple_repetition_should_match_with_absurdly_tiny_buffers (void)
static void fill_with_pseudorandom_letters (uint8_t *buf, uint32_t size, uint32_t seed)
TEST pseudorandom_data_should_match (uint32_t size, uint32_t seed, cfg_info *cfg)
TEST small_input_buffer_should_not_impact_decoder_correctness (void)
TEST regression_backreference_counters_should_not_roll_over (void)
TEST regression_index_fail (void)
TEST sixty_four_k (void)
GREATEST_MAIN_DEFS ()
int main (int argc, char **argv)
Function Documentation
compress_and_expand_and_check()
static int compress_and_expand_and_check (uint8_t * input, uint32_t input_size, cfg_info * cfg) static
Definition at line 638 of file test_heatshrink_dynamic.c.
References ASSERT, ASSERT_EQ, cfg_info::decoder_input_buffer_size, dump_buf(), FAILm, free, heatshrink_decoder_alloc(), heatshrink_decoder_finish(), heatshrink_decoder_free(), heatshrink_decoder_poll(), heatshrink_decoder_sink(), heatshrink_encoder_alloc(), heatshrink_encoder_finish(), heatshrink_encoder_free(), heatshrink_encoder_poll(), heatshrink_encoder_sink(), hsd, HSDR_FINISH_DONE, HSDR_FINISH_MORE, HSDR_POLL_EMPTY, HSDR_POLL_MORE, hse, HSER_FINISH_DONE, HSER_FINISH_MORE, HSER_POLL_EMPTY, HSER_POLL_MORE, cfg_info::log_lvl, cfg_info::lookahead_sz2, malloc, memset, PASS, printf, and cfg_info::window_sz2.
Referenced by data_with_simple_repetition_should_compress_and_decompress_properly(), data_without_duplication_should_match(), pseudorandom_data_should_match(), regression_backreference_counters_should_not_roll_over(), regression_index_fail(), sixty_four_k(), and small_input_buffer_should_not_impact_decoder_correctness().
data_with_simple_repetition_should_compress_and_decompress_properly()
TEST data_with_simple_repetition_should_compress_and_decompress_properly (void)
Definition at line 758 of file test_heatshrink_dynamic.c.
References compress_and_expand_and_check(), cfg_info::decoder_input_buffer_size, cfg_info::log_lvl, cfg_info::lookahead_sz2, and cfg_info::window_sz2.
Referenced by SUITE().
data_with_simple_repetition_should_match_with_absurdly_tiny_buffers()
TEST data_with_simple_repetition_should_match_with_absurdly_tiny_buffers (void)
Definition at line 812 of file test_heatshrink_dynamic.c.
References ASSERT, ASSERT_EQ, dump_buf(), heatshrink_decoder_alloc(), heatshrink_decoder_free(), heatshrink_decoder_poll(), heatshrink_decoder_sink(), heatshrink_encoder_alloc(), heatshrink_encoder_finish(), heatshrink_encoder_free(), heatshrink_encoder_poll(), heatshrink_encoder_sink(), hsd, hse, HSER_FINISH_MORE, and PASS.
Referenced by SUITE().
data_without_duplication_should_match()
TEST data_without_duplication_should_match (void)
Definition at line 746 of file test_heatshrink_dynamic.c.
References compress_and_expand_and_check(), cfg_info::decoder_input_buffer_size, cfg_info::log_lvl, cfg_info::lookahead_sz2, and cfg_info::window_sz2.
Referenced by SUITE().
data_without_duplication_should_match_with_absurdly_tiny_buffers()
TEST data_without_duplication_should_match_with_absurdly_tiny_buffers (void)
Definition at line 771 of file test_heatshrink_dynamic.c.
References ASSERT, ASSERT_EQ, dump_buf(), heatshrink_decoder_alloc(), heatshrink_decoder_free(), heatshrink_decoder_poll(), heatshrink_decoder_sink(), heatshrink_encoder_alloc(), heatshrink_encoder_finish(), heatshrink_encoder_free(), heatshrink_encoder_poll(), heatshrink_encoder_sink(), hsd, hse, HSER_FINISH_MORE, and PASS.
Referenced by SUITE().
decoder_alloc_should_reject_excessively_small_window()
TEST decoder_alloc_should_reject_excessively_small_window (void)
Definition at line 251 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, heatshrink_decoder_alloc(), HEATSHRINK_MIN_WINDOW_BITS, and PASS.
Referenced by SUITE().
decoder_alloc_should_reject_zero_byte_input_buffer()
TEST decoder_alloc_should_reject_zero_byte_input_buffer (void)
Definition at line 257 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, heatshrink_decoder_alloc(), HEATSHRINK_MIN_WINDOW_BITS, and PASS.
Referenced by SUITE().
decoder_finish_should_note_when_done()
TEST decoder_finish_should_note_when_done (void)
Definition at line 508 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, heatshrink_decoder_alloc(), heatshrink_decoder_finish(), heatshrink_decoder_free(), heatshrink_decoder_poll(), heatshrink_decoder_sink(), hsd, HSDR_FINISH_DONE, HSDR_POLL_EMPTY, HSDR_SINK_OK, memset, and PASS.
Referenced by SUITE().
decoder_finish_should_reject_null_input()
TEST decoder_finish_should_reject_null_input (void)
Definition at line 498 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, heatshrink_decoder_alloc(), heatshrink_decoder_finish(), heatshrink_decoder_free(), hsd, HSDR_FINISH_ERROR_NULL, and PASS.
Referenced by SUITE().
decoder_poll_should_expand_short_literal()
TEST decoder_poll_should_expand_short_literal (void)
Definition at line 358 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, heatshrink_decoder_alloc(), heatshrink_decoder_free(), heatshrink_decoder_poll(), heatshrink_decoder_sink(), hsd, HSDR_POLL_EMPTY, HSDR_SINK_OK, and PASS.
Referenced by SUITE().
decoder_poll_should_expand_short_literal_and_backref()
TEST decoder_poll_should_expand_short_literal_and_backref (void)
Definition at line 379 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, dump_buf(), heatshrink_decoder_alloc(), heatshrink_decoder_free(), heatshrink_decoder_poll(), heatshrink_decoder_sink(), hsd, HSDR_SINK_OK, memset, and PASS.
Referenced by SUITE().
decoder_poll_should_expand_short_literal_and_backref_when_fed_input_byte_by_byte()
TEST decoder_poll_should_expand_short_literal_and_backref_when_fed_input_byte_by_byte (void)
Definition at line 469 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, heatshrink_decoder_alloc(), heatshrink_decoder_finish(), heatshrink_decoder_free(), heatshrink_decoder_poll(), heatshrink_decoder_sink(), hsd, HSDR_POLL_EMPTY, HSDR_SINK_OK, memset, and PASS.
Referenced by SUITE().
decoder_poll_should_expand_short_self_overlapping_backref()
TEST decoder_poll_should_expand_short_self_overlapping_backref (void)
Definition at line 405 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, dump_buf(), heatshrink_decoder_alloc(), heatshrink_decoder_free(), heatshrink_decoder_poll(), heatshrink_decoder_sink(), hsd, HSDR_SINK_OK, and PASS.
Referenced by SUITE().
decoder_poll_should_reject_null_hsd()
TEST decoder_poll_should_reject_null_hsd (void)
Definition at line 330 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, heatshrink_decoder_poll(), HSDR_POLL_ERROR_NULL, and PASS.
Referenced by SUITE().
decoder_poll_should_reject_null_output_buffer()
TEST decoder_poll_should_reject_null_output_buffer (void)
Definition at line 338 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, heatshrink_decoder_alloc(), heatshrink_decoder_free(), heatshrink_decoder_poll(), HEATSHRINK_MIN_WINDOW_BITS, hsd, HSDR_POLL_ERROR_NULL, and PASS.
Referenced by SUITE().
decoder_poll_should_reject_null_output_size_pointer()
TEST decoder_poll_should_reject_null_output_size_pointer (void)
Definition at line 348 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, heatshrink_decoder_alloc(), heatshrink_decoder_free(), heatshrink_decoder_poll(), HEATSHRINK_MIN_WINDOW_BITS, hsd, HSDR_POLL_ERROR_NULL, and PASS.
Referenced by SUITE().
decoder_poll_should_return_empty_if_empty()
TEST decoder_poll_should_return_empty_if_empty (void)
Definition at line 319 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, heatshrink_decoder_alloc(), heatshrink_decoder_free(), heatshrink_decoder_poll(), HEATSHRINK_MIN_WINDOW_BITS, hsd, HSDR_POLL_EMPTY, and PASS.
Referenced by SUITE().
decoder_poll_should_suspend_if_out_of_space_in_output_buffer_during_backref_expansion()
TEST decoder_poll_should_suspend_if_out_of_space_in_output_buffer_during_backref_expansion (void)
Definition at line 446 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, heatshrink_decoder_alloc(), heatshrink_decoder_free(), heatshrink_decoder_poll(), heatshrink_decoder_sink(), hsd, HSDR_POLL_MORE, HSDR_SINK_OK, memset, and PASS.
Referenced by SUITE().
decoder_poll_should_suspend_if_out_of_space_in_output_buffer_during_literal_expansion()
TEST decoder_poll_should_suspend_if_out_of_space_in_output_buffer_during_literal_expansion (void)
Definition at line 427 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, heatshrink_decoder_alloc(), heatshrink_decoder_free(), heatshrink_decoder_poll(), heatshrink_decoder_sink(), hsd, HSDR_POLL_MORE, HSDR_SINK_OK, and PASS.
Referenced by SUITE().
decoder_should_not_get_stuck_with_finish_yielding_MORE_but_0_bytes_output_from_poll()
TEST decoder_should_not_get_stuck_with_finish_yielding_MORE_but_0_bytes_output_from_poll (void)
Definition at line 563 of file test_heatshrink_dynamic.c.
References ASSERT, ASSERT_EQ, heatshrink_decoder_alloc(), heatshrink_decoder_finish(), heatshrink_decoder_free(), heatshrink_decoder_poll(), heatshrink_decoder_reset(), heatshrink_decoder_sink(), hsd, HSDR_FINISH_DONE, HSDR_POLL_EMPTY, HSDR_SINK_OK, memset, and PASS.
Referenced by SUITE().
decoder_sink_should_reject_excessively_large_input()
TEST decoder_sink_should_reject_excessively_large_input (void)
Definition at line 288 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, heatshrink_decoder_alloc(), heatshrink_decoder_free(), heatshrink_decoder_sink(), HEATSHRINK_MIN_WINDOW_BITS, hsd, HSDR_SINK_FULL, HSDR_SINK_OK, and PASS.
Referenced by SUITE().
decoder_sink_should_reject_null_count_pointer()
TEST decoder_sink_should_reject_null_count_pointer (void)
Definition at line 279 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, heatshrink_decoder_alloc(), heatshrink_decoder_free(), heatshrink_decoder_sink(), HEATSHRINK_MIN_WINDOW_BITS, hsd, HSDR_SINK_ERROR_NULL, and PASS.
Referenced by SUITE().
decoder_sink_should_reject_null_hsd_pointer()
TEST decoder_sink_should_reject_null_hsd_pointer (void)
Definition at line 263 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, heatshrink_decoder_sink(), HSDR_SINK_ERROR_NULL, and PASS.
Referenced by SUITE().
decoder_sink_should_reject_null_input_pointer()
TEST decoder_sink_should_reject_null_input_pointer (void)
Definition at line 270 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, heatshrink_decoder_alloc(), heatshrink_decoder_free(), heatshrink_decoder_sink(), HEATSHRINK_MIN_WINDOW_BITS, hsd, HSDR_SINK_ERROR_NULL, and PASS.
Referenced by SUITE().
decoder_sink_should_sink_data_when_preconditions_hold()
TEST decoder_sink_should_sink_data_when_preconditions_hold (void)
Definition at line 306 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, heatshrink_decoder_alloc(), heatshrink_decoder_free(), heatshrink_decoder_sink(), HEATSHRINK_MIN_WINDOW_BITS, hsd, HSDR_SINK_OK, heatshrink_decoder::input_index, heatshrink_decoder::input_size, and PASS.
Referenced by SUITE().
dump_buf()
static void dump_buf (char * name, uint8_t * buf, uint16_t count) static
Definition at line 20 of file test_heatshrink_dynamic.c.
References printf.
Referenced by compress_and_expand_and_check(), data_with_simple_repetition_should_match_with_absurdly_tiny_buffers(), data_without_duplication_should_match_with_absurdly_tiny_buffers(), decoder_poll_should_expand_short_literal_and_backref(), decoder_poll_should_expand_short_self_overlapping_backref(), encoder_poll_should_detect_repeated_substring(), encoder_poll_should_detect_repeated_substring_and_preserve_trailing_literal(), and encoder_should_emit_series_of_same_byte_as_literal_then_backref().
encoder_alloc_should_reject_invalid_arguments()
TEST encoder_alloc_should_reject_invalid_arguments (void)
Definition at line 27 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, heatshrink_encoder_alloc(), HEATSHRINK_MAX_WINDOW_BITS, HEATSHRINK_MIN_LOOKAHEAD_BITS, HEATSHRINK_MIN_WINDOW_BITS, and PASS.
Referenced by SUITE().
encoder_finish_should_reject_nulls()
TEST encoder_finish_should_reject_nulls (void)
Definition at line 64 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, heatshrink_encoder_finish(), HSER_FINISH_ERROR_NULL, and PASS.
Referenced by SUITE().
encoder_poll_should_detect_repeated_substring()
TEST encoder_poll_should_detect_repeated_substring (void)
Definition at line 180 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, dump_buf(), heatshrink_encoder_alloc(), heatshrink_encoder_finish(), heatshrink_encoder_free(), heatshrink_encoder_poll(), heatshrink_encoder_sink(), hse, HSER_FINISH_DONE, HSER_FINISH_MORE, HSER_POLL_EMPTY, HSER_SINK_OK, memset, and PASS.
Referenced by SUITE().
encoder_poll_should_detect_repeated_substring_and_preserve_trailing_literal()
TEST encoder_poll_should_detect_repeated_substring_and_preserve_trailing_literal (void)
Definition at line 207 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, dump_buf(), heatshrink_encoder_alloc(), heatshrink_encoder_finish(), heatshrink_encoder_free(), heatshrink_encoder_poll(), heatshrink_encoder_sink(), hse, HSER_FINISH_DONE, HSER_FINISH_MORE, HSER_POLL_EMPTY, HSER_SINK_OK, memset, and PASS.
Referenced by SUITE().
encoder_poll_should_indicate_when_no_input_is_provided()
TEST encoder_poll_should_indicate_when_no_input_is_provided (void)
Definition at line 97 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, heatshrink_encoder_alloc(), heatshrink_encoder_free(), heatshrink_encoder_poll(), hse, HSER_POLL_EMPTY, and PASS.
Referenced by SUITE().
encoder_poll_should_reject_nulls()
TEST encoder_poll_should_reject_nulls (void)
Definition at line 49 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, heatshrink_encoder_alloc(), heatshrink_encoder_free(), heatshrink_encoder_poll(), hse, HSER_POLL_ERROR_NULL, and PASS.
Referenced by SUITE().
encoder_should_emit_data_without_repetitions_as_literal_sequence()
TEST encoder_should_emit_data_without_repetitions_as_literal_sequence (void)
Definition at line 109 of file test_heatshrink_dynamic.c.
References ASSERT, ASSERT_EQ, heatshrink_encoder_alloc(), heatshrink_encoder_finish(), heatshrink_encoder_free(), heatshrink_encoder_poll(), heatshrink_encoder_sink(), hse, HSER_FINISH_DONE, HSER_FINISH_MORE, HSER_POLL_EMPTY, HSER_SINK_OK, memset, and PASS.
Referenced by SUITE().
encoder_should_emit_series_of_same_byte_as_literal_then_backref()
TEST encoder_should_emit_series_of_same_byte_as_literal_then_backref (void)
Definition at line 145 of file test_heatshrink_dynamic.c.
References ASSERT, ASSERT_EQ, dump_buf(), heatshrink_encoder_alloc(), heatshrink_encoder_finish(), heatshrink_encoder_free(), heatshrink_encoder_poll(), heatshrink_encoder_sink(), hse, HSER_FINISH_DONE, HSER_FINISH_MORE, HSER_POLL_EMPTY, HSER_SINK_OK, memset, and PASS.
Referenced by SUITE().
encoder_sink_should_accept_input_when_it_will_fit()
TEST encoder_sink_should_accept_input_when_it_will_fit (void)
Definition at line 69 of file test_heatshrink_dynamic.c.
References ASSERT, ASSERT_EQ, heatshrink_encoder_alloc(), heatshrink_encoder_free(), heatshrink_encoder_sink(), hse, HSER_SINK_OK, memset, and PASS.
Referenced by SUITE().
encoder_sink_should_accept_partial_input_when_some_will_fit()
TEST encoder_sink_should_accept_partial_input_when_some_will_fit (void)
Definition at line 83 of file test_heatshrink_dynamic.c.
References ASSERT, ASSERT_EQ, heatshrink_encoder_alloc(), heatshrink_encoder_free(), heatshrink_encoder_sink(), hse, HSER_SINK_OK, memset, and PASS.
Referenced by SUITE().
encoder_sink_should_reject_nulls()
TEST encoder_sink_should_reject_nulls (void)
Definition at line 37 of file test_heatshrink_dynamic.c.
References ASSERT, ASSERT_EQ, heatshrink_encoder_alloc(), heatshrink_encoder_free(), heatshrink_encoder_sink(), hse, HSER_SINK_ERROR_NULL, and PASS.
Referenced by SUITE().
fill_with_pseudorandom_letters()
static void fill_with_pseudorandom_letters (uint8_t * buf, uint32_t size, uint32_t seed) static
Definition at line 854 of file test_heatshrink_dynamic.c.
References hs_index::size.
Referenced by pseudorandom_data_should_match(), regression_backreference_counters_should_not_roll_over(), regression_index_fail(), and sixty_four_k().
gen()
TEST gen (void)
Definition at line 537 of file test_heatshrink_dynamic.c.
References ASSERT_EQ, heatshrink_encoder_alloc(), heatshrink_encoder_finish(), heatshrink_encoder_free(), heatshrink_encoder_poll(), heatshrink_encoder_sink(), hse, HSER_FINISH_DONE, HSER_FINISH_MORE, HSER_POLL_EMPTY, HSER_SINK_OK, memset, PASS, and printf.
Referenced by SUITE().
GREATEST_MAIN_DEFS()
GREATEST_MAIN_DEFS ()
Referenced by SUITE().
main()
int main (int argc, char ** argv)
Definition at line 989 of file test_heatshrink_dynamic.c.
References GREATEST_MAIN_BEGIN, GREATEST_MAIN_END, and RUN_SUITE.
pseudorandom_data_should_match()
TEST pseudorandom_data_should_match (uint32_t size, uint32_t seed, cfg_info * cfg)
Definition at line 862 of file test_heatshrink_dynamic.c.
References compress_and_expand_and_check(), cfg_info::decoder_input_buffer_size, fill_with_pseudorandom_letters(), cfg_info::log_lvl, printf, and hs_index::size.
Referenced by SUITE().
regression_backreference_counters_should_not_roll_over()
TEST regression_backreference_counters_should_not_roll_over (void)
Definition at line 885 of file test_heatshrink_dynamic.c.
References compress_and_expand_and_check(), cfg_info::decoder_input_buffer_size, fill_with_pseudorandom_letters(), cfg_info::log_lvl, cfg_info::lookahead_sz2, hs_index::size, and cfg_info::window_sz2.
Referenced by SUITE().
regression_index_fail()
TEST regression_index_fail (void)
Definition at line 900 of file test_heatshrink_dynamic.c.
References compress_and_expand_and_check(), cfg_info::decoder_input_buffer_size, fill_with_pseudorandom_letters(), cfg_info::log_lvl, cfg_info::lookahead_sz2, hs_index::size, and cfg_info::window_sz2.
Referenced by SUITE().
sixty_four_k()
TEST sixty_four_k (void)
Definition at line 917 of file test_heatshrink_dynamic.c.
References compress_and_expand_and_check(), cfg_info::decoder_input_buffer_size, fill_with_pseudorandom_letters(), cfg_info::log_lvl, cfg_info::lookahead_sz2, hs_index::size, and cfg_info::window_sz2.
Referenced by SUITE().
small_input_buffer_should_not_impact_decoder_correctness()
TEST small_input_buffer_should_not_impact_decoder_correctness (void)
Definition at line 872 of file test_heatshrink_dynamic.c.
References compress_and_expand_and_check(), cfg_info::decoder_input_buffer_size, cfg_info::log_lvl, cfg_info::lookahead_sz2, PASS, hs_index::size, and cfg_info::window_sz2.
Referenced by SUITE().
SUITE() [1/3]
SUITE (encoding)
Definition at line 233 of file test_heatshrink_dynamic.c.
References encoder_alloc_should_reject_invalid_arguments(), encoder_finish_should_reject_nulls(), encoder_poll_should_detect_repeated_substring(), encoder_poll_should_detect_repeated_substring_and_preserve_trailing_literal(), encoder_poll_should_indicate_when_no_input_is_provided(), encoder_poll_should_reject_nulls(), encoder_should_emit_data_without_repetitions_as_literal_sequence(), encoder_should_emit_series_of_same_byte_as_literal_then_backref(), encoder_sink_should_accept_input_when_it_will_fit(), encoder_sink_should_accept_partial_input_when_some_will_fit(), encoder_sink_should_reject_nulls(), and RUN_TEST.
SUITE() [2/3]
SUITE (decoding)
Definition at line 601 of file test_heatshrink_dynamic.c.
References decoder_alloc_should_reject_excessively_small_window(), decoder_alloc_should_reject_zero_byte_input_buffer(), decoder_finish_should_note_when_done(), decoder_finish_should_reject_null_input(), decoder_poll_should_expand_short_literal(), decoder_poll_should_expand_short_literal_and_backref(), decoder_poll_should_expand_short_literal_and_backref_when_fed_input_byte_by_byte(), decoder_poll_should_expand_short_self_overlapping_backref(), decoder_poll_should_reject_null_hsd(), decoder_poll_should_reject_null_output_buffer(), decoder_poll_should_reject_null_output_size_pointer(), decoder_poll_should_return_empty_if_empty(), decoder_poll_should_suspend_if_out_of_space_in_output_buffer_during_backref_expansion(), decoder_poll_should_suspend_if_out_of_space_in_output_buffer_during_literal_expansion(), decoder_should_not_get_stuck_with_finish_yielding_MORE_but_0_bytes_output_from_poll(), decoder_sink_should_reject_excessively_large_input(), decoder_sink_should_reject_null_count_pointer(), decoder_sink_should_reject_null_hsd_pointer(), decoder_sink_should_reject_null_input_pointer(), decoder_sink_should_sink_data_when_preconditions_hold(), gen(), and RUN_TEST.
SUITE() [3/3]
SUITE (integration)
Definition at line 932 of file test_heatshrink_dynamic.c.
References data_with_simple_repetition_should_compress_and_decompress_properly(), data_with_simple_repetition_should_match_with_absurdly_tiny_buffers(), data_without_duplication_should_match(), data_without_duplication_should_match_with_absurdly_tiny_buffers(), cfg_info::decoder_input_buffer_size, GREATEST_IS_VERBOSE, GREATEST_MAIN_DEFS(), cfg_info::log_lvl, cfg_info::lookahead_sz2, printf, pseudorandom_data_should_match(), regression_backreference_counters_should_not_roll_over(), regression_index_fail(), RUN_TEST, RUN_TESTp, sixty_four_k(), hs_index::size, small_input_buffer_should_not_impact_decoder_correctness(), and cfg_info::window_sz2.