MeterLogger: esp-open-lwip/include/lwip/timers.h File Reference
timers.h File Reference
#include "lwip/opt.h"
#include "lwip/err.h"
#include "lwip/sys.h"
Data Structures
struct sys_timeo
Macros
#define LWIP_TIMERS (!NO_SYS || (NO_SYS && !NO_SYS_NO_TIMERS))
#define LWIP_DEBUG_TIMERNAMES 0
Typedefs
typedef void(* sys_timeout_handler) (void *arg)
Functions
void sys_timeouts_init (void) ICACHE_FLASH_ATTR
void sys_timeout (u32_t msecs, sys_timeout_handler handler, void *arg) ICACHE_FLASH_ATTR
void sys_untimeout (sys_timeout_handler handler, void *arg) ICACHE_FLASH_ATTR
void sys_timeouts_mbox_fetch (sys_mbox_t *mbox, void **msg)
Macro Definition Documentation
LWIP_DEBUG_TIMERNAMES
#define LWIP_DEBUG_TIMERNAMES 0
Definition at line 54 of file timers.h.
LWIP_TIMERS
#define LWIP_TIMERS (!NO_SYS || (NO_SYS && !NO_SYS_NO_TIMERS))
Definition at line 39 of file timers.h.
Typedef Documentation
sys_timeout_handler
typedef void(* sys_timeout_handler) (void *arg)
Function prototype for a timeout callback function. Register such a function using sys_timeout().
Parameters
arg Additional argument to pass to the function - set up by sys_timeout()
Definition at line 63 of file timers.h.
Function Documentation
sys_timeout()
void sys_timeout (u32_t msecs, sys_timeout_handler handler, void * arg)
Referenced by tcpip_thread().
sys_timeouts_init()
void sys_timeouts_init (void)
Referenced by lwip_init().
sys_timeouts_mbox_fetch()
void sys_timeouts_mbox_fetch (sys_mbox_t * mbox, void ** msg)
Referenced by tcpip_thread().
sys_untimeout()
void sys_untimeout (sys_timeout_handler handler, void * arg)
Referenced by tcpip_thread().