MeterLogger: user/tinyprintf.c File Reference
tinyprintf.c File Reference
#include <esp8266.h>
#include "tinyprintf.h"
#include <sys/types.h>
Data Structures
struct param
struct _vsnprintf_putcf_data
struct _vsprintf_putcf_data
Macros
#define PRINTF_LONG_SUPPORT
#define PRINTF_LONG_LONG_SUPPORT
#define PRINTF_SIZE_T_SUPPORT
#define PRINTF_LONG_SUPPORT
#define _TFP_GCC_NO_INLINE_
Functions
static ICACHE_FLASH_ATTR void _TFP_GCC_NO_INLINE_ ulli2a (unsigned long long int num, struct param *p)
static ICACHE_FLASH_ATTR void lli2a (long long int num, struct param *p)
static ICACHE_FLASH_ATTR void uli2a (unsigned long int num, struct param *p)
static ICACHE_FLASH_ATTR void li2a (long num, struct param *p)
static ICACHE_FLASH_ATTR void ui2a (unsigned int num, struct param *p)
static ICACHE_FLASH_ATTR void i2a (int num, struct param *p)
static ICACHE_FLASH_ATTR int a2d (char ch)
static ICACHE_FLASH_ATTR char a2u (char ch, const char **src, int base, unsigned int *nump)
static ICACHE_FLASH_ATTR void putchw (void *putp, putcf putf, struct param *p)
ICACHE_FLASH_ATTR void tfp_format (void *putp, putcf putf, const char *fmt, va_list va)
ICACHE_FLASH_ATTR void init_printf (void *putp, putcf putf)
ICACHE_FLASH_ATTR void tfp_printf (char *fmt,...)
static ICACHE_FLASH_ATTR void _vsnprintf_putcf (void *p, char c)
ICACHE_FLASH_ATTR int tfp_vsnprintf (char *str, size_t size, const char *format, va_list ap)
ICACHE_FLASH_ATTR int tfp_snprintf (char *str, size_t size, const char *format,...)
static ICACHE_FLASH_ATTR void _vsprintf_putcf (void *p, char c)
ICACHE_FLASH_ATTR int tfp_vsprintf (char *str, const char *format, va_list ap)
ICACHE_FLASH_ATTR int tfp_sprintf (char *str, const char *format,...)
Variables
static putcf stdout_putf
static void * stdout_putp
Macro Definition Documentation
_TFP_GCC_NO_INLINE_
#define _TFP_GCC_NO_INLINE_
Definition at line 68 of file tinyprintf.c.
PRINTF_LONG_LONG_SUPPORT
#define PRINTF_LONG_LONG_SUPPORT
Definition at line 35 of file tinyprintf.c.
PRINTF_LONG_SUPPORT [1/2]
#define PRINTF_LONG_SUPPORT
Definition at line 48 of file tinyprintf.c.
PRINTF_LONG_SUPPORT [2/2]
#define PRINTF_LONG_SUPPORT
Definition at line 48 of file tinyprintf.c.
PRINTF_SIZE_T_SUPPORT
#define PRINTF_SIZE_T_SUPPORT
Definition at line 38 of file tinyprintf.c.
Function Documentation
_vsnprintf_putcf()
static ICACHE_FLASH_ATTR void _vsnprintf_putcf (void * p, char c) static
Definition at line 452 of file tinyprintf.c.
References _vsnprintf_putcf_data::dest, _vsnprintf_putcf_data::dest_capacity, and _vsnprintf_putcf_data::num_chars.
Referenced by tfp_vsnprintf().
 {
   struct _vsnprintf_putcf_data *data = (struct _vsnprintf_putcf_data*)p;
   if (data->num_chars < data->dest_capacity)
     data->dest[data->num_chars] = c;
   data->num_chars ++;
 }
_vsprintf_putcf()
static ICACHE_FLASH_ATTR void _vsprintf_putcf (void * p, char c) static
Definition at line 497 of file tinyprintf.c.
References _vsprintf_putcf_data::dest, and _vsprintf_putcf_data::num_chars.
Referenced by tfp_vsprintf().
 {
   struct _vsprintf_putcf_data *data = (struct _vsprintf_putcf_data*)p;
   data->dest[data->num_chars++] = c;
 }
a2d()
static ICACHE_FLASH_ATTR int a2d (char ch) static
Definition at line 175 of file tinyprintf.c.
Referenced by a2u().
 {
     if (ch >= '0' && ch <= '9')
         return ch - '0';
     else if (ch >= 'a' && ch <= 'f')
         return ch - 'a' + 10;
     else if (ch >= 'A' && ch <= 'F')
         return ch - 'A' + 10;
     else
         return -1;
 }
a2u()
static ICACHE_FLASH_ATTR char a2u (char ch, const char ** src, int base, unsigned int * nump) static
Definition at line 187 of file tinyprintf.c.
References a2d().
Referenced by tfp_format().
 {
     const char *p = *src;
     unsigned int num = 0;
     int digit;
     while ((digit = a2d(ch)) >= 0) {
         if (digit > base)
             break;
         num = num * base + digit;
         ch = *p++;
     }
     *src = p;
     *nump = num;
     return ch;
 }
i2a()
static ICACHE_FLASH_ATTR void i2a (int num, struct param * p) static
Definition at line 166 of file tinyprintf.c.
References param::sign, and ui2a().
Referenced by tfp_format().
 {
     if (num < 0) {
         num = -num;
         p->sign = '-';
     }
     ui2a(num, p);
 }
init_printf()
ICACHE_FLASH_ATTR void init_printf (void * putp, putcf putf)
Definition at line 429 of file tinyprintf.c.
References stdout_putf, and stdout_putp.
 {
     stdout_putf = putf;
     stdout_putp = putp;
 }
li2a()
static ICACHE_FLASH_ATTR void li2a (long num, struct param * p) static
Definition at line 137 of file tinyprintf.c.
References param::sign, and uli2a().
Referenced by tfp_format().
 {
     if (num < 0) {
         num = -num;
         p->sign = '-';
     }
     uli2a(num, p);
 }
lli2a()
static ICACHE_FLASH_ATTR void lli2a (long long int num, struct param * p) static
Definition at line 107 of file tinyprintf.c.
References param::sign, and ulli2a().
Referenced by tfp_format().
 {
     if (num < 0) {
         num = -num;
         p->sign = '-';
     }
     ulli2a(num, p);
 }
putchw()
static ICACHE_FLASH_ATTR void putchw (void * putp, putcf putf, struct param * p) static
Definition at line 203 of file tinyprintf.c.
References param::align_left, param::alt, param::base, param::bf, param::lz, param::sign, param::uc, and param::width.
Referenced by tfp_format().
 {
     char ch;
     int n = p->width;
     char *bf = p->bf;
     /* Number of filling characters */
     while (*bf++ && n > 0)
         n--;
     if (p->sign)
         n--;
     if (p->alt && p->base == 16)
         n -= 2;
     else if (p->alt && p->base == 8)
         n--;
     /* Fill with space to align to the right, before alternate or sign */
     if (!p->lz && !p->align_left) {
         while (n-- > 0)
             putf(putp, ' ');
     }
     /* print sign */
     if (p->sign)
         putf(putp, p->sign);
     /* Alternate */
     if (p->alt && p->base == 16) {
         putf(putp, '0');
         putf(putp, (p->uc ? 'X' : 'x'));
     } else if (p->alt && p->base == 8) {
         putf(putp, '0');
     }
     /* Fill with zeros, after alternate or sign */
     if (p->lz) {
         while (n-- > 0)
             putf(putp, '0');
     }
     /* Put actual buffer */
     bf = p->bf;
     while ((ch = *bf++))
         putf(putp, ch);
     /* Fill with space to align to the left, after string */
     if (!p->lz && p->align_left) {
         while (n-- > 0)
             putf(putp, ' ');
     }
 }
tfp_format()
ICACHE_FLASH_ATTR void tfp_format (void * putp, putcf putf, const char * fmt, va_list va)
Definition at line 255 of file tinyprintf.c.
References a2u(), param::align_left, param::alt, param::base, param::bf, i2a(), li2a(), lli2a(), param::lz, putchw(), param::sign, param::uc, ui2a(), uli2a(), ulli2a(), and param::width.
Referenced by tfp_printf(), tfp_vsnprintf(), and tfp_vsprintf().
 {
     struct param p;
 #ifdef PRINTF_LONG_SUPPORT
     char bf[23];  /* long = 64b on some architectures */
 #else
     char bf[12];  /* int = 32b on some architectures */
 #endif
     char ch;
     p.bf = bf;
     while ((ch = *(fmt++))) {
         if (ch != '%') {
             putf(putp, ch);
         } else {
 #ifdef PRINTF_LONG_SUPPORT
             char lng = 0;  /* 1 for long, 2 for long long */
 #endif
             /* Init parameter struct */
             p.lz = 0;
             p.alt = 0;
             p.width = 0;
             p.align_left = 0;
             p.sign = 0;
             /* Flags */
             while ((ch = *(fmt++))) {
                 switch (ch) {
                 case '-':
                     p.align_left = 1;
                     continue;
                 case '0':
                     p.lz = 1;
                     continue;
                 case '#':
                     p.alt = 1;
                     continue;
                 default:
                     break;
                 }
                 break;
             }
             /* Width */
             if (ch >= '0' && ch <= '9') {
                 ch = a2u(ch, &fmt, 10, &(p.width));
             }
             /* We accept 'x.y' format but don't support it completely:
              * we ignore the 'y' digit => this ignores 0-fill
              * size and makes it == width (ie. 'x') */
             if (ch == '.') {
               p.lz = 1;  /* zero-padding */
               /* ignore actual 0-fill size: */
               do {
                 ch = *(fmt++);
               } while ((ch >= '0') && (ch <= '9'));
             }
 #ifdef PRINTF_SIZE_T_SUPPORT
 # ifdef PRINTF_LONG_SUPPORT
             if (ch == 'z') {
                 ch = *(fmt++);
                 if (sizeof(size_t) == sizeof(unsigned long int))
                     lng = 1;
 #  ifdef PRINTF_LONG_LONG_SUPPORT
                 else if (sizeof(size_t) == sizeof(unsigned long long int))
                     lng = 2;
 #  endif
             } else
 # endif
 #endif
 #ifdef PRINTF_LONG_SUPPORT
             if (ch == 'l') {
                 ch = *(fmt++);
                 lng = 1;
 #ifdef PRINTF_LONG_LONG_SUPPORT
                 if (ch == 'l') {
                   ch = *(fmt++);
                   lng = 2;
                 }
 #endif
             }
 #endif
             switch (ch) {
             case 0:
                 goto abort;
             case 'u':
                 p.base = 10;
 #ifdef PRINTF_LONG_SUPPORT
 #ifdef PRINTF_LONG_LONG_SUPPORT
                 if (2 == lng)
                     ulli2a(va_arg(va, unsigned long long int), &p);
                 else
 #endif
                   if (1 == lng)
                     uli2a(va_arg(va, unsigned long int), &p);
                 else
 #endif
                     ui2a(va_arg(va, unsigned int), &p);
                 putchw(putp, putf, &p);
                 break;
             case 'd':
             case 'i':
                 p.base = 10;
 #ifdef PRINTF_LONG_SUPPORT
 #ifdef PRINTF_LONG_LONG_SUPPORT
                 if (2 == lng)
                     lli2a(va_arg(va, long long int), &p);
                 else
 #endif
                   if (1 == lng)
                     li2a(va_arg(va, long int), &p);
                 else
 #endif
                     i2a(va_arg(va, int), &p);
                 putchw(putp, putf, &p);
                 break;
 #ifdef SIZEOF_POINTER
             case 'p':
                 p.alt = 1;
 # if defined(SIZEOF_INT) && SIZEOF_POINTER <= SIZEOF_INT
                 lng = 0;
 # elif defined(SIZEOF_LONG) && SIZEOF_POINTER <= SIZEOF_LONG
                 lng = 1;
 # elif defined(SIZEOF_LONG_LONG) && SIZEOF_POINTER <= SIZEOF_LONG_LONG
                 lng = 2;
 # endif
 #endif
             case 'x':
             case 'X':
                 p.base = 16;
                 p.uc = (ch == 'X')?1:0;
 #ifdef PRINTF_LONG_SUPPORT
 #ifdef PRINTF_LONG_LONG_SUPPORT
                 if (2 == lng)
                     ulli2a(va_arg(va, unsigned long long int), &p);
                 else
 #endif
                   if (1 == lng)
                     uli2a(va_arg(va, unsigned long int), &p);
                 else
 #endif
                     ui2a(va_arg(va, unsigned int), &p);
                 putchw(putp, putf, &p);
                 break;
             case 'o':
                 p.base = 8;
                 ui2a(va_arg(va, unsigned int), &p);
                 putchw(putp, putf, &p);
                 break;
             case 'c':
                 putf(putp, (char)(va_arg(va, int)));
                 break;
             case 's':
                 p.bf = va_arg(va, char *);
                 putchw(putp, putf, &p);
                 p.bf = bf;
                 break;
             case '%':
                 putf(putp, ch);
             default:
                 break;
             }
         }
     }
  abort:;
 }
tfp_printf()
ICACHE_FLASH_ATTR void tfp_printf (char * fmt, ...)
Definition at line 435 of file tinyprintf.c.
References stdout_putf, stdout_putp, and tfp_format().
 {
     va_list va;
     va_start(va, fmt);
     tfp_format(stdout_putp, stdout_putf, fmt, va);
     va_end(va);
 }
tfp_snprintf()
ICACHE_FLASH_ATTR int tfp_snprintf (char * str, size_t size, const char * format, ...)
Definition at line 480 of file tinyprintf.c.
References tfp_vsnprintf().
Referenced by cfg_load(), cgiWiFiScan(), cleanup_decimal_str(), divide_str_by_10(), divide_str_by_100(), en61107_received_task(), en61107_response_set_unit(), en61107_response_set_value(), httpdHeader(), httpdRedirect(), httpdStartResponse(), kmp_received_task(), kmp_request_send(), kmp_value_to_string(), kw_to_w_str(), parse_mc66cde_inst_values_frame(), parse_mc66cde_standard_data_1_frame(), tplSetup(), w_to_kw_str(), wifi_connect(), wifi_default(), wifi_fallback(), and wifi_softap_config().
 {
   va_list ap;
   int retval;
   va_start(ap, format);
   retval = tfp_vsnprintf(str, size, format, ap);
   va_end(ap);
   return retval;
 }
tfp_sprintf()
ICACHE_FLASH_ATTR int tfp_sprintf (char * str, const char * format, ...)
Definition at line 513 of file tinyprintf.c.
References tfp_vsprintf().
 {
   va_list ap;
   int retval;
   va_start(ap, format);
   retval = tfp_vsprintf(str, format, ap);
   va_end(ap);
   return retval;
 }
tfp_vsnprintf()
ICACHE_FLASH_ATTR int tfp_vsnprintf (char * str, size_t size, const char * format, va_list ap)
Definition at line 460 of file tinyprintf.c.
References _vsnprintf_putcf(), _vsnprintf_putcf_data::dest, _vsnprintf_putcf_data::dest_capacity, _vsnprintf_putcf_data::num_chars, and tfp_format().
Referenced by tfp_snprintf().
 {
   struct _vsnprintf_putcf_data data;
   if (size < 1)
     return 0;
   data.dest = str;
   data.dest_capacity = size-1;
   data.num_chars = 0;
   tfp_format(&data, _vsnprintf_putcf, format, ap);
   if (data.num_chars < data.dest_capacity)
     data.dest[data.num_chars] = '\0';
   else
     data.dest[data.dest_capacity] = '\0';
   return data.num_chars;
 }
tfp_vsprintf()
ICACHE_FLASH_ATTR int tfp_vsprintf (char * str, const char * format, va_list ap)
Definition at line 503 of file tinyprintf.c.
References _vsprintf_putcf(), _vsprintf_putcf_data::dest, _vsprintf_putcf_data::num_chars, and tfp_format().
Referenced by tfp_sprintf().
 {
   struct _vsprintf_putcf_data data;
   data.dest = str;
   data.num_chars = 0;
   tfp_format(&data, _vsprintf_putcf, format, ap);
   data.dest[data.num_chars] = '\0';
   return data.num_chars;
 }
ui2a()
static ICACHE_FLASH_ATTR void ui2a (unsigned int num, struct param * p) static
Definition at line 147 of file tinyprintf.c.
References param::base, param::bf, and param::uc.
Referenced by i2a(), and tfp_format().
 {
     int n = 0;
     unsigned int d = 1;
     char *bf = p->bf;
     while (num / d >= p->base)
         d *= p->base;
     while (d != 0) {
         int dgt = num / d;
         num %= d;
         d /= p->base;
         if (n || dgt > 0 || d == 0) {
             *bf++ = dgt + (dgt < 10 ? '0' : (p->uc ? 'A' : 'a') - 10);
             ++n;
         }
     }
     *bf = 0;
 }
uli2a()
static ICACHE_FLASH_ATTR void uli2a (unsigned long int num, struct param * p) static
Definition at line 118 of file tinyprintf.c.
References param::base, param::bf, and param::uc.
Referenced by li2a(), and tfp_format().
 {
     int n = 0;
     unsigned long int d = 1;
     char *bf = p->bf;
     while (num / d >= p->base)
         d *= p->base;
     while (d != 0) {
         int dgt = num / d;
         num %= d;
         d /= p->base;
         if (n || dgt > 0 || d == 0) {
             *bf++ = dgt + (dgt < 10 ? '0' : (p->uc ? 'A' : 'a') - 10);
             ++n;
         }
     }
     *bf = 0;
 }
ulli2a()
static ICACHE_FLASH_ATTR void _TFP_GCC_NO_INLINE_ ulli2a (unsigned long long int num, struct param * p) static
Definition at line 87 of file tinyprintf.c.
References param::base, param::bf, and param::uc.
Referenced by lli2a(), and tfp_format().
 {
     int n = 0;
     unsigned long long int d = 1;
     char *bf = p->bf;
     while (num / d >= p->base)
         d *= p->base;
     while (d != 0) {
         int dgt = num / d;
         num %= d;
         d /= p->base;
         if (n || dgt > 0 || d == 0) {
             *bf++ = dgt + (dgt < 10 ? '0' : (p->uc ? 'A' : 'a') - 10);
             ++n;
         }
     }
     *bf = 0;
 }
Variable Documentation
stdout_putf
putcf stdout_putf static
Definition at line 426 of file tinyprintf.c.
Referenced by init_printf(), and tfp_printf().
stdout_putp
void* stdout_putp static
Definition at line 427 of file tinyprintf.c.
Referenced by init_printf(), and tfp_printf().