MeterLogger: user/tinyprintf.h File Reference
tinyprintf.h File Reference
#include <stdarg.h>
#include <sys/types.h>
Macros
#define TINYPRINTF_DEFINE_TFP_PRINTF 1
#define TINYPRINTF_DEFINE_TFP_SPRINTF 1
#define TINYPRINTF_OVERRIDE_LIBC 0
#define _TFP_SPECIFY_PRINTF_FMT(fmt_idx, arg1_idx)
Typedefs
typedef void(* putcf) (void *, char)
Functions
ICACHE_FLASH_ATTR void tfp_format (void *putp, putcf putf, const char *fmt, va_list va)
ICACHE_FLASH_ATTR int tfp_vsnprintf (char *str, size_t size, const char *fmt, va_list ap)
ICACHE_FLASH_ATTR int tfp_snprintf (char *str, size_t size, const char *fmt,...) _TFP_SPECIFY_PRINTF_FMT(3
ICACHE_FLASH_ATTR int ICACHE_FLASH_ATTR int tfp_vsprintf (char *str, const char *fmt, va_list ap)
ICACHE_FLASH_ATTR int tfp_sprintf (char *str, const char *fmt,...) _TFP_SPECIFY_PRINTF_FMT(2
ICACHE_FLASH_ATTR int ICACHE_FLASH_ATTR void init_printf (void *putp, putcf putf)
ICACHE_FLASH_ATTR void tfp_printf (char *fmt,...) _TFP_SPECIFY_PRINTF_FMT(1
Macro Definition Documentation
_TFP_SPECIFY_PRINTF_FMT
#define _TFP_SPECIFY_PRINTF_FMT (fmt_idx, arg1_idx)
Definition at line 138 of file tinyprintf.h.
TINYPRINTF_DEFINE_TFP_PRINTF
#define TINYPRINTF_DEFINE_TFP_PRINTF 1
Definition at line 110 of file tinyprintf.h.
TINYPRINTF_DEFINE_TFP_SPRINTF
#define TINYPRINTF_DEFINE_TFP_SPRINTF 1
Definition at line 116 of file tinyprintf.h.
TINYPRINTF_OVERRIDE_LIBC
#define TINYPRINTF_OVERRIDE_LIBC 0
Definition at line 123 of file tinyprintf.h.
Typedef Documentation
putcf
typedef void(* putcf) (void *, char)
Definition at line 145 of file tinyprintf.h.
Function Documentation
init_printf()
ICACHE_FLASH_ATTR int ICACHE_FLASH_ATTR void init_printf (void * putp, putcf putf)
Definition at line 429 of file tinyprintf.c.
References stdout_putf, and stdout_putp.
 {
     stdout_putf = putf;
     stdout_putp = putp;
 }
tfp_format()
ICACHE_FLASH_ATTR void tfp_format (void * putp, putcf putf, const char * fmt, va_list va)
Definition at line 255 of file tinyprintf.c.
References a2u(), param::align_left, param::alt, param::base, param::bf, i2a(), li2a(), lli2a(), param::lz, putchw(), param::sign, param::uc, ui2a(), uli2a(), ulli2a(), and param::width.
Referenced by tfp_printf(), tfp_vsnprintf(), and tfp_vsprintf().
 {
     struct param p;
 #ifdef PRINTF_LONG_SUPPORT
     char bf[23];  /* long = 64b on some architectures */
 #else
     char bf[12];  /* int = 32b on some architectures */
 #endif
     char ch;
     p.bf = bf;
     while ((ch = *(fmt++))) {
         if (ch != '%') {
             putf(putp, ch);
         } else {
 #ifdef PRINTF_LONG_SUPPORT
             char lng = 0;  /* 1 for long, 2 for long long */
 #endif
             /* Init parameter struct */
             p.lz = 0;
             p.alt = 0;
             p.width = 0;
             p.align_left = 0;
             p.sign = 0;
             /* Flags */
             while ((ch = *(fmt++))) {
                 switch (ch) {
                 case '-':
                     p.align_left = 1;
                     continue;
                 case '0':
                     p.lz = 1;
                     continue;
                 case '#':
                     p.alt = 1;
                     continue;
                 default:
                     break;
                 }
                 break;
             }
             /* Width */
             if (ch >= '0' && ch <= '9') {
                 ch = a2u(ch, &fmt, 10, &(p.width));
             }
             /* We accept 'x.y' format but don't support it completely:
              * we ignore the 'y' digit => this ignores 0-fill
              * size and makes it == width (ie. 'x') */
             if (ch == '.') {
               p.lz = 1;  /* zero-padding */
               /* ignore actual 0-fill size: */
               do {
                 ch = *(fmt++);
               } while ((ch >= '0') && (ch <= '9'));
             }
 #ifdef PRINTF_SIZE_T_SUPPORT
 # ifdef PRINTF_LONG_SUPPORT
             if (ch == 'z') {
                 ch = *(fmt++);
                 if (sizeof(size_t) == sizeof(unsigned long int))
                     lng = 1;
 #  ifdef PRINTF_LONG_LONG_SUPPORT
                 else if (sizeof(size_t) == sizeof(unsigned long long int))
                     lng = 2;
 #  endif
             } else
 # endif
 #endif
 #ifdef PRINTF_LONG_SUPPORT
             if (ch == 'l') {
                 ch = *(fmt++);
                 lng = 1;
 #ifdef PRINTF_LONG_LONG_SUPPORT
                 if (ch == 'l') {
                   ch = *(fmt++);
                   lng = 2;
                 }
 #endif
             }
 #endif
             switch (ch) {
             case 0:
                 goto abort;
             case 'u':
                 p.base = 10;
 #ifdef PRINTF_LONG_SUPPORT
 #ifdef PRINTF_LONG_LONG_SUPPORT
                 if (2 == lng)
                     ulli2a(va_arg(va, unsigned long long int), &p);
                 else
 #endif
                   if (1 == lng)
                     uli2a(va_arg(va, unsigned long int), &p);
                 else
 #endif
                     ui2a(va_arg(va, unsigned int), &p);
                 putchw(putp, putf, &p);
                 break;
             case 'd':
             case 'i':
                 p.base = 10;
 #ifdef PRINTF_LONG_SUPPORT
 #ifdef PRINTF_LONG_LONG_SUPPORT
                 if (2 == lng)
                     lli2a(va_arg(va, long long int), &p);
                 else
 #endif
                   if (1 == lng)
                     li2a(va_arg(va, long int), &p);
                 else
 #endif
                     i2a(va_arg(va, int), &p);
                 putchw(putp, putf, &p);
                 break;
 #ifdef SIZEOF_POINTER
             case 'p':
                 p.alt = 1;
 # if defined(SIZEOF_INT) && SIZEOF_POINTER <= SIZEOF_INT
                 lng = 0;
 # elif defined(SIZEOF_LONG) && SIZEOF_POINTER <= SIZEOF_LONG
                 lng = 1;
 # elif defined(SIZEOF_LONG_LONG) && SIZEOF_POINTER <= SIZEOF_LONG_LONG
                 lng = 2;
 # endif
 #endif
             case 'x':
             case 'X':
                 p.base = 16;
                 p.uc = (ch == 'X')?1:0;
 #ifdef PRINTF_LONG_SUPPORT
 #ifdef PRINTF_LONG_LONG_SUPPORT
                 if (2 == lng)
                     ulli2a(va_arg(va, unsigned long long int), &p);
                 else
 #endif
                   if (1 == lng)
                     uli2a(va_arg(va, unsigned long int), &p);
                 else
 #endif
                     ui2a(va_arg(va, unsigned int), &p);
                 putchw(putp, putf, &p);
                 break;
             case 'o':
                 p.base = 8;
                 ui2a(va_arg(va, unsigned int), &p);
                 putchw(putp, putf, &p);
                 break;
             case 'c':
                 putf(putp, (char)(va_arg(va, int)));
                 break;
             case 's':
                 p.bf = va_arg(va, char *);
                 putchw(putp, putf, &p);
                 p.bf = bf;
                 break;
             case '%':
                 putf(putp, ch);
             default:
                 break;
             }
         }
     }
  abort:;
 }
tfp_printf()
ICACHE_FLASH_ATTR void tfp_printf (char * fmt, ...)
tfp_snprintf()
ICACHE_FLASH_ATTR int tfp_snprintf (char * str, size_t size, const char * fmt, ...)
tfp_sprintf()
ICACHE_FLASH_ATTR int tfp_sprintf (char * str, const char * fmt, ...)
tfp_vsnprintf()
ICACHE_FLASH_ATTR int tfp_vsnprintf (char * str, size_t size, const char * fmt, va_list ap)
Definition at line 460 of file tinyprintf.c.
References _vsnprintf_putcf(), _vsnprintf_putcf_data::dest, _vsnprintf_putcf_data::dest_capacity, _vsnprintf_putcf_data::num_chars, and tfp_format().
Referenced by tfp_snprintf().
 {
   struct _vsnprintf_putcf_data data;
   if (size < 1)
     return 0;
   data.dest = str;
   data.dest_capacity = size-1;
   data.num_chars = 0;
   tfp_format(&data, _vsnprintf_putcf, format, ap);
   if (data.num_chars < data.dest_capacity)
     data.dest[data.num_chars] = '\0';
   else
     data.dest[data.dest_capacity] = '\0';
   return data.num_chars;
 }
tfp_vsprintf()
ICACHE_FLASH_ATTR int ICACHE_FLASH_ATTR int tfp_vsprintf (char * str, const char * fmt, va_list ap)
Definition at line 503 of file tinyprintf.c.
References _vsprintf_putcf(), _vsprintf_putcf_data::dest, _vsprintf_putcf_data::num_chars, and tfp_format().
Referenced by tfp_sprintf().
 {
   struct _vsprintf_putcf_data data;
   data.dest = str;
   data.num_chars = 0;
   tfp_format(&data, _vsprintf_putcf, format, ap);
   data.dest[data.num_chars] = '\0';
   return data.num_chars;
 }