MeterLogger: include/driver/uart.h File Reference
uart.h File Reference
#include "uart_register.h"
#include "eagle_soc.h"
#include "c_types.h"
Data Structures
struct RcvMsgBuff
struct TrxMsgBuff
struct UartDevice
struct UartBuffer
struct UartRxBuff
Macros
#define UART_TX_BUFFER_SIZE 256
#define UART_RX_BUFFER_SIZE 256
#define UART_BUFF_EN 0
#define UART_SELFTEST 0
#define UART_HW_RTS 0
#define UART_HW_CTS 0
#define UART_LINE_INV_MASK (0x3f<<19)
#define UART0 0
#define UART1 1
#define UART_FIFO_LEN 128
#define UART_TX_EMPTY_THRESH_VAL 0x10
Enumerations
enum UartBitsNum4Char { FIVE_BITS = 0x0, SIX_BITS = 0x1, SEVEN_BITS = 0x2, EIGHT_BITS = 0x3 }
enum UartStopBitsNum { ONE_STOP_BIT = 0x1, ONE_HALF_STOP_BIT = 0x2, TWO_STOP_BIT = 0x3 }
enum UartParityMode { NONE_BITS = 0x2, ODD_BITS = 1, EVEN_BITS = 0 }
enum UartExistParity { STICK_PARITY_DIS = 0, STICK_PARITY_EN = 1 }
enum UART_LineLevelInverse {
UART_None_Inverse = 0x0, UART_Rxd_Inverse = UART_RXD_INV, UART_CTS_Inverse = UART_CTS_INV, UART_Txd_Inverse = UART_TXD_INV,
UART_RTS_Inverse = UART_RTS_INV
}
enum UartBautRate {
BIT_RATE_300 = 300, BIT_RATE_600 = 600, BIT_RATE_1200 = 1200, BIT_RATE_2400 = 2400,
BIT_RATE_4800 = 4800, BIT_RATE_9600 = 9600, BIT_RATE_19200 = 19200, BIT_RATE_38400 = 38400,
BIT_RATE_57600 = 57600, BIT_RATE_74880 = 74880, BIT_RATE_115200 = 115200, BIT_RATE_230400 = 230400,
BIT_RATE_460800 = 460800, BIT_RATE_921600 = 921600, BIT_RATE_1843200 = 1843200, BIT_RATE_3686400 = 3686400
}
enum UartFlowCtrl { NONE_CTRL, HARDWARE_CTRL, XON_XOFF_CTRL }
enum UART_HwFlowCtrl { USART_HardwareFlowControl_None = 0x0, USART_HardwareFlowControl_RTS = 0x1, USART_HardwareFlowControl_CTS = 0x2, USART_HardwareFlowControl_CTS_RTS = 0x3 }
enum RcvMsgBuffState { EMPTY, UNDER_WRITE, WRITE_OVER }
enum RcvMsgState {
BAUD_RATE_DET, WAIT_SYNC_FRM, SRCH_MSG_HEAD, RCV_MSG_BODY,
RCV_ESC_CHAR
}
enum TCPState { RUN = 0, BLOCK = 1 }
Functions
void uart_init (UartBautRate uart0_br, UartBautRate uart1_br)
void uart0_sendStr (const char *str)
STATUS uart_tx_one_char (uint8 uart, uint8 TxChar)
STATUS uart_tx_one_char_no_wait (uint8 uart, uint8 TxChar)
void uart1_sendStr_no_wait (const char *str)
struct UartBuffer * Uart_Buf_Init ()
void uart_rx_intr_enable (uint8 uart_no)
void uart_rx_intr_disable (uint8 uart_no)
void uart0_tx_buffer (uint8 *buf, uint16 len)
void ICACHE_FLASH_ATTR uart_set_word_length (uint8_t uart_no, UartBitsNum4Char len)
void ICACHE_FLASH_ATTR uart_set_stop_bits (uint8_t uart_no, UartStopBitsNum bit_num)
void ICACHE_FLASH_ATTR uart_set_line_inverse (uint8_t uart_no, UART_LineLevelInverse inverse_mask)
void ICACHE_FLASH_ATTR uart_set_parity (uint8_t uart_no, UartParityMode Parity_mode)
void ICACHE_FLASH_ATTR uart_set_baudrate (uint8_t uart_no, uint32_t baud_rate)
Macro Definition Documentation
UART0
#define UART0 0
Definition at line 37 of file uart.h.
Referenced by en61107_delayed_uart_change_setting_timer_func(), en61107_uart_send_en61107(), en61107_uart_send_en61107_ident(), en61107_uart_send_inst_values(), en61107_uart_send_standard_data_1(), en61107_uart_send_standard_data_2(), uart0_rx_intr_handler(), uart0_sendStr(), uart0_tx_buffer(), uart0_write_char(), uart_config(), and uart_init().
UART1
#define UART1 1
Definition at line 38 of file uart.h.
Referenced by uart1_write_char(), uart_config(), and uart_init().
UART_BUFF_EN
#define UART_BUFF_EN 0
Definition at line 27 of file uart.h.
UART_FIFO_LEN
#define UART_FIFO_LEN 128
Definition at line 153 of file uart.h.
UART_HW_CTS
#define UART_HW_CTS 0
Definition at line 31 of file uart.h.
UART_HW_RTS
#define UART_HW_RTS 0
Definition at line 30 of file uart.h.
UART_LINE_INV_MASK
#define UART_LINE_INV_MASK (0x3f<<19)
Definition at line 33 of file uart.h.
Referenced by uart_set_line_inverse().
UART_RX_BUFFER_SIZE
#define UART_RX_BUFFER_SIZE 256
Definition at line 25 of file uart.h.
UART_SELFTEST
#define UART_SELFTEST 0
Definition at line 28 of file uart.h.
UART_TX_BUFFER_SIZE
#define UART_TX_BUFFER_SIZE 256
Definition at line 24 of file uart.h.
UART_TX_EMPTY_THRESH_VAL
#define UART_TX_EMPTY_THRESH_VAL 0x10
Definition at line 154 of file uart.h.
Enumeration Type Documentation
RcvMsgBuffState
enum RcvMsgBuffState
Enumerator
EMPTY
UNDER_WRITE
WRITE_OVER
Definition at line 106 of file uart.h.
              {
     EMPTY,
     UNDER_WRITE,
     WRITE_OVER
 } RcvMsgBuffState;
RcvMsgState
enum RcvMsgState
Enumerator
BAUD_RATE_DET
WAIT_SYNC_FRM
SRCH_MSG_HEAD
RCV_MSG_BODY
RCV_ESC_CHAR
Definition at line 126 of file uart.h.
              {
     BAUD_RATE_DET,
     WAIT_SYNC_FRM,
     SRCH_MSG_HEAD,
     RCV_MSG_BODY,
     RCV_ESC_CHAR,
 } RcvMsgState;
TCPState
enum TCPState
Enumerator
RUN
BLOCK
Definition at line 177 of file uart.h.
              {
     RUN = 0,
     BLOCK = 1,
 } TCPState;
UART_HwFlowCtrl
enum UART_HwFlowCtrl
Enumerator
USART_HardwareFlowControl_None
USART_HardwareFlowControl_RTS
USART_HardwareFlowControl_CTS
USART_HardwareFlowControl_CTS_RTS
Definition at line 99 of file uart.h.
              {
     USART_HardwareFlowControl_None = 0x0,
     USART_HardwareFlowControl_RTS = 0x1,
     USART_HardwareFlowControl_CTS = 0x2,
     USART_HardwareFlowControl_CTS_RTS = 0x3
 } UART_HwFlowCtrl;
UART_LineLevelInverse
enum UART_LineLevelInverse
Enumerator
UART_None_Inverse
UART_Rxd_Inverse
UART_CTS_Inverse
UART_Txd_Inverse
UART_RTS_Inverse
Definition at line 65 of file uart.h.
              {
     UART_None_Inverse = 0x0,
     UART_Rxd_Inverse = UART_RXD_INV,
     UART_CTS_Inverse = UART_CTS_INV,
     UART_Txd_Inverse = UART_TXD_INV,
     UART_RTS_Inverse = UART_RTS_INV,
 } UART_LineLevelInverse;
UartBautRate
enum UartBautRate
Enumerator
BIT_RATE_300
BIT_RATE_600
BIT_RATE_1200
BIT_RATE_2400
BIT_RATE_4800
BIT_RATE_9600
BIT_RATE_19200
BIT_RATE_38400
BIT_RATE_57600
BIT_RATE_74880
BIT_RATE_115200
BIT_RATE_230400
BIT_RATE_460800
BIT_RATE_921600
BIT_RATE_1843200
BIT_RATE_3686400
Definition at line 74 of file uart.h.
              {
     BIT_RATE_300 = 300,
     BIT_RATE_600 = 600,
     BIT_RATE_1200 = 1200,
     BIT_RATE_2400 = 2400,
     BIT_RATE_4800 = 4800,
     BIT_RATE_9600   = 9600,
     BIT_RATE_19200  = 19200,
     BIT_RATE_38400  = 38400,
     BIT_RATE_57600  = 57600,
     BIT_RATE_74880  = 74880,
     BIT_RATE_115200 = 115200,
     BIT_RATE_230400 = 230400,
     BIT_RATE_460800 = 460800,
     BIT_RATE_921600 = 921600,
     BIT_RATE_1843200 = 1843200,
     BIT_RATE_3686400 = 3686400,
 } UartBautRate;
UartBitsNum4Char
enum UartBitsNum4Char
Enumerator
FIVE_BITS
SIX_BITS
SEVEN_BITS
EIGHT_BITS
Definition at line 41 of file uart.h.
              {
     FIVE_BITS = 0x0,
     SIX_BITS = 0x1,
     SEVEN_BITS = 0x2,
     EIGHT_BITS = 0x3
 } UartBitsNum4Char;
UartExistParity
enum UartExistParity
Enumerator
STICK_PARITY_DIS
STICK_PARITY_EN
Definition at line 60 of file uart.h.
              {
     STICK_PARITY_DIS   = 0,
     STICK_PARITY_EN    = 1
 } UartExistParity;
UartFlowCtrl
enum UartFlowCtrl
Enumerator
NONE_CTRL
HARDWARE_CTRL
XON_XOFF_CTRL
Definition at line 93 of file uart.h.
              {
     NONE_CTRL,
     HARDWARE_CTRL,
     XON_XOFF_CTRL
 } UartFlowCtrl;
UartParityMode
enum UartParityMode
Enumerator
NONE_BITS
ODD_BITS
EVEN_BITS
Definition at line 54 of file uart.h.
              {
     NONE_BITS = 0x2,
     ODD_BITS   = 1,
     EVEN_BITS = 0
 } UartParityMode;
UartStopBitsNum
enum UartStopBitsNum
Enumerator
ONE_STOP_BIT
ONE_HALF_STOP_BIT
TWO_STOP_BIT
Definition at line 48 of file uart.h.
              {
     ONE_STOP_BIT             = 0x1,
     ONE_HALF_STOP_BIT        = 0x2,
     TWO_STOP_BIT             = 0x3
 } UartStopBitsNum;
Function Documentation
uart0_sendStr()
void uart0_sendStr (const char * str)
Definition at line 183 of file uart.c.
References LOCAL, UART0, and uart_tx_one_char().
 {
     while(*str)
     {
         uart_tx_one_char(UART0, *str++);
     }
 }
uart0_tx_buffer()
void uart0_tx_buffer (uint8 * buf, uint16 len)
Definition at line 165 of file uart.c.
References ICACHE_FLASH_ATTR, UART0, and uart_tx_one_char().
Referenced by en61107_uart_send_en61107(), en61107_uart_send_en61107_ident(), en61107_uart_send_inst_values(), en61107_uart_send_standard_data_1(), en61107_uart_send_standard_data_2(), kmp_get_register_timer_func(), and kmp_get_serial_timer_func().
 {
   uint16 i;
   for (i = 0; i < len; i++)
   {
     uart_tx_one_char(UART0, buf[i]);
   }
 }
uart1_sendStr_no_wait()
void uart1_sendStr_no_wait (const char * str)
Uart_Buf_Init()
struct UartBuffer* Uart_Buf_Init ()
uart_init()
void uart_init (UartBautRate uart0_br, UartBautRate uart1_br)
Definition at line 275 of file uart.c.
References UartDevice::baut_rate, UartDevice::data_bits, EIGHT_BITS, ETS_UART_INTR_ENABLE, EVEN_BITS, UartDevice::exist_parity, ICACHE_FLASH_ATTR, NONE_BITS, os_install_putc1, UartDevice::parity, SEVEN_BITS, STICK_PARITY_DIS, STICK_PARITY_EN, UartDevice::stop_bits, TWO_STOP_BIT, UART0, uart0_write_char(), UART1, and uart_config().
 {
   // rom use 74880 baut_rate, here reinitialize
 #ifndef EN61107
   UartDev.baut_rate = uart0_br;
   UartDev.exist_parity = STICK_PARITY_DIS;
   UartDev.data_bits = EIGHT_BITS;
   UartDev.parity = NONE_BITS;
   UartDev.stop_bits = TWO_STOP_BIT;
 #else
   UartDev.baut_rate = uart0_br;
   UartDev.exist_parity = STICK_PARITY_EN;
   UartDev.data_bits = SEVEN_BITS;
   UartDev.parity = EVEN_BITS;
   UartDev.stop_bits = TWO_STOP_BIT;
 #endif
   uart_config(UART0);
 #ifndef EN61107
   UartDev.baut_rate = uart1_br;
   UartDev.exist_parity = STICK_PARITY_DIS;
   UartDev.data_bits = EIGHT_BITS;
   UartDev.parity = NONE_BITS;
   UartDev.stop_bits = TWO_STOP_BIT;
 #else
   UartDev.baut_rate = uart1_br;
   UartDev.exist_parity = STICK_PARITY_EN;
   UartDev.data_bits = SEVEN_BITS;
   UartDev.parity = EVEN_BITS;
   UartDev.stop_bits = TWO_STOP_BIT;
 #endif
   uart_config(UART1);
   ETS_UART_INTR_ENABLE();
   // install uart1 putc callback
   os_install_putc1((void *)uart0_write_char);
 }
uart_rx_intr_disable()
void uart_rx_intr_disable (uint8 uart_no)
uart_rx_intr_enable()
void uart_rx_intr_enable (uint8 uart_no)
uart_set_baudrate()
void ICACHE_FLASH_ATTR uart_set_baudrate (uint8_t uart_no, uint32_t baud_rate)
uart_set_line_inverse()
void ICACHE_FLASH_ATTR uart_set_line_inverse (uint8_t uart_no, UART_LineLevelInverse inverse_mask)
Definition at line 323 of file uart.c.
References CLEAR_PERI_REG_MASK, ICACHE_FLASH_ATTR, SET_PERI_REG_MASK, UART_CONF0, and UART_LINE_INV_MASK.
{
     CLEAR_PERI_REG_MASK(UART_CONF0(uart_no), UART_LINE_INV_MASK);
     SET_PERI_REG_MASK(UART_CONF0(uart_no), inverse_mask);
 }
uart_set_parity()
void ICACHE_FLASH_ATTR uart_set_parity (uint8_t uart_no, UartParityMode Parity_mode)
Definition at line 329 of file uart.c.
References CLEAR_PERI_REG_MASK, ICACHE_FLASH_ATTR, NONE_BITS, SET_PERI_REG_MASK, UART_CONF0, UART_PARITY, and UART_PARITY_EN.
Referenced by en61107_uart_send_en61107(), en61107_uart_send_en61107_ident(), en61107_uart_send_inst_values(), en61107_uart_send_standard_data_1(), and en61107_uart_send_standard_data_2().
{
     CLEAR_PERI_REG_MASK(UART_CONF0(uart_no), UART_PARITY | UART_PARITY_EN);
     if (Parity_mode == NONE_BITS) {
     }
     else {
         SET_PERI_REG_MASK(UART_CONF0(uart_no), Parity_mode| UART_PARITY_EN);
     }
 }
uart_set_stop_bits()
void ICACHE_FLASH_ATTR uart_set_stop_bits (uint8_t uart_no, UartStopBitsNum bit_num)
Definition at line 318 of file uart.c.
References ICACHE_FLASH_ATTR, SET_PERI_REG_BITS, UART_CONF0, UART_STOP_BIT_NUM, and UART_STOP_BIT_NUM_S.
Referenced by en61107_delayed_uart_change_setting_timer_func(), en61107_uart_send_en61107(), en61107_uart_send_en61107_ident(), en61107_uart_send_inst_values(), en61107_uart_send_standard_data_1(), and en61107_uart_send_standard_data_2().
{
     SET_PERI_REG_BITS(UART_CONF0(uart_no), UART_STOP_BIT_NUM, bit_num, UART_STOP_BIT_NUM_S);
 }
uart_set_word_length()
void ICACHE_FLASH_ATTR uart_set_word_length (uint8_t uart_no, UartBitsNum4Char len)
Definition at line 313 of file uart.c.
References ICACHE_FLASH_ATTR, SET_PERI_REG_BITS, UART_BIT_NUM, UART_BIT_NUM_S, and UART_CONF0.
Referenced by en61107_uart_send_en61107(), en61107_uart_send_en61107_ident(), en61107_uart_send_inst_values(), en61107_uart_send_standard_data_1(), and en61107_uart_send_standard_data_2().
{
     SET_PERI_REG_BITS(UART_CONF0(uart_no), UART_BIT_NUM, len, UART_BIT_NUM_S);
 }
uart_tx_one_char()
STATUS uart_tx_one_char (uint8 uart, uint8 TxChar)
Definition at line 106 of file uart.c.
References ICACHE_FLASH_ATTR, OK, READ_PERI_REG, UART_FIFO, UART_STATUS, UART_TXFIFO_CNT, UART_TXFIFO_CNT_S, and WRITE_PERI_REG.
Referenced by uart0_sendStr(), uart0_tx_buffer(), uart0_write_char(), and uart1_write_char().
 {
     while (true)
     {
       uint32 fifo_cnt = READ_PERI_REG(UART_STATUS(uart)) & (UART_TXFIFO_CNT<<UART_TXFIFO_CNT_S);
       if ((fifo_cnt >> UART_TXFIFO_CNT_S & UART_TXFIFO_CNT) < 126) {
         break;
       }
     }
     WRITE_PERI_REG(UART_FIFO(uart) , TxChar);
     return OK;
 }
uart_tx_one_char_no_wait()
STATUS uart_tx_one_char_no_wait (uint8 uart, uint8 TxChar)