MeterLogger: user/unix_time.h File Reference
unix_time.h File Reference
Functions
ICACHE_FLASH_ATTR void init_unix_time (void)
ICACHE_FLASH_ATTR uint32_t get_unix_time (void)
ICACHE_FLASH_ATTR uint32_t get_uptime (void)
Function Documentation
get_unix_time()
ICACHE_FLASH_ATTR uint32_t get_unix_time (void)
Definition at line 55 of file unix_time.c.
References current_unix_time, and sntp_get_current_timestamp().
Referenced by en61107_received_task(), en61107_request_send(), kmp_received_task(), kmp_request_send(), and minute_timer_func().
{
     current_unix_time = sntp_get_current_timestamp();
     return current_unix_time;
 }
get_uptime()
ICACHE_FLASH_ATTR uint32_t get_uptime (void)
Definition at line 61 of file unix_time.c.
References current_unix_time, init_time, ntp_offline_second_counter, and sntp_get_current_timestamp().
Referenced by add_watchdog(), reset_watchdog(), and watchdog_timer_func().
{
     current_unix_time = sntp_get_current_timestamp();
     if (init_time == 0) {
         return ntp_offline_second_counter;
     }
     else {
         return current_unix_time - init_time + ntp_offline_second_counter;
     }
 }
init_unix_time()
ICACHE_FLASH_ATTR void init_unix_time (void)
Definition at line 37 of file unix_time.c.
References ntp_offline_second_counter, ntp_offline_second_counter_timer, ntp_offline_second_counter_timer_func(), NULL, os_timer_arm, os_timer_disarm, os_timer_func_t, os_timer_setfn, sntp_check_timer, sntp_check_timer_func(), sntp_init(), sntp_set_timezone(), and sntp_setservername().
{
     // init sntp
     sntp_setservername(0, "dk.pool.ntp.org"); // set server 0 by domain name
     sntp_setservername(1, "us.pool.ntp.org"); // set server 1 by domain name
     sntp_set_timezone(0);   // UTC time
     sntp_init();
     // start timer to make sure we go ntp reply
     os_timer_disarm(&sntp_check_timer);
     os_timer_setfn(&sntp_check_timer, (os_timer_func_t *)sntp_check_timer_func, NULL);
     os_timer_arm(&sntp_check_timer, 2000, 0);
     ntp_offline_second_counter = 0;
     os_timer_disarm(&ntp_offline_second_counter_timer);
     os_timer_setfn(&ntp_offline_second_counter_timer, (os_timer_func_t *)ntp_offline_second_counter_timer_func, NULL);
     os_timer_arm(&ntp_offline_second_counter_timer, 1000, 1);       // every seconds
 }