MeterLogger: user/user_main.c File Reference
user_main.c File Reference
#include <esp8266.h>
#include "driver/uart.h"
#include "mqtt.h"
#include "crypto/crypto.h"
#include "crypto/aes.h"
#include "crypto/sha256.h"
#include "crypto/hmac-sha256.h"
#include "wifi.h"
#include "config.h"
#include "debug.h"
#include "httpd.h"
#include "httpd_user_init.h"
#include "user_config.h"
#include "unix_time.h"
#include "cron/cron.h"
#include "led.h"
#include "ac/ac_out.h"
#include "utils.h"
#include "user_main.h"
#include "captdns.h"
#include "tinyprintf.h"
#include "driver/ext_spi_flash.h"
#include "watchdog.h"
#include "version.h"
#include "kmp_request.h"
Functions
ICACHE_FLASH_ATTR static void sample_mode_timer_func (void *arg)
ICACHE_FLASH_ATTR static void config_mode_timer_func (void *arg)
ICACHE_FLASH_ATTR static void sample_timer_func (void *arg)
ICACHE_FLASH_ATTR static void kmp_request_send_timer_func (void *arg)
ICACHE_FLASH_ATTR void wifi_changed_cb (uint8_t status)
ICACHE_FLASH_ATTR void mqtt_connected_cb (uint32_t *args)
ICACHE_FLASH_ATTR void mqtt_disconnected_cb (uint32_t *args)
ICACHE_FLASH_ATTR void mqtt_published_cb (uint32_t *args)
ICACHE_FLASH_ATTR void mqtt_timeout_cb (uint32_t *args)
ICACHE_FLASH_ATTR void mqtt_data_cb (uint32_t *args, const char *topic, uint32_t topic_len, const char *data, uint32_t data_len)
ICACHE_FLASH_ATTR void user_init (void)
ICACHE_FLASH_ATTR void system_init_done (void)
Variables
MQTT_Client mqtt_client
static os_timer_t sample_timer
static os_timer_t config_mode_timer
static os_timer_t sample_mode_timer
static os_timer_t kmp_request_send_timer
struct rst_info * rtc_info
uint8_t mesh_ssid [64]
Function Documentation
config_mode_timer_func()
ICACHE_FLASH_ATTR static void config_mode_timer_func (void * arg) static
Definition at line 132 of file user_main.c.
References AP_PASSWORD, AP_SSID, captdnsInit(), en61107_get_received_serial(), httpd_user_init(), kmp_get_received_serial(), STA_TYPE, sys_cfg, tfp_snprintf(), and wifi_softap_config().
Referenced by system_init_done().
kmp_request_send_timer_func()
ICACHE_FLASH_ATTR static void kmp_request_send_timer_func (void * arg) static
Definition at line 243 of file user_main.c.
References cfg_save(), ICACHE_FLASH_ATTR, kmp_request_send(), printf, sys_cfg, and uptime().
Referenced by system_init_done().
mqtt_connected_cb()
ICACHE_FLASH_ATTR void mqtt_connected_cb (uint32_t * args)
Definition at line 289 of file user_main.c.
References syscfg_t::ac_thermo_state, en61107_get_received_serial(), en61107_set_mqtt_client(), encrypt_aes_hmac_combined(), get_unix_time(), HW_MODEL, kmp_get_received_serial(), kmp_set_mqtt_client(), led_pattern_b(), memset, MQTT_MESSAGE_L, MQTT_Publish(), MQTT_Subscribe(), MQTT_TOPIC_L, NULL, os_timer_arm, os_timer_disarm, os_timer_func_t, os_timer_setfn, sample_timer, sample_timer_func(), strlen, sys_cfg, system_get_sdk_version(), tfp_snprintf(), uptime(), and wifi_fallback_is_present().
Referenced by sample_mode_timer_func(), and wifi_changed_cb().
mqtt_data_cb()
ICACHE_FLASH_ATTR void mqtt_data_cb (uint32_t * args, const char * topic, uint32_t topic_len, const char * data, uint32_t data_len)
Definition at line 400 of file user_main.c.
References ac_off(), ac_test(), ac_thermo_close(), ac_thermo_open(), ac_thermo_pwm(), syscfg_t::ac_thermo_state, add_cron_job_from_query(), atoi(), BIT, BIT5, cfg_save(), clear_cron_jobs(), syscfg_t::cron_jobs, decrypt_aes_hmac_combined(), en61107_get_received_serial(), encrypt_aes_hmac_combined(), ETS_GPIO_INTR_ATTACH, ETS_GPIO_INTR_DISABLE, ETS_GPIO_INTR_ENABLE, FUNC_GPIO5, FUNCTIONNAME_L, get_unix_time(), GPIO_DIS_OUTPUT, GPIO_ID_PIN, GPIO_IN_ADDRESS, gpio_intr_ack(), GPIO_PIN_INTR_ANYEDGE, GPIO_PIN_INTR_DISABLE, gpio_pin_intr_state_set(), GPIO_REG_READ, GPIO_REG_WRITE, GPIO_STATUS_ADDRESS, GPIO_STATUS_W1TC_ADDRESS, HW_MODEL, ICACHE_FLASH_ATTR, kmp_get_received_serial(), memcpy, memset, MQTT_MESSAGE_L, MQTT_Publish(), MQTT_TOPIC_L, cron_jobs_t::n, NULL, os_delay_us, os_printf(), os_timer_arm, os_timer_disarm, os_timer_func_t, os_timer_setfn, PERIPHS_IO_MUX_GPIO5_U, PIN_FUNC_SELECT, PIN_PULLUP_EN, printf, rst_info::reason, syscfg_t::sta_pwd, syscfg_t::sta_ssid, strlen, strncmp, strncpy, sys_cfg, system_get_free_heap_size(), system_get_sdk_version(), system_get_time(), system_print_meminfo(), tfp_snprintf(), uptime(), wifi_get_rssi(), and wifi_get_status().
Referenced by sample_mode_timer_func().
mqtt_disconnected_cb()
ICACHE_FLASH_ATTR void mqtt_disconnected_cb (uint32_t * args)
Definition at line 390 of file user_main.c.
Referenced by sample_mode_timer_func().
mqtt_published_cb()
ICACHE_FLASH_ATTR void mqtt_published_cb (uint32_t * args)
Definition at line 393 of file user_main.c.
References MQTT_WATCHDOG_ID, and reset_watchdog().
Referenced by sample_mode_timer_func().
mqtt_timeout_cb()
ICACHE_FLASH_ATTR void mqtt_timeout_cb (uint32_t * args)
Definition at line 397 of file user_main.c.
Referenced by sample_mode_timer_func().
sample_mode_timer_func()
ICACHE_FLASH_ATTR static void sample_mode_timer_func (void * arg) static
Definition at line 74 of file user_main.c.
References add_watchdog(), AP_MESH_PASS, AP_MESH_SSID, AP_MESH_TYPE, captdnsStop(), cfg_load(), syscfg_t::device_id, en61107_get_received_serial(), httpdStop(), INFO, kmp_get_received_serial(), led_on(), mesh_ssid, mqtt_connected_cb(), mqtt_data_cb(), mqtt_disconnected_cb(), syscfg_t::mqtt_host, MQTT_InitClient(), MQTT_InitConnection(), MQTT_InitLWT(), syscfg_t::mqtt_keepalive, MQTT_OnConnected(), MQTT_OnData(), MQTT_OnDisconnected(), MQTT_OnPublished(), MQTT_OnTimeout(), syscfg_t::mqtt_pass, syscfg_t::mqtt_port, mqtt_published_cb(), mqtt_timeout_cb(), MQTT_TOPIC_L, syscfg_t::mqtt_user, MQTT_WATCHDOG_ID, MQTT_WATCHDOG_TIMEOUT, NETWORK_RESTART, syscfg_t::security, syscfg_t::sta_pwd, syscfg_t::sta_ssid, STATION_MODE, sys_cfg, system_get_chip_id(), tfp_snprintf(), wifi_changed_cb(), wifi_connect(), wifi_set_opmode_current(), wifi_softap_config(), and wifi_softap_ip_config().
Referenced by system_init_done().
sample_timer_func()
ICACHE_FLASH_ATTR static void sample_timer_func (void * arg) static
Definition at line 150 of file user_main.c.
References decimal_number_length(), en61107_request_send(), encrypt_aes_hmac_combined(), get_unix_time(), ICACHE_FLASH_ATTR, kmp_request_send(), memset, MQTT_MESSAGE_L, MQTT_Ping(), MQTT_Publish(), MQTT_TOPIC_L, MQTT_WATCHDOG_ID, NULL, MQTT_Client::pCon, printf, reset_watchdog(), strcat, strcpy, strlen, sys_cfg, system_get_free_heap_size(), tfp_snprintf(), and uptime().
Referenced by mqtt_connected_cb().
system_init_done()
ICACHE_FLASH_ATTR void system_init_done (void)
Definition at line 886 of file user_main.c.
References config_mode_timer, config_mode_timer_func(), rst_info::depc, rst_info::epc1, rst_info::epc2, rst_info::epc3, rst_info::exccause, rst_info::excvaddr, init_unix_time(), kmp_request_send_timer, kmp_request_send_timer_func(), NULL, os_printf(), os_timer_arm, os_timer_disarm, os_timer_func_t, os_timer_setfn, printf, rst_info::reason, REASON_DEFAULT_RST, REASON_EXCEPTION_RST, REASON_EXT_SYS_RST, REASON_SOFT_WDT_RST, REASON_WDT_RST, sample_mode_timer, sample_mode_timer_func(), and system_get_rst_info().
Referenced by user_init().
user_init()
ICACHE_FLASH_ATTR void user_init (void)
Definition at line 790 of file user_main.c.
References ac_out_init(), ac_thermo_close(), ac_thermo_open(), syscfg_t::ac_thermo_state, BIT_RATE_115200, BIT_RATE_1200, BIT_RATE_300, cfg_load(), cron_init(), en61107_request_init(), ext_spi_init(), gpio_init(), HW_MODEL, init_aes_hmac_combined(), init_watchdog(), syscfg_t::key, kmp_request_init(), led_init(), memset, printf, start_watchdog(), STATIONAP_MODE, sys_cfg, system_get_sdk_version(), system_init_done(), system_init_done_cb(), system_set_os_print(), system_update_cpu_freq(), uart_init(), and wifi_set_opmode_current().
wifi_changed_cb()
ICACHE_FLASH_ATTR void wifi_changed_cb (uint8_t status)
Definition at line 274 of file user_main.c.
References RINGBUF::fill_cnt, ICACHE_FLASH_ATTR, MQTT_Connect(), mqtt_connected_cb(), MQTT_Client::msgQueue, os_printf(), QUEUE::rb, RINGBUF::size, and STATION_GOT_IP.
Referenced by sample_mode_timer_func().
Variable Documentation
config_mode_timer
os_timer_t config_mode_timer static
Definition at line 52 of file user_main.c.
Referenced by system_init_done().
kmp_request_send_timer
os_timer_t kmp_request_send_timer static
Definition at line 60 of file user_main.c.
Referenced by system_init_done().
mesh_ssid
uint8_t mesh_ssid[64]
Definition at line 71 of file user_main.c.
Referenced by sample_mode_timer_func().
mqtt_client
MQTT_Client mqtt_client
Definition at line 50 of file user_main.c.
rtc_info
struct rst_info* rtc_info
Definition at line 68 of file user_main.c.
sample_mode_timer
os_timer_t sample_mode_timer static
Definition at line 53 of file user_main.c.
Referenced by system_init_done().
sample_timer
os_timer_t sample_timer static
Definition at line 51 of file user_main.c.
Referenced by mqtt_connected_cb().