MeterLogger: user/user_main.h File Reference
user_main.h File Reference
Functions
ICACHE_FLASH_ATTR void wifi_changed_cb (uint8_t status)
ICACHE_FLASH_ATTR void mqtt_connected_cb (uint32_t *args)
ICACHE_FLASH_ATTR void mqtt_disconnected_cb (uint32_t *args)
ICACHE_FLASH_ATTR void mqtt_published_cb (uint32_t *args)
ICACHE_FLASH_ATTR void mqtt_data_cb (uint32_t *args, const char *topic, uint32_t topic_len, const char *data, uint32_t data_len)
ICACHE_FLASH_ATTR void mqtt_timeout_cb (uint32_t *args)
ICACHE_FLASH_ATTR void user_init (void)
ICACHE_FLASH_ATTR void system_init_done (void)
Function Documentation
mqtt_connected_cb()
ICACHE_FLASH_ATTR void mqtt_connected_cb (uint32_t * args)
Definition at line 289 of file user_main.c.
References syscfg_t::ac_thermo_state, en61107_get_received_serial(), en61107_set_mqtt_client(), encrypt_aes_hmac_combined(), get_unix_time(), HW_MODEL, kmp_get_received_serial(), kmp_set_mqtt_client(), led_pattern_b(), memset, MQTT_MESSAGE_L, MQTT_Publish(), MQTT_Subscribe(), MQTT_TOPIC_L, sample_timer, sample_timer_func(), strlen, sys_cfg, tfp_snprintf(), uptime(), and wifi_fallback_is_present().
Referenced by sample_mode_timer_func(), and wifi_changed_cb().
mqtt_data_cb()
ICACHE_FLASH_ATTR void mqtt_data_cb (uint32_t * args, const char * topic, uint32_t topic_len, const char * data, uint32_t data_len)
Definition at line 400 of file user_main.c.
References ac_off(), ac_test(), ac_thermo_close(), ac_thermo_open(), ac_thermo_pwm(), syscfg_t::ac_thermo_state, add_cron_job_from_query(), atoi(), cfg_save(), clear_cron_jobs(), syscfg_t::cron_jobs, decrypt_aes_hmac_combined(), en61107_get_received_serial(), encrypt_aes_hmac_combined(), FUNCTIONNAME_L, get_unix_time(), HW_MODEL, ICACHE_FLASH_ATTR, kmp_get_received_serial(), memcpy, memset, MQTT_MESSAGE_L, MQTT_Publish(), MQTT_TOPIC_L, cron_jobs_t::n, os_printf(), printf, rtc_info, syscfg_t::sta_pwd, syscfg_t::sta_ssid, strlen, strncmp, strncpy, sys_cfg, system_get_time(), tfp_snprintf(), uptime(), wifi_get_rssi(), and wifi_get_status().
Referenced by sample_mode_timer_func().
mqtt_disconnected_cb()
ICACHE_FLASH_ATTR void mqtt_disconnected_cb (uint32_t * args)
Definition at line 390 of file user_main.c.
Referenced by sample_mode_timer_func().
mqtt_published_cb()
ICACHE_FLASH_ATTR void mqtt_published_cb (uint32_t * args)
Definition at line 393 of file user_main.c.
References MQTT_WATCHDOG_ID, and reset_watchdog().
Referenced by sample_mode_timer_func().
mqtt_timeout_cb()
ICACHE_FLASH_ATTR void mqtt_timeout_cb (uint32_t * args)
Definition at line 397 of file user_main.c.
Referenced by sample_mode_timer_func().
system_init_done()
ICACHE_FLASH_ATTR void system_init_done (void)
Definition at line 886 of file user_main.c.
References config_mode_timer, config_mode_timer_func(), init_unix_time(), kmp_request_send_timer, kmp_request_send_timer_func(), os_printf(), printf, rtc_info, sample_mode_timer, and sample_mode_timer_func().
Referenced by user_init().
user_init()
ICACHE_FLASH_ATTR void user_init (void)
Definition at line 790 of file user_main.c.
References ac_out_init(), ac_thermo_close(), ac_thermo_open(), syscfg_t::ac_thermo_state, BIT_RATE_115200, BIT_RATE_1200, BIT_RATE_300, cfg_load(), cron_init(), en61107_request_init(), ext_spi_init(), HW_MODEL, init_aes_hmac_combined(), init_watchdog(), syscfg_t::key, kmp_request_init(), led_init(), memset, printf, start_watchdog(), sys_cfg, system_init_done(), and uart_init().
wifi_changed_cb()
ICACHE_FLASH_ATTR void wifi_changed_cb (uint8_t status)
Definition at line 274 of file user_main.c.
References RINGBUF::fill_cnt, ICACHE_FLASH_ATTR, MQTT_Connect(), mqtt_connected_cb(), MQTT_Client::msgQueue, os_printf(), QUEUE::rb, and RINGBUF::size.
Referenced by sample_mode_timer_func().