MeterLogger: user/utils.h File Reference
utils.h File Reference
Functions
ICACHE_FLASH_ATTR uint16_t ccit_crc16 (uint16_t crc16, uint8_t *data_p, unsigned int length)
ICACHE_FLASH_ATTR void w_to_kw_str (char *w, char *kw)
ICACHE_FLASH_ATTR void kw_to_w_str (char *kw, char *w)
ICACHE_FLASH_ATTR void mw_to_w_str (char *mw, char *w)
ICACHE_FLASH_ATTR void divide_str_by_10 (char *str, char *decimal_str)
ICACHE_FLASH_ATTR void divide_str_by_100 (char *str, char *decimal_str)
ICACHE_FLASH_ATTR void cleanup_decimal_str (char *decimal_str, char *cleaned_up_str, unsigned int length)
ICACHE_FLASH_ATTR unsigned int decimal_number_length (int n)
ICACHE_FLASH_ATTR int int_pow (int x, int y)
Function Documentation
ccit_crc16()
ICACHE_FLASH_ATTR uint16_t ccit_crc16 (uint16_t crc16, uint8_t * data_p, unsigned int length)
Definition at line 47 of file utils.c.
Referenced by cfg_load(), cfg_save(), and kmp_crc16().
{
     while (length--) {
         crc16 = (crc16 << 8) ^ ccit_crc16_table[((crc16 >> 8) ^ *data_p++) & 0x00FF];
     }
     return crc16;
 }
cleanup_decimal_str()
ICACHE_FLASH_ATTR void cleanup_decimal_str (char * decimal_str, char * cleaned_up_str, unsigned int length)
Definition at line 146 of file utils.c.
References atoi(), decimal_number_length(), ICACHE_FLASH_ATTR, memcpy, NULL, strcat, strncpy, strstr, and tfp_snprintf().
Referenced by parse_en61107_frame(), and parse_mc66cde_standard_data_1_frame().
{
     uint32_t value_int, value_frac;
     char *pos;
     uint8_t decimals = 0;
     uint8_t prepend_zeroes;
     char zeroes[8];
     memcpy(cleaned_up_str, decimal_str, length);
     cleaned_up_str[length] = 0; // null terminate
     pos = strstr(cleaned_up_str, ".");
     if (pos == NULL) {
         // non fractional number
         value_int = atoi(cleaned_up_str);
         tfp_snprintf(cleaned_up_str, length, "%u", value_int);
     }
     else {
         // parse frac
         while ((*(pos + 1 + decimals) >= '0') && (*(pos + 1 + decimals) <= '9')) {
             // count the decimals
             decimals++;
         }
         value_frac = atoi(pos + 1);
         prepend_zeroes = decimals - decimal_number_length(atoi(pos + 1));
         zeroes[0] = 0;  // null terminate
         while (prepend_zeroes--) {
             strcat(zeroes, "0");
         }
         // parse int
         strncpy(cleaned_up_str, decimal_str, (pos - cleaned_up_str));
         cleaned_up_str[cleaned_up_str - pos] = 0;   // null terminate
         value_int = atoi(cleaned_up_str);
         tfp_snprintf(cleaned_up_str, length, "%u.%s%u", value_int, zeroes, value_frac);
     }
 }
decimal_number_length()
ICACHE_FLASH_ATTR unsigned int decimal_number_length (int n)
Definition at line 186 of file utils.c.
References ICACHE_FLASH_ATTR.
Referenced by cleanup_decimal_str(), and kmp_value_to_string().
{
     int digits;
     digits = n < 0; //count "minus"
     do {
         digits++;
     } while (n /= 10);
     return digits;
 }
divide_str_by_10()
ICACHE_FLASH_ATTR void divide_str_by_10 (char * str, char * decimal_str)
Definition at line 110 of file utils.c.
References atoi(), and tfp_snprintf().
Referenced by parse_mc66cde_standard_data_1_frame().
{
     int32_t result_int, result_frac;
     int32_t value_int;
     value_int = atoi(str);
     // ...divide by 10 and prepare decimal string
     result_int = (int32_t)(value_int / 10);
     if (result_int < 0) {
         result_frac = -1 * (value_int % 10);
     }
     else {
         result_frac = value_int % 100;
     }
     tfp_snprintf(decimal_str, 8, "%d.%01u", result_int, result_frac);
 }
divide_str_by_100()
ICACHE_FLASH_ATTR void divide_str_by_100 (char * str, char * decimal_str)
Definition at line 128 of file utils.c.
References atoi(), and tfp_snprintf().
Referenced by parse_mc66cde_inst_values_frame(), and parse_mc66cde_standard_data_1_frame().
{
     int32_t result_int, result_frac;
     int32_t value_int;
     value_int = atoi(str);
     // ...divide by 100 and prepare decimal string
     result_int = (int32_t)(value_int / 100);
     if (result_int < 0) {
         result_frac = -1 * (value_int % 100);
     }
     else {
         result_frac = value_int % 100;
     }
     tfp_snprintf(decimal_str, 8, "%d.%02u", result_int, result_frac);
 }
int_pow()
ICACHE_FLASH_ATTR int int_pow (int x, int y)
Definition at line 198 of file utils.c.
Referenced by kmp_value_to_double(), kmp_value_to_string(), and kw_to_w_str().
{
     int i;
     int result;
     if (y == 0) {
         return 1;
     }
     result = x;
     for (i = 1; i < y; i++) {
         result *= x;
     }
     return result;
 }
kw_to_w_str()
ICACHE_FLASH_ATTR void kw_to_w_str (char * kw, char * w)
Definition at line 67 of file utils.c.
References atoi(), int_pow(), strlen, and tfp_snprintf().
Referenced by cgiSetup(), and mw_to_w_str().
{
     uint32_t result_int, result_frac;
     uint32_t i;
     uint32_t len;
     bool dec_separator;
     char result_int_str[32 + 1];
     uint32_t pos_int;
     uint32_t pos_frac;
     len = strlen(kw);
     result_frac = 0;
     pos_int = 0;
     pos_frac = 0;
     dec_separator = false;
     for (i = 0; i < len && pos_frac < 3; i++) {
         if (kw[i] == '.') {
             dec_separator = 1;
         }
         else if (!dec_separator) {
             result_int_str[pos_int++] = kw[i];
         }
         else {
             //result_frac_str[pos_frac++] = kw[i];
             result_frac += (kw[i] - '0') * int_pow(10, 2 - pos_frac);
             pos_frac++;
         }
     }
     result_int_str[pos_int] = 0;    // null terminate
     result_int = 1000 * atoi(result_int_str);   // multiply by 1000
     result_int += result_frac;
     tfp_snprintf(w, 11, "%u", result_int);
 }
mw_to_w_str()
ICACHE_FLASH_ATTR void mw_to_w_str (char * mw, char * w)
Definition at line 105 of file utils.c.
References kw_to_w_str().
Referenced by en61107_get_received_energy_kwh(), and kmp_get_received_energy_kwh().
{
     // just a wrapper
     kw_to_w_str(mw, w);
 }
w_to_kw_str()
ICACHE_FLASH_ATTR void w_to_kw_str (char * w, char * kw)
Definition at line 54 of file utils.c.
References atoi(), and tfp_snprintf().
Referenced by tplSetup().
{
     uint32_t result_int, result_frac;
     uint32_t w_int;
     w_int = atoi(w);
     // ...divide by 1000 and prepare decimal string in kWh
     result_int = (int32_t)(w_int / 1000);
     result_frac = w_int % 1000;
     tfp_snprintf(kw, 15, "%u.%03u", result_int, result_frac);
 }