MeterLogger: user/utils.c File Reference
utils.c File Reference
#include <esp8266.h>
#include "config.h"
#include "user_config.h"
#include "debug.h"
#include "utils.h"
#include "tinyprintf.h"
Functions
ICACHE_FLASH_ATTR uint16_t ccit_crc16 (uint16_t crc16, uint8_t *data_p, unsigned int length)
ICACHE_FLASH_ATTR void w_to_kw_str (char *w, char *kw)
ICACHE_FLASH_ATTR void kw_to_w_str (char *kw, char *w)
ICACHE_FLASH_ATTR void divide_str_by_10 (char *str, char *decimal_str)
ICACHE_FLASH_ATTR void divide_str_by_100 (char *str, char *decimal_str)
ICACHE_FLASH_ATTR void cleanup_decimal_str (char *decimal_str, char *cleaned_up_str, unsigned int length)
ICACHE_FLASH_ATTR unsigned int decimal_number_length (int n)
ICACHE_FLASH_ATTR int int_pow (int x, int y)
Variables
const uint16_t ccit_crc16_table [256]
Function Documentation
ccit_crc16()
ICACHE_FLASH_ATTR uint16_t ccit_crc16 (uint16_t crc16, uint8_t * data_p, unsigned int length)
Definition at line 47 of file utils.c.
Referenced by cfg_load(), cfg_save(), and kmp_crc16().
cleanup_decimal_str()
ICACHE_FLASH_ATTR void cleanup_decimal_str (char * decimal_str, char * cleaned_up_str, unsigned int length)
Definition at line 141 of file utils.c.
References atoi(), decimal_number_length(), ICACHE_FLASH_ATTR, memcpy, NULL, strcat, strncpy, strstr, and tfp_snprintf().
Referenced by parse_en61107_frame(), and parse_mc66cde_standard_data_1_frame().
decimal_number_length()
ICACHE_FLASH_ATTR unsigned int decimal_number_length (int n)
Definition at line 181 of file utils.c.
References ICACHE_FLASH_ATTR.
Referenced by cleanup_decimal_str(), and kmp_value_to_string().
divide_str_by_10()
ICACHE_FLASH_ATTR void divide_str_by_10 (char * str, char * decimal_str)
Definition at line 105 of file utils.c.
References atoi(), and tfp_snprintf().
Referenced by parse_mc66cde_standard_data_1_frame().
divide_str_by_100()
ICACHE_FLASH_ATTR void divide_str_by_100 (char * str, char * decimal_str)
Definition at line 123 of file utils.c.
References atoi(), and tfp_snprintf().
Referenced by parse_mc66cde_inst_values_frame(), and parse_mc66cde_standard_data_1_frame().
int_pow()
ICACHE_FLASH_ATTR int int_pow (int x, int y)
Definition at line 193 of file utils.c.
Referenced by kmp_value_to_double(), kmp_value_to_string(), and kw_to_w_str().
kw_to_w_str()
ICACHE_FLASH_ATTR void kw_to_w_str (char * kw, char * w)
Definition at line 67 of file utils.c.
References atoi(), int_pow(), strlen, and tfp_snprintf().
Referenced by cgiSetup().
w_to_kw_str()
ICACHE_FLASH_ATTR void w_to_kw_str (char * w, char * kw)
Definition at line 54 of file utils.c.
References atoi(), and tfp_snprintf().
Referenced by tplSetup().
Variable Documentation
ccit_crc16_table
const uint16_t ccit_crc16_table[256]
Definition at line 10 of file utils.c.