MeterLogger: modules/include/wifi.h File Reference
wifi.h File Reference
Typedefs
typedef void(* WifiCallback) (uint8_t)
Functions
static void ICACHE_FLASH_ATTR wifi_get_rssi_timer_func (void *arg)
static void ICACHE_FLASH_ATTR wifi_scan_timer_func (void *arg)
bool ICACHE_FLASH_ATTR acl_check_packet (struct pbuf *p)
void wifi_handle_event_cb (System_Event_t *evt)
void ICACHE_FLASH_ATTR wifi_scan_done_cb (void *arg, STATUS status)
void ICACHE_FLASH_ATTR wifi_default ()
void ICACHE_FLASH_ATTR wifi_fallback ()
void ICACHE_FLASH_ATTR wifi_connect (uint8_t *ssid, uint8_t *pass, WifiCallback cb)
void ICACHE_FLASH_ATTR wifi_softap_config (uint8_t *ssid, uint8_t *pass, uint8_t authmode)
void ICACHE_FLASH_ATTR wifi_softap_ip_config (void)
sint8_t ICACHE_FLASH_ATTR wifi_get_rssi ()
bool ICACHE_FLASH_ATTR wifi_get_status ()
void ICACHE_FLASH_ATTR wifi_start_scan ()
void ICACHE_FLASH_ATTR wifi_stop_scan ()
bool ICACHE_FLASH_ATTR wifi_scan_is_running ()
bool ICACHE_FLASH_ATTR wifi_fallback_is_present ()
Typedef Documentation
WifiCallback
typedef void(* WifiCallback) (uint8_t)
Definition at line 10 of file wifi.h.
Function Documentation
acl_check_packet()
bool ICACHE_FLASH_ATTR acl_check_packet (struct pbuf * p)
Definition at line 94 of file wifi.c.
References dns_ip, IP2STR, IP_PROTO_ICMP, IP_PROTO_TCP, IP_PROTO_UDP, IPH_PROTO, pbuf::len, ntohs, os_printf(), pbuf::payload, sta_network_addr, and sta_network_mask.
Referenced by my_input_ap().
wifi_connect()
void ICACHE_FLASH_ATTR wifi_connect (uint8_t * ssid, uint8_t * pass, WifiCallback cb)
Definition at line 337 of file wifi.c.
References config_pass, config_ssid, INFO, led_stop_pattern(), NULL, os_memset, os_timer_arm, os_timer_disarm, os_timer_func_t, os_timer_setfn, station_config::password, RSSI_CHECK_INTERVAL, station_config::ssid, STATIONAP_MODE, tfp_snprintf(), wifi_cb, wifi_get_rssi_timer, wifi_get_rssi_timer_func(), wifi_handle_event_cb(), wifi_set_event_handler_cb(), wifi_set_opmode(), wifi_start_scan(), wifi_station_connect(), wifi_station_disconnect(), wifi_station_set_auto_connect(), and wifi_station_set_config().
wifi_default()
void ICACHE_FLASH_ATTR wifi_default ()
Definition at line 298 of file wifi.c.
References config_pass, config_ssid, NULL, os_memset, os_printf(), os_timer_arm, os_timer_disarm, os_timer_func_t, os_timer_setfn, station_config::password, RSSI_CHECK_INTERVAL, station_config::ssid, STATIONAP_MODE, tfp_snprintf(), wifi_get_rssi_timer, wifi_get_rssi_timer_func(), wifi_set_opmode_current(), wifi_station_connect(), wifi_station_disconnect(), wifi_station_get_config(), and wifi_station_set_config_current().
Referenced by wifi_scan_done_cb().
wifi_fallback()
void ICACHE_FLASH_ATTR wifi_fallback ()
Definition at line 320 of file wifi.c.
References os_memset, os_printf(), station_config::password, station_config::ssid, STA_FALLBACK_PASS, STA_FALLBACK_SSID, STATIONAP_MODE, tfp_snprintf(), wifi_set_opmode_current(), wifi_station_connect(), wifi_station_disconnect(), wifi_station_get_config(), and wifi_station_set_config_current().
Referenced by wifi_scan_done_cb().
wifi_fallback_is_present()
bool ICACHE_FLASH_ATTR wifi_fallback_is_present ()
Definition at line 473 of file wifi.c.
References wifi_fallback_present.
wifi_get_rssi()
sint8_t ICACHE_FLASH_ATTR wifi_get_rssi ()
Definition at line 446 of file wifi.c.
References get_rssi_running, and rssi.
Referenced by wifi_scan_timer_func().
wifi_get_rssi_timer_func()
static void ICACHE_FLASH_ATTR wifi_get_rssi_timer_func (void * arg) static
wifi_get_status()
bool ICACHE_FLASH_ATTR wifi_get_status ()
Definition at line 453 of file wifi.c.
References wifi_default_ok.
wifi_handle_event_cb()
void wifi_handle_event_cb (System_Event_t * evt)
Definition at line 172 of file wifi.c.
References Event_SoftAPMode_StaConnected_t::aid, Event_Info_u::disconnected, _esp_event::event, _esp_event::event_info, EVENT_SOFTAPMODE_STACONNECTED, EVENT_STAMODE_CONNECTED, EVENT_STAMODE_DISCONNECTED, EVENT_STAMODE_GOT_IP, Event_Info_u::got_ip, Event_StaMode_Got_IP_t::ip, Event_SoftAPMode_StaConnected_t::mac, MAC2STR, MACSTR, Event_StaMode_Got_IP_t::mask, my_input_ap(), my_output_ap(), os_memset, os_printf(), os_sprintf, os_strncmp, patch_netif_ap(), Event_StaMode_Disconnected_t::reason, station_config::ssid, Event_StaMode_Disconnected_t::ssid, Event_Info_u::sta_connected, sta_network_addr, sta_network_mask, syscfg_t::sta_ssid, sys_cfg, wifi_cb, wifi_default_ok, wifi_event, wifi_softap_ip_config(), wifi_station_get_config(), wifi_station_get_connect_status(), and wifi_status.
Referenced by wifi_connect().
wifi_scan_done_cb()
void ICACHE_FLASH_ATTR wifi_scan_done_cb (void * arg, STATUS status)
Definition at line 253 of file wifi.c.
References led_pattern_a(), led_stop_pattern(), NULL, OK, os_printf(), os_strncmp, bss_info::ssid, STA_FALLBACK_SSID, syscfg_t::sta_ssid, sys_cfg, wifi_default(), wifi_fallback(), wifi_fallback_last_present, wifi_fallback_present, wifi_present, wifi_scan_runnning, and wifi_start_scan().
Referenced by wifi_scan_timer_func().
wifi_scan_is_running()
bool ICACHE_FLASH_ATTR wifi_scan_is_running ()
Definition at line 469 of file wifi.c.
References wifi_scan_runnning.
Referenced by wifi_reconnect_timer_func().
wifi_scan_timer_func()
static void ICACHE_FLASH_ATTR wifi_scan_timer_func (void * arg) static
wifi_softap_config()
void ICACHE_FLASH_ATTR wifi_softap_config (uint8_t * ssid, uint8_t * pass, uint8_t authmode)
Definition at line 370 of file wifi.c.
References softap_config::authmode, softap_config::beacon_interval, softap_config::channel, softap_config::max_connection, memset, softap_config::password, softap_config::ssid, softap_config::ssid_hidden, softap_config::ssid_len, tfp_snprintf(), wifi_softap_get_config(), and wifi_softap_set_config().
wifi_softap_ip_config()
void ICACHE_FLASH_ATTR wifi_softap_ip_config (void)
Definition at line 389 of file wifi.c.
References AP_NETWORK, ap_network_addr, dhcps_set_DNS(), dns_ip, dhcps_lease::end_ip, espconn_dns_setserver(), ip_info::gw, ip_info::ip, IP2STR, IP4_ADDR, ip4_addr3, ip4_addr4, ip_addr_cmp, IPSTR, netif_list, ip_info::netmask, netif::next, NULL, netif::num, os_printf(), sta_network_addr, dhcps_lease::start_ip, UTILS_StrToIP(), wifi_set_ip_info(), wifi_softap_dhcps_start(), wifi_softap_dhcps_stop(), and wifi_softap_set_dhcps_lease().
Referenced by wifi_handle_event_cb().
wifi_start_scan()
void ICACHE_FLASH_ATTR wifi_start_scan ()
Definition at line 457 of file wifi.c.
References NULL, os_timer_arm, os_timer_disarm, os_timer_func_t, os_timer_setfn, WIFI_SCAN_INTERVAL, wifi_scan_timer, and wifi_scan_timer_func().
Referenced by wifi_connect(), wifi_reconnect_timer_func(), and wifi_scan_done_cb().
wifi_stop_scan()
void ICACHE_FLASH_ATTR wifi_stop_scan ()
Definition at line 464 of file wifi.c.
References os_timer_disarm, and wifi_scan_timer.
Referenced by watchdog_timer_func().