MeterLogger: esp-open-lwip/include/netif/wlan_lwip_if.h File Reference
wlan_lwip_if.h File Reference
Macros
#define LWIP_IF0_PRIO 28
#define LWIP_IF1_PRIO 29
Enumerations
enum { SIG_LWIP_RX = 0 }
Functions
struct netif * eagle_lwip_if_alloc (struct ieee80211_conn *conn, const uint8 *macaddr, struct ip_info *info)
struct netif * eagle_lwip_getif (uint8 index)
sint8 ieee80211_output_pbuf (struct netif *ifp, struct pbuf *pb)
Macro Definition Documentation
LWIP_IF0_PRIO
#define LWIP_IF0_PRIO 28
Definition at line 9 of file wlan_lwip_if.h.
LWIP_IF1_PRIO
#define LWIP_IF1_PRIO 29
Definition at line 10 of file wlan_lwip_if.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SIG_LWIP_RX
Definition at line 12 of file wlan_lwip_if.h.
      {
     SIG_LWIP_RX = 0,
 };
Function Documentation
eagle_lwip_getif()
struct netif* eagle_lwip_getif (uint8 index)
Referenced by dhcps_start(), dhcps_stop(), espconn_udp_sendto(), espconn_udp_sent(), and ip_route().
eagle_lwip_if_alloc()
struct netif* eagle_lwip_if_alloc (struct ieee80211_conn * conn, const uint8 * macaddr, struct ip_info * info)
ieee80211_output_pbuf()
sint8 ieee80211_output_pbuf (struct netif * ifp, struct pbuf * pb)