ICACHE_FLASH_ATTR void ac_out_init();
ICACHE_FLASH_ATTR void static ac_test_timer_func(void *arg);
ICACHE_FLASH_ATTR void ac_test();
ICACHE_FLASH_ATTR void static ac_out_off_timer_func(void *arg);
ICACHE_FLASH_ATTR void static ac_pwm_timer_func(void *arg);
ICACHE_FLASH_ATTR void ac_motor_valve_open();
ICACHE_FLASH_ATTR void ac_motor_valve_close();
ICACHE_FLASH_ATTR void ac_thermo_open();
ICACHE_FLASH_ATTR void ac_thermo_close();
ICACHE_FLASH_ATTR void ac_thermo_pwm(unsigned int pwm);
ICACHE_FLASH_ATTR void ac_off();
